Repository google/WebFundamentals, pull requests merged in 2018-11, with the labels that each got.

#6800 Add Signed HTTP Exchange announcement
  src/content/en/images/contributors/kinukoyasuda.jpg
  src/content/en/updates/2018/11/signed-exchanges.md
  src/content/en/updates/images/2018/11/signed-exchanges.svg
  src/data/_contributors.yaml
  src/data/commonTags.json
Labels: cla: yes

#6801 Fixing typo in digi-cert
  src/content/en/updates/2018/11/signed-exchanges.md
Labels: cla: yes

#6799 Fix typo in web push protocol
  src/content/en/fundamentals/push-notifications/web-push-protocol.md
Labels: cla: yes

#6797 Removing broken promise demos
  src/content/en/fundamentals/primers/promises.md
Labels: cla: yes, type-Content

#6785 update Shadow DOM article with current browser support
  src/content/en/fundamentals/web-components/shadowdom.md
Labels: cla: no

#6808 CDS T-minus-one-week banner
  src/data/announcement.yaml
Labels: cla: yes

#6816 Http 203 podcast
  src/content/en/shows/http203/podcast/stress-canvas-jam.md
Labels: cla: yes, type-Content

#6805 Dvd updates
  src/content/en/shows/designer-vs-developer/_toc.yaml
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E01-creating-a-collaborative-environment.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E02-balancing-creativity-with-user-testing.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E03-Adopting-the-native-language-of-the-web.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E04-are-designers-born-or-made.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E05-who-is-responsible-for-design.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E06-are-design-tools-fit-for-purpose.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E01-becoming-a-creative-coder.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E02-designing-a-great-performance.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E03-improving-your-creative-confidence.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E04-learn-how-to-design.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E05-designing-for-the-next-billion-users.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E06-how-the-web-can-compete-with-native.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E01-designing-for-css-grid.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E02-designing-for-standards.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E03-getting-a-start-in-industry.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E04-creative-ways-of-prototyping.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E05-using-the-gestalt-principles.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E06-how-to-design-a-vr-game.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E07-Designing-for-offline.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS4E01-how-we-designed-chrome.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS4E02-ux-research-usability-testingy.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS4E03-material-design-components.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS4E04-prototyping-motion.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS4E05-using-autocomplete.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS4E06-pwas-firebase.md
  src/content/en/shows/designer-vs-developer/podcast/images/dvd-s04-e06-cover-large.jpg
  src/content/en/shows/designer-vs-developer/podcast/images/dvd-s04-e06-cover.jpg
Labels: cla: no

#6820 A few Workbox doc fixes
  src/content/en/tools/workbox/_shared/config/single/runtimeCaching.html
  src/content/en/tools/workbox/modules/workbox-precaching.md
Labels: cla: yes

#6812 Typo fix in Workbox reference
  src/content/en/tools/workbox/reference-docs/latest/workbox.routing.Route.html
Labels: cla: yes

#6811 Add `Request.destination` recipe to Workbox guides
  src/content/en/tools/workbox/guides/common-recipes.md
Labels: cla: yes

#6806 Lighthouse scoring doc updates
  src/content/en/tools/lighthouse/scoring.md
  src/content/en/tools/lighthouse/v3/imgs/ui.png
  src/content/en/tools/lighthouse/v3/scoring.md
Labels: cla: yes

#6818 CDS Live - Watch Now banner
  src/data/announcement.yaml
Labels: cla: yes

#6766 Web Capabilities page
  src/content/en/updates/2018/11/writable-files.md
  src/content/en/updates/_book.yaml
  src/content/en/updates/_shared/capabilities.html
  src/content/en/updates/capabilities.md
  src/content/en/updates/images/generic/file.png
  src/content/en/updates/images/generic/thumbs-up.png
  src/data/commonTags.json
Labels: cla: yes

#6833 [lighthouse] remove framebox
  src/content/en/tools/lighthouse/audits/preload.md
Labels: P1, cla: yes, section-tools, type-Content

#6823 6814 | Fix GitHub link
  src/content/en/tools/lighthouse/audits/speed-index.md
  src/content/es/tools/lighthouse/audits/speed-index.md
  src/content/id/tools/lighthouse/audits/speed-index.md
  src/content/ja/tools/lighthouse/audits/speed-index.md
  src/content/ko/tools/lighthouse/audits/speed-index.md
  src/content/pt-br/tools/lighthouse/audits/speed-index.md
  src/content/zh-cn/tools/lighthouse/audits/speed-index.md
  src/content/zh-tw/tools/lighthouse/audits/speed-index.md
Labels: cla: yes

#6846 Discover URL fixes
  src/content/en/fundamentals/discovery/social-discovery/_code/social-sites.html
  src/content/en/fundamentals/discovery/social-discovery/_code/social-sites2.html
Labels: cla: yes

#6845 DPWA on Mac
  src/content/en/progressive-web-apps/desktop.md
Labels: cla: yes

#6789 Nikkei case study
  src/content/en/showcase/2018/images/nikkei/featured.jpg
  src/content/en/showcase/2018/images/nikkei/nikkei-01.jpg
  src/content/en/showcase/2018/images/nikkei/nikkei-02.jpg
  src/content/en/showcase/2018/images/nikkei/nikkei-03.jpg
  src/content/en/showcase/2018/images/nikkei/nikkei-04.jpg
  src/content/en/showcase/2018/images/nikkei/nikkei-05.jpg
  src/content/en/showcase/2018/images/nikkei/nikkei-06.jpg
  src/content/en/showcase/2018/images/nikkei/nikkei-07.jpg
  src/content/en/showcase/2018/images/nikkei/nikkei-08.jpg
  src/content/en/showcase/2018/images/nikkei/nikkei-09.mp4
  src/content/en/showcase/2018/images/nikkei/nikkei-09.webm
  src/content/en/showcase/2018/nikkei.md
  src/content/en/showcase/2018/pdf/nikkei-pwa.pdf
Labels: cla: yes

#6855 Remove <p> in framebox. Fixes #5762
  src/content/en/fundamentals/accessibility/accessible-styles.md
Labels: cla: yes

#6853 Post CDS banner
  src/content/en/_project.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes

#6856 [devtools] fix #6837
  src/content/en/tools/chrome-devtools/images/sw-cache.png
  src/content/en/tools/chrome-devtools/progressive-web-apps.md
Labels: P2, cla: yes, section-tools, type-Content

#6857 [devtools] fix #6821
  src/content/en/tools/chrome-devtools/remote-debugging/index.md
Labels: P1, cla: yes, section-tools, type-Content

#6851 Adding client hints guide.
  src/content/en/fundamentals/performance/_toc.yaml
  src/content/en/fundamentals/performance/optimizing-content-efficiency/client-hints/images/figure-1.svg
  src/content/en/fundamentals/performance/optimizing-content-efficiency/client-hints/images/figure-2-1x.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/client-hints/images/figure-2-2x.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/client-hints/images/figure-3.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/client-hints/images/figure-4.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/client-hints/index.md
Labels: cla: yes

#6863 fix pdf link for nikkei case study
  src/content/en/showcase/2018/nikkei.md
Labels: cla: yes

#6865 Update anchor id for "quota usage"
  src/content/en/tools/chrome-devtools/progressive-web-apps.md
Labels: cla: yes

#6870 [devtools] make the ToC less wordy
  src/content/en/tools/chrome-devtools/_toc.yaml
Labels: P2, cla: yes, section-tools, type-Content

#6869 Add MediaStream video support section
  src/content/en/updates/2018/10/watch-video-using-picture-in-picture.md
Labels: cla: yes

#6874 New Autoplay Web Audio Blog Post
  src/content/en/images/contributors/mlamouri.jpg
  src/content/en/images/contributors/tomgreenaway.jpg
  src/content/en/updates/2018/11/web-audio-autoplay.md
  src/content/en/updates/images/2018/11/web-audio-games.png
  src/data/_contributors.yaml
Labels: cla: yes, type-Content

#6864 Switch localStorage to IDB in SW recommendations
  src/content/en/fundamentals/performance/optimizing-content-efficiency/client-hints/index.md
Labels: cla: yes

#6888 Add section on transpiling/polyfilling BigInt
  src/content/en/updates/2018/05/bigint.md
Labels: cla: yes

#6889 Fix typo
  src/content/en/updates/2018/05/bigint.md
Labels: cla: yes

#6885 NoState Prefetch: Update the docs with "Purpose: Prefetch"
  src/content/en/updates/2018/07/nostate-prefetch.md
Labels: cla: no

#6883 Propose different spelling
  src/content/en/updates/2018/11/web-audio-autoplay.md
Labels: cla: yes

#6900 [devtools] add wndt72
  src/content/en/updates/2018/11/devtools.md
  src/content/en/updates/images/2018/11/copyjs.png
  src/content/en/updates/images/2018/11/libs.png
  src/content/en/updates/images/2018/11/lighthouse.png
  src/content/en/updates/images/2018/11/metrics.png
  src/content/en/updates/images/2018/11/text.png
Labels: P1, cla: yes, section-updates, type-Content

#6896 Rename “package name maps” to “import maps”
  src/content/en/fundamentals/primers/modules.md
Labels: cla: yes

#6905 Fix typo in "What's new in DevTools 72"
  src/content/en/updates/2018/11/devtools.md
Labels: cla: yes

#6910 Correct podcast size
  src/content/en/shows/http203/podcast/stress-canvas-jam.md
Labels: cla: yes, type-Content

#6917 fix #6740 by mentioning how to track FMP in wild
  src/content/en/tools/lighthouse/audits/first-meaningful-paint.md
Labels: P2, cla: yes, section-tools, type-Content
