Repository google/WebFundamentals, pull requests merged in 2018-08, with the labels that each got.

#6445 Fix of typo in code example
  src/content/en/fundamentals/discovery/social-discovery/_code/social-sites.html
Labels: cla: yes

#6449 Add deprecations/removals blurb to standard location.
  src/content/en/updates/2018/07/reportingobserver.md
Labels: cla: yes

#6451 Deprecations and Removals in Chrome 69
  src/content/en/updates/2018/08/chrome-69-deps-rems.md
  src/content/en/updates/_shared/see-all-dep-rem.html
  src/content/en/updates/images/generic/warning.png
Labels: cla: yes

#6453 Add "Audio/Video Updates in Chrome 69" /updates article (without PiP)
  src/content/en/updates/2018/08/chrome-69-media-updates.md
  src/content/en/updates/images/2018/08/media-intent-handler.png
  src/content/en/updates/images/2018/08/pts-dts.png
Labels: cla: yes

#6455 Fix publication date.
  src/content/en/updates/2018/08/chrome-69-deps-rems.md
Labels: cla: yes

#6456 Change status of AV1 decoder.
  src/content/en/updates/2018/08/chrome-69-media-updates.md
Labels: cla: yes

#6458 Fix AV1 flag formatting
  src/content/en/updates/2018/08/chrome-69-media-updates.md
Labels: cla: yes

#6460 Remove incorrect and unnecessary section Ids
  src/content/en/updates/2018/07/css-scroll-snap.md
Labels: cla: yes

#6452 HTTP 203 podcast
  src/content/en/shows/http203/podcast/io-chats-v-eric.md
Labels: cla: yes, section-shows, type-Content

#6475 Http 203 podcast
  src/content/en/shows/http203/podcast/corb-cast-switch-face.md
  src/content/en/shows/http203/podcast/images/jake-in-pain.jpg
Labels: cla: yes, section-shows, type-Content

#6477 CrUX Dash announcement
  src/content/en/images/contributors/mkazi.jpg
  src/content/en/updates/2018/08/chrome-ux-report-dashboard.md
  src/content/en/updates/images/2018/08/crux-dash-device.png
  src/content/en/updates/images/2018/08/crux-dash-ect.png
  src/content/en/updates/images/2018/08/crux-dash-fcp.png
  src/data/_contributors.yaml
  src/data/commonTags.json
Labels: cla: yes

#6472 Fix typo
  src/content/en/fundamentals/performance/rail.md
  src/content/en/tools/chrome-devtools/network-performance/reference.md
  src/content/en/updates/2013/07/Alpha-transparency-in-Chrome-video.md
  src/content/en/updates/2014/12/Fundamental-of-Mobile-Web-Development.md
  src/content/en/updates/2015/01/ES6-Template-Strings.md
  src/content/en/updates/2015/04/autocapitalize.md
  src/content/en/updates/2018/07/pwacompat.md
  src/content/en/updates/2018/08/chrome-69-media-updates.md
Labels: cla: yes

#6470 Resolves #5629 | Typo fix + npm warning fixes
  src/content/en/updates/2017/06/headless-karma-mocha-chai.md
Labels: cla: yes

#6469 Resolves #5685 | Typo fix
  src/content/en/tools/lighthouse/audits/first-meaningful-paint.md
  src/content/ja/tools/lighthouse/audits/first-meaningful-paint.md
Labels: cla: yes

#6468 Resolves #6367 | Typo fix
  src/content/en/tools/chrome-devtools/network-performance/reference.md
Labels: cla: yes

#6467 Resolves #6212 | Grammar fix + test fix
  src/content/en/fundamentals/index.md
Labels: cla: yes

#6466 Resolves #6463 | Grammar issue fix
  src/content/en/fundamentals/design-and-ux/principles/index.md
  src/content/hi/fundamentals/design-and-ux/principles/index.md
Labels: cla: yes

#6465 Fixing constraints 404
  src/content/en/fundamentals/design-and-ux/input/forms/index.md
  src/content/es/fundamentals/design-and-ux/input/forms/index.md
  src/content/id/fundamentals/design-and-ux/input/forms/index.md
  src/content/ja/fundamentals/design-and-ux/input/forms/index.md
  src/content/ko/fundamentals/design-and-ux/input/forms/index.md
  src/content/pt-br/fundamentals/design-and-ux/input/forms/index.md
  src/content/ru/fundamentals/design-and-ux/input/forms/index.md
  src/content/zh-cn/fundamentals/design-and-ux/input/forms/index.md
  src/content/zh-tw/fundamentals/design-and-ux/input/forms/index.md
Labels: cla: yes

#6478 Resolves #6414 | Typo fix
  src/content/en/fundamentals/performance/rendering/optimize-javascript-execution.md
  src/content/en/updates/2018/08/chrome-ux-report-dashboard.md
Labels: cla: yes

#6482 update introductory sections
  src/content/en/tools/chrome-devtools/beginners/html.md
  src/content/en/tools/chrome-devtools/beginners/imgs/finished.png
Labels: DO NOT MERGE, cla: yes

#6492 Fix typo
  src/content/en/updates/2018/05/devtools.md
Labels: cla: yes

#6497 Direct to the Chrome 63+ workspaces page
  src/content/en/tools/chrome-devtools/sources.md
Labels: cla: yes

#6487 Updated media intent handler image.
  src/content/en/updates/images/2018/08/media-intent-handler.png
Labels: cla: yes

#6495 [lighthouse] add first contentful paint (FCP) doc
  src/content/en/tools/lighthouse/_toc.yaml
  src/content/en/tools/lighthouse/audits/first-contentful-paint.md
Labels: P1, cla: yes, section-tools, type-Content

#6500 Fixing parsing errors for this file- js to javascript
  src/content/en/tools/workbox/modules/workbox-sw.md
Labels: cla: yes

#6501 One more try to fix workbox error
  src/content/en/tools/workbox/modules/workbox-sw.md
Labels: cla: yes

#6502 And now I found out inverse is fix needed for devsite
  src/content/en/tools/workbox/modules/workbox-sw.md
Labels: cla: yes

#6505 Adding OffscreenCanvas update article
  src/content/en/updates/2018/08/offscreen-canvas.md
Labels: cla: yes

#6511 Fixes a typo in the Workbox docs
  src/content/en/tools/workbox/guides/generate-complete-sw.md
Labels: cla: yes

#6503 [lighthouse] update TTI reference
  src/content/en/tools/_redirects.yaml
  src/content/en/tools/lighthouse/_toc.yaml
  src/content/en/tools/lighthouse/audits/consistently-interactive.md
  src/content/en/tools/lighthouse/audits/time-to-interactive.md
Labels: P1, cla: yes, section-tools, type-Content

#6513 add "was this page helpful?" widget to performance docs
  src/content/en/fundamentals/performance/critical-rendering-path/adding-interactivity-with-javascript.md
  src/content/en/fundamentals/performance/critical-rendering-path/analyzing-crp.md
  src/content/en/fundamentals/performance/critical-rendering-path/constructing-the-object-model.md
  src/content/en/fundamentals/performance/critical-rendering-path/index.md
  src/content/en/fundamentals/performance/critical-rendering-path/measure-crp.md
  src/content/en/fundamentals/performance/critical-rendering-path/optimizing-critical-rendering-path.md
  src/content/en/fundamentals/performance/critical-rendering-path/page-speed-rules-and-recommendations.md
  src/content/en/fundamentals/performance/critical-rendering-path/render-blocking-css.md
  src/content/en/fundamentals/performance/critical-rendering-path/render-tree-construction.md
  src/content/en/fundamentals/performance/get-started/graphicalcontent-4.md
  src/content/en/fundamentals/performance/get-started/httpcaching-6.md
  src/content/en/fundamentals/performance/get-started/httprequests-5.md
  src/content/en/fundamentals/performance/get-started/index.md
  src/content/en/fundamentals/performance/get-started/measuringperf-2.md
  src/content/en/fundamentals/performance/get-started/textcontent-3.md
  src/content/en/fundamentals/performance/get-started/wrapup-7.md
  src/content/en/fundamentals/performance/http2/index.md
  src/content/en/fundamentals/performance/navigation-and-resource-timing/index.md
  src/content/en/fundamentals/performance/optimizing-content-efficiency/eliminate-downloads.md
  src/content/en/fundamentals/performance/optimizing-content-efficiency/http-caching.md
  src/content/en/fundamentals/performance/optimizing-content-efficiency/image-optimization.md
  src/content/en/fundamentals/performance/optimizing-content-efficiency/index.md
  src/content/en/fundamentals/performance/optimizing-content-efficiency/optimize-encoding-and-transfer.md
  src/content/en/fundamentals/performance/optimizing-content-efficiency/webfont-optimization.md
  src/content/en/fundamentals/performance/poor-connectivity/index.md
  src/content/en/fundamentals/performance/prpl-pattern/index.md
  src/content/en/fundamentals/performance/rail.md
  src/content/en/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing.md
  src/content/en/fundamentals/performance/rendering/debounce-your-input-handlers.md
  src/content/en/fundamentals/performance/rendering/index.md
  src/content/en/fundamentals/performance/rendering/optimize-javascript-execution.md
  src/content/en/fundamentals/performance/rendering/reduce-the-scope-and-complexity-of-style-calculations.md
  src/content/en/fundamentals/performance/rendering/simplify-paint-complexity-and-reduce-paint-areas.md
  src/content/en/fundamentals/performance/rendering/stick-to-compositor-only-properties-and-manage-layer-count.md
  src/content/en/fundamentals/performance/resource-prioritization.md
  src/content/en/fundamentals/performance/speed-tools/index.md
  src/content/en/fundamentals/performance/user-centric-performance-metrics.md
  src/content/en/fundamentals/performance/webpack/conclusion.md
  src/content/en/fundamentals/performance/webpack/decrease-frontend-size.md
  src/content/en/fundamentals/performance/webpack/index.md
  src/content/en/fundamentals/performance/webpack/monitor-and-analyze.md
  src/content/en/fundamentals/performance/webpack/use-long-term-caching.md
  src/content/en/fundamentals/performance/why-performance-matters/index.md
Labels: P1, cla: yes, section-fundamentals, type-Content

#6512 remove chrome web store script
  src/content/en/tools/lighthouse/index.md
Labels: cla: yes

#6514 Fix typo | Addresses #6498
  src/content/en/ilt/pwa/introduction-to-service-worker.md
Labels: cla: yes

#6523 Update Google Fonts caching advice
  src/content/en/tools/workbox/_index.yaml
  src/content/en/tools/workbox/guides/common-recipes.md
Labels: cla: yes

#6524 [devtools] edit content in DOM tutorial
  src/content/en/tools/chrome-devtools/beginners/html.md
  src/content/en/tools/chrome-devtools/beginners/imgs/2tabs.png
  src/content/en/tools/chrome-devtools/beginners/imgs/add1.png
  src/content/en/tools/chrome-devtools/beginners/imgs/add2.png
  src/content/en/tools/chrome-devtools/beginners/imgs/add3.png
  src/content/en/tools/chrome-devtools/beginners/imgs/add4.png
  src/content/en/tools/chrome-devtools/beginners/imgs/add5.png
  src/content/en/tools/chrome-devtools/beginners/imgs/copy1.png
  src/content/en/tools/chrome-devtools/beginners/imgs/copy2.png
  src/content/en/tools/chrome-devtools/beginners/imgs/delete1.png
  src/content/en/tools/chrome-devtools/beginners/imgs/delete2.png
  src/content/en/tools/chrome-devtools/beginners/imgs/dom1.png
  src/content/en/tools/chrome-devtools/beginners/imgs/dom2.png
  src/content/en/tools/chrome-devtools/beginners/imgs/dom3.png
  src/content/en/tools/chrome-devtools/beginners/imgs/dom4.png
  src/content/en/tools/chrome-devtools/beginners/imgs/edit1.png
  src/content/en/tools/chrome-devtools/beginners/imgs/edit2.png
  src/content/en/tools/chrome-devtools/beginners/imgs/edit3.png
  src/content/en/tools/chrome-devtools/beginners/imgs/editashtml.png
  src/content/en/tools/chrome-devtools/beginners/imgs/elpanel.png
  src/content/en/tools/chrome-devtools/beginners/imgs/endgame.png
  src/content/en/tools/chrome-devtools/beginners/imgs/init.png
  src/content/en/tools/chrome-devtools/beginners/imgs/inspectel.png
  src/content/en/tools/chrome-devtools/beginners/imgs/list.png
  src/content/en/tools/chrome-devtools/beginners/imgs/menu.png
  src/content/en/tools/chrome-devtools/beginners/imgs/reorder1.png
  src/content/en/tools/chrome-devtools/beginners/imgs/reorder2.png
  src/content/en/tools/chrome-devtools/beginners/imgs/reorder3.png
  src/content/en/tools/chrome-devtools/beginners/imgs/setup1.png
  src/content/en/tools/chrome-devtools/beginners/imgs/setup2.png
  src/content/en/tools/chrome-devtools/beginners/imgs/setup3.png
  src/content/en/tools/chrome-devtools/beginners/imgs/setup4.png
  src/content/en/tools/chrome-devtools/beginners/imgs/siteview.png
  src/content/en/tools/chrome-devtools/index.md
Labels: P1, cla: yes, section-tools, type-Content

#6473 [devtools] add first tutorial in beginners series
  src/content/en/images/contributors/katjackson.jpg
  src/content/en/tools/chrome-devtools/_toc.yaml
  src/content/en/tools/chrome-devtools/beginners/html.md
  src/content/en/tools/chrome-devtools/beginners/imgs/add1.png
  src/content/en/tools/chrome-devtools/beginners/imgs/add2.png
  src/content/en/tools/chrome-devtools/beginners/imgs/add3.png
  src/content/en/tools/chrome-devtools/beginners/imgs/add4.png
  src/content/en/tools/chrome-devtools/beginners/imgs/add5.png
  src/content/en/tools/chrome-devtools/beginners/imgs/copy1.png
  src/content/en/tools/chrome-devtools/beginners/imgs/copy2.png
  src/content/en/tools/chrome-devtools/beginners/imgs/delete1.png
  src/content/en/tools/chrome-devtools/beginners/imgs/delete2.png
  src/content/en/tools/chrome-devtools/beginners/imgs/dom1.png
  src/content/en/tools/chrome-devtools/beginners/imgs/dom2.png
  src/content/en/tools/chrome-devtools/beginners/imgs/dom3.png
  src/content/en/tools/chrome-devtools/beginners/imgs/dom4.png
  src/content/en/tools/chrome-devtools/beginners/imgs/edit1.png
  src/content/en/tools/chrome-devtools/beginners/imgs/edit2.png
  src/content/en/tools/chrome-devtools/beginners/imgs/edit3.png
  src/content/en/tools/chrome-devtools/beginners/imgs/finished.png
  src/content/en/tools/chrome-devtools/beginners/imgs/reorder1.png
  src/content/en/tools/chrome-devtools/beginners/imgs/reorder2.png
  src/content/en/tools/chrome-devtools/beginners/imgs/reorder3.png
  src/content/en/tools/chrome-devtools/beginners/imgs/setup1.png
  src/content/en/tools/chrome-devtools/beginners/imgs/setup2.png
  src/content/en/tools/chrome-devtools/beginners/imgs/setup3.png
  src/content/en/tools/chrome-devtools/beginners/imgs/setup4.png
  src/content/en/tools/chrome-devtools/index.md
  src/data/_contributors.yaml
Labels: DO NOT MERGE, P1, cla: yes, section-tools, type-Content

#6521 Added Web Perf Made Easy article
  src/content/en/updates/2018/08/images/web-performance-made-easy/after-code-splitting.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/avoid-invisible-text.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/avoid-round-trips.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/bundle-auditing.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/code-coverage-gains.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/code-coverage.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/enormous-payload.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/font-display.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/guess.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/image-audits.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/js-bootup-time.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/js-processing.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/minify.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/new-lighthouse-audits.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/oodle-priority.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/oodles-report.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/optimize-images.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/perceived-perf.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/perf-joke.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/pizza.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/predictive-bundling.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/preload-font.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/preload.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/priority-hints.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/regression.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/replace-video.png
  src/content/en/updates/2018/08/images/web-performance-made-easy/ux-hierarchy.png
  src/content/en/updates/2018/08/web-performance-made-easy.md
Labels: cla: yes

#6450 Add site audit articles to performance section
  src/content/en/fundamentals/performance/_toc.yaml
  src/content/en/fundamentals/performance/audit/images/devtools-349KB.png
  src/content/en/fundamentals/performance/audit/images/devtools-security-1000.png
  src/content/en/fundamentals/performance/audit/images/devtools-security-500.png
  src/content/en/fundamentals/performance/audit/images/lighthouse-download-1000.png
  src/content/en/fundamentals/performance/audit/images/lighthouse-download-500.png
  src/content/en/fundamentals/performance/audit/images/lighthouse-gist-1000.png
  src/content/en/fundamentals/performance/audit/images/lighthouse-gist-500.png
  src/content/en/fundamentals/performance/audit/images/not-secure.png
  src/content/en/fundamentals/performance/audit/images/site-cost-1000.png
  src/content/en/fundamentals/performance/audit/images/site-cost-500.png
  src/content/en/fundamentals/performance/audit/images/site-speed-1000.png
  src/content/en/fundamentals/performance/audit/images/site-speed-500.png
  src/content/en/fundamentals/performance/audit/images/task-manager.png
  src/content/en/fundamentals/performance/audit/images/two-devices.jpg
  src/content/en/fundamentals/performance/audit/index.md
  src/content/en/fundamentals/performance/audit/next.md
  src/content/en/fundamentals/performance/audit/prework.md
  src/content/en/fundamentals/performance/audit/security.md
  src/content/en/fundamentals/performance/audit/share.md
  src/content/en/fundamentals/performance/audit/tools.md
Labels: cla: yes, needs-CopyEdit, type-Content

#6526 Article about porting the AV1 video decoder to WebAssembly
  src/content/en/updates/2018/08/wasm-av1.md
Labels: cla: yes, section-updates

#6528 Fix broken link
  src/content/en/updates/2018/08/wasm-av1.md
Labels: cla: yes, section-updates

#6531 Tip about getting a fresh response body in cacheDidUpdate
  src/content/en/tools/workbox/guides/using-plugins.md
Labels: cla: yes

#6532 [devtools] update the HAR section
  src/content/en/tools/chrome-devtools/network-performance/reference.md
Labels: P2, cla: yes, section-tools, type-Content

#6522 New wasm embind article
  src/content/en/updates/2018/08/embind.md
  src/content/en/updates/images/2018/08/embind/code.png
  src/content/en/updates/images/2018/08/embind/error.png
Labels: cla: yes

#6533 [devtools] embed video version of speed tutorial
  src/content/en/tools/chrome-devtools/speed/get-started.md
Labels: P1, cla: yes, section-tools, type-Content

#6534 [devtools] update the homepage
  src/content/en/tools/chrome-devtools/index.md
Labels: P1, cla: yes, section-tools, type-Content

#6530 Remove + redirect outdated Workbox slide landing page
  src/content/en/ilt/_redirects.yaml
  src/content/en/ilt/pwa/_book.yaml
  src/content/en/ilt/pwa/workbox-slides.md
Labels: cla: yes

#6541 Add note for Windows 10
  src/content/en/updates/2015/07/interact-with-ble-devices-on-the-web.md
Labels: cla: yes, type-Content

#6542 update 2 sections to show how to make them publish-ready
  src/content/en/tools/chrome-devtools/beginners/css.md
  src/content/en/tools/chrome-devtools/beginners/imgs/css/intro1.png
  src/content/en/tools/chrome-devtools/beginners/imgs/css/intro2.png
  src/content/en/tools/chrome-devtools/beginners/imgs/css/setup1.png
  src/content/en/tools/chrome-devtools/beginners/imgs/css/setup2.png
  src/content/en/tools/chrome-devtools/beginners/imgs/css/setup3.png
Labels: P1, cla: yes, section-tools, type-Content

#6544 Grammar fixes
  src/content/en/fundamentals/app-install-banners/index.md
Labels: cla: yes

#6536 OffscreeCanvas: Fix inlined markdown link in HTML section
  src/content/en/updates/2018/08/offscreen-canvas.md
Labels: cla: yes

#6509 Fix duplicate alt attributes
  src/content/ar/fundamentals/performance/critical-rendering-path/analyzing-crp.md
  src/content/de/fundamentals/performance/critical-rendering-path/analyzing-crp.md
  src/content/en/fundamentals/performance/critical-rendering-path/analyzing-crp.md
  src/content/es/fundamentals/performance/critical-rendering-path/analyzing-crp.md
  src/content/fr/fundamentals/performance/critical-rendering-path/analyzing-crp.md
  src/content/id/fundamentals/performance/critical-rendering-path/analyzing-crp.md
  src/content/it/fundamentals/performance/critical-rendering-path/analyzing-crp.md
  src/content/ja/fundamentals/performance/critical-rendering-path/analyzing-crp.md
  src/content/ko/fundamentals/performance/critical-rendering-path/analyzing-crp.md
  src/content/nl/fundamentals/performance/critical-rendering-path/analyzing-crp.md
  src/content/pl/fundamentals/performance/critical-rendering-path/analyzing-crp.md
  src/content/pt-br/fundamentals/performance/critical-rendering-path/analyzing-crp.md
  src/content/ru/fundamentals/performance/critical-rendering-path/analyzing-crp.md
  src/content/tr/fundamentals/performance/critical-rendering-path/analyzing-crp.md
  src/content/zh-cn/fundamentals/performance/critical-rendering-path/analyzing-crp.md
  src/content/zh-tw/fundamentals/performance/critical-rendering-path/analyzing-crp.md
Labels: cla: yes

#6508 Fix typo
  src/content/de/fundamentals/performance/critical-rendering-path/analyzing-crp.md
Labels: cla: yes

#6507 Fix typo ja critical-rendering-path
  src/content/ja/fundamentals/performance/critical-rendering-path/adding-interactivity-with-javascript.md
  src/content/ja/fundamentals/performance/critical-rendering-path/analyzing-crp.md
  src/content/ja/fundamentals/performance/critical-rendering-path/constructing-the-object-model.md
  src/content/ja/fundamentals/performance/critical-rendering-path/index.md
  src/content/ja/fundamentals/performance/critical-rendering-path/measure-crp.md
  src/content/ja/fundamentals/performance/critical-rendering-path/page-speed-rules-and-recommendations.md
  src/content/ja/fundamentals/performance/critical-rendering-path/render-blocking-css.md
  src/content/ja/fundamentals/performance/critical-rendering-path/render-tree-construction.md
Labels: cla: yes

#6494 Update web agencies JSON
  src/content/en/agencies/data/agencies.json
Labels: P3, cla: yes, section-agencies, type-Content

#6447 Add update message to existing AR/VR articles.
  src/content/en/updates/2018/05/welcome-to-immersive.md
  src/content/en/updates/2018/06/ar-for-the-web.md
  src/content/en/updates/2018/06/webar-chacmool.md
Labels: cla: yes

#6547 ILT & Code Lab Updates
  src/content/en/ilt/pwa/img/290daea91df4c1a4.png
  src/content/en/ilt/pwa/img/35efeeeabb7cd6ee.png
  src/content/en/ilt/pwa/img/66c556928e5120d7.png
  src/content/en/ilt/pwa/img/8b1dd4e1fcbfa1ce.png
  src/content/en/ilt/pwa/img/8ce3de94fa0d4691.png
  src/content/en/ilt/pwa/img/a04fbe987867d477.png
  src/content/en/ilt/pwa/img/d6318271a453de45.png
  src/content/en/ilt/pwa/img/e11f7fd7ee1efd5f.png
  src/content/en/ilt/pwa/img/e7f833e549e1ee5f.png
  src/content/en/ilt/pwa/img/f563fd774d4d0b5d.png
  src/content/en/ilt/pwa/lab-auditing-with-lighthouse.md
  src/content/en/ilt/pwa/lab-caching-files-with-service-worker.md
  src/content/en/ilt/pwa/lab-fetch-api.md
  src/content/en/ilt/pwa/lab-gulp-setup.md
  src/content/en/ilt/pwa/lab-indexeddb.md
  src/content/en/ilt/pwa/lab-integrating-analytics.md
  src/content/en/ilt/pwa/lab-integrating-web-push.md
  src/content/en/ilt/pwa/lab-migrating-to-workbox-from-sw-precache-and-sw-toolbox.md
  src/content/en/ilt/pwa/lab-offline-quickstart.md
  src/content/en/ilt/pwa/lab-promises.md
  src/content/en/ilt/pwa/lab-responsive-design.md
  src/content/en/ilt/pwa/lab-responsive-images.md
  src/content/en/ilt/pwa/lab-scripting-the-service-worker.md
  src/content/en/ilt/pwa/lab-workbox.md
  src/content/en/ilt/pwa/setting-up-the-labs.md
  src/content/en/updates/2017/12/audio-worklet.md
  src/data/blinkComponents.json
  src/data/codelabs/your-first-pwapp/codelab.json
  src/data/ilt-pwa/lab-auditing-with-lighthouse/codelab.json
  src/data/ilt-pwa/lab-caching-files-with-service-worker/codelab.json
  src/data/ilt-pwa/lab-fetch-api/codelab.json
  src/data/ilt-pwa/lab-gulp-setup/codelab.json
  src/data/ilt-pwa/lab-indexeddb/codelab.json
  src/data/ilt-pwa/lab-integrating-analytics/codelab.json
  src/data/ilt-pwa/lab-integrating-web-push/codelab.json
  src/data/ilt-pwa/lab-migrating-to-workbox-from-sw-precache-and-sw-toolbox/codelab.json
  src/data/ilt-pwa/lab-offline-quickstart/codelab.json
  src/data/ilt-pwa/lab-promises/codelab.json
  src/data/ilt-pwa/lab-responsive-design/codelab.json
  src/data/ilt-pwa/lab-responsive-images/codelab.json
  src/data/ilt-pwa/lab-scripting-the-service-worker/codelab.json
  src/data/ilt-pwa/lab-workbox/codelab.json
  src/data/ilt-pwa/setting-up-the-labs/codelab.json
Labels: cla: yes

#6554 [devtools] add WNDT70
  src/content/en/updates/2018/08/devtools.md
  src/content/en/updates/images/2018/08/audiocontext.png
  src/content/en/updates/images/2018/08/autocomplete.png
  src/content/en/updates/images/2018/08/create-live-expression.png
  src/content/en/updates/images/2018/08/live1.png
  src/content/en/updates/images/2018/08/live2.png
  src/content/en/updates/images/2018/08/live3.png
  src/content/en/updates/images/2018/08/malformed.png
  src/content/en/updates/images/2018/08/memory.png
  src/content/en/updates/images/2018/08/ndb.png
  src/content/en/updates/images/2018/08/node.png
  src/content/en/updates/images/2018/08/performance.png
  src/content/en/updates/images/2018/08/throttling.png
Labels: P1, cla: yes, section-updates, type-Content

#6571 [devtools] update wndt70
  src/content/en/tools/chrome-devtools/console/command-line-reference.md
  src/content/en/updates/2018/08/devtools.md
  src/content/en/updates/images/2018/08/live1.png
  src/content/en/updates/images/2018/08/live2.png
  src/content/en/updates/images/2018/08/live3.png
  src/content/en/updates/images/2018/08/node.png
Labels: P1, cla: yes, section-updates, type-Content
