Repository google/WebFundamentals, pull requests merged in 2018-04, with the labels that each got.

#5968 Add an update about the macOS native echo cancellation trial in M66.
  src/content/en/updates/2018/03/macos-native-echo-cancellation.md
Labels: cla: yes

#5958 Puppeteer: ssr with headless chrome article.
  src/content/en/tools/puppeteer/_toc.yaml
  src/content/en/tools/puppeteer/articles/images/chromestatus-normal.png
  src/content/en/tools/puppeteer/articles/images/chromestatus-prerender.png
  src/content/en/tools/puppeteer/articles/ssr.md
Labels: cla: yes, section-tools

#5974 Feeds for tools/showcase/fundamentals per year
  gulp-tasks/build.js
  gulp-tasks/wfTemplateHelper.js
  gulpfile.js
Labels: cla: yes, type-Infrastructure

#5995 [devtools] attempt to fix devsite bug with verbatim tag
  src/content/en/tools/chrome-devtools/console/get-started.md
Labels: P1, cla: yes, section-tools, type-Content

#5992 ssr pptr: fix typo.
  src/content/en/tools/puppeteer/articles/ssr.md
Labels: cla: yes, type-Content

#5997 [lighthouse] add redirects reference; update template
  src/content/en/tools/lighthouse/_toc.yaml
  src/content/en/tools/lighthouse/audits/_template.md
  src/content/en/tools/lighthouse/audits/redirects.md
Labels: P1, cla: yes, section-tools, type-Content

#5996 Webpack article fixes
  src/content/en/fundamentals/performance/webpack/decrease-frontend-size.md
Labels: cla: yes

#5993 Added a missing `new` to a Workbox webpack guide
  src/content/en/tools/workbox/guides/precache-files/webpack.md
Labels: cla: yes

#5999 Updated voot lite logo
  src/content/en/showcase/2017/images/voot/voot-lite.png
Labels: cla: yes

#5998 Adding Save-Data updates.
  src/content/en/_redirects.yaml
  src/content/en/fundamentals/performance/_toc.yaml
  src/content/en/fundamentals/performance/optimizing-content-efficiency/save-data/images/omitted-images-1x.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/save-data/images/omitted-images-2x.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/save-data/index.md
  src/content/en/updates/2016/02/save-data.md
Labels: DO NOT MERGE, cla: yes

#6005 Fix typo
  src/content/en/tools/workbox/modules/workbox-webpack-plugin.md
Labels: cla: yes

#6004 Wider audio podcast element
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E01-creating-a-collaborative-environment.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E02-balancing-creativity-with-user-testing.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E03-Adopting-the-native-language-of-the-web.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E04-are-designers-born-or-made.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E05-who-is-responsible-for-design.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E06-are-design-tools-fit-for-purpose.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E01-becoming-a-creative-coder.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E02-designing-a-great-performance.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E03-improving-your-creative-confidence.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E04-learn-how-to-design.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E05-designing-for-the-next-billion-users.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E06-how-the-web-can-compete-with-native.md
  src/content/en/shows/http203/podcast/a-is-for-effort.md
  src/content/en/shows/http203/podcast/cooties-symbols-and-shaders.md
  src/content/en/shows/http203/podcast/eventtarget-imports-and-nudists.md
  src/content/en/shows/http203/podcast/http-203-cors-forced-layouts-and-raptor-kebab-shops.md
  src/content/en/shows/http203/podcast/http-203-legs-wasps-and-web-stuff.md
  src/content/en/shows/http203/podcast/http-203-making-burgers-and-maintainable-code.md
  src/content/en/shows/http203/podcast/http-203-poetry-and-delegated-event-listeners.md
  src/content/en/shows/http203/podcast/http-203-promises-mistakes-and-door-handles.md
  src/content/en/shows/http203/podcast/http-203-quizzing-animating-and-canceling.md
  src/content/en/shows/http203/podcast/http-203-slippers-and-chips.md
  src/content/en/shows/http203/podcast/http-203-springy-css-storage-and-bisecting.md
  src/content/en/shows/http203/podcast/twelve-things-for-2018.md
  src/content/en/shows/http203/podcast/web-whispers-and-sleepy-thoughts.md
  src/content/en/shows/http203/podcast/webrtc-again-and-about-blank.md
  src/content/en/shows/http203/podcast/wet-nose-cough.md
Labels: cla: yes

#6002 Fix: Lazy-loading images image path
  src/content/en/fundamentals/performance/lazy-loading-guidance/images-and-video/index.md
Labels: cla: yes, type-Content

#5980 Add Presentation API article
  src/content/en/updates/2018/04/present-web-pages-to-secondary-attached-displays.md
  src/content/en/updates/images/2018/04/present-web-pages-to-secondary-attached-displays/hero.jpg
  src/content/en/updates/images/2018/04/present-web-pages-to-secondary-attached-displays/inspect.png
  src/content/en/updates/images/2018/04/present-web-pages-to-secondary-attached-displays/picker.png
  src/content/en/updates/images/2018/04/present-web-pages-to-secondary-attached-displays/step1.jpg
  src/content/en/updates/images/2018/04/present-web-pages-to-secondary-attached-displays/step2.jpg
Labels: cla: yes, type-Content

#5966 [Translation zh-tw] Updates > 2017 > 04 > Devtools Release Notes
  src/content/zh-tw/updates/2017/04/devtools-release-notes.md
Labels: cla: no

#6009 Catch typos in translations
  src/data/common-typos.yaml
Labels: cla: yes

#6003 Explain rel=noreferrer as well as rel=noopener
  src/content/en/tools/lighthouse/audits/noopener.md
Labels: cla: yes

#6010 Fix typo: console.err is not a function
  src/content/en/tools/puppeteer/articles/ssr.md
Labels: cla: yes

#5982 [Translation zh-cn] Updates > 2017 > 09 > Sensors For The Web!
  src/content/zh-cn/updates/2017/09/sensors-for-the-web.md
  src/data/_contributors.yaml
Labels: cla: no

#5659 [Translation it] Fundamentals > Payments > Android Pay
  src/content/it/fundamentals/payments/android-pay.md
Labels: cla: no

#5645 [Translation it] Fundamentals > Payments
  src/content/it/fundamentals/payments/index.md
Labels: cla: no

#6012 404 fixes
  src/content/en/ilt/pwa/index.md
  src/content/en/tools/lighthouse/index.md
  src/content/en/tools/workbox/guides/codelabs/_shared/end.md
Labels: cla: yes

#6011 getText() -> readText()
  src/content/en/updates/2018/03/clipboardapi.md
Labels: cla: yes

#6020 Update insecure video src from 'https' to 'http'
  src/content/en/fundamentals/security/prevent-mixed-content/_code/passive-mixed-content.html
Labels: cla: yes

#6016 Fixed typo
  src/content/en/tools/workbox/guides/advanced-recipes.md
Labels: cla: yes

#6015 fixes small grammatical error on Text Alternatives for Images
  src/content/en/fundamentals/accessibility/semantics-builtin/text-alternatives-for-images.md
Labels: cla: yes

#6013 Claat strip whitespace
  gulp-tasks/wfCodeLabHelper.js
  src/content/en/fundamentals/codelabs/debugging-service-workers/index.md
  src/content/en/fundamentals/codelabs/offline/index.md
  src/content/en/fundamentals/codelabs/payment-request-api/index.md
  src/content/en/fundamentals/codelabs/push-notifications/index.md
  src/content/en/fundamentals/codelabs/web-perf/index.md
  src/content/en/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/en/ilt/pwa/caching-files-with-service-worker.md
  src/content/en/ilt/pwa/e-commerce-lab-1-create-a-service-worker.md
  src/content/en/ilt/pwa/e-commerce-lab-2-add-to-homescreen.md
  src/content/en/ilt/pwa/integrating-analytics.md
  src/content/en/ilt/pwa/introduction-to-gulp.md
  src/content/en/ilt/pwa/introduction-to-progressive-web-app-architectures.md
  src/content/en/ilt/pwa/introduction-to-push-notifications.md
  src/content/en/ilt/pwa/introduction-to-service-worker.md
  src/content/en/ilt/pwa/introduction-to-the-payment-request-api.md
  src/content/en/ilt/pwa/lab-auditing-with-lighthouse.md
  src/content/en/ilt/pwa/lab-caching-files-with-service-worker.md
  src/content/en/ilt/pwa/lab-fetch-api.md
  src/content/en/ilt/pwa/lab-gulp-setup.md
  src/content/en/ilt/pwa/lab-indexeddb.md
  src/content/en/ilt/pwa/lab-integrating-analytics.md
  src/content/en/ilt/pwa/lab-integrating-web-push.md
  src/content/en/ilt/pwa/lab-migrating-to-workbox-from-sw-precache-and-sw-toolbox.md
  src/content/en/ilt/pwa/lab-offline-quickstart.md
  src/content/en/ilt/pwa/lab-promises.md
  src/content/en/ilt/pwa/lab-responsive-design.md
  src/content/en/ilt/pwa/lab-responsive-images.md
  src/content/en/ilt/pwa/lab-scripting-the-service-worker.md
  src/content/en/ilt/pwa/lab-workbox.md
  src/content/en/ilt/pwa/lighthouse-pwa-analysis-tool.md
  src/content/en/ilt/pwa/live-data-in-the-service-worker.md
  src/content/en/ilt/pwa/offline-quickstart.md
  src/content/en/ilt/pwa/setting-up-the-labs.md
  src/content/en/ilt/pwa/tools-for-pwa-developers.md
  src/content/en/ilt/pwa/working-with-indexeddb.md
  src/content/en/ilt/pwa/working-with-promises.md
  src/content/en/ilt/pwa/working-with-the-fetch-api.md
Labels: cla: yes

#6001 [zh-tw] Workbox - Guides - Get Started
  src/content/zh-tw/tools/workbox/guides/get-started.md
Labels: cla: no

#6021 Fix typo: undefined stylesheetContents variable
  src/content/en/tools/puppeteer/articles/ssr.md
Labels: cla: yes

#6024 Small typo fix for the Workbox landing page
  src/content/en/tools/workbox/_index.yaml
Labels: cla: yes

#6026 [Sensors For The Web] Update the artice as motion sensors are shipped
  src/content/en/updates/2017/09/sensors-for-the-web.md
Labels: cla: yes

#6025 Correcting PolyFill Link
  src/content/en/tools/lighthouse/audits/offscreen-images.md
Labels: cla: yes

#6028 Minor tweaks and fixes to the Save-Data article.
  src/content/en/fundamentals/performance/optimizing-content-efficiency/save-data/index.md
Labels: cla: yes

#6030 Fix typo and change my website URL
  src/content/en/ilt/pwa/introduction-to-service-worker.md
  src/content/en/ilt/pwa/live-data-in-the-service-worker.md
  src/content/en/ilt/pwa/working-with-indexeddb.md
  src/content/en/updates/2016/03/access-usb-devices-on-the-web.md
  src/content/en/updates/2018/03/chrome-66-deprecations.md
  src/data/_contributors.yaml
Labels: cla: yes

#6031 [Sensors For The Web] Remove references to old OriginTrials
  src/content/en/updates/2017/09/sensors-for-the-web.md
Labels: cla: no

#6033 [devtools] add WNDT67
  src/content/en/updates/2018/04/devtools.md
  src/content/en/updates/images/2018/04/audit-config.png
  src/content/en/updates/images/2018/04/bottom-up.png
  src/content/en/updates/images/2018/04/certificate-transparency.png
  src/content/en/updates/images/2018/04/dark-theme.png
  src/content/en/updates/images/2018/04/fetch.png
  src/content/en/updates/images/2018/04/js-vm.png
  src/content/en/updates/images/2018/04/match-case.png
  src/content/en/updates/images/2018/04/memory-isolation.png
  src/content/en/updates/images/2018/04/network-search.png
  src/content/en/updates/images/2018/04/page.png
  src/content/en/updates/images/2018/04/pause.png
  src/content/en/updates/images/2018/04/perf-isolation.png
  src/content/en/updates/images/2018/04/regex.png
  src/content/en/updates/images/2018/04/search-ui.png
  src/content/en/updates/images/2018/04/stop.png
  src/content/en/updates/images/2018/04/use-regex.png
  src/content/en/updates/images/2018/04/view-trace.png
Labels: P0, cla: yes, section-updates, type-Content

#6035 Fixing an innacuracy in an image in the Save-Data article.
  src/content/en/fundamentals/performance/optimizing-content-efficiency/save-data/images/omitted-images-1x.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/save-data/images/omitted-images-2x.png
Labels: cla: yes

#6037 Fix nits in "Loading WebAssembly modules" article
  src/content/en/updates/2018/04/loading-wasm.md
Labels: cla: yes

#6032 Fixed broken layout on contributors page
  src/data/_contributors.yaml
Labels: cla: yes

#6039 Weekly ILT & code lab updates
  gulp-tasks/wfUpdatedOn.js
  src/content/en/fundamentals/codelabs/debugging-service-workers/index.md
  src/content/en/fundamentals/codelabs/offline/index.md
  src/content/en/fundamentals/codelabs/payment-request-api/index.md
  src/content/en/fundamentals/codelabs/push-notifications/index.md
  src/content/en/fundamentals/codelabs/web-perf/index.md
  src/content/en/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/en/ilt/pwa/caching-files-with-service-worker.md
  src/content/en/ilt/pwa/e-commerce-lab-1-create-a-service-worker.md
  src/content/en/ilt/pwa/e-commerce-lab-2-add-to-homescreen.md
  src/content/en/ilt/pwa/integrating-analytics.md
  src/content/en/ilt/pwa/introduction-to-gulp.md
  src/content/en/ilt/pwa/introduction-to-progressive-web-app-architectures.md
  src/content/en/ilt/pwa/introduction-to-push-notifications.md
  src/content/en/ilt/pwa/introduction-to-service-worker.md
  src/content/en/ilt/pwa/introduction-to-the-payment-request-api.md
  src/content/en/ilt/pwa/lab-auditing-with-lighthouse.md
  src/content/en/ilt/pwa/lab-caching-files-with-service-worker.md
  src/content/en/ilt/pwa/lab-fetch-api.md
  src/content/en/ilt/pwa/lab-gulp-setup.md
  src/content/en/ilt/pwa/lab-indexeddb.md
  src/content/en/ilt/pwa/lab-integrating-analytics.md
  src/content/en/ilt/pwa/lab-integrating-web-push.md
  src/content/en/ilt/pwa/lab-migrating-to-workbox-from-sw-precache-and-sw-toolbox.md
  src/content/en/ilt/pwa/lab-offline-quickstart.md
  src/content/en/ilt/pwa/lab-promises.md
  src/content/en/ilt/pwa/lab-responsive-design.md
  src/content/en/ilt/pwa/lab-responsive-images.md
  src/content/en/ilt/pwa/lab-scripting-the-service-worker.md
  src/content/en/ilt/pwa/lab-workbox.md
  src/content/en/ilt/pwa/lighthouse-pwa-analysis-tool.md
  src/content/en/ilt/pwa/offline-quickstart.md
  src/content/en/ilt/pwa/setting-up-the-labs.md
  src/content/en/ilt/pwa/tools-for-pwa-developers.md
  src/content/en/ilt/pwa/working-with-promises.md
  src/content/en/ilt/pwa/working-with-the-fetch-api.md
  src/data/blinkComponents.json
  src/data/codelabs/your-first-pwapp/codelab.json
  src/data/ilt-pwa/introduction-to-service-worker/codelab.json
  src/data/ilt-pwa/lab-workbox/codelab.json
  src/data/ilt-pwa/live-data-in-the-service-worker/codelab.json
  src/data/ilt-pwa/working-with-indexeddb/codelab.json
Labels: cla: yes

#6038 Tweak Emscripten article
  src/content/en/updates/2018/03/emscripting-a-c-library.md
Labels: cla: yes

#6043 Fix console.log in "Loading WASM" article
  src/content/en/updates/2018/04/loading-wasm.md
Labels: cla: yes

#6047 Clarify that WebAssembly.Instance also has the 4 KB limit
  src/content/en/updates/2018/04/loading-wasm.md
Labels: cla: yes

#6044 Add WebAssembly Studio link
  src/content/en/updates/2018/04/loading-wasm.md
Labels: cla: yes

#6042 Update app-shell.md - Remove duplicate title
  src/content/en/fundamentals/architecture/app-shell.md
Labels: cla: no

#6027 Workbox makeRequest() recipe
  src/content/en/tools/workbox/guides/advanced-recipes.md
Labels: cla: yes

#6053 Fixed 404 link in `decrease-frontend-size`
  src/content/en/fundamentals/performance/webpack/decrease-frontend-size.md
Labels: cla: no

#6048 customelements: update for custom built-in shipping
  src/content/en/fundamentals/web-components/customelements.md
Labels: cla: yes

#6055 Workbox latest docs
  src/content/en/tools/workbox/_footer.yaml
  src/content/en/tools/workbox/_shared/config/single/importScripts.html
  src/content/en/tools/workbox/_shared/config/single/injectionPointRegexp.html
  src/content/en/tools/workbox/_shared/config/single/manifestTransforms.html
  src/content/en/tools/workbox/_shared/config/single/navigateFallback.html
  src/content/en/tools/workbox/_shared/config/single/runtimeCaching.html
  src/content/en/tools/workbox/_shared/config/single/swSrc.html
  src/content/en/tools/workbox/_shared/config/webpack-single/swSrc.html
  src/content/en/tools/workbox/guides/advanced-recipes.md
  src/content/en/tools/workbox/guides/migrations/migrate-from-v2.md
  src/content/en/tools/workbox/guides/using-plugins.md
  src/content/en/tools/workbox/modules/_index.yaml
  src/content/en/tools/workbox/modules/workbox-cache-expiration.md
  src/content/en/tools/workbox/modules/workbox-google-analytics.md
  src/content/en/tools/workbox/modules/workbox-range-requests.md
  src/content/en/tools/workbox/modules/workbox-routing.md
  src/content/en/tools/workbox/modules/workbox-strategies.md
Labels: cla: no

#6057 Update links to the Origin Trial Guide.
  src/content/en/updates/2015/07/interact-with-ble-devices-on-the-web.md
  src/content/en/updates/2016/03/access-usb-devices-on-the-web.md
  src/content/en/updates/2016/06/persistent-storage.md
  src/content/en/updates/2016/09/foreign-fetch.md
  src/content/en/updates/2016/09/navigator-share.md
  src/content/en/updates/2016/11/nic55.md
  src/content/en/updates/2017/02/navigation-preload.md
  src/content/en/updates/2017/04/chrome-59-deprecations.md
  src/content/en/updates/2017/04/getinstalledrelatedapps.md
  src/content/en/updates/2017/06/budget-api.md
Labels: cla: yes

#6058 NIC66 post
  src/content/en/updates/2018/04/nic66.md
Labels: cla: yes

#6061 [devtools] add vid to wndt66
  src/content/en/updates/2018/02/devtools.md
Labels: P1, cla: yes, section-updates, type-Content

#6060 HTTP 203 episode 16
  src/content/en/shows/http203/podcast/smooshy-wasm-stacks.md
Labels: cla: yes, type-Content

#6067 Info about the crossorigin attribute in the Workbox cross origin guide
  src/content/en/tools/workbox/guides/handle-third-party-requests.md
Labels: cla: yes

#6050 Adding guide for replacing GIFs with video.
  src/content/en/fundamentals/performance/_toc.yaml
  src/content/en/fundamentals/performance/optimizing-content-efficiency/replace-animated-gifs-with-video/images/gif-in-dev-tools-1x.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/replace-animated-gifs-with-video/images/gif-in-dev-tools-2x.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/replace-animated-gifs-with-video/images/gif-perf-panel-1x.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/replace-animated-gifs-with-video/images/gif-perf-panel-2x.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/replace-animated-gifs-with-video/images/gif-vs-mp4-1x.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/replace-animated-gifs-with-video/images/gif-vs-mp4-2x.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/replace-animated-gifs-with-video/images/mp4-vs-webm-1x.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/replace-animated-gifs-with-video/images/mp4-vs-webm-2x.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/replace-animated-gifs-with-video/index.md
  src/content/en/images/contributors/jeremywagner.jpg
Labels: cla: yes, section-fundamentals

#6070 NIC 66: Add AudioWorklet section
  src/content/en/updates/2018/04/nic66.md
Labels: cla: no

#6068 Fixes typo & updates title in NIC66 post
  src/content/en/updates/2018/04/nic66.md
Labels: cla: yes

#6071 Add link to SmooshGate explainer
  src/content/en/shows/http203/podcast/smooshy-wasm-stacks.md
Labels: cla: yes

#6075 Fixing issues with left hand navigation on new articles.
  src/content/en/fundamentals/performance/_toc.yaml
  src/content/en/fundamentals/performance/optimizing-content-efficiency/replace-animated-gifs-with-video/index.md
  src/content/en/fundamentals/performance/optimizing-content-efficiency/save-data/index.md
Labels: cla: yes

#6076 Removing comment widget on Save-Data article.
  src/content/en/fundamentals/performance/optimizing-content-efficiency/save-data/index.md
Labels: cla: yes

#6077 Fix error when parsing HTML page without <html> on devserver
  devsiteParseHTML.py
Labels: cla: yes

#6080 [devtools] add workspaces tutorial
  src/content/en/tools/chrome-devtools/_toc.yaml
  src/content/en/tools/chrome-devtools/workspaces/imgs/cake.png
  src/content/en/tools/chrome-devtools/workspaces/imgs/cakehtml.png
  src/content/en/tools/chrome-devtools/workspaces/imgs/commandmenu.png
  src/content/en/tools/chrome-devtools/workspaces/imgs/console.png
  src/content/en/tools/chrome-devtools/workspaces/imgs/demo.png
  src/content/en/tools/chrome-devtools/workspaces/imgs/download.png
  src/content/en/tools/chrome-devtools/workspaces/imgs/filesystem.png
  src/content/en/tools/chrome-devtools/workspaces/imgs/fuchsia.png
  src/content/en/tools/chrome-devtools/workspaces/imgs/glitch.png
  src/content/en/tools/chrome-devtools/workspaces/imgs/green.png
  src/content/en/tools/chrome-devtools/workspaces/imgs/italic.png
  src/content/en/tools/chrome-devtools/workspaces/imgs/mapping.png
  src/content/en/tools/chrome-devtools/workspaces/imgs/open.png
  src/content/en/tools/chrome-devtools/workspaces/imgs/quicksource.png
  src/content/en/tools/chrome-devtools/workspaces/index.md
  src/content/en/tools/setup/_toc.yaml
  src/content/en/tools/setup/setup-workflow.md
Labels: P1, cla: yes, section-tools, type-Content

#6082 Fix a grammatical error
  src/content/en/fundamentals/push-notifications/subscribing-a-user.md
Labels: cla: yes

#6083 Highlight code
  src/content/en/fundamentals/push-notifications/subscribing-a-user.md
Labels: cla: no

#6085 Referencing video vs. GIF article in Why Performance Matters overview piece.
  src/content/en/fundamentals/performance/why-performance-matters/index.md
Labels: cla: yes

#6087 Replace broken tracing link in GIF/video article
  src/content/en/fundamentals/performance/optimizing-content-efficiency/replace-animated-gifs-with-video/index.md
Labels: cla: yes, type-Content

#6056 Add temporary updates for WebVR and WebXR for Chrome 67 beta
  src/content/en/_shared/webxr-status.html
  src/content/en/fundamentals/vr/adding-input-to-a-webvr-scene/index.md
  src/content/en/fundamentals/vr/getting-started-with-webvr/index.md
  src/content/en/fundamentals/vr/index.md
  src/content/en/fundamentals/vr/status/index.md
  src/content/en/fundamentals/vr/vr-perspective/index.md
Labels: cla: yes, section-fundamentals

#6089 Add switches to MEI
  src/content/en/updates/2017/09/autoplay-policy-changes.md
Labels: cla: no

#6090 Add "Was this page helpful?" widget
  src/content/en/_shared/helpful.html
  src/content/en/tools/chrome-devtools/console/get-started.md
  src/content/en/tools/chrome-devtools/css/index.md
  src/content/en/tools/chrome-devtools/progressive-web-apps.md
  src/content/en/tools/chrome-devtools/security.md
  src/content/en/tools/chrome-devtools/snippets.md
  src/content/en/tools/chrome-devtools/sources.md
  src/content/en/tools/chrome-devtools/ui.md
  src/content/en/tools/chrome-devtools/workspaces/index.md
Labels: P1, cla: no, section-tools, type-Infrastructure

#6092 Adds shortlinks I'll use for my IO talk
  src/content/en/_redirects.yaml
Labels: cla: yes

#6091 Add Chrome enterprise policies
  src/content/en/fundamentals/vr/adding-input-to-a-webvr-scene/index.md
  src/content/en/fundamentals/vr/getting-started-with-webvr/index.md
  src/content/en/fundamentals/vr/index.md
  src/content/en/fundamentals/vr/status/index.md
  src/content/en/fundamentals/vr/vr-perspective/index.md
  src/content/en/tools/chrome-devtools/console/get-started.md
  src/content/en/tools/chrome-devtools/css/index.md
  src/content/en/tools/chrome-devtools/progressive-web-apps.md
  src/content/en/tools/chrome-devtools/security.md
  src/content/en/tools/chrome-devtools/snippets.md
  src/content/en/tools/chrome-devtools/sources.md
  src/content/en/tools/chrome-devtools/ui.md
  src/content/en/tools/chrome-devtools/workspaces/index.md
  src/content/en/updates/2017/09/autoplay-policy-changes.md
Labels: cla: yes

#6078 Deprecations and Removals for Chrome 67
  src/content/en/updates/2018/04/chrome-67-deps-rems.md
Labels: cla: no

#6094 Add BigInt article
  src/content/en/updates/2018/05/bigint.md
  src/content/en/updates/images/2018/05/bigint-perf.png
Labels: cla: yes

#6093 AppCache is a deprecation, not a removal
  src/content/en/updates/2018/04/chrome-67-deps-rems.md
Labels: cla: yes
