Repository google/WebFundamentals, pull requests merged in 2018-05, with the labels that each got.

#6098 New dvd podcast
  src/content/en/shows/designer-vs-developer/_toc.yaml
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E01-designing-for-css-grid.md
  src/content/en/shows/designer-vs-developer/podcast/images/dvd-s03-e01-cover-large.jpg
  src/content/en/shows/designer-vs-developer/podcast/images/dvd-s03-e01-cover.jpg
Labels: cla: no

#6097 Correct a sentence
  src/content/en/fundamentals/push-notifications/sending-messages-with-web-push-libraries.md
Labels: cla: yes

#6096 Remove tags from project yaml
  gulp-tasks/tests/projectYaml.js
  src/content/en/_project.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/fundamentals/_project.yaml
Labels: cla: yes

#6102 crux docs tweak
  src/content/en/tools/chrome-user-experience-report/index.md
Labels: cla: yes

#6105 [devtools] revert helpful widget
  src/content/en/_shared/helpful.html
  src/content/en/tools/chrome-devtools/console/get-started.md
  src/content/en/tools/chrome-devtools/css/index.md
  src/content/en/tools/chrome-devtools/progressive-web-apps.md
  src/content/en/tools/chrome-devtools/security.md
  src/content/en/tools/chrome-devtools/snippets.md
  src/content/en/tools/chrome-devtools/sources.md
  src/content/en/tools/chrome-devtools/ui.md
  src/content/en/tools/chrome-devtools/workspaces/index.md
Labels: P1, cla: yes, section-tools, type-Infrastructure

#6110 [devtools] set up A/B experiment
  src/content/en/updates/2018/04/_experiments.yaml
  src/content/en/updates/2018/04/devtools.md
Labels: P1, cla: yes, section-updates, type-Content, type-Infrastructure

#6108 Fixes a link used in the workbox-sw module guide.
  src/content/en/tools/workbox/modules/workbox-sw.md
Labels: cla: yes

#6109 Small typo in the urlManipulation example
  src/content/en/tools/workbox/modules/workbox-precaching.md
Labels: cla: yes

#6107 [autoplay-policy] Document media switches
  src/content/en/updates/2017/09/autoplay-policy-changes.md
Labels: cla: yes

#6117 Welcome to the Immersive Web
  src/content/en/updates/2018/05/welcome-to-immersive.md
  src/content/en/updates/images/2018/05/immersive-spectrum.png
  src/content/en/updates/images/2018/05/rendered-vr.png
  src/content/en/updates/images/2018/05/selecting-in-vr.png
  src/content/en/updates/images/2018/05/user-gesture.png
  src/content/en/updates/images/2018/05/welcome-to-vr.png
  src/content/en/updates/images/generic/vr-in-chrome.png
  src/data/commonTags.json
Labels: cla: yes, section-updates

#6118 DOMContentReady -> DOMContentLoaded
  src/content/en/fundamentals/security/csp/index.md
Labels: cla: yes

#6123 Updates to TWA content
  src/content/en/updates/2017/10/using-twa.md
Labels: cla: yes

#6122 Desktop PWA accouncement
  src/content/en/_redirects.yaml
  src/content/en/updates/2018/05/dpwa.md
  src/content/en/updates/app-window-elements.png
  src/content/en/updates/images/2018/05/app-menu.png
  src/content/en/updates/images/2018/05/app-window-elements.png
  src/content/en/updates/images/2018/05/device-usage.png
  src/content/en/updates/images/2018/05/dpwa-resp-1.png
  src/content/en/updates/images/2018/05/dpwa-resp-2.png
  src/content/en/updates/images/2018/05/dpwa-resp-3.png
  src/content/en/updates/images/2018/05/dpwa-resp-4.png
  src/content/en/updates/images/2018/05/spotify-a2hs.png
  src/content/en/updates/images/2018/05/spotify-screenshot.jpg
  src/data/commonTags.json
Labels: cla: yes

#6121 Updated A2HS content
  src/content/en/fundamentals/app-install-banners/_a2hs-criteria.html
  src/content/en/fundamentals/app-install-banners/index.md
  src/content/en/fundamentals/app-install-banners/native.md
  src/content/en/fundamentals/integration/_toc.yaml
Labels: cla: yes

#6115 Remove new keyword from workbox.strategies inside registerRoute method
  src/content/en/tools/workbox/guides/configure-workbox.md
Labels: cla: yes

#6124 [lighthouse] replace image in scoring guide
  src/content/en/tools/lighthouse/v3/imgs/ui.png
  src/content/en/tools/lighthouse/v3/scoring.md
Labels: P1, cla: yes, section-updates, type-Content

#6127 Update to add "patterns that break autofill" section
  src/content/en/fundamentals/design-and-ux/input/forms/index.md
Labels: cla: yes

#6126 Add FID article and assets
  src/content/en/updates/2018/05/first-input-delay.md
  src/content/en/updates/images/2018/05/first-Input-delay-full.svg
  src/content/en/updates/images/2018/05/first-input-delay-base.svg
  src/content/en/updates/images/2018/05/first-input-delay-fcp-tti.svg
Labels: DO NOT MERGE, cla: yes, section-updates

#6111 New lighthouse audits post.
  src/content/en/updates/2018/05/images/fig-1-1x.png
  src/content/en/updates/2018/05/images/fig-1-2x.png
  src/content/en/updates/2018/05/images/fig-2-1x.png
  src/content/en/updates/2018/05/images/fig-2-2x.png
  src/content/en/updates/2018/05/images/fig-3-1x.png
  src/content/en/updates/2018/05/images/fig-3-2x.png
  src/content/en/updates/2018/05/images/fig-4-1x.png
  src/content/en/updates/2018/05/images/fig-4-2x.png
  src/content/en/updates/2018/05/images/fig-5-1x.png
  src/content/en/updates/2018/05/images/fig-5-2x.png
  src/content/en/updates/2018/05/images/fig-6-1x.png
  src/content/en/updates/2018/05/images/fig-6-2x.png
  src/content/en/updates/2018/05/images/fig-7-1x.png
  src/content/en/updates/2018/05/images/fig-7-2x.png
  src/content/en/updates/2018/05/images/fig-8-1x.png
  src/content/en/updates/2018/05/images/fig-8-2x.png
  src/content/en/updates/2018/05/images/fig-9-1x.png
  src/content/en/updates/2018/05/images/fig-9-2x.png
  src/content/en/updates/2018/05/lighthouse.md
Labels: DO NOT MERGE, cla: yes, section-fundamentals

#6131 Fix alt text typos
  src/content/en/updates/2018/05/first-input-delay.md
  src/content/en/updates/images/2018/05/first-input-delay-full.svg
Labels: cla: yes

#6132 Tweaks to dPWA article
  src/content/en/updates/2018/05/dpwa.md
Labels: cla: yes

#6134 Correct canary errors.
  src/content/en/updates/2018/05/welcome-to-immersive.md
Labels: cla: yes

#6137 Fix reference to WebGL context.
  src/content/en/updates/2018/05/welcome-to-immersive.md
Labels: cla: yes

#6136 Updates to Lighthouse audits post.
  src/content/en/updates/2018/05/images/fig-10-1x.png
  src/content/en/updates/2018/05/images/fig-10-2x.png
  src/content/en/updates/2018/05/images/fig-11-1x.png
  src/content/en/updates/2018/05/images/fig-11-2x.png
  src/content/en/updates/2018/05/lighthouse.md
Labels: cla: yes

#6139 Puppeteer: add io video
  src/content/en/tools/puppeteer/index.md
Labels: cla: yes, type-Content

#6140 Fixed typos in Lighthouse3 update
  src/content/en/updates/2018/05/lighthouse3.md
Labels: cla: yes

#6143 Embed session video of WebAuthn
  src/content/en/updates/2018/05/webauthn.md
Labels: cla: yes

#6145 Update BigInt article
  src/content/en/updates/2018/05/bigint.md
  src/content/en/updates/images/2018/05/bigint-perf.png
Labels: cla: yes

#6138 Web App Manifest updates
  src/content/en/_redirects.yaml
  src/content/en/fundamentals/app-install-banners/_a2hs-criteria.html
  src/content/en/fundamentals/app-install-banners/index.md
  src/content/en/fundamentals/web-app-manifest/index.md
  src/content/en/updates/2014/11/Support-for-installable-web-apps-with-webapp-manifest-in-chrome-38-for-Android.md
  src/content/en/updates/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android.md
  src/content/en/updates/2015/08/using-web-app-manifest-to-set-solid-color-loading-screen.md
  src/content/en/updates/2015/10/display-mode.md
  src/content/en/updates/2015/10/splashscreen.md
  src/content/en/updates/_redirects.yaml
Labels: cla: yes

#6141 Revert "[Autoplay policy] Add MediaStream section"
  src/content/en/updates/2017/09/autoplay-policy-changes.md
Labels: cla: yes

#6150 Added video to lighthouse updates.
  src/content/en/updates/2018/05/lighthouse.md
Labels: cla: yes

#6148 Fix trivial typo
  src/content/en/fundamentals/instant-and-offline/web-storage/cache-api.md
Labels: cla: yes

#6149 Fix figcaption formatting
  src/content/en/updates/2018/05/bigint.md
Labels: cla: yes

#6151 Update <link rel=modulepreload> article
  src/content/en/updates/2017/12/modulepreload.md
Labels: cla: yes

#6153 Remove duplicate word
  src/content/en/updates/2018/05/first-input-delay.md
Labels: cla: yes

#6157 Small update to the Workbox fetchDidFail docs
  src/content/en/tools/workbox/guides/using-plugins.md
Labels: cla: yes

#6160 Add SEO terms to XHR/Fetch section
  src/content/en/tools/chrome-devtools/javascript/breakpoints.md
Labels: P2, cla: yes, section-tools, type-Content

#6158 Updated the workbox-build example with some logged details
  src/content/en/tools/workbox/guides/precache-files/workbox-build.md
Labels: cla: yes

#6162 Podcast with Ben & Dion
  src/content/en/shows/http203/podcast/images/io.jpg
  src/content/en/shows/http203/podcast/io-chats-ben-dion.md
Labels: cla: yes, section-shows

#6163 Fix typos
  src/content/en/fundamentals/design-and-ux/input/forms/index.md
  src/content/en/updates/2018/05/welcome-to-immersive.md
Labels: cla: yes

#6159 Add mirrored displays note
  src/content/en/updates/2018/04/present-web-pages-to-secondary-attached-displays.md
Labels: cla: yes

#6166 A2HS display requirement
  src/content/en/fundamentals/app-install-banners/_a2hs-criteria.html
  src/content/en/fundamentals/app-install-banners/index.md
  src/content/en/fundamentals/web-app-manifest/index.md
Labels: cla: yes

#6165 Add CSS Paint Polyfill
  src/content/en/updates/2018/01/paintapi.md
Labels: cla: no

#6167 New dvd podcast
  src/content/en/shows/designer-vs-developer/_toc.yaml
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E02-designing-for-standards.md
  src/content/en/shows/designer-vs-developer/podcast/images/dvd-s03-e02-cover-large.jpg
  src/content/en/shows/designer-vs-developer/podcast/images/dvd-s03-e02-cover.jpg
Labels: cla: no

#6169 Move improved a2hs to webfu
  src/content/en/_redirects.yaml
  src/content/en/fundamentals/app-install-banners/index.md
  src/content/en/fundamentals/integration/_toc.yaml
  src/content/en/fundamentals/integration/webapks.md
  src/content/en/updates/2017/02/improved-add-to-home-screen.md
  src/data/common-typos.yaml
Labels: cla: yes, section-fundamentals, type-Content

#6170 Add a note to the Workbox Google Analytics page about testing
  src/content/en/tools/workbox/modules/workbox-google-analytics.md
Labels: cla: no

#6171 Small tweak on WebAuthn article
  src/content/en/updates/2018/05/webauthn.md
Labels: cla: yes

#6176 HTTP 203 podcast with Monica
  src/content/en/shows/http203/podcast/io-chats-monica.md
Labels: cla: yes, section-shows

#6173 Payments: update links to Google Pay Payment Request tutorial
  src/content/en/fundamentals/_redirects.yaml
  src/content/en/fundamentals/payments/_toc.yaml
  src/content/en/fundamentals/payments/android-pay.md
  src/content/en/fundamentals/payments/deep-dive-into-payment-request.md
  src/content/en/fundamentals/payments/index.md
Labels: cla: yes

#6182 SmooshGate: update article per resolution
  src/content/en/updates/2018/03/smooshgate.md
Labels: cla: yes

#6181 A11y touch fix
  src/content/en/fundamentals/accessibility/accessible-styles.md
  src/content/en/fundamentals/accessibility/imgs/touch-target2.jpg
  src/content/es/fundamentals/accessibility/accessible-styles.md
  src/content/id/fundamentals/accessibility/accessible-styles.md
  src/content/it/fundamentals/accessibility/accessible-styles.md
  src/content/ja/fundamentals/accessibility/accessible-styles.md
  src/content/ko/fundamentals/accessibility/accessible-styles.md
  src/content/pt-br/fundamentals/accessibility/accessible-styles.md
  src/content/zh-cn/fundamentals/accessibility/accessible-styles.md
  src/content/zh-tw/fundamentals/accessibility/accessible-styles.md
Labels: cla: yes

#6185 [devtools] add wndt68
  src/content/en/updates/2018/05/_experiments.yaml
  src/content/en/updates/2018/05/devtools.md
  src/content/en/updates/images/2018/05/arghints.png
  src/content/en/updates/images/2018/05/autocomplete.png
  src/content/en/updates/images/2018/05/await.png
  src/content/en/updates/images/2018/05/bigint.png
  src/content/en/updates/images/2018/05/eagereval.png
  src/content/en/updates/images/2018/05/settings.png
  src/content/en/updates/images/2018/05/watch.png
Labels: P1, cla: yes, section-updates, type-Content

#6184 Add WebAudio switch
  src/content/en/updates/2017/09/autoplay-policy-changes.md
Labels: cla: yes

#6187 Clarified translated title to make it more digestible for PT-BR
  src/content/pt-br/fundamentals/security/hacked/fixing_the_cloaked_keywords_hack.html
Labels: cla: yes

#6189 remove contributor mention
  src/content/en/updates/2018/05/devtools.md
Labels: P2, cla: yes, section-updates, type-Content

#6200 NIC67 post
  src/content/en/updates/2018/05/nic67.md
Labels: cla: yes

#6201 a2hs with links to other browsers criteria
  src/content/en/fundamentals/app-install-banners/_a2hs-criteria.html
Labels: cla: yes

#6204 Update teaser of AR functionality.
  src/content/en/updates/2018/05/welcome-to-immersive.md
Labels: cla: yes

#6205 Add license to CrUX docs
  src/content/en/tools/chrome-user-experience-report/index.md
Labels: cla: yes
