Repository google/WebFundamentals, pull requests merged in 2018-10, with the labels that each got.

#6680 [lighthouse] minor updates to metrics docs
  src/content/en/tools/_redirects.yaml
  src/content/en/tools/lighthouse/_toc.yaml
  src/content/en/tools/lighthouse/audits/first-cpu-idle.md
  src/content/en/tools/lighthouse/audits/time-to-interactive.md
Labels: cla: yes

#6681 [lighthouse] s/perceptual speed index/speed index/
  src/content/en/tools/lighthouse/_toc.yaml
  src/content/en/tools/lighthouse/audits/speed-index.md
Labels: P1, cla: yes, section-tools, type-Content

#6690 Add AV1 decoder to Chrome 70
  src/content/en/updates/2018/08/chrome-69-media-updates.md
  src/content/en/updates/2018/09/chrome-70-media-updates.md
  src/content/en/updates/images/2018/09/stats-for-nerds-featuring-av1-in-youtube.png
Labels: cla: yes

#6688 Typo fix | Addresses #6600
  src/content/en/fundamentals/web-app-manifest/index.md
Labels: cla: yes

#6695 edit "why performance matters" to use less and simpler words
  src/content/en/fundamentals/performance/why-performance-matters/index.md
Labels: P1, cla: yes, section-fundamentals, type-Content

#6698 [devtools] add vid to wndt70
  src/content/en/updates/2018/08/devtools.md
Labels: P1, cla: yes, section-updates, type-Content

#6705 Fix broken link.
  src/content/en/updates/2018/06/webar-chacmool.md
Labels: cla: yes

#6703 Fix Feature Policy URL
  src/content/en/updates/2017/09/autoplay-policy-changes.md
Labels: cla: yes

#6704 Dvds4e4
  src/content/en/shows/designer-vs-developer/_toc.yaml
  src/content/en/shows/designer-vs-developer/podcast/DVDS4E04-prototyping-motion.md
  src/content/en/shows/designer-vs-developer/podcast/images/dvd-s04-e04-cover-large.jpg
  src/content/en/shows/designer-vs-developer/podcast/images/dvd-s04-e04-cover.jpg
Labels: cla: yes

#6708 [devtools] add wndt71
  src/content/en/tools/chrome-devtools/images/shared/main-menu.png
  src/content/en/updates/2018/10/devtools.md
  src/content/en/updates/images/2018/10/HAR1.png
  src/content/en/updates/images/2018/10/HAR2.png
  src/content/en/updates/images/2018/10/HAR3.png
  src/content/en/updates/images/2018/10/beforeinstallprompt1.png
  src/content/en/updates/images/2018/10/command-menu1.png
  src/content/en/updates/images/2018/10/focus1.png
  src/content/en/updates/images/2018/10/focus2.png
  src/content/en/updates/images/2018/10/focus3.png
  src/content/en/updates/images/2018/10/focus4.png
  src/content/en/updates/images/2018/10/hover1.png
  src/content/en/updates/images/2018/10/pip1.png
  src/content/en/updates/images/2018/10/store1.png
  src/content/en/updates/images/2018/10/store2.png
Labels: P0, cla: yes, section-updates, type-Content

#6711 [devtools] remove focus section from wndt71
  src/content/en/updates/2018/10/devtools.md
  src/content/en/updates/images/2018/10/focus1.png
  src/content/en/updates/images/2018/10/focus2.png
  src/content/en/updates/images/2018/10/focus3.png
  src/content/en/updates/images/2018/10/focus4.png
Labels: P0, cla: yes, section-updates, type-Content

#6712 [devtools] remove the beforeinstallprompt section from wndt71
  src/content/en/updates/2018/10/devtools.md
  src/content/en/updates/images/2018/10/beforeinstallprompt1.png
Labels: P0, cla: yes, section-updates, type-Content

#6710 Issue #6707 | Spelling fix
  src/content/en/fundamentals/primers/async-functions.md
Labels: cla: yes

#6713 Workbox guide updates
  src/content/en/tools/workbox/guides/advanced-recipes.md
  src/content/en/tools/workbox/guides/common-recipes.md
  src/content/en/tools/workbox/guides/route-requests.md
Labels: cla: yes

#6701 AnimationWorklet article
  src/content/en/updates/2018/10/animation-worklet.md
  src/content/en/updates/images/2018/10/animation-worklet/slowprop.png
  src/content/en/updates/images/2018/10/animation-worklet/social.png
Labels: cla: yes

#6715 [devtools] remove ndb mention
  src/content/en/updates/2018/08/devtools.md
Labels: P1, cla: yes, section-updates, type-Content

#6716 Revert "[devtools] remove ndb mention"
  src/content/en/updates/2018/08/devtools.md
Labels: cla: yes

#6719 Fixes widget escaping
  src/content/en/resources/widgets.md
Labels: cla: yes

#6722 Add M69 paint timing issues post
  src/content/en/images/contributors/tdresser.jpg
  src/content/en/updates/2018/10/paint-timing-issues.md
  src/data/_contributors.yaml
Labels: cla: yes, section-updates, type-Content

#6726 Fix typo
  src/content/en/updates/2018/08/devtools.md
Labels: cla: yes

#6723 Update Firefox and Edge browser support
  src/content/en/fundamentals/web-components/customelements.md
Labels: cla: yes

#6721 fixing linking error
  src/content/en/shows/designer-vs-developer/_toc.yaml
Labels: cla: yes

#6706 Update agencies directory data
  src/content/en/agencies/data/agencies.json
  src/content/en/agencies/images/gmic_chance.png
  src/content/en/agencies/images/lunar_works_lab_ltd.png
  src/content/en/agencies/images/uasoft.png
Labels: P2, cla: yes, section-agencies

#6702 Adding missing fields
  src/templates/shows/podcast.xml
Labels: cla: yes, type-Infrastructure

#6730 Reword the intro paragraph
  src/content/en/updates/2018/10/paint-timing-issues.md
Labels: cla: yes, section-updates, type-Content

#6731 Desktop PWA refactor
  app.yaml
  appengine_main.py
  src/content/en/_redirects.yaml
  src/content/en/fundamentals/app-install-banners/_a2hs-criteria.html
  src/content/en/fundamentals/app-install-banners/index.md
  src/content/en/progressive-web-apps/_book.yaml
  src/content/en/progressive-web-apps/_index.yaml
  src/content/en/progressive-web-apps/desktop.md
  src/content/en/progressive-web-apps/images/app-menu.png
  src/content/en/progressive-web-apps/images/app-window-elements.png
  src/content/en/progressive-web-apps/images/device-usage.png
  src/content/en/progressive-web-apps/images/dpwa-resp-1.png
  src/content/en/progressive-web-apps/images/dpwa-resp-2.png
  src/content/en/progressive-web-apps/images/dpwa-resp-3.png
  src/content/en/progressive-web-apps/images/dpwa-resp-4.png
  src/content/en/progressive-web-apps/images/spotify-screenshot.jpg
  src/content/en/shows/http203/podcast/io-chats-ben-dion.md
  src/content/en/updates/2018/05/nic67.md
Labels: cla: yes

#6729 NIC70 post
  src/content/en/updates/2018/10/nic70.md
  src/content/en/updates/_redirects.yaml
  src/content/en/updates/images/2018/10/webauth.png
Labels: cla: yes

#6738 Small typo fix/rewording of a Workbox guide
  src/content/en/tools/workbox/guides/handle-third-party-requests.md
Labels: cla: yes

#6739 Remove extra bracket from snippet
  src/content/en/tools/workbox/guides/advanced-recipes.md
Labels: cla: yes, section-tools, type-Content

#6728 cache.addAll() and importScripts() updates for M71
  src/content/en/updates/2018/10/tweaks-to-addAll-importScripts.md
  src/content/en/updates/images/2018/10/cache-addall-warning.png
Labels: cla: yes

#6743 Add Linux announce for m70
  src/content/en/fundamentals/app-install-banners/index.md
  src/content/en/progressive-web-apps/desktop.md
  src/content/en/updates/2018/10/nic70.md
Labels: cla: yes, section-fundamentals, type-Content

#6648 Update Lighthouse, add generator tool, improve English, explain sizeS
  src/content/en/fundamentals/web-app-manifest/index.md
Labels: cla: yes

#6203 Add "Watch video using Picture-in-Picture" article
  src/content/en/updates/2017/09/picture-in-picture.md
  src/content/en/updates/2018/09/chrome-70-media-updates.md
  src/content/en/updates/2018/10/watch-video-using-picture-in-picture.md
  src/content/en/updates/images/2018/06/watch-video-using-picture-in-picture/hero.png
  src/content/en/updates/images/2018/10/watch-video-using-picture-in-picture/hero.png
Labels: cla: no, type-Content

#6749 Port CL to PR
  src/content/en/_translation.yaml
Labels: cla: yes

#6742 FMP documentation isn't a spec.
  src/content/en/tools/lighthouse/audits/first-meaningful-paint.md
Labels: cla: yes, section-tools, type-Content

#6753 Podcast image fix
  src/templates/shows/podcast.xml
Labels: cla: yes, type-Infrastructure

#6754 Add Intl.RelativeTimeFormat API update
  src/content/en/updates/2018/10/intl-relativetimeformat.md
Labels: type-Content

#6759 Fix indentation
  src/content/en/updates/2018/10/intl-relativetimeformat.md
Labels: cla: yes

#6757 Fix punctuation mark typo
  src/content/en/fundamentals/design-and-ux/animations/animations-and-performance.md
Labels: cla: yes

#6755 Remove non printable characters and fix typo
  src/content/en/updates/2018/09/inside-browser-part4.md
Labels: cla: yes

#6748 Remove sentence fragment that was completed as subsequent note in section
  src/content/en/tools/workbox/modules/workbox-broadcast-cache-update.md
Labels: cla: yes

#6763 Update links to V8 website
  src/content/en/fundamentals/performance/optimizing-javascript/tree-shaking/index.md
  src/content/en/fundamentals/primers/modules.md
  src/content/en/updates/2017/03/devtools-release-notes.md
  src/content/en/updates/2017/07/upcoming-regexp-features.md
  src/content/en/updates/2018/02/meltdown-spectre.md
  src/content/en/updates/2018/04/loading-wasm.md
  src/content/en/updates/2018/05/bigint.md
  src/content/zh-cn/updates/2017/03/devtools-release-notes.md
  src/content/zh-tw/updates/2017/03/devtools-release-notes.md
Labels: cla: yes, type-Content

#6767 Dropped details on Appcache
  src/content/en/ilt/pwa/offline-quickstart.md
Labels: cla: yes

#6778 Wasm threads release update post
  src/content/en/updates/2018/10/wasm-threads.md
  src/content/en/updates/images/2018/10/WasmThreads1.png
  src/content/en/updates/images/2018/10/WasmThreads2.png
  src/content/en/updates/images/2018/10/WasmThreads3.png
  src/content/en/updates/images/2018/10/WasmThreads4.png
Labels: cla: yes

#6756 Another WB recipe typo fix.
  src/content/en/tools/workbox/guides/advanced-recipes.md
Labels: cla: yes

#6786 Fixed link to bug tracker.
  src/content/en/updates/2018/10/wasm-threads.md
Labels: cla: yes, section-updates

#6784 Change link on security index page to use cleaner grammar.
  src/content/en/fundamentals/security/index.md
Labels: cla: no

#6780 fix the dead link to the Shadow DOM specification
  src/content/en/fundamentals/web-components/shadowdom.md
Labels: cla: yes

#6779 Changes requested by DevSite team
  src/content/en/_index.yaml
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_0.jpg
  src/content/en/tools/workbox/_index.yaml
Labels: cla: yes

#6765 When webapk updates
  src/content/en/fundamentals/app-install-banners/index.md
  src/content/en/fundamentals/integration/webapks.md
Labels: cla: yes

#6764 Common tag updates
  src/content/en/updates/2012/11/Content-Security-Policy-1-0-is-officially-awesome.md
  src/content/en/updates/2018/07/reportingobserver.md
  src/content/en/updates/2018/09/reportingapi.md
  src/data/blinkComponents.json
  src/data/commonTags.json
Labels: cla: yes

#6747 Deprecations/Removals for Chrome 71
  src/content/en/updates/2018/10/chrome-71-deps-rems.md
Labels: cla: no

#6781 Docs for opaque responses in DevTools
  src/content/en/tools/chrome-devtools/progressive-web-apps.md
  src/data/glossary.yaml
Labels: cla: yes

#6795 Meta typo!
  src/data/common-typos.yaml
Labels: cla: yes

#6792 Workbox migration guide typo fix
  src/content/en/tools/workbox/guides/migrations/migrate-from-sw.md
Labels: cla: yes
