Repository google/WebFundamentals, pull requests merged in 2018-06, with the labels that each got.

#6209 Adding a link to UC Browser's A2HS docs page to our docs page
  src/content/en/fundamentals/app-install-banners/_a2hs-criteria.html
Labels: cla: no

#6208 Add TWA video to TWA post
  src/content/en/updates/2017/10/using-twa.md
Labels: cla: yes

#6207 Foreign fetch was removed from the SW spec.
  src/content/en/updates/2016/09/foreign-fetch.md
Labels: cla: yes

#6210 Fix minor typos
  src/content/en/updates/2018/05/nic67.md
Labels: cla: yes

#6211 Add a more complete set of tags for the immersive web.
  src/content/en/updates/2018/05/welcome-to-immersive.md
  src/data/commonTags.json
Labels: cla: yes

#6214 Fix Workbox docs typo: s/weary/wary
  src/content/en/tools/workbox/guides/route-requests.md
Labels: cla: yes

#6217 Add a missing 'to'
  src/content/en/updates/2018/05/devtools.md
Labels: cla: yes

#6219 "Fresher service workers, by default" post
  src/content/en/updates/2018/06/fresher-sw.md
Labels: cla: yes

#6220 A2HS Updates
  src/content/en/fundamentals/app-install-banners/_a2hs-criteria.html
  src/content/en/updates/2018/06/a2hs-updates.md
  src/content/en/updates/images/2018/06/a2hs-banner-g.png
  src/content/en/updates/images/2018/06/a2hs-dialog-cropped.png
  src/content/en/updates/images/2018/06/a2hs-dialog-g.png
  src/content/en/updates/images/2018/06/a2hs-infobar-cropped.png
  src/content/en/updates/images/2018/06/a2hs-infobar-g.png
  src/content/en/updates/images/2018/06/a2hs-omnibox-cropped.png
  src/content/en/updates/images/2018/06/a2hs-spotify.png
  src/data/blinkComponents.json
Labels: cla: yes

#6206 Updates to the Workbox Plugin docs
  src/content/en/tools/workbox/guides/using-plugins.md
Labels: cla: yes, section-tools, type-Content

#6221 Fix frameworks note.
  src/content/en/updates/2018/05/welcome-to-immersive.md
Labels: cla: yes

#6188 Shows: Add rss/atom feed per year
  gulp-tasks/build.js
  gulp-tasks/wfYouTubeShows.js
  package.json
Labels: cla: yes, section-shows

#6225 Makes building RSS/ATOM feeds optional
  gulp-tasks/build.js
  gulp-tasks/wfTemplateHelper.js
  gulp-tasks/wfYouTubeShows.js
  gulpfile.js
Labels: cla: yes

#6226 Http 203 podcast
  src/content/en/shows/http203/podcast/images/io-mariko.jpg
  src/content/en/shows/http203/podcast/images/io.jpg
  src/content/en/shows/http203/podcast/io-chats-mariko.md
Labels: cla: yes, section-shows

#5886 [Translation zh-tw] Fundamentals > Payments
  src/content/zh-tw/fundamentals/payments/index.md
Labels: cla: no

#6232 Revert "[Translation zh-tw] Fundamentals > Payments"
  src/content/zh-tw/fundamentals/payments/index.md
Labels: cla: yes

#6224 Adding navigation and resource timing guide.
  src/content/en/fundamentals/performance/_toc.yaml
  src/content/en/fundamentals/performance/navigation-and-resource-timing/images/figure-1-1x.png
  src/content/en/fundamentals/performance/navigation-and-resource-timing/images/figure-1-2x.png
  src/content/en/fundamentals/performance/navigation-and-resource-timing/images/figure-2-1x.png
  src/content/en/fundamentals/performance/navigation-and-resource-timing/images/figure-2-2x.png
  src/content/en/fundamentals/performance/navigation-and-resource-timing/images/figure-3-1x.png
  src/content/en/fundamentals/performance/navigation-and-resource-timing/images/figure-3-2x.png
  src/content/en/fundamentals/performance/navigation-and-resource-timing/index.md
Labels: cla: yes

#6116 Propose different spelling
  src/content/en/updates/2018/04/chrome-67-deps-rems.md
Labels: DO NOT MERGE, cla: yes

#6233 Nav resource timing fixes
  src/content/en/fundamentals/performance/navigation-and-resource-timing/index.md
Labels: cla: yes

#6230 Update to the caching headers section of the SW lifecycle doc
  src/content/en/fundamentals/primers/service-workers/lifecycle.md
Labels: cla: yes

#6228 Add Payment Handler API announcement article
  src/content/en/updates/2016/07/payment-request.md
  src/content/en/updates/2018/06/payment-handler-api.md
  src/content/en/updates/images/generic/credit_card.png
Labels: cla: yes, section-updates

#6235 Add missing DOCTYPEs
  src/content/en/fundamentals/performance/critical-rendering-path/_code/analysis_with_css.html
  src/content/en/fundamentals/performance/critical-rendering-path/_code/analysis_with_css_js.html
  src/content/en/fundamentals/performance/critical-rendering-path/_code/analysis_with_css_js_async.html
  src/content/en/fundamentals/performance/critical-rendering-path/_code/analysis_with_css_nb_js_async.html
  src/content/en/fundamentals/performance/critical-rendering-path/_code/basic_dom.html
  src/content/en/fundamentals/performance/critical-rendering-path/_code/basic_dom_nostyle.html
  src/content/en/fundamentals/performance/critical-rendering-path/_code/measure_crp.html
  src/content/en/fundamentals/performance/critical-rendering-path/_code/measure_crp_async.html
  src/content/en/fundamentals/performance/critical-rendering-path/_code/measure_crp_inlined.html
  src/content/en/fundamentals/performance/critical-rendering-path/_code/measure_crp_timing.html
  src/content/en/fundamentals/performance/critical-rendering-path/_code/nested.html
  src/content/en/fundamentals/performance/critical-rendering-path/_code/script.html
  src/content/en/fundamentals/performance/critical-rendering-path/_code/split_script.html
  src/content/en/fundamentals/performance/critical-rendering-path/_code/split_script_async.html
  src/content/en/fundamentals/performance/critical-rendering-path/_code/split_script_print.html
Labels: cla: yes

#6223 Deprecations and Remvoals for Chrome 68.
  src/content/en/updates/2018/06/chrome-68-deps-rems.md
Labels: cla: yes

#6244 Update dynamic import article
  src/content/en/updates/2017/11/dynamic-import.md
Labels: cla: yes

#6238 Update for new behavior of confirm
  src/content/en/updates/2017/03/dialogs-policy.md
Labels: cla: yes

#6248 Fix missing images in map infoboxes in web agency directory
  src/content/en/agencies/js/directory.js
Labels: cla: yes

#6249 Add tech editors to guides. Minor copy fixes.
  src/content/en/fundamentals/performance/lazy-loading-guidance/images-and-video/index.md
  src/content/en/fundamentals/performance/navigation-and-resource-timing/index.md
  src/content/en/fundamentals/performance/optimizing-content-efficiency/replace-animated-gifs-with-video/index.md
  src/content/en/fundamentals/performance/why-performance-matters/index.md
  src/content/en/updates/2018/05/lighthouse.md
Labels: cla: yes

#6251 Fix slight formatting issues with paragraph and nested lists
  src/content/en/tools/workbox/modules/workbox-precaching.md
Labels: cla: yes

#6256 Podcast with Darin
  src/content/en/shows/http203/podcast/io-chats-darin.md
Labels: cla: yes, section-shows

#6255 Add reference to privacy whitepaper
  src/content/en/updates/2013/01/Voice-Driven-Web-Apps-Introduction-to-the-Web-Speech-API.md
Labels: cla: no

#6252 Update the nested lists for better readability
  src/content/en/tools/workbox/guides/using-plugins.md
Labels: cla: yes

#6250 puppeteer: link to pptr.dev api docs
  gulp-tasks/puppeteer/build_docs.js
Labels: cla: yes, type-Content

#6261 New DvD podcast (replaces #6260)
  src/content/en/shows/designer-vs-developer/_toc.yaml
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E01-becoming-a-creative-coder.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E02-designing-a-great-performance.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E04-learn-how-to-design.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E05-designing-for-the-next-billion-users.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E06-how-the-web-can-compete-with-native.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E01-designing-for-css-grid.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E02-designing-for-standards.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E04-creative-ways-of-prototyping.md
  src/content/en/shows/designer-vs-developer/podcast/images/dvd-s03-e04-cover-large.jpg
  src/content/en/shows/designer-vs-developer/podcast/images/dvd-s03-e04-cover.jpg
Labels: cla: yes

#6262 Weekly CLAAT & Other File Updates
  src/content/en/fundamentals/codelabs/debugging-service-workers/index.md
  src/content/en/fundamentals/codelabs/offline/index.md
  src/content/en/fundamentals/codelabs/payment-request-api/index.md
  src/content/en/fundamentals/codelabs/push-notifications/index.md
  src/content/en/fundamentals/codelabs/web-perf/index.md
  src/content/en/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/en/ilt/pwa/caching-files-with-service-worker.md
  src/content/en/ilt/pwa/e-commerce-lab-1-create-a-service-worker.md
  src/content/en/ilt/pwa/e-commerce-lab-2-add-to-homescreen.md
  src/content/en/ilt/pwa/integrating-analytics.md
  src/content/en/ilt/pwa/introduction-to-gulp.md
  src/content/en/ilt/pwa/introduction-to-progressive-web-app-architectures.md
  src/content/en/ilt/pwa/introduction-to-push-notifications.md
  src/content/en/ilt/pwa/introduction-to-service-worker.md
  src/content/en/ilt/pwa/introduction-to-the-payment-request-api.md
  src/content/en/ilt/pwa/lab-auditing-with-lighthouse.md
  src/content/en/ilt/pwa/lab-caching-files-with-service-worker.md
  src/content/en/ilt/pwa/lab-fetch-api.md
  src/content/en/ilt/pwa/lab-gulp-setup.md
  src/content/en/ilt/pwa/lab-indexeddb.md
  src/content/en/ilt/pwa/lab-integrating-analytics.md
  src/content/en/ilt/pwa/lab-integrating-web-push.md
  src/content/en/ilt/pwa/lab-migrating-to-workbox-from-sw-precache-and-sw-toolbox.md
  src/content/en/ilt/pwa/lab-offline-quickstart.md
  src/content/en/ilt/pwa/lab-promises.md
  src/content/en/ilt/pwa/lab-responsive-design.md
  src/content/en/ilt/pwa/lab-responsive-images.md
  src/content/en/ilt/pwa/lab-scripting-the-service-worker.md
  src/content/en/ilt/pwa/lab-workbox.md
  src/content/en/ilt/pwa/lighthouse-pwa-analysis-tool.md
  src/content/en/ilt/pwa/live-data-in-the-service-worker.md
  src/content/en/ilt/pwa/offline-quickstart.md
  src/content/en/ilt/pwa/setting-up-the-labs.md
  src/content/en/ilt/pwa/tools-for-pwa-developers.md
  src/content/en/ilt/pwa/working-with-promises.md
  src/content/en/ilt/pwa/working-with-the-fetch-api.md
  src/data/blinkComponents.json
  src/data/codelabs/debugging-service-workers/codelab.json
  src/data/codelabs/offline/codelab.json
  src/data/codelabs/payment-request-api/codelab.json
  src/data/codelabs/push-notifications/codelab.json
  src/data/codelabs/web-perf/codelab.json
  src/data/codelabs/your-first-pwapp/codelab.json
  src/data/ilt-pwa/e-commerce-lab-2-add-to-homescreen/codelab.json
  src/data/ilt-pwa/live-data-in-the-service-worker/codelab.json
Labels: cla: yes

#6196 [Translate ru] billions -> index
  src/content/ru/billions/_index.yaml
Labels: cla: no

#6254 Add AR hit test support to status.
  src/content/en/fundamentals/vr/_toc.yaml
  src/content/en/fundamentals/vr/status/index.md
Labels: cla: yes

#6218 [Translate ru] Accessibility -> index
  src/content/ru/fundamentals/accessibility/index.md
Labels: cla: no

#6258 Add "AR for the web" article.
  src/content/en/updates/2018/06/ar-for-the-web.md
  src/content/en/updates/images/2018/06/sunflowers.jpg
  src/data/commonTags.json
Labels: cla: yes

#6257 WebAR-Chacmool: Ancient artifacts at Your Fingertips
  src/content/en/updates/2018/06/webar-chacmool.md
  src/content/en/updates/images/2018/06/webar-chacmool.jpg
  src/data/_contributors.yaml
  src/data/commonTags.json
Labels: cla: yes

#6264 Fix image path.
  src/content/en/updates/2018/06/ar-for-the-web.md
Labels: cla: yes

#6259 Fix IE specific bugs for /web/agencies
  src/content/en/agencies/css/directory.css
  src/content/en/agencies/js/directory.js
Labels: DO NOT MERGE, P2, cla: yes, section-agencies

#6266 Change title of Chacmool article.
  src/content/en/updates/2018/06/webar-chacmool.md
Labels: cla: yes

#6267 Add ARCore to requirements.
  src/content/en/updates/2018/06/ar-for-the-web.md
  src/content/en/updates/2018/06/webar-chacmool.md
Labels: cla: yes

#6270 Update the manifestTransform example.
  src/content/en/tools/workbox/_shared/config/single/manifestTransforms.html
Labels: cla: yes

#6269 Fix variable name.
  src/content/en/updates/2018/06/ar-for-the-web.md
Labels: cla: yes

#6268 Minor copy tweaks to the cache expiration page
  src/content/en/tools/workbox/modules/workbox-cache-expiration.md
Labels: cla: yes

#6272 Add guide on JS modules
  .github/PULL_REQUEST_TEMPLATE.md
  src/content/en/fundamentals/primers/imgs/async-defer.svg
  src/content/en/fundamentals/primers/imgs/renderer-main-thread-time-breakdown.png
  src/content/en/fundamentals/primers/modules.md
Labels: cla: yes

#6274 Add missing credit
  src/content/en/fundamentals/primers/modules.md
Labels: cla: yes

#6276 [devtools] add speed tutorial
  src/content/en/tools/chrome-devtools/_toc.yaml
  src/content/en/tools/chrome-devtools/evaluate-performance/index.md
  src/content/en/tools/chrome-devtools/index.md
  src/content/en/tools/chrome-devtools/network-performance/index.md
  src/content/en/tools/chrome-devtools/speed/get-started.md
  src/content/en/tools/chrome-devtools/speed/imgs/addpattern.png
  src/content/en/tools/chrome-devtools/speed/imgs/audits.png
  src/content/en/tools/chrome-devtools/speed/imgs/blockedlibs.png
  src/content/en/tools/chrome-devtools/speed/imgs/blocking.png
  src/content/en/tools/chrome-devtools/speed/imgs/bottomup.png
  src/content/en/tools/chrome-devtools/speed/imgs/building.png
  src/content/en/tools/chrome-devtools/speed/imgs/capture.png
  src/content/en/tools/chrome-devtools/speed/imgs/commandmenu.png
  src/content/en/tools/chrome-devtools/speed/imgs/compression.png
  src/content/en/tools/chrome-devtools/speed/imgs/compressionreport.png
  src/content/en/tools/chrome-devtools/speed/imgs/config.png
  src/content/en/tools/chrome-devtools/speed/imgs/coverage.png
  src/content/en/tools/chrome-devtools/speed/imgs/coveragereport.png
  src/content/en/tools/chrome-devtools/speed/imgs/demo.png
  src/content/en/tools/chrome-devtools/speed/imgs/devtools.png
  src/content/en/tools/chrome-devtools/speed/imgs/diagnostics.png
  src/content/en/tools/chrome-devtools/speed/imgs/editor.png
  src/content/en/tools/chrome-devtools/speed/imgs/error.png
  src/content/en/tools/chrome-devtools/speed/imgs/fmp.png
  src/content/en/tools/chrome-devtools/speed/imgs/gzip.png
  src/content/en/tools/chrome-devtools/speed/imgs/headers.png
  src/content/en/tools/chrome-devtools/speed/imgs/jquery.png
  src/content/en/tools/chrome-devtools/speed/imgs/largerows.png
  src/content/en/tools/chrome-devtools/speed/imgs/libs.png
  src/content/en/tools/chrome-devtools/speed/imgs/main.png
  src/content/en/tools/chrome-devtools/speed/imgs/menu.png
  src/content/en/tools/chrome-devtools/speed/imgs/metrics.png
  src/content/en/tools/chrome-devtools/speed/imgs/mine.png
  src/content/en/tools/chrome-devtools/speed/imgs/model.png
  src/content/en/tools/chrome-devtools/speed/imgs/more-panels.png
  src/content/en/tools/chrome-devtools/speed/imgs/network.png
  src/content/en/tools/chrome-devtools/speed/imgs/opportunities.png
  src/content/en/tools/chrome-devtools/speed/imgs/overall.png
  src/content/en/tools/chrome-devtools/speed/imgs/overview.png
  src/content/en/tools/chrome-devtools/speed/imgs/passed.png
  src/content/en/tools/chrome-devtools/speed/imgs/perform.png
  src/content/en/tools/chrome-devtools/speed/imgs/performance.png
  src/content/en/tools/chrome-devtools/speed/imgs/reference.png
  src/content/en/tools/chrome-devtools/speed/imgs/reload.png
  src/content/en/tools/chrome-devtools/speed/imgs/remove.png
  src/content/en/tools/chrome-devtools/speed/imgs/render.png
  src/content/en/tools/chrome-devtools/speed/imgs/report.png
  src/content/en/tools/chrome-devtools/speed/imgs/report2.png
  src/content/en/tools/chrome-devtools/speed/imgs/report3.png
  src/content/en/tools/chrome-devtools/speed/imgs/report4.png
  src/content/en/tools/chrome-devtools/speed/imgs/report5.png
  src/content/en/tools/chrome-devtools/speed/imgs/report6.png
  src/content/en/tools/chrome-devtools/speed/imgs/requests.png
  src/content/en/tools/chrome-devtools/speed/imgs/resize.png
  src/content/en/tools/chrome-devtools/speed/imgs/resizereport.png
  src/content/en/tools/chrome-devtools/speed/imgs/screenshots.png
  src/content/en/tools/chrome-devtools/speed/imgs/server.png
  src/content/en/tools/chrome-devtools/speed/imgs/tony.jpg
  src/content/en/tools/chrome-devtools/speed/imgs/undocked.png
  src/content/en/tools/chrome-devtools/speed/imgs/usertiming.png
Labels: P1, cla: yes, section-tools, type-Content

#6280 [devtools] edit speed tutorial
  src/content/en/tools/chrome-devtools/speed/get-started.md
Labels: P1, cla: yes, section-tools, type-Content

#6275 Prepare frame of reference name change ahead of Chrome merge.
  src/content/en/updates/2018/05/welcome-to-immersive.md
Labels: cla: yes

#6281 Update the Google Fonts example.
  src/content/en/tools/workbox/guides/common-recipes.md
Labels: cla: yes

#6253 Adding tree shaking guide.
  src/content/en/fundamentals/performance/_toc.yaml
  src/content/en/fundamentals/performance/optimizing-javascript/tree-shaking/images/figure-1.svg
  src/content/en/fundamentals/performance/optimizing-javascript/tree-shaking/images/figure-2-1x.png
  src/content/en/fundamentals/performance/optimizing-javascript/tree-shaking/images/figure-2-2x.png
  src/content/en/fundamentals/performance/optimizing-javascript/tree-shaking/images/figure-3-1x.png
  src/content/en/fundamentals/performance/optimizing-javascript/tree-shaking/images/figure-3-2x.png
  src/content/en/fundamentals/performance/optimizing-javascript/tree-shaking/images/figure-4-1x.png
  src/content/en/fundamentals/performance/optimizing-javascript/tree-shaking/images/figure-4-2x.png
  src/content/en/fundamentals/performance/optimizing-javascript/tree-shaking/images/figure-5-1x.png
  src/content/en/fundamentals/performance/optimizing-javascript/tree-shaking/images/figure-5-2x.png
  src/content/en/fundamentals/performance/optimizing-javascript/tree-shaking/index.md
Labels: cla: yes

#6282 Change XRPresentationFrame to XRFrame.
  src/content/en/updates/2018/05/welcome-to-immersive.md
Labels: cla: yes

#6289 Fix #5578
  src/content/en/tools/chrome-devtools/network-performance/imgs/large-request-rows.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/small-request-rows.png
  src/content/en/tools/chrome-devtools/network-performance/reference.md
Labels: P2, cla: yes, section-tools, type-Content

#6279 New HTTP 203 podcast
  src/content/en/shows/http203/podcast/io-chats-ewa.md
Labels: cla: yes, section-shows, type-Content

#6283 Update AR/VR status.
  src/content/en/fundamentals/vr/status/index.md
Labels: cla: yes

#6295 Fix codelab link.
  src/content/en/updates/2018/06/ar-for-the-web.md
Labels: cla: yes

#6296 Fix typo
  src/content/en/tools/chrome-devtools/speed/get-started.md
  src/content/en/updates/2017/10/using-twa.md
  src/content/en/updates/2018/03/smooshgate.md
  src/content/en/updates/2018/05/welcome-to-immersive.md
  src/content/en/updates/2018/06/ar-for-the-web.md
Labels: cla: yes

#6308 update UA link
  src/content/en/tools/chrome-user-experience-report/index.md
Labels: cla: yes

#6302 Typo in code example on cache expiration page
  src/content/en/tools/workbox/modules/workbox-cache-expiration.md
Labels: cla: yes

#6311 Mistake in 203 podcast. I am idiot.
  src/content/en/shows/http203/podcast/io-chats-ewa.md
Labels: cla: yes, section-shows, type-Content
