Repository google/WebFundamentals, pull requests merged in 2018-07, with the labels that each got.

#6312 Dvd s3e5
  src/content/en/shows/designer-vs-developer/_toc.yaml
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E01-creating-a-collaborative-environment.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E02-balancing-creativity-with-user-testing.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E03-Adopting-the-native-language-of-the-web.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E04-are-designers-born-or-made.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E05-who-is-responsible-for-design.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E06-are-design-tools-fit-for-purpose.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E03-improving-your-creative-confidence.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E04-creative-ways-of-prototyping.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E05-using-the-gestalt-principles.md
  src/content/en/shows/designer-vs-developer/podcast/images/dvd-s03-e05-cover-large.jpg
  src/content/en/shows/designer-vs-developer/podcast/images/dvd-s03-e05-cover.jpg
Labels: cla: yes

#6317 Updates to templates for new Markdown processor
  src/templates/article-list.md
  src/templates/contributors/article-list.md
  src/templates/contributors/include.html
  src/templates/contributors/index.md
  src/templates/fundamentals/glossary.md
  src/templates/index.yaml
  src/templates/landing-page/latest-show.html
  src/templates/landing-page/latest-updates.html
  src/templates/latest_articles.html
  src/templates/showcase/index.yaml
  src/templates/showcase/region.md
  src/templates/showcase/vertical.md
  src/templates/shows/index.md
  src/templates/shows/latest.html
  src/templates/tags/tag-index.md
  src/templates/tags/tag_toc.yaml
  src/templates/toc-month.yaml
  src/templates/workbox/contributors.html
Labels: cla: yes

#6315 Fix typo
  src/content/en/tools/chrome-devtools/speed/get-started.md
Labels: cla: yes

#6288 More native echo cancellation
  src/content/en/updates/2018/03/macos-native-echo-cancellation.md
  src/content/en/updates/2018/06/more-native-echo-cancellation.md
Labels: cla: no

#6298 Workbox quota best practices guide
  src/content/en/tools/workbox/guides/_toc.yaml
  src/content/en/tools/workbox/guides/storage-quota.md
Labels: cla: yes

#6294 Fixed URL for Policy List
  src/content/en/updates/2017/09/autoplay-policy-changes.md
Labels: cla: no

#6287 AudioWorklet Design Pattern
  src/content/en/updates/2018/06/audio-worklet-design-pattern.md
  src/content/en/updates/images/2018/06/aw-design-pattern-1.png
  src/content/en/updates/images/2018/06/aw-design-pattern-2.png
  src/content/en/updates/images/2018/06/aw-design-pattern-3.png
  src/content/en/updates/images/2018/06/aw-design-pattern-4.png
  src/content/en/updates/images/2018/06/aw-design-pattern-5.png
  src/content/en/updates/images/2018/06/aw-design-pattern-6.png
  src/content/en/updates/images/2018/06/aw-design-pattern-7.png
  src/content/en/updates/images/generic/webaudio.png
  src/data/commonTags.json
Labels: cla: yes

#6292 Update: Intro to Feature Policy
  src/content/en/updates/2018/06/feature-policy.md
  src/content/en/updates/images/2018/06/featurepolicy/violation.png
  src/content/en/updates/images/generic/checklist.png
Labels: cla: no, type-Content

#6318 Weekly Resource Updates
  src/content/en/fundamentals/codelabs/your-first-pwapp/index.md
  src/data/blinkComponents.json
  src/data/codelabs/your-first-pwapp/codelab.json
Labels: cla: yes

#6278 Update ignoreUrlParametersMatching example
  src/content/en/tools/workbox/modules/workbox-precaching.md
Labels: cla: no

#6320 Markdown linting for new MD parser
  src/content/en/fundamentals/codelabs/debugging-service-workers/index.md
  src/content/en/fundamentals/codelabs/offline/index.md
  src/content/en/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/en/fundamentals/design-and-ux/responsive/images.md
  src/content/en/fundamentals/media/manipulating/cheatsheet.md
  src/content/en/fundamentals/payments/payment-request-ux-considerations.md
  src/content/en/fundamentals/performance/optimizing-content-efficiency/javascript-startup-optimization/index.md
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/index.md
  src/content/en/fundamentals/push-notifications/subscribing-a-user.md
  src/content/en/ilt/pwa/e-commerce-lab-3-payment-request-api.md
  src/content/en/ilt/pwa/introduction-to-progressive-web-app-architectures.md
  src/content/en/ilt/pwa/introduction-to-push-notifications.md
  src/content/en/ilt/pwa/lab-indexeddb.md
  src/content/en/ilt/pwa/lab-integrating-web-push.md
  src/content/en/tools/lighthouse/audits/address-bar.md
  src/content/en/tools/lighthouse/audits/custom-splash-screen.md
  src/content/en/tools/lighthouse/audits/deprecated-apis.md
  src/content/en/tools/lighthouse/audits/dom-size.md
  src/content/en/tools/lighthouse/audits/fast-3g.md
  src/content/en/tools/lighthouse/audits/first-interactive.md
  src/content/en/tools/lighthouse/audits/network-payloads.md
  src/content/en/tools/lighthouse/audits/oversized-images.md
  src/content/en/tools/lighthouse/audits/text-compression.md
  src/content/en/updates/2013/06/sourceMappingURL-and-sourceURL-syntax-changed.md
  src/content/en/updates/2015/09/tab-discarding.md
  src/content/en/updates/2016/07/infinite-scroller.md
  src/content/en/updates/2017/01/scrolling-intervention.md
  src/content/en/updates/2017/03/chrome-58-media-updates.md
  src/content/en/updates/2017/03/devtools-release-notes.md
  src/content/en/updates/2017/05/devtools-release-notes.md
  src/content/en/updates/2017/06/budget-api.md
  src/content/en/updates/2017/06/headless-karma-mocha-chai.md
  src/content/en/updates/2017/06/play-request-was-interrupted.md
  src/content/en/updates/2018/03/cssom.md
  src/data/codelabs/debugging-service-workers/codelab.json
  src/data/codelabs/offline/codelab.json
  src/data/codelabs/your-first-pwapp/codelab.json
  src/data/ilt-pwa/e-commerce-lab-3-payment-request-api/codelab.json
  src/data/ilt-pwa/introduction-to-progressive-web-app-architectures/codelab.json
  src/data/ilt-pwa/introduction-to-push-notifications/codelab.json
  src/data/ilt-pwa/lab-indexeddb/codelab.json
  src/data/ilt-pwa/lab-integrating-web-push/codelab.json
Labels: cla: yes

#6309 Fixes for bugs #6222 and #6079
  src/content/en/tools/chrome-devtools/console/command-line-reference.md
  src/content/en/tools/chrome-devtools/console/images/all-selector-div.png
  src/content/en/tools/chrome-devtools/console/images/all-selector.png
  src/content/en/tools/chrome-devtools/console/images/assert.png
  src/content/en/tools/chrome-devtools/console/images/autocomplete.png
  src/content/en/tools/chrome-devtools/console/images/cause.png
  src/content/en/tools/chrome-devtools/console/images/debug.png
  src/content/en/tools/chrome-devtools/console/images/dir.png
  src/content/en/tools/chrome-devtools/console/images/element-0.png
  src/content/en/tools/chrome-devtools/console/images/element-1.png
  src/content/en/tools/chrome-devtools/console/images/error-stack.png
  src/content/en/tools/chrome-devtools/console/images/get-event-listeners.png
  src/content/en/tools/chrome-devtools/console/images/grouped-profiles.png
  src/content/en/tools/chrome-devtools/console/images/inspect.png
  src/content/en/tools/chrome-devtools/console/images/keys-values.png
  src/content/en/tools/chrome-devtools/console/images/monitor-events.png
  src/content/en/tools/chrome-devtools/console/images/monitor-key.png
  src/content/en/tools/chrome-devtools/console/images/monitor.png
  src/content/en/tools/chrome-devtools/console/images/recently-evaluated-expression-1.png
  src/content/en/tools/chrome-devtools/console/images/recently-evaluated-expression-2.png
  src/content/en/tools/chrome-devtools/console/images/scrolling-list-expanded.png
  src/content/en/tools/chrome-devtools/console/images/scrolling-list.png
  src/content/en/tools/chrome-devtools/console/images/selector-img-div-src.png
  src/content/en/tools/chrome-devtools/console/images/selector-img-src.png
  src/content/en/tools/chrome-devtools/console/images/selector-img.png
  src/content/en/tools/chrome-devtools/console/images/table.png
  src/content/en/tools/chrome-devtools/console/images/xpath-p-a-example.png
  src/content/en/tools/chrome-devtools/console/images/xpath-p-example.png
  src/content/en/tools/chrome-devtools/console/images/xpath-p-node-example.png
  src/content/en/tools/chrome-devtools/evaluate-performance/reference.md
Labels: cla: yes, type-Content

#6326 Adding data saver note to video-over-gif guide.
  src/content/en/fundamentals/performance/optimizing-content-efficiency/replace-animated-gifs-with-video/index.md
Labels: cla: yes

#6323 feature policy: few more tweaks
  src/content/en/updates/2018/06/feature-policy.md
Labels: cla: yes

#6322 Update the Google Fonts homepage recipe
  src/content/en/tools/workbox/_index.yaml
Labels: cla: yes

#6321 Remove outdated contrast ratio doc.
  src/content/en/tools/_redirects.yaml
  src/content/en/tools/lighthouse/_toc.yaml
  src/content/en/tools/lighthouse/audits/_feedback/contrast-ratio.html
  src/content/en/tools/lighthouse/audits/contrast-ratio.md
  src/content/ko/tools/lighthouse/audits/contrast-ratio.md
Labels: cla: yes

#6332 Anchors for config options in Workbox docs
  src/content/en/tools/workbox/_shared/config/single/cacheId.html
  src/content/en/tools/workbox/_shared/config/single/clientsClaim.html
  src/content/en/tools/workbox/_shared/config/single/directoryIndex.html
  src/content/en/tools/workbox/_shared/config/single/dontCacheBustUrlsMatching.html
  src/content/en/tools/workbox/_shared/config/single/globDirectory.html
  src/content/en/tools/workbox/_shared/config/single/globFollow.html
  src/content/en/tools/workbox/_shared/config/single/globIgnores.html
  src/content/en/tools/workbox/_shared/config/single/globPatterns.html
  src/content/en/tools/workbox/_shared/config/single/globStrict.html
  src/content/en/tools/workbox/_shared/config/single/ignoreUrlParametersMatching.html
  src/content/en/tools/workbox/_shared/config/single/importScripts.html
  src/content/en/tools/workbox/_shared/config/single/importWorkboxFrom.html
  src/content/en/tools/workbox/_shared/config/single/injectionPointRegexp.html
  src/content/en/tools/workbox/_shared/config/single/manifestTransforms.html
  src/content/en/tools/workbox/_shared/config/single/maximumFileSizeToCacheInBytes.html
  src/content/en/tools/workbox/_shared/config/single/modifyUrlPrefix.html
  src/content/en/tools/workbox/_shared/config/single/navigateFallback.html
  src/content/en/tools/workbox/_shared/config/single/navigateFallbackBlacklist.html
  src/content/en/tools/workbox/_shared/config/single/navigateFallbackWhitelist.html
  src/content/en/tools/workbox/_shared/config/single/runtimeCaching.html
  src/content/en/tools/workbox/_shared/config/single/skipWaiting.html
  src/content/en/tools/workbox/_shared/config/single/swDest.html
  src/content/en/tools/workbox/_shared/config/single/swSrc.html
  src/content/en/tools/workbox/_shared/config/single/templatedUrls.html
  src/content/en/tools/workbox/_shared/config/webpack-single/chunks.html
  src/content/en/tools/workbox/_shared/config/webpack-single/exclude.html
  src/content/en/tools/workbox/_shared/config/webpack-single/excludeChunks.html
  src/content/en/tools/workbox/_shared/config/webpack-single/importsDirectory.html
  src/content/en/tools/workbox/_shared/config/webpack-single/include.html
  src/content/en/tools/workbox/_shared/config/webpack-single/precacheManifestFilename.html
  src/content/en/tools/workbox/_shared/config/webpack-single/swDest.html
  src/content/en/tools/workbox/_shared/config/webpack-single/swSrc.html
  src/content/en/tools/workbox/modules/workbox-build.md
  src/content/en/tools/workbox/modules/workbox-cli.md
  src/content/en/tools/workbox/modules/workbox-webpack-plugin.md
Labels: cla: yes

#6334 Make testing template tags optional
  gulp-tasks/test.js
  gulp-tasks/tests/validateContent.js
Labels: cla: yes

#6335 FID in CrUX update
  src/content/en/updates/2018/07/first-input-delay-in-crux.md
  src/content/en/updates/images/misc/fid-secretlycanadian-filmstrip.png
  src/content/en/updates/images/misc/fid-secretlycanadian-waterfall.png
  src/content/en/updates/images/misc/fid-wtfast-filmstrip.png
  src/content/en/updates/images/misc/fid-wtfast-waterfall.png
  src/content/en/updates/images/misc/first-input-delay.png
Labels: cla: yes

#6344 Add Site Isolation update
  src/content/en/updates/2018/07/site-isolation.md
Labels: cla: yes

#6345 Fix-ups to old Meltdown/Spectre post
  src/content/en/updates/2018/02/meltdown-spectre.md
  src/content/en/updates/2018/05/bigint.md
  src/content/en/updates/2018/07/site-isolation.md
Labels: cla: yes

#6340 New podcast
  src/content/en/shows/http203/podcast/io-chats-pirish-jason.md
Labels: cla: yes, section-shows, type-Content

#6337 [devtools] minor fixes to the speed tutorial
  src/content/en/tools/chrome-devtools/speed/get-started.md
  src/content/en/tools/chrome-devtools/speed/imgs/audits.png
Labels: P2, cla: yes, section-tools, type-Content

#6338 Add section + diagram to explain how queuing affects available input response time
  src/content/en/fundamentals/performance/images/rail-response-details.png
  src/content/en/fundamentals/performance/rail.md
Labels: cla: yes

#6351 Add missing tag.
  src/content/en/updates/2017/10/remove-shadow-piercing.md
Labels: cla: yes

#6352 workbox-navigation-preload module doc
  src/content/en/tools/workbox/modules/_index.yaml
  src/content/en/tools/workbox/modules/_toc.yaml
  src/content/en/tools/workbox/modules/workbox-navigation-preload.md
  src/content/en/tools/workbox/modules/workbox-range-requests.md
Labels: cla: yes

#6342 custom elements: beef up polyfill information.
  src/content/en/fundamentals/web-components/customelements.md
Labels: cla: no, type-Content

#6372 Generate feeds by year, sorted by published date
  gulp-tasks/build.js
Labels: cla: yes

#6373 Weekly content updates (0716)
  src/content/en/fundamentals/codelabs/debugging-service-workers/index.md
  src/content/en/fundamentals/codelabs/offline/index.md
  src/data/blinkComponents.json
  src/data/codelabs/debugging-service-workers/codelab.json
  src/data/codelabs/offline/codelab.json
  src/data/codelabs/your-first-pwapp/codelab.json
Labels: cla: yes

#6377 Fix landing page typo.
  src/content/en/fundamentals/index.md
Labels: cla: yes

#6375 Writing mistake
  src/content/tr/fundamentals/security/hacked/fixing_the_cloaked_keywords_hack.html
Labels: cla: yes

#6378 typo: you -> your
  src/content/en/fundamentals/app-install-banners/index.md
Labels: cla: yes

#6379 PWACompat update post
  src/content/en/updates/2018/07/pwacompat.md
  src/content/en/updates/images/2018/07/emojityper-ios.mp4
  src/content/en/updates/images/2018/07/pwacompat.png
  src/content/en/updates/images/2018/07/webmanifest.png
Labels: cla: yes

#6380 DPWA status update
  src/content/en/updates/2018/05/dpwa.md
Labels: cla: yes

#6381 PWACompat post fix
  src/content/en/updates/2018/07/pwacompat.md
Labels: cla: yes

#6383 HTTP 203 podcast
  src/content/en/shows/http203/podcast/io-chats-emily-chris.md
Labels: cla: yes, section-shows, type-Content

#6387 [devtools] add vid to wndt68
  src/content/en/updates/2018/05/devtools.md
Labels: P1, cla: yes, section-updates, type-Content

#6385 Change 'exclusive' to 'immersive'.
  src/content/en/updates/2018/05/welcome-to-immersive.md
  src/content/en/updates/2018/06/ar-for-the-web.md
Labels: cla: yes

#6386 Update agency directory json to add mediology software
  src/content/en/agencies/data/agencies.json
  src/content/en/agencies/images/mediology_software_readwhere_cms.png
Labels: P2, cla: yes, section-agencies

#6388 DvD s3e6 - Replacement for PR #6382
  src/content/en/shows/designer-vs-developer/_toc.yaml
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E01-designing-for-css-grid.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E02-designing-for-standards.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E05-using-the-gestalt-principles.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E06-how-to-design-a-vr-game.md
  src/content/en/shows/designer-vs-developer/podcast/images/dvd-s03-e06-cover-large.jpg
  src/content/en/shows/designer-vs-developer/podcast/images/dvd-s03-e06-cover.jpg
Labels: cla: yes

#6389 Fix the cacheName option in the Workbox guides.
  src/content/en/tools/workbox/guides/generate-service-worker/cli.md
  src/content/en/tools/workbox/guides/generate-service-worker/webpack.md
  src/content/en/tools/workbox/guides/generate-service-worker/workbox-build.md
Labels: cla: yes

#6390 Update metrics and screenshot.
  src/content/en/fundamentals/performance/images/lighthouse-performance.jpg
  src/content/en/fundamentals/performance/images/lighthouse-performance.png
  src/content/en/fundamentals/performance/rail.md
Labels: cla: yes, type-Content

#6376 TR Typo corrections in OCE - Elim Downloads
  src/content/tr/fundamentals/performance/optimizing-content-efficiency/eliminate-downloads.md
Labels: cla: yes

#6369 [devtools] add a11y reference
  src/content/en/tools/chrome-devtools/_toc.yaml
  src/content/en/tools/chrome-devtools/accessibility/imgs/a11y-pane.png
  src/content/en/tools/chrome-devtools/accessibility/imgs/a11y-tree.png
  src/content/en/tools/chrome-devtools/accessibility/imgs/aXe.png
  src/content/en/tools/chrome-devtools/accessibility/imgs/aria.png
  src/content/en/tools/chrome-devtools/accessibility/imgs/attributes.png
  src/content/en/tools/chrome-devtools/accessibility/imgs/color-picker.png
  src/content/en/tools/chrome-devtools/accessibility/imgs/color.png
  src/content/en/tools/chrome-devtools/accessibility/imgs/computed-a11y.png
  src/content/en/tools/chrome-devtools/accessibility/imgs/config.png
  src/content/en/tools/chrome-devtools/accessibility/imgs/contrast-ratio-line.png
  src/content/en/tools/chrome-devtools/accessibility/imgs/documentation.png
  src/content/en/tools/chrome-devtools/accessibility/imgs/inspect.png
  src/content/en/tools/chrome-devtools/accessibility/imgs/report.png
  src/content/en/tools/chrome-devtools/accessibility/reference.md
  src/content/en/tools/chrome-devtools/images/shared/more-tabs.png
Labels: DO NOT MERGE, P1, cla: yes, section-tools, type-Content

#6392 Tiny typo: users -> user's
  src/content/en/updates/2018/05/dpwa.md
Labels: cla: yes

#6393 [lighthouse] add unused css reference
  src/content/en/tools/chrome-devtools/css/imgs/command-menu.png
  src/content/en/tools/chrome-devtools/css/imgs/coverage-detail.png
  src/content/en/tools/chrome-devtools/css/imgs/coverage-empty.png
  src/content/en/tools/chrome-devtools/css/imgs/coverage-overview.png
  src/content/en/tools/chrome-devtools/css/imgs/reload.png
  src/content/en/tools/chrome-devtools/css/reference.md
  src/content/en/tools/lighthouse/_toc.yaml
  src/content/en/tools/lighthouse/audits/unused-css.md
Labels: P1, cla: yes, section-tools, type-Content

#6395 add a no-config "was this page helpful?" feedback widget
  src/content/en/_shared/helpful.html
  src/content/en/tools/lighthouse/audits/unused-css.md
Labels: P1, cla: yes, section-tools, type-Content

#6394 feature policy: add devtools extension link.
  src/content/en/updates/2018/06/feature-policy.md
Labels: cla: yes, migrate-content

#6391 Handful of 404 fixes
  src/content/en/fundamentals/performance/why-performance-matters/index.md
  src/content/en/fundamentals/security/hacked/fixing_the_cloaked_keywords_hack.md
  src/content/en/fundamentals/security/hacked/fixing_the_gibberish_hack.md
  src/content/en/fundamentals/security/hacked/fixing_the_japanese_keyword_hack.md
  src/content/en/tools/_redirects.yaml
Labels: cla: yes

#6384 Add help text about hover states to a11y how-to-review page
  src/content/en/fundamentals/accessibility/how-to-review.md
Labels: cla: no

#6399 Fixed some typos in PWACompat article
  src/content/en/updates/2018/07/pwacompat.md
Labels: cla: yes

#6400 Fixed single quotes in App Shell article
  src/content/en/fundamentals/architecture/app-shell.md
Labels: cla: yes

#6401 Fixed some typos in UX Basics
  src/content/en/fundamentals/design-and-ux/ux-basics/index.md
Labels: cla: yes

#6403 Improved some wording in Design and UX Principles
  src/content/en/fundamentals/design-and-ux/principles/index.md
Labels: cla: yes

#6406 Fix Typo: ctor -> constructor
  src/content/en/fundamentals/web-components/customelements.md
  src/content/en/fundamentals/web-components/shadowdom.md
  src/content/es/fundamentals/web-components/customelements.md
  src/content/es/fundamentals/web-components/shadowdom.md
  src/content/id/fundamentals/web-components/customelements.md
  src/content/id/fundamentals/web-components/shadowdom.md
  src/content/ja/fundamentals/web-components/customelements.md
  src/content/ja/fundamentals/web-components/shadowdom.md
  src/content/ko/fundamentals/web-components/customelements.md
  src/content/ko/fundamentals/web-components/shadowdom.md
  src/content/pt-br/fundamentals/web-components/customelements.md
  src/content/pt-br/fundamentals/web-components/shadowdom.md
  src/content/zh-cn/fundamentals/web-components/customelements.md
  src/content/zh-cn/fundamentals/web-components/shadowdom.md
  src/content/zh-tw/fundamentals/web-components/customelements.md
  src/content/zh-tw/fundamentals/web-components/shadowdom.md
Labels: cla: yes

#6409 Fix some wording.
  src/content/en/fundamentals/design-and-ux/ux-basics/index.md
Labels: cla: yes

#6413 Add "Speed is now a landing page factor for Google Search and Ads."
  src/content/en/updates/2018/07/search-ads-speed.md
  src/content/en/updates/images/2018/07/infographic-speed-tools.jpg
Labels: cla: yes, section-updates, type-Content

#6416 New HTTP 203 podcast.
  src/content/en/shows/http203/podcast/io-chats-martin.md
Labels: cla: yes, section-shows, type-Content

#6412 add rollup-plugin-purgecss mention to "unused css" reference
  src/content/en/tools/lighthouse/audits/unused-css.md
Labels: P2, cla: yes, type-Content

#6404 Add Page Lifecycle API article
  src/content/en/updates/2018/07/page-lifecycle-api.md
  src/content/en/updates/images/2018/07/chrome-discards.png
  src/content/en/updates/images/2018/07/page-lifecycle-api-state-event-flow.png
Labels: cla: yes, section-updates

#6418 Adds new Feedback Widget to several pages
  src/content/en/fundamentals/app-install-banners/index.md
  src/content/en/fundamentals/app-install-banners/native.md
  src/content/en/fundamentals/instant-and-offline/offline-cookbook/index.md
  src/content/en/fundamentals/integration/webapks.md
  src/content/en/fundamentals/performance/optimizing-content-efficiency/http-caching.md
  src/content/en/fundamentals/primers/async-functions.md
  src/content/en/fundamentals/primers/modules.md
  src/content/en/fundamentals/primers/promises.md
  src/content/en/fundamentals/web-app-manifest/index.md
  src/content/en/progressive-web-apps/checklist.md
  src/content/en/updates/2016/03/chrome-50-deprecations.md
  src/content/en/updates/2017/09/autoplay-policy-changes.md
  src/content/en/updates/2018/07/nic68.md
Labels: cla: yes

#6422 Fix captions not supporting links.
  src/content/en/updates/2018/07/search-ads-speed.md
Labels: cla: yes, type-Content

#6423 Page lifecycle api updates
  src/content/en/images/contributors/philipwalton.jpg
  src/content/en/updates/2018/07/page-lifecycle-api.md
Labels: cla: yes

#6420 Font update & Code Highlighting
  devsiteParseHTML.py
  devsiteParseMD.py
  gae/includes/page-head.html
  gae/page-base.html
Labels: cla: yes

#6419 Tip for updating icons
  src/content/en/fundamentals/app-install-banners/index.md
Labels: cla: yes

#6424 FID aspect ratio
  src/content/en/updates/images/misc/first-input-delay.png
Labels: cla: yes

#6426 Add missing AMP mention to speed as a factor of search/ads doc
  src/content/en/updates/2018/07/search-ads-speed.md
Labels: cla: yes, section-updates, type-Content

#6421 docs: fix typo
  src/content/en/fundamentals/payments/deep-dive-into-payment-request.md
  src/content/en/fundamentals/push-notifications/notification-behaviour.md
Labels: cla: yes

#6429 Fix array mutation on RSS generation
  gulp-tasks/build.js
  gulp-tasks/wfTemplateHelper.js
Labels: cla: yes

#6397 Add NoState Prefetch article
  src/content/en/updates/2018/07/nostate-prefetch.md
  src/content/en/updates/images/2018/07/nostate-prefetch.png
  src/data/_contributors.yaml
Labels: cla: yes

#6431 adding new podcast files and optimizing images
  src/content/en/shows/designer-vs-developer/_toc.yaml
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E07-Designing-for-offline.md
  src/content/en/shows/designer-vs-developer/podcast/images/dvd-s03-e01-cover-large.jpg
  src/content/en/shows/designer-vs-developer/podcast/images/dvd-s03-e02-cover-large.jpg
  src/content/en/shows/designer-vs-developer/podcast/images/dvd-s03-e07-cover-large.jpg
  src/content/en/shows/designer-vs-developer/podcast/images/dvd-s03-e07-cover.jpg
Labels: cla: yes

#6432 Fixed Spelling.
  gulp-tasks/tests/commonTypos.js
  gulp-tasks/tests/validateContent.js
  gulp-tasks/tests/validateHtml.js
  gulp-tasks/tests/validateMarkdown.js
  src/content/en/updates/2015/07/rotationAngle-and-touchRadius.md
Labels: cla: yes

#6434 [lighthouse] add reference for robots.txt audit
  src/content/en/tools/lighthouse/_toc.yaml
  src/content/en/tools/lighthouse/audits/images/robots.png
  src/content/en/tools/lighthouse/audits/robots.md
Labels: P1, cla: yes, section-tools, type-Content

#6433 Reporting Observer update
  src/content/en/updates/2018/07/reportingobserver.md
  src/content/en/updates/images/2018/07/reporting/consolewarnings.png
  src/content/en/updates/images/2018/07/reporting/lighthouse_deprecations.png
  src/content/en/updates/images/generic/send.png
Labels: cla: yes, type-Content

#6437 Fix Workbox docs typo s/networkTimetoutSeconds/networkTimeoutSeconds/g
  src/content/en/tools/workbox/guides/common-recipes.md
Labels: cla: yes

#6442 Remove Auto Quotes from code in updates. Fixes #6441
  src/content/en/updates/2012/03/A-New-Experimental-Feature-style-scoped.md
  src/content/en/updates/2012/07/Drag-and-drop-a-folder-onto-Chrome-now-available.md
  src/content/en/updates/2015/01/Lets-build-some-apps-with-Polymer.md
  src/content/en/updates/2015/08/material-design-lite-1-0-4-release.md
  src/content/en/updates/2016/12/chrome-56-deprecations.md
  src/content/en/updates/2016/12/performant-parallaxing.md
  src/content/en/updates/2018/07/nostate-prefetch.md
Labels: cla: yes

#6444 Brits be gone - Removes u's and s's... Fixes #6443
  src/content/en/updates/2013/07/Alpha-transparency-in-Chrome-video.md
  src/content/en/updates/2014/12/Fundamental-of-Mobile-Web-Development.md
  src/content/en/updates/2015/01/ES6-Template-Strings.md
  src/content/en/updates/2015/01/What-the-Viewport.md
  src/content/en/updates/2015/04/autocapitalize.md
  src/content/en/updates/2015/05/notifying-you-of-changes-to-notifications.md
  src/content/en/updates/2015/05/some-ui-and-feature-enhancements-to-the-colour-picker-tool.md
  src/content/en/updates/2015/07/network-colour-groups.md
  src/content/en/updates/2015/08/material-design-lite-1-0-4-release.md
  src/content/en/updates/2015/08/simple-keyboard-tricks-to-use-in-the-styles-pane.md
  src/content/en/updates/2015/08/using-manifest-to-set-sitewide-theme-color.md
  src/content/en/updates/2015/09/tab-discarding.md
  src/content/en/updates/2016/02/es2015-proxies.md
  src/content/en/updates/2016/03/mse-sourcebuffer.md
  src/content/en/updates/2016/03/notifications.md
  src/content/en/updates/2016/04/scroll-anchoring.md
  src/content/en/updates/2016/07/autoplay.md
  src/content/en/updates/2016/10/pointer-events.md
  src/content/en/updates/2017/01/scrolling-intervention.md
  src/content/en/updates/2017/02/chrome-57-deprecations.md
  src/content/en/updates/2017/02/media-session.md
  src/content/en/updates/2017/02/navigation-preload.md
  src/content/en/updates/2017/07/chrome-61-media-updates.md
  src/content/en/updates/2017/09/autoplay-policy-changes.md
  src/content/en/updates/2017/12/chrome-63-64-media-updates.md
Labels: cla: yes, type-Content
