Repository google/WebFundamentals, pull requests merged in 2018-09, with the labels that each got.

#6575 Fix typo
  src/content/en/fundamentals/performance/audit/tools.md
  src/content/en/fundamentals/performance/webpack/use-long-term-caching.md
Labels: cla: yes

#6576 New in Chrome 69
  .gitignore
  gae/page-base.html
  gae/scripts/devsite-dev.js
  src/content/en/updates/2018/09/nic69.md
  src/content/en/updates/_redirects.yaml
  src/content/en/updates/images/2018/09/conic-gradient.jpg
  src/content/en/updates/images/2018/09/notch-extra-margin.png
  src/content/en/updates/images/2018/09/simple-notch.png
  tools/update-resources.sh
Labels: cla: yes

#6577 Add a link to the heuristics doc
  src/content/en/updates/2018/07/page-lifecycle-api.md
Labels: cla: yes, type-Content

#6568 fix(japanese): switch to better translation for the word "accesibility"
  src/content/ja/fundamentals/accessibility/accessible-styles.md
  src/content/ja/fundamentals/accessibility/focus/index.md
  src/content/ja/fundamentals/accessibility/index.md
  src/content/ja/fundamentals/accessibility/semantics-aria/hiding-and-updating-content.md
  src/content/ja/fundamentals/accessibility/semantics-aria/index.md
  src/content/ja/fundamentals/accessibility/semantics-builtin/index.md
  src/content/ja/fundamentals/accessibility/semantics-builtin/navigating-content.md
  src/content/ja/fundamentals/accessibility/semantics-builtin/the-accessibility-tree.md
  src/content/ja/fundamentals/design-and-ux/responsive/images.md
  src/content/ja/fundamentals/design-and-ux/responsive/index.md
  src/content/ja/fundamentals/media/video.md
  src/content/ja/fundamentals/performance/optimizing-content-efficiency/webfont-optimization.md
  src/content/ja/fundamentals/web-components/customelements.md
Labels: cla: yes

#6584 Remove AV1 from media updates post
  src/content/en/updates/2018/08/chrome-69-media-updates.md
Labels: cla: yes

#6583 Updates to NIC69 post
  src/content/en/updates/2018/09/nic69.md
Labels: cla: yes

#6580 reinstate mkazi as contributor to CrUX post
  src/content/en/updates/2018/08/chrome-ux-report-dashboard.md
Labels: cla: yes

#6578 Update offline-for-pwa.md - Added mention to Workbox
  src/content/en/fundamentals/instant-and-offline/web-storage/offline-for-pwa.md
Labels: cla: yes

#6570 Reporting API article
  src/content/en/updates/2018/06/feature-policy.md
  src/content/en/updates/2018/07/reportingobserver.md
  src/content/en/updates/2018/09/reportingapi.md
  src/content/en/updates/images/2018/08/reporting/about_network.png
Labels: cla: yes, type-Content

#6559 Fix typos, warnings
  src/content/en/fundamentals/payments/payment-request-ux-considerations.md
  src/content/en/fundamentals/performance/optimizing-content-efficiency/image-optimization.md
  src/content/en/shows/cds/2013/polymer.md
  src/content/en/shows/ttt/series-2/es2015.md
  src/content/en/shows/ttt/series-2/windows-commandline.md
  src/content/en/tools/chrome-devtools/beginners/html.md
  src/content/en/tools/workbox/guides/generate-complete-sw.md
  src/content/fr/fundamentals/security/hacked/glossary_for_hacked_sites.html
  src/content/fr/fundamentals/security/hacked/top_ways_websites_get_hacked_by_spammers.html
  src/content/fr/fundamentals/security/hacked/use_search_console.html
  src/content/nl/fundamentals/security/hacked/glossary_for_hacked_sites.html
  src/content/nl/fundamentals/security/hacked/top_ways_websites_get_hacked_by_spammers.html
  src/content/pl/fundamentals/security/hacked/use_search_console.html
  src/content/pt-br/fundamentals/codelabs/your-first-multi-screen-site/index.md
  src/content/pt-br/fundamentals/design-and-ux/input/forms/index.md
  src/content/pt-br/fundamentals/design-and-ux/ux-basics/index.md
  src/content/pt-br/fundamentals/instant-and-offline/offline-cookbook/index.md
  src/content/pt-br/fundamentals/payments/android-pay.md
  src/content/pt-br/fundamentals/payments/index.md
  src/content/pt-br/fundamentals/security/credential-management/index.md
  src/content/pt-br/fundamentals/security/encrypt-in-transit/enable-https.md
  src/content/pt-br/fundamentals/security/hacked/glossary_for_hacked_sites.html
  src/content/pt-br/fundamentals/security/hacked/top_ways_websites_get_hacked_by_spammers.html
  src/content/pt-br/fundamentals/security/hacked/use_search_console.html
Labels: cla: yes

#6572 Add post about the Cookie Store API.
  src/content/en/images/contributors/victorcostan.jpg
  src/content/en/updates/2018/09/asynchronous-access-to-http-cookies.md
  src/data/_contributors.yaml
Labels: cla: yes

#6586 Updated New in Chrome thumbnail
  src/content/en/updates/images/generic/new-in-chrome.png
Labels: cla: yes

#6585 Fix wording in reporting API conclusion
  src/content/en/updates/2018/09/reportingapi.md
Labels: cla: yes

#6595 Fix published date for Cookie Store API article
  src/content/en/updates/2018/09/asynchronous-access-to-http-cookies.md
Labels: cla: yes

#6592 Add inside-browser article part2
  src/content/en/updates/2018/09/inside-browser-part2.md
  src/content/en/updates/images/inside-browser/part2/beforeunload.png
  src/content/en/updates/images/inside-browser/part2/browserprocesses.png
  src/content/en/updates/images/inside-browser/part2/commit.png
  src/content/en/updates/images/inside-browser/part2/findrenderer.png
  src/content/en/updates/images/inside-browser/part2/input.png
  src/content/en/updates/images/inside-browser/part2/loaded.png
  src/content/en/updates/images/inside-browser/part2/navpreload.png
  src/content/en/updates/images/inside-browser/part2/navstart.png
  src/content/en/updates/images/inside-browser/part2/renderer_init.png
  src/content/en/updates/images/inside-browser/part2/response.png
  src/content/en/updates/images/inside-browser/part2/scope_lookup.png
  src/content/en/updates/images/inside-browser/part2/serviceworker.png
  src/content/en/updates/images/inside-browser/part2/sniff.png
  src/content/en/updates/images/inside-browser/part2/unload.png
Labels: cla: yes, type-Content

#6598 Nav preload no longer an origin trial
  src/content/en/updates/2017/02/navigation-preload.md
Labels: cla: yes, section-updates, type-Content

#6591 Fix run-on sentence
  src/content/en/fundamentals/app-install-banners/index.md
Labels: cla: yes

#6588 Inside browser part 1 - edit
  src/content/en/updates/2018/09/inside-browser-part1.md
  src/content/en/updates/images/inside-browser/part1/CPU.png
  src/content/en/updates/images/inside-browser/part1/GPU.png
  src/content/en/updates/images/inside-browser/part1/browser-arch.png
  src/content/en/updates/images/inside-browser/part1/browser-arch2.png
  src/content/en/updates/images/inside-browser/part1/browserui.png
  src/content/en/updates/images/inside-browser/part1/hw-os-app.png
  src/content/en/updates/images/inside-browser/part1/isolation.png
  src/content/en/updates/images/inside-browser/part1/memory.png
  src/content/en/updates/images/inside-browser/part1/memory.svg
  src/content/en/updates/images/inside-browser/part1/process-thread.png
  src/content/en/updates/images/inside-browser/part1/servicfication.png
  src/content/en/updates/images/inside-browser/part1/servicfication.svg
  src/content/en/updates/images/inside-browser/part1/tabs.png
  src/content/en/updates/images/inside-browser/part1/tabs.svg
  src/content/en/updates/images/inside-browser/part1/workerprocess.png
  src/content/en/updates/images/inside-browser/part1/workerprocess.svg
Labels: cla: yes, type-Content

#6589 /web/agencies update JSON and bugfixes
  src/content/en/agencies/css/directory.css
  src/content/en/agencies/data/agencies.json
  src/content/en/agencies/images/digifutura.png
  src/content/en/agencies/images/wunderman.png
  src/content/en/agencies/js/directory.js
Labels: P2, cla: yes, section-agencies

#6597 waitFor should be waitUntil in async cookies post
  src/content/en/updates/2018/09/asynchronous-access-to-http-cookies.md
Labels: cla: yes

#6604 CDS Banner
  src/content/en/_project.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes

#6621 Rewrite lead paragraph, remove duplicate text
  src/content/en/fundamentals/design-and-ux/input/forms/index.md
Labels: cla: yes

#6620 geolocation-on-secure-contexts-only - fix code snippet
  src/content/en/updates/2016/04/geolocation-on-secure-contexts-only.md
Labels: cla: yes

#6615 New HTTP 203 podcast
  src/content/en/shows/http203/podcast/transform-transpile-urinal.md
Labels: cla: yes, section-shows, type-Content

#6623 Add BBVA Spain to Who is using Workbox
  src/content/en/tools/workbox/_index.yaml
  src/content/en/tools/workbox/images/third_party/logos/bbva.png
Labels: cla: yes

#6609 Manual doc updates for Workbox 3.5.0
  src/content/en/tools/workbox/_shared/config/groups/common-generate-schema.html
  src/content/en/tools/workbox/_shared/config/single/offlineGoogleAnalytics.html
  src/content/en/tools/workbox/_shared/config/single/runtimeCaching.html
Labels: cla: yes

#6610 reporting observer: fix link
  src/content/en/updates/2018/07/reportingobserver.md
Labels: cla: yes

#6307 Web payments docs
  src/content/en/fundamentals/_redirects.yaml
  src/content/en/fundamentals/payments/_toc.yaml
  src/content/en/fundamentals/payments/android-pay.md
  src/content/en/fundamentals/payments/basics/how-payment-ecosyste-works.md
  src/content/en/fundamentals/payments/basics/how-payment-request-api-works.md
  src/content/en/fundamentals/payments/basics/payment-method-basics.md
  src/content/en/fundamentals/payments/images/android-payment-apps/diagram1.png
  src/content/en/fundamentals/payments/images/android-payment-apps/diagram2.png
  src/content/en/fundamentals/payments/images/android-payment-apps/diagram3.png
  src/content/en/fundamentals/payments/images/android-payment-apps/diagram4.png
  src/content/en/fundamentals/payments/images/android-payment-apps/diagram5.png
  src/content/en/fundamentals/payments/images/overview/easy-consistent.png
  src/content/en/fundamentals/payments/images/overview/secure-flexible.png
  src/content/en/fundamentals/payments/images/overview/standard-open.png
  src/content/en/fundamentals/payments/images/payment-ecosystem/payment-interactions.png
  src/content/en/fundamentals/payments/images/payment-ecosystem/payment-transaction-process.png
  src/content/en/fundamentals/payments/images/payment-method-basics/payment-methods.png
  src/content/en/fundamentals/payments/images/ux-considerations/affordance-touch-targets.png
  src/content/en/fundamentals/payments/images/ux-considerations/basic-intro-poster.png
  src/content/en/fundamentals/payments/images/ux-considerations/delivery-options-delivery.png
  src/content/en/fundamentals/payments/images/ux-considerations/delivery-options-pickup.png
  src/content/en/fundamentals/payments/images/ux-considerations/delivery-options-with-dates.png
  src/content/en/fundamentals/payments/images/ux-considerations/general-ux-buy-now.png
  src/content/en/fundamentals/payments/images/ux-considerations/gift-card-checkout-flow.png
  src/content/en/fundamentals/payments/images/ux-considerations/graceful-error-messaging.png
  src/content/en/fundamentals/payments/images/ux-considerations/graceful-stepper.png
  src/content/en/fundamentals/payments/images/ux-considerations/mid-way-flow.png
  src/content/en/fundamentals/payments/images/ux-considerations/show-to-promise.png
  src/content/en/fundamentals/payments/images/ux-considerations/state01-receipt-view.png
  src/content/en/fundamentals/payments/images/ux-considerations/state02-edit-view.png
  src/content/en/fundamentals/payments/images/ux-considerations/user-flow-diagram.png
  src/content/en/fundamentals/payments/images/ux-considerations/what-can-be-changed.png
  src/content/en/fundamentals/payments/images/ux-considerations/wooCommerce.png
  src/content/en/fundamentals/payments/images/web-payment-apps/manifest-icons.png
  src/content/en/fundamentals/payments/images/web-payment-apps/pay-with-bobpay.png
  src/content/en/fundamentals/payments/images/web-payment-apps/payment-handler.png
  src/content/en/fundamentals/payments/images/web-payment-apps/user-hint.png
  src/content/en/fundamentals/payments/index.md
  src/content/en/fundamentals/payments/merchant-guide/deep-dive-into-payment-request.md
  src/content/en/fundamentals/payments/merchant-guide/payment-request-ux-considerations.md
  src/content/en/fundamentals/payments/payment-apps-developer-guide/android-payment-apps.md
  src/content/en/fundamentals/payments/payment-apps-developer-guide/web-payment-apps.md
  src/content/en/images/contributors/rsolomakhin.jpg
  src/data/_contributors.yaml
Labels: cla: yes

#6627 adding new episode
  src/content/en/shows/designer-vs-developer/_toc.yaml
  src/content/en/shows/designer-vs-developer/podcast/DVDS4E02-ux-research-usability-testingy.md
Labels: cla: yes

#6625 Deprecations and removals for Chrome 70
  src/content/en/updates/2018/09/chrome-70-deps-rems.md
Labels: cla: no

#6613 Remove outdated info on 'The Offline Cookbook' page
  src/content/en/fundamentals/instant-and-offline/offline-cookbook/index.md
Labels: cla: yes

#6612 PWA-ILT: v2 ecommerce content
  src/content/en/ilt/pwa/_book.yaml
  src/content/en/ilt/pwa/challenge-convert-an-e-commerce-site-to-a-pwa.md
  src/content/en/ilt/pwa/img/4ba00f8716979a32.png
  src/content/en/ilt/pwa/img/7b09e0d55e1235b3.png
  src/data/ilt-pwa/challenge-convert-an-e-commerce-site-to-a-pwa/codelab.json
  src/data/ilt-pwa/lab-cloud-firestore/codelab.json
Labels: cla: yes, type-Content

#6607 Mention that Chrome OS does not display the mini-info bar
  src/content/en/fundamentals/app-install-banners/index.md
Labels: cla: yes

#6606 Fix more grammar issues
  src/content/en/fundamentals/app-install-banners/index.md
Labels: cla: yes

#6605 Fix run-on sentence
  src/content/en/fundamentals/app-install-banners/_a2hs-criteria.html
Labels: cla: yes

#6611 Fix typos
  src/content/en/updates/2018/09/inside-browser-part1.md
  src/content/en/updates/2018/09/reportingapi.md
Labels: cla: yes

#6629 Add polyfill note to HTML import deprecation.
  src/content/en/updates/2018/09/chrome-70-deps-rems.md
Labels: cla: yes

#6631 docs: fix typo
  src/content/en/fundamentals/instant-and-offline/offline-ux.md
Labels: cla: yes

#6632 adds note about win & mac support
  src/content/en/updates/2018/05/dpwa.md
Labels: cla: yes

#6520 Document delayed Web Audio API launch
  src/content/en/updates/2017/09/autoplay-policy-changes.md
Labels: cla: yes

#6633 Add "Audio/Video Updates in Chrome 70" /updates article
  src/content/en/updates/2018/09/chrome-70-media-updates.md
  src/content/en/updates/images/2018/09/protected-content-setting.png
Labels: DO NOT MERGE, cla: yes, type-Content

#6634 Fix date on media article.
  src/content/en/updates/2018/09/chrome-70-media-updates.md
Labels: cla: yes

#6581 Addressing some feedback for the code splitting article.
  src/content/en/fundamentals/performance/optimizing-javascript/code-splitting/images/figure-6-1x.png
  src/content/en/fundamentals/performance/optimizing-javascript/code-splitting/images/figure-6-2x.png
  src/content/en/fundamentals/performance/optimizing-javascript/code-splitting/index.md
Labels: DO NOT MERGE, cla: yes

#6638 [Web Payments] Adds a video, made small changes
  src/content/en/fundamentals/payments/basics/how-payment-ecosyste-works.md
  src/content/en/fundamentals/payments/basics/payment-method-basics.md
  src/content/en/fundamentals/payments/index.md
Labels: cla: yes, section-fundamentals, type-Content

#6639 Removes gendered pronouns
  src/content/en/updates/2017/09/autoplay-policy-changes.md
  src/data/common-typos.yaml
Labels: cla: yes

#6641 Nits
  src/content/en/updates/2018/09/chrome-70-media-updates.md
Labels: cla: yes

#6635 Document the changes from Workbox PR 1640
  src/content/en/tools/workbox/guides/using-plugins.md
Labels: cla: yes

#6649 Fix typo
  src/content/en/fundamentals/payments/_toc.yaml
  src/content/en/updates/2018/09/asynchronous-access-to-http-cookies.md
  src/content/en/updates/2018/09/chrome-70-deps-rems.md
  src/content/en/updates/2018/09/inside-browser-part1.md
Labels: cla: yes

#6651 add homepage and toc links
  src/content/en/tools/chrome-devtools/_toc.yaml
  src/content/en/tools/chrome-devtools/index.md
Labels: P1, cla: yes, section-tools, type-Content

#6654 Mention CORS in Dynamic Imports
  src/content/en/updates/2017/11/dynamic-import.md
Labels: cla: yes

#6657 Add note re: code caching
  src/content/en/fundamentals/primers/modules.md
Labels: cla: yes

#6658 add last 2 articles of inside-browser article
  src/content/en/updates/2018/09/inside-browser-part1.md
  src/content/en/updates/2018/09/inside-browser-part2.md
  src/content/en/updates/2018/09/inside-browser-part3.md
  src/content/en/updates/2018/09/inside-browser-part4.md
  src/content/en/updates/images/inside-browser/part3/composit.mp4
  src/content/en/updates/images/inside-browser/part3/composit.png
  src/content/en/updates/images/inside-browser/part3/computedstyle.png
  src/content/en/updates/images/inside-browser/part3/dom.png
  src/content/en/updates/images/inside-browser/part3/drawgame.png
  src/content/en/updates/images/inside-browser/part3/layer.png
  src/content/en/updates/images/inside-browser/part3/layout.mp4
  src/content/en/updates/images/inside-browser/part3/layout.png
  src/content/en/updates/images/inside-browser/part3/naive_rastering.mp4
  src/content/en/updates/images/inside-browser/part3/pagejank1.png
  src/content/en/updates/images/inside-browser/part3/pagejank2.png
  src/content/en/updates/images/inside-browser/part3/paint.png
  src/content/en/updates/images/inside-browser/part3/raf.png
  src/content/en/updates/images/inside-browser/part3/raster.png
  src/content/en/updates/images/inside-browser/part3/renderer.png
  src/content/en/updates/images/inside-browser/part3/tellgame.png
  src/content/en/updates/images/inside-browser/part3/trees.mp4
  src/content/en/updates/images/inside-browser/part3/zindex.png
  src/content/en/updates/images/inside-browser/part4/coalescedevents.png
  src/content/en/updates/images/inside-browser/part4/getCoalescedEvents.png
  src/content/en/updates/images/inside-browser/part4/hittest.png
  src/content/en/updates/images/inside-browser/part4/input.png
  src/content/en/updates/images/inside-browser/part4/nfsr1.png
  src/content/en/updates/images/inside-browser/part4/nfsr2.png
  src/content/en/updates/images/inside-browser/part4/rawevents.png
  src/content/en/updates/images/inside-browser/part4/scroll.png
  src/content/en/updates/images/inside-browser/part4/thanks.png
Labels: cla: yes, type-Content

#6656 Dvds4e3
  src/content/en/shows/designer-vs-developer/_toc.yaml
  src/content/en/shows/designer-vs-developer/podcast/DVDS4E03-material-design-components.md
Labels: cla: yes

#6653 [Web Payments] Change "W3C Payment APIs" to "Web Payments", etc.
  src/content/en/fundamentals/payments/basics/how-payment-ecosyste-works.md
  src/content/en/fundamentals/payments/basics/how-payment-request-api-works.md
  src/content/en/fundamentals/payments/basics/payment-method-basics.md
  src/content/en/fundamentals/payments/images/webpayments.png
  src/content/en/fundamentals/payments/index.md
  src/content/en/fundamentals/payments/payment-apps-developer-guide/android-payment-apps.md
  src/content/en/fundamentals/payments/payment-apps-developer-guide/web-payment-apps.md
Labels: cla: yes

#6659 Revise "Enter Audio Worklet" article
  src/content/en/updates/2017/12/audio-worklet.md
Labels: cla: yes

#6664 [Web Payments] Add durgapandey, fixed a typo
  src/content/en/fundamentals/payments/_toc.yaml
  src/content/en/fundamentals/payments/basics/how-payment-ecosystem-works.md
  src/content/en/fundamentals/payments/index.md
  src/content/en/images/contributors/durgapandey.jpg
  src/data/_contributors.yaml
Labels: cla: yes

#6645 Link regex and pwa ilt
  gulp-tasks/wfCodeLabHelper.js
  src/content/en/ilt/pwa/challenge-convert-a-news-app-to-a-pwa.md
  src/content/en/ilt/pwa/e-commerce-lab-1-create-a-service-worker.md
  src/content/en/ilt/pwa/e-commerce-lab-2-add-to-homescreen.md
  src/content/en/ilt/pwa/e-commerce-lab-3-payment-request-api.md
  src/content/en/ilt/pwa/lab-auditing-with-lighthouse.md
  src/content/en/ilt/pwa/lab-build-a-progressive-web-amp.md
  src/content/en/ilt/pwa/lab-caching-files-with-service-worker.md
  src/content/en/ilt/pwa/lab-fetch-api.md
  src/content/en/ilt/pwa/lab-gulp-setup.md
  src/content/en/ilt/pwa/lab-indexeddb.md
  src/content/en/ilt/pwa/lab-integrating-analytics.md
  src/content/en/ilt/pwa/lab-integrating-web-push.md
  src/content/en/ilt/pwa/lab-migrating-to-workbox-from-sw-precache-and-sw-toolbox.md
  src/content/en/ilt/pwa/lab-offline-quickstart.md
  src/content/en/ilt/pwa/lab-promises.md
  src/content/en/ilt/pwa/lab-responsive-design.md
  src/content/en/ilt/pwa/lab-responsive-images.md
  src/content/en/ilt/pwa/lab-scripting-the-service-worker.md
  src/content/en/ilt/pwa/lab-workbox.md
  src/data/ilt-pwa/e-commerce-lab-1-create-a-service-worker/codelab.json
  src/data/ilt-pwa/e-commerce-lab-2-add-to-homescreen/codelab.json
  src/data/ilt-pwa/e-commerce-lab-3-payment-request-api/codelab.json
  src/data/ilt-pwa/lab-scripting-the-service-worker/codelab.json
  src/data/ilt-pwa/lab-workbox/codelab.json
Labels: cla: yes, type-Content, type-Infrastructure

#6644 AudioWorklet -> Audio Worklet
  src/content/en/updates/2018/06/audio-worklet-design-pattern.md
Labels: cla: yes

#6669 fix for #6668
  src/content/en/updates/2018/09/chrome-70-deps-rems.md
Labels: cla: yes

#6670 Fix typo
  src/content/en/updates/2018/09/inside-browser-part3.md
Labels: cla: yes

#6675 Be more accurate in light of the sequence properties proposal
  src/content/en/updates/2017/07/upcoming-regexp-features.md
Labels: cla: yes

#6677 update wndt70
  src/content/en/updates/2018/08/_experiments.yaml
  src/content/en/updates/2018/08/devtools.md
  src/content/en/updates/images/2018/08/usertiming.png
Labels: P1, cla: yes, section-updates, type-Content

#6679 [devtools] update device mode overview
  src/content/en/tools/chrome-devtools/device-mode/imgs/breakpoint.png
  src/content/en/tools/chrome-devtools/device-mode/imgs/commandmenu.png
  src/content/en/tools/chrome-devtools/device-mode/imgs/cpu.png
  src/content/en/tools/chrome-devtools/device-mode/imgs/device-list.png
  src/content/en/tools/chrome-devtools/device-mode/imgs/device-toolbar.png
  src/content/en/tools/chrome-devtools/device-mode/imgs/geolocation.png
  src/content/en/tools/chrome-devtools/device-mode/imgs/iphone-frame.png
  src/content/en/tools/chrome-devtools/device-mode/imgs/landscape.png
  src/content/en/tools/chrome-devtools/device-mode/imgs/network.png
  src/content/en/tools/chrome-devtools/device-mode/imgs/network2.png
  src/content/en/tools/chrome-devtools/device-mode/imgs/orientation.png
  src/content/en/tools/chrome-devtools/device-mode/imgs/responsive-handles.png
  src/content/en/tools/chrome-devtools/device-mode/imgs/rotate.png
  src/content/en/tools/chrome-devtools/device-mode/imgs/rulers.png
  src/content/en/tools/chrome-devtools/device-mode/imgs/sensors.png
  src/content/en/tools/chrome-devtools/device-mode/imgs/show-device-frame.png
  src/content/en/tools/chrome-devtools/device-mode/imgs/show-media-queries.png
  src/content/en/tools/chrome-devtools/device-mode/imgs/show-rulers.png
  src/content/en/tools/chrome-devtools/device-mode/imgs/show-sensors.png
  src/content/en/tools/chrome-devtools/device-mode/imgs/throttling.png
  src/content/en/tools/chrome-devtools/device-mode/imgs/zoom-viewport.png
  src/content/en/tools/chrome-devtools/device-mode/index.md
  src/content/en/tools/chrome-devtools/images/shared/capture-settings.png
  src/content/en/tools/chrome-devtools/images/shared/customize-and-control-devtools.png
  src/content/en/tools/chrome-devtools/images/shared/toggle-device-toolbar.png
Labels: P1, cla: yes, section-tools, type-Content
