Repository google/WebFundamentals, pull requests merged in 2018-03, with the labels that each got.

#5843 [lighthouse] organize ToC by category
  src/content/en/tools/lighthouse/_toc.yaml
Labels: P2, cla: yes, section-tools, type-Content

#5847 Fix typo
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/index.md
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/index.md
Labels: cla: yes

#5845 adding surmacharge link
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/index.md
Labels: cla: yes

#5844 Fix for loading third-party JS in TOC
  src/content/en/fundamentals/performance/_toc.yaml
Labels: cla: yes, type-Content

#5840 Adds an advanced Workbox recipe for a custom postMessagePlugin
  src/content/en/tools/workbox/guides/advanced-recipes.md
Labels: cla: yes

#5848 Typo in async functions article
  src/content/en/fundamentals/primers/async-functions.md
Labels: cla: yes

#5841 Adding FAQ with scope info
  src/content/en/tools/workbox/guides/troubleshoot-and-debug.md
  src/content/en/tools/workbox/images/guides/troubleshoot-and-debug/scope-no-clients.png
  src/content/en/tools/workbox/images/guides/troubleshoot-and-debug/scope-with-clients.png
Labels: cla: yes

#5851 Fixed some broken images
  src/content/en/fundamentals/performance/optimizing-content-efficiency/automating-image-optimization/index.md
Labels: cla: yes

#5850 Small update in Web Font Optimization article
  src/content/en/fundamentals/performance/optimizing-content-efficiency/webfont-optimization.md
Labels: cla: yes

#5856 add video to WNDT65
  src/content/en/updates/2018/01/devtools.md
Labels: P1, cla: yes, section-updates, type-Content

#5855 [lighthouse] add reference for "title" audit
  src/content/en/tools/lighthouse/_toc.yaml
  src/content/en/tools/lighthouse/audits/_template.md
  src/content/en/tools/lighthouse/audits/title.md
Labels: P1, cla: yes, section-tools, type-Content

#5857 [lighthouse] add reference for indexing audit
  src/content/en/tools/chrome-devtools/images/headers.svg
  src/content/en/tools/chrome-devtools/network-performance/reference.md
  src/content/en/tools/lighthouse/audits/indexing.md
Labels: P1, cla: yes, section-tools, type-Content

#5854 Adds test to check for files with eXecutable attributes
  gulp-tasks/test.js
  gulp-tasks/tests/validatePermissions.js
Labels: cla: yes

#5852 Adds x-frame-options to headers
  app.yaml
  appengine_main.py
Labels: cla: yes

#5862 Better recommendations for inte/ar site urls
  src/content/en/fundamentals/security/encrypt-in-transit/enable-https.md
Labels: cla: yes

#5861 Wasm post
  src/content/en/updates/2018/03/emscripting-a-c-library.md
  src/content/en/updates/images/2018/03/emscripting-a-c-library/error.png
  src/content/en/updates/images/2018/03/emscripting-a-c-library/result.jpg
  src/content/en/updates/images/2018/03/emscripting-a-c-library/version.png
  src/content/en/updates/images/2018/03/emscripting-a-c-library/wasmcode.png
Labels: cla: no

#5864 Fixes a typo in one of Workbox's guides
  src/content/en/tools/workbox/guides/handle-third-party-requests.md
Labels: cla: yes

#5865 RSS & Atom Feed Widgets
  gulp-tasks/test.js
  gulp-tasks/tests/validateMarkdown.js
  src/content/en/_shared/rss-widget-fundamentals.html
  src/content/en/_shared/rss-widget-showcase.html
  src/content/en/_shared/rss-widget-shows.html
  src/content/en/_shared/rss-widget-tools.html
  src/content/en/_shared/rss-widget-updates.html
  src/content/en/updates/2018/01/crux.md
  src/content/en/updates/2018/01/devtools-without-devtools.md
  src/content/en/updates/2018/01/devtools.md
  src/content/en/updates/2018/01/lighthouse.md
  src/content/en/updates/2018/01/nic64.md
  src/content/en/updates/2018/01/paintapi.md
  src/content/en/updates/2018/02/chrome-65-deprecations.md
  src/content/en/updates/2018/02/devtools.md
  src/content/en/updates/2018/02/lighthouse.md
  src/content/en/updates/2018/03/emscripting-a-c-library.md
Labels: cla: yes

#5868 Minor tweaks to third-party JS article
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_0.jpg
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_18.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_2.jpg
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_2.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_6.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/index.md
Labels: cla: yes, type-Content

#5867 Small fixes for wasm article
  src/content/en/updates/2018/03/emscripting-a-c-library.md
Labels: cla: yes

#5853 Added a section on configuring fetch() options
  src/content/en/tools/workbox/guides/configure-workbox.md
Labels: cla: yes

#5863 New in Chrome 65
  src/content/en/updates/2018/03/nic65.md
  src/content/en/updates/images/2018/03/nic65-server-timing-devtools.png
Labels: DO NOT MERGE, cla: yes

#5874 [lighthouse] add reference for "rel=canonical" audit
  src/content/en/tools/lighthouse/_toc.yaml
  src/content/en/tools/lighthouse/audits/canonical.md
Labels: P1, cla: yes, section-tools, type-Content

#5858 Adding "Why Performance Matters" article
  src/content/en/fundamentals/performance/_redirects.yaml
  src/content/en/fundamentals/performance/_toc.yaml
  src/content/en/fundamentals/performance/why-performance-matters/images/impact-calculator-1x.png
  src/content/en/fundamentals/performance/why-performance-matters/images/impact-calculator-2x.png
  src/content/en/fundamentals/performance/why-performance-matters/images/lighthouse-1x.png
  src/content/en/fundamentals/performance/why-performance-matters/images/lighthouse-2x.png
  src/content/en/fundamentals/performance/why-performance-matters/images/speed-comparison.png
  src/content/en/fundamentals/performance/why-performance-matters/images/speed-scorecard-1x.png
  src/content/en/fundamentals/performance/why-performance-matters/images/speed-scorecard-2x.png
  src/content/en/fundamentals/performance/why-performance-matters/index.md
  src/content/en/images/contributors/jeremywagner.jpg
  src/data/_contributors.yaml
Labels: cla: yes

#5876 Updating images to remove publishers per @addyosmani
  src/content/en/fundamentals/performance/why-performance-matters/images/speed-scorecard-1x.png
  src/content/en/fundamentals/performance/why-performance-matters/images/speed-scorecard-2x.png
Labels: cla: yes

#5877 Fixed grammar issue
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/index.md
Labels: cla: yes

#5879 Add tests for content in HTML files
  gulp-tasks/test.js
  gulp-tasks/tests/helpers.js
  gulp-tasks/tests/validateContent.js
  gulp-tasks/tests/validateHtml.js
  gulp-tasks/tests/validateMarkdown.js
  gulp-tasks/wfHelper.js
  gulp-tasks/wfRegEx.js
  src/content/en/_shared/contributors/_generated.md
  src/content/en/_shared/feedback.html
  src/content/en/ilt/pwa/_slides-slides-only.html
  src/content/en/ilt/pwa/_slides.html
  src/content/en/tools/chrome-devtools/javascript/_feedback/2.html
  src/content/en/tools/chrome-devtools/javascript/_feedback/3.html
  src/content/en/tools/chrome-devtools/javascript/_feedback/4.html
  src/content/en/tools/chrome-devtools/javascript/_feedback/5.html
  src/content/en/tools/chrome-devtools/javascript/_feedback/6.html
  src/content/en/tools/chrome-devtools/javascript/_feedback/7.html
  src/content/en/tools/chrome-devtools/javascript/_feedback/8.html
  src/content/en/tools/lighthouse/audits/_feedback/_helpful.html
  src/content/en/tools/lighthouse/audits/_template.md
  src/content/en/tools/lighthouse/audits/implementation-heading.html
  src/content/es/tools/lighthouse/audits/_template.md
  src/content/es/tools/lighthouse/audits/implementation-heading.html
  src/content/id/tools/lighthouse/audits/_template.md
  src/content/id/tools/lighthouse/audits/implementation-heading.html
  src/content/ja/tools/lighthouse/audits/_template.md
  src/content/ja/tools/lighthouse/audits/implementation-heading.html
  src/content/ko/tools/lighthouse/audits/_template.md
  src/content/ko/tools/lighthouse/audits/implementation-heading.html
  src/content/pt-br/tools/lighthouse/audits/_template.md
  src/content/pt-br/tools/lighthouse/audits/implementation-heading.html
  src/content/zh-cn/_shared/udacity/ud891.html
  src/content/zh-cn/tools/lighthouse/audits/_template.md
  src/content/zh-cn/tools/lighthouse/audits/implementation-heading.html
  src/content/zh-tw/tools/lighthouse/audits/_template.md
  src/content/zh-tw/tools/lighthouse/audits/implementation-heading.html
Labels: cla: yes

#5881 Social sharing images
  gae/includes/page-head.html
  gulp-tasks/tests/projectYaml.js
  src/content/en/_project.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/images/social-webfu-16x9.png
  src/content/en/tools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/content/en/tools/workbox/images/workbox-social.png
Labels: cla: yes

#5884 New in Chrome 65: Fix "it's" [sic] grammar
  src/content/en/updates/2018/03/nic65.md
Labels: cla: yes

#5889 [devtools] add "get started with the console"
  src/content/en/tools/chrome-devtools/_toc.yaml
  src/content/en/tools/chrome-devtools/console/get-started.md
  src/content/en/tools/chrome-devtools/console/images/cause.png
  src/content/en/tools/chrome-devtools/console/images/change-fail.png
  src/content/en/tools/chrome-devtools/console/images/error-stack.png
  src/content/en/tools/chrome-devtools/console/images/iframe-context.png
  src/content/en/tools/chrome-devtools/console/images/inspect-button.png
  src/content/en/tools/chrome-devtools/console/images/open.png
  src/content/en/tools/chrome-devtools/console/images/sidebar-regex.png
  src/content/en/tools/chrome-devtools/images/panels/console.png
  src/content/en/tools/chrome-devtools/images/shared/expand.png
  src/content/en/tools/chrome-devtools/index.md
Labels: P1, cla: yes, section-tools, type-Content

#5890 Workbox v2 to v3 migration guide
  src/content/en/tools/_redirects.yaml
  src/content/en/tools/workbox/guides/_toc.yaml
  src/content/en/tools/workbox/guides/migrations/migrate-from-sw.md
  src/content/en/tools/workbox/guides/migrations/migrate-from-v2.md
  src/content/en/tools/workbox/images/guides/migrate-from-v2/bypass-for-network.png
  src/content/en/tools/workbox/images/guides/migrate-from-v2/debug-logging.png
Labels: cla: yes

#5894 Fix typo
  src/content/en/fundamentals/performance/why-performance-matters/index.md
  src/content/en/tools/lighthouse/audits/canonical.md
  src/content/en/tools/workbox/guides/migrations/migrate-from-v2.md
Labels: cla: yes

#5899 Updating speed tools PDF. Made minor typo correction.
  src/content/en/fundamentals/performance/speed-tools/index.md
  src/content/en/fundamentals/performance/speed-tools/pdf/Infographic-How_To_Think_About_Speed_Tools.pdf
  src/content/en/fundamentals/performance/speed-tools/pdf/Infographic_HowToThinkAboutSpeedTools.pdf
  src/content/en/fundamentals/performance/why-performance-matters/index.md
Labels: cla: yes

#5895 Fix the link to the v3 migration guide
  src/content/en/tools/workbox/guides/_toc.yaml
Labels: cla: yes

#5893 [Translation zh-tw] Fundamentals > Related Guides
  src/content/zh-tw/_shared/related-guides/heading.html
Labels: cla: no

#5896 Tests for common typos, product names, and improperly used words
  gulp-tasks/test.js
  gulp-tasks/tests/commonTypos.js
  gulp-tasks/tests/validateCommonTyposFile.js
  gulp-tasks/tests/validateContent.js
  src/data/common-typos.yaml
Labels: cla: yes

#5902 [devtools] update console tutorial
  src/content/en/tools/chrome-devtools/console/get-started.md
Labels: P0, cla: yes, section-tools, type-Content

#5891 Delete store-credentials.md
  src/content/en/fundamentals/security/_redirects.yaml
  src/content/en/fundamentals/security/credential-management/store-credentials.md
Labels: cla: no

#5660 [Translation it] Fundamentals > Architecture > App-shell
  src/content/it/fundamentals/architecture/app-shell.md
Labels: cla: no

#5888 [Translation zh-tw] Fundamentals > Accessibility
  src/content/zh-tw/fundamentals/accessibility/index.md
Labels: cla: yes

#5875 Workbox "Getting Started" updates for v3
  src/content/en/tools/workbox/get-started/_shared/create.md
  src/content/en/tools/workbox/get-started/_shared/end.md
  src/content/en/tools/workbox/get-started/_shared/register.md
  src/content/en/tools/workbox/get-started/gulp.md
  src/content/en/tools/workbox/get-started/npm-script.md
  src/content/en/tools/workbox/get-started/webpack.md
Labels: cla: yes

#5910 Add support for gcs_id to project.yaml
  gulp-tasks/tests/projectYaml.js
Labels: cla: yes

#5909 Add translation out of date widget to some pt-br docs
  src/content/pt-br/fundamentals/app-install-banners/index.md
  src/content/pt-br/fundamentals/payments/android-pay.md
  src/content/pt-br/fundamentals/payments/index.md
  src/content/pt-br/fundamentals/performance/rail.md
  src/content/pt-br/fundamentals/web-app-manifest/index.md
Labels: cla: yes

#5883 The new feature detection to the CM API
  src/content/en/fundamentals/security/credential-management/index.md
  src/content/en/fundamentals/security/credential-management/retrieve-credentials.md
  src/content/en/fundamentals/security/credential-management/save-forms.md
  src/content/en/updates/2016/04/credential-management-api.md
  src/content/en/updates/2017/06/credential-management-updates.md
  src/content/en/updates/2018/03/webauthn-credential-management.md
Labels: cla: yes, section-fundamentals, section-updates, type-Content

#5908 Update async clipboard api
  src/content/en/images/contributors/developit.jpg
  src/content/en/updates/2018/03/clipboardapi.md
  src/content/en/updates/images/2018/03/clipboardapi/prompt.png
  src/data/_contributors.yaml
Labels: cla: yes, type-Content

#5914 Updated translations for hacked -- request review
  src/content/ar/fundamentals/security/hacked/request_review.html
  src/content/ar/fundamentals/security/hacked/request_review.md
  src/content/de/fundamentals/security/hacked/request_review.html
  src/content/de/fundamentals/security/hacked/request_review.md
  src/content/es/fundamentals/security/hacked/request_review.html
  src/content/es/fundamentals/security/hacked/request_review.md
  src/content/fr/fundamentals/security/hacked/request_review.html
  src/content/fr/fundamentals/security/hacked/request_review.md
  src/content/hi/fundamentals/security/hacked/request_review.html
  src/content/hi/fundamentals/security/hacked/request_review.md
  src/content/id/fundamentals/security/hacked/request_review.html
  src/content/id/fundamentals/security/hacked/request_review.md
  src/content/it/fundamentals/security/hacked/request_review.html
  src/content/it/fundamentals/security/hacked/request_review.md
  src/content/ja/fundamentals/security/hacked/request_review.html
  src/content/ja/fundamentals/security/hacked/request_review.md
  src/content/ko/fundamentals/security/hacked/request_review.html
  src/content/ko/fundamentals/security/hacked/request_review.md
  src/content/nl/fundamentals/security/hacked/request_review.html
  src/content/nl/fundamentals/security/hacked/request_review.md
  src/content/pl/fundamentals/security/hacked/request_review.html
  src/content/pl/fundamentals/security/hacked/request_review.md
  src/content/pt-br/fundamentals/security/hacked/request_review.html
  src/content/pt-br/fundamentals/security/hacked/request_review.md
  src/content/ru/fundamentals/security/hacked/request_review.html
  src/content/ru/fundamentals/security/hacked/request_review.md
  src/content/th/fundamentals/security/hacked/request_review.html
  src/content/th/fundamentals/security/hacked/request_review.md
  src/content/tr/fundamentals/security/hacked/request_review.html
  src/content/tr/fundamentals/security/hacked/request_review.md
  src/content/vi/fundamentals/security/hacked/request_review.html
  src/content/vi/fundamentals/security/hacked/request_review.md
  src/content/zh-cn/fundamentals/security/hacked/request_review.html
  src/content/zh-cn/fundamentals/security/hacked/request_review.md
  src/content/zh-tw/fundamentals/security/hacked/request_review.html
  src/content/zh-tw/fundamentals/security/hacked/request_review.md
Labels: cla: yes

#5915 Add 'who' survey to WebFu
  src/content/en/_project.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
Labels: cla: yes

#5912 Http 203 ep 15
  src/content/en/shows/http203/podcast/cooties-symbols-and-shaders.md
Labels: cla: yes, section-shows

#5918 injectManifest Mode code sample typo fixed
  src/content/en/tools/workbox/modules/workbox-build.md
Labels: cla: yes

#5920 Remove [brackets] from code links
  src/content/en/updates/2018/03/clipboardapi.md
Labels: cla: yes

#5919 Tests for _book.yaml files
  gulp-tasks/test.js
  gulp-tasks/tests/bookYaml.js
  src/content/en/_upper_tabs-Fundamentals.yaml
  src/content/en/_upper_tabs-Showcase.yaml
  src/content/en/_upper_tabs-Tools.yaml
  src/content/en/_upper_tabs-Updates.yaml
  src/content/en/shows/lazyweb/2015/_toc.yaml
Labels: cla: yes

#5830 Add web/agencies/ and update app.yaml to accept json
  app.yaml
  src/content/en/_footer.yaml
  src/content/en/agencies/_index.yaml
  src/content/en/agencies/_partials/web-directory.html
  src/content/en/agencies/css/directory.css
  src/content/en/agencies/css/web-agencies-styles.css
  src/content/en/agencies/data/agencies.json
  src/content/en/agencies/images/22feet_tribal_worldwide_pvt_ltd.png
  src/content/en/agencies/images/enovate.png
  src/content/en/agencies/images/featurist_ltd.png
  src/content/en/agencies/images/gits_indonesia.png
  src/content/en/agencies/images/hero-web-agencies.png
  src/content/en/agencies/images/hex_digital_ltd.png
  src/content/en/agencies/images/jh.png
  src/content/en/agencies/images/makassar_website.png
  src/content/en/agencies/images/positive_technology.png
  src/content/en/agencies/images/proditech_solutions.png
  src/content/en/agencies/images/remarkable.net.png
  src/content/en/agencies/images/scriptpainter.png
  src/content/en/agencies/images/selesti_ltd.png
  src/content/en/agencies/images/sidekick_digital_limited.png
  src/content/en/agencies/images/uatech.png
  src/content/en/agencies/images/your_favourite_story.png
  src/content/en/agencies/js/directory.js
  src/content/en/agencies/redcube_digital_media_private_limited.png
Labels: P0, cla: yes, section-agencies

#5924 broadcastUpdate.Plugin channelName new syntax applied in Migration from v2 guide
  src/content/en/tools/workbox/guides/migrations/migrate-from-v2.md
Labels: cla: yes

#5926 broadcastUpdate.Plugin channelName new syntax applied
  src/content/en/tools/workbox/modules/workbox-broadcast-cache-update.md
Labels: cla: yes

#5928 Cleans up a few issues with the module docs for the Workbox build tools
  src/content/en/tools/workbox/_shared/config/groups/base-schema.html
  src/content/en/tools/workbox/_shared/config/groups/common-webpack.html
  src/content/en/tools/workbox/_shared/config/single/swSrc.html
  src/content/en/tools/workbox/modules/_toc.yaml
  src/content/en/tools/workbox/modules/workbox-build.md
  src/content/en/tools/workbox/modules/workbox-cli.md
Labels: cla: yes

#5923 fix: globPatthers -> globPatterns
  src/content/en/tools/workbox/guides/generate-service-worker/workbox-build.md
  src/content/en/tools/workbox/guides/precache-files/workbox-build.md
Labels: cla: yes

#5911 Includes some info on lesser-used workbox-build methods
  src/content/en/tools/workbox/guides/migrations/migrate-from-v2.md
Labels: cla: yes

#5927 Update agencies json to latest data
  src/content/en/agencies/data/agencies.json
Labels: P0, cla: yes, section-agencies

#5925 Update AudioWorklet article for M66 launch
  src/content/en/updates/2017/12/audio-worklet.md
Labels: cla: yes

#5929 Add enforce logo
  src/content/en/agencies/images/enforce.png
Labels: P0, cla: yes, section-agencies

#5931 Updated Google Consumer Survey ID
  gae/includes/survey.html
  src/content/en/_project.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
Labels: cla: yes

#5932 Update section title for "Mobile Web Video Playback"
  src/content/en/fundamentals/media/_toc.yaml
Labels: cla: yes

#5933 Typo fix in WB docs
  src/content/en/tools/workbox/guides/precache-files/index.md
Labels: cla: yes

#5937 Add #SmooshGate FAQ
  src/content/en/updates/2018/03/smooshgate.md
  src/data/_contributors.yaml
Labels: cla: yes

#5939 Fix typo
  src/content/en/updates/2018/03/smooshgate.md
Labels: cla: yes

#5892 Remove /web/events
  src/content/en/_footer.yaml
  src/content/en/_translation.yaml
  src/content/en/events/_book.yaml
  src/content/en/events/_index.yaml
  src/content/en/events/embeds/event-map.css
  src/content/en/events/embeds/event-map.js
  src/content/en/events/images/polymer-marker.png
  src/content/en/events/images/polytechnic-item.jpg
  src/content/en/events/images/pwa-roadshow-item.jpg
  src/content/en/events/images/pwaroadshow-marker.png
  src/content/en/events/images/sponsored-pwaroadshow-marker.png
  src/content/en/events/polytechnic/_index.yaml
  src/content/en/events/pwa-agency-training/_index.yaml
  src/content/en/events/pwa-agency-training/training-landing.css
  src/content/en/events/pwaroadshow/_index.yaml
Labels: cla: yes

#5944 Fix typo
  src/content/en/updates/2018/03/smooshgate.md
Labels: cla: yes

#5945 Reword TC39 consensus
  src/content/en/updates/2018/03/smooshgate.md
Labels: cla: yes

#5943 Fix 404s due to Workbox codelabs migration
  src/content/en/tools/workbox/guides/codelabs/_shared/end.md
  src/content/en/tools/workbox/guides/codelabs/_shared/register.md
  src/content/en/tools/workbox/guides/codelabs/_shared/try-complete.md
  src/content/en/tools/workbox/guides/codelabs/_shared/try-initial.md
  src/content/en/tools/workbox/guides/codelabs/webpack.md
Labels: cla: yes

#5941 More Workbox docs fixes
  src/content/en/tools/workbox/_shared/config/single/globPatterns.html
  src/content/en/tools/workbox/guides/_toc.yaml
  src/content/en/tools/workbox/guides/generate-service-worker/webpack.md
  src/content/en/tools/workbox/guides/migrations/migrate-from-v2.md
  src/content/en/tools/workbox/modules/workbox-webpack-plugin.md
Labels: cla: yes

#5946 Rephrase
  src/content/en/updates/2018/03/smooshgate.md
Labels: cla: yes

#5942 custom-elements served from gstatic
  src/content/en/fundamentals/accessibility/focus/using-tabindex.md
  src/content/es/fundamentals/accessibility/focus/using-tabindex.md
  src/content/id/fundamentals/accessibility/focus/using-tabindex.md
  src/content/ja/fundamentals/accessibility/focus/using-tabindex.md
  src/content/ko/fundamentals/accessibility/focus/using-tabindex.md
  src/content/pt-br/fundamentals/accessibility/focus/using-tabindex.md
  src/content/zh-cn/fundamentals/accessibility/focus/using-tabindex.md
  src/content/zh-tw/fundamentals/accessibility/focus/using-tabindex.md
Labels: cla: yes

#5950 Typo fix in workbox-strategies module docs
  src/content/en/tools/workbox/modules/workbox-strategies.md
Labels: cla: yes

#5951 Updated Voot logo
  src/content/en/showcase/2017/images/voot/voot-lite.png
  src/content/en/showcase/2017/images/voot/voot.png
  src/content/en/showcase/2017/voot.md
Labels: cla: yes

#5949 Remove Origin Trial from Media Capabilities
  src/content/en/updates/2017/12/chrome-63-64-media-updates.md
Labels: cla: yes

#5948 s/vp9/vp09.00.10.08/g
  src/content/en/fundamentals/media/eme.md
  src/content/en/fundamentals/media/fast-playback-with-video-preload.md
  src/content/en/fundamentals/media/mse/basics.md
  src/content/en/updates/2017/09/chrome-62-media-updates.md
  src/content/en/updates/2017/12/chrome-63-64-media-updates.md
  src/content/it/fundamentals/media/fast-playback-with-video-preload.md
Labels: cla: yes

#5952 [Sensors For The Web] add decription for screen coordinates
  src/content/en/updates/2017/09/sensors-for-the-web.md
  src/content/en/updates/images/2017/09/sensors/device_coordinate_system.png
  src/content/en/updates/images/2017/09/sensors/screen_coordinate_system.png
Labels: cla: yes

#5953 Update footer.yaml
  src/content/en/_footer.yaml
  src/content/zh-tw/_footer.yaml
Labels: cla: yes

#5954 Revert "Remove Origin Trial from Media Capabilities"
  src/content/en/updates/2017/12/chrome-63-64-media-updates.md
Labels: cla: yes

#5963 [devtools] fix console tutorial demos
  src/content/en/tools/chrome-devtools/console/get-started.md
Labels: cla: yes, section-tools

#5798 Webpack guide updates for webpack 4
  src/content/en/fundamentals/performance/webpack/decrease-frontend-size.md
  src/content/en/fundamentals/performance/webpack/monitor-and-analyze.md
  src/content/en/fundamentals/performance/webpack/use-long-term-caching.md
Labels: DO NOT MERGE, cla: yes, section-fundamentals, type-Content

#5957 CSS Type Object Model update
  src/content/en/updates/2018/03/cssom.md
Labels: cla: yes, section-updates

#5976 [lighthouse] add plugins reference
  src/content/en/tools/lighthouse/_toc.yaml
  src/content/en/tools/lighthouse/audits/plugins.md
Labels: P1, cla: yes, section-tools, type-Content

#5985 Deprecate old offline analytics post
  src/content/en/updates/2016/07/offline-google-analytics.md
Labels: cla: yes

#5983 Service workers images
  src/content/en/fundamentals/primers/service-workers/index.md
  src/content/ja/fundamentals/primers/service-workers/index.md
  src/content/ja/fundamentals/primers/service-workers/registration.md
Labels: cla: yes

#5981 replace invite link to slack
  src/content/en/feedback/_index.yaml
  src/content/en/resources/translations.md
  src/content/en/tools/workbox/community.md
  src/content/en/updates/2016/11/get-ready-for-cds.md
  src/content/ja/resources/translations.md
  src/content/zh-cn/resources/translations.md
  src/content/zh-tw/resources/translations.md
Labels: cla: yes, type-Content

#5978 Fixing code typo found by Evan
  src/content/en/fundamentals/media/capturing-images/index.md
Labels: cla: yes

#5977 Rename google.com/pay to Google Pay from Pay with Google
  src/content/en/fundamentals/payments/deep-dive-into-payment-request.md
  src/content/en/fundamentals/payments/index.md
Labels: cla: yes

#5971 [lighthouse] add hreflang reference
  src/content/en/tools/lighthouse/_toc.yaml
  src/content/en/tools/lighthouse/audits/hreflang.md
Labels: P1, cla: yes, section-tools, type-Content

#5969 Update basics.md
  src/content/en/fundamentals/media/mse/basics.md
Labels: cla: yes

#5965 Fix “Atom” capitalization
  src/content/en/_shared/rss-widget-updates.html
Labels: cla: yes

#5964 Deprecations and removals in Chrome 66
  src/content/en/updates/2018/03/chrome-66-deprecations.md
Labels: cla: yes

#5961 Add note for WebAudio
  src/content/en/updates/2017/09/autoplay-policy-changes.md
Labels: cla: no

#5960 Fix HDR demo
  src/content/en/updates/2017/12/chrome-63-64-media-updates.md
Labels: cla: yes

#5984 Update es2015-proxies.md
  src/content/en/updates/2016/02/es2015-proxies.md
Labels: cla: no

#5973 Migrated lazy loading guidance doc from Google Docs to markdown.
  src/content/en/fundamentals/performance/_toc.yaml
  src/content/en/fundamentals/performance/lazy-loading-guidance/images-and-video/images/lazy-loading-example-1x.jpg
  src/content/en/fundamentals/performance/lazy-loading-guidance/images-and-video/images/lazy-loading-example-2x.jpg
  src/content/en/fundamentals/performance/lazy-loading-guidance/images-and-video/images/offscreen-audit-1x.png
  src/content/en/fundamentals/performance/lazy-loading-guidance/images-and-video/images/offscreen-audit-2x.png
  src/content/en/fundamentals/performance/lazy-loading-guidance/images-and-video/index.md
Labels: cla: yes

#5988 [lighthouse] add reference doc for preload audit
  src/content/en/tools/lighthouse/audits/images/after.png
  src/content/en/tools/lighthouse/audits/images/before.png
  src/content/en/tools/lighthouse/audits/preload.md
Labels: P1, cla: yes, section-tools, type-Content

#5990 [lighthouse] add cache policy reference
  src/content/en/tools/lighthouse/_toc.yaml
  src/content/en/tools/lighthouse/audits/_template.md
  src/content/en/tools/lighthouse/audits/cache-policy.md
  src/content/en/tools/lighthouse/audits/images/cache-control-header.png
  src/content/en/tools/lighthouse/audits/images/size.png
Labels: P1, cla: yes, section-tools, type-Content

#5989 Update WebUSB demo code to latest Arduino library
  src/content/en/updates/2016/03/access-usb-devices-on-the-web.md
Labels: cla: yes

#5986 Docs for some new workbox-webpack-plugin options
  src/content/en/tools/workbox/_shared/config/groups/common-webpack.html
  src/content/en/tools/workbox/_shared/config/webpack-single/importsDirectory.html
  src/content/en/tools/workbox/_shared/config/webpack-single/precacheManifestFilename.html
Labels: cla: yes

#5991 [lighthouse] add css minification reference
  src/content/en/tools/lighthouse/_toc.yaml
  src/content/en/tools/lighthouse/audits/minify-css.md
Labels: P1, cla: yes, section-tools, type-Content
