Repository google/WebFundamentals, pull requests merged in 2018-02, with the labels that each got.

#5773 Fix typo
  src/content/en/updates/2016/03/web-enabled-internet-of-things.md
Labels: cla: yes

#5662 Deprecations and Removals in Chrome 65
  src/content/en/updates/2018/02/chrome-65-deprecations.md
Labels: cla: yes

#5774 Adding new links to paths for review after hack / malware / phishing detection
  src/content/en/fundamentals/security/hacked/request_review.md
Labels: cla: no

#5775 request_review Tweaks
  src/content/ar/fundamentals/security/hacked/request_review.html
  src/content/de/fundamentals/security/hacked/request_review.html
  src/content/en/fundamentals/security/hacked/request_review.md
  src/content/es/fundamentals/security/hacked/request_review.html
  src/content/fr/fundamentals/security/hacked/request_review.html
  src/content/hi/fundamentals/security/hacked/request_review.html
  src/content/id/fundamentals/security/hacked/request_review.html
  src/content/it/fundamentals/security/hacked/request_review.html
  src/content/ja/fundamentals/security/hacked/request_review.html
  src/content/ko/fundamentals/security/hacked/request_review.html
  src/content/nl/fundamentals/security/hacked/request_review.html
  src/content/pl/fundamentals/security/hacked/request_review.html
  src/content/pt-br/fundamentals/security/hacked/request_review.html
  src/content/ru/fundamentals/security/hacked/request_review.html
  src/content/th/fundamentals/security/hacked/request_review.html
  src/content/tr/fundamentals/security/hacked/request_review.html
  src/content/vi/fundamentals/security/hacked/request_review.html
  src/content/zh-cn/fundamentals/security/hacked/request_review.html
  src/content/zh-tw/fundamentals/security/hacked/request_review.html
Labels: cla: yes

#5771 update(karma-mocha-headless): sudo: required per new instructions
  src/content/en/updates/2017/06/headless-karma-mocha-chai.md
Labels: cla: no, section-updates

#5778 [lighthouse] add 2.8 update
  src/content/en/updates/2018/02/lighthouse.md
  src/content/en/updates/images/2018/02/LOAD.gif
  src/content/en/updates/images/2018/02/canonical.png
  src/content/en/updates/images/2018/02/manual.png
  src/content/en/updates/images/2018/02/minify.png
  src/content/en/updates/images/2018/02/plugins.png
Labels: P1, cla: yes, section-updates, type-Content

#5760 [Autoplay policy changes] Update ETA & iframe delegation section, add WebAudio
  src/content/en/updates/2017/09/autoplay-policy-changes.md
Labels: cla: yes

#5776 Updates for the Webpack performance guide
  src/content/en/fundamentals/performance/webpack/decrease-frontend-size.md
  src/content/en/fundamentals/performance/webpack/use-long-term-caching.md
Labels: cla: yes

#5779 Update illustration reference to bundle-buddy
  src/content/en/fundamentals/performance/webpack/index.md
Labels: cla: yes, type-Content

#5782 Remove errant character that breaks RSS feed output
  src/content/en/updates/2018/01/paintapi.md
Labels: cla: yes

#5785 Fix incorrect title on Japanese Keyword Hack doc
  src/content/en/fundamentals/security/hacked/fixing_the_japanese_keyword_hack.md
Labels: cla: yes

#5781 Add section about testing installation banner on real device
  src/content/en/fundamentals/web-app-manifest/index.md
Labels: cla: yes

#5418 chore(link): update link issue for Custom Elements extends
  src/content/en/fundamentals/web-components/customelements.md
  src/content/es/fundamentals/web-components/customelements.md
  src/content/id/fundamentals/web-components/customelements.md
  src/content/ja/fundamentals/web-components/customelements.md
  src/content/ko/fundamentals/web-components/customelements.md
  src/content/pt-br/fundamentals/web-components/customelements.md
  src/content/zh-cn/fundamentals/web-components/customelements.md
Labels: cla: yes

#5784 Misc 404 fixes
  src/content/en/fundamentals/security/encrypt-in-transit/enable-https.md
  src/content/en/fundamentals/security/prevent-mixed-content/what-is-mixed-content.md
  src/content/en/updates/2018/01/nic64.md
  src/content/es/fundamentals/security/encrypt-in-transit/enable-https.md
  src/content/es/fundamentals/security/prevent-mixed-content/what-is-mixed-content.md
  src/content/id/fundamentals/security/encrypt-in-transit/enable-https.md
  src/content/id/fundamentals/security/prevent-mixed-content/what-is-mixed-content.md
  src/content/ja/fundamentals/security/encrypt-in-transit/enable-https.md
  src/content/ja/fundamentals/security/prevent-mixed-content/what-is-mixed-content.md
  src/content/ko/fundamentals/security/encrypt-in-transit/enable-https.md
  src/content/ko/fundamentals/security/prevent-mixed-content/what-is-mixed-content.md
  src/content/pt-br/fundamentals/security/encrypt-in-transit/enable-https.md
  src/content/pt-br/fundamentals/security/prevent-mixed-content/what-is-mixed-content.md
  src/content/ru/fundamentals/security/encrypt-in-transit/enable-https.md
  src/content/zh-cn/fundamentals/security/encrypt-in-transit/enable-https.md
  src/content/zh-cn/fundamentals/security/prevent-mixed-content/what-is-mixed-content.md
  src/content/zh-tw/fundamentals/security/encrypt-in-transit/enable-https.md
Labels: cla: yes

#5787 Changing the example for bg sync
  src/content/en/tools/workbox/modules/workbox-background-sync.md
Labels: cla: yes

#5710 [Translate zh-tw] Feedback > File a Bug
  src/content/zh-tw/feedback/file-a-bug.md
Labels: cla: no

#5791 Remove caveat about importWorkboxFrom: 'local' and InjectManifest
  src/content/en/tools/workbox/_shared/config/single/importWorkboxFrom.html
Labels: cla: yes

#5790 Update workbox-cache-expiration.md
  src/content/en/tools/workbox/modules/workbox-cache-expiration.md
Labels: cla: yes

#5792 [lighthouse] add "JS bootup" reference
  src/content/en/tools/lighthouse/_toc.yaml
  src/content/en/tools/lighthouse/audits/bootup.md
Labels: P1, cla: yes, section-tools, type-Content

#5788 Refactored tests in separate files
  gulp-tasks/test.js
  gulp-tasks/tests/commonTagsJson.js
  gulp-tasks/tests/contributorsYaml.js
  gulp-tasks/tests/glossaryYaml.js
  gulp-tasks/tests/helpers.js
  gulp-tasks/tests/lintJavaScript.js
  gulp-tasks/tests/projectYaml.js
  gulp-tasks/tests/redirectsYaml.js
  gulp-tasks/tests/validateFilename.js
  gulp-tasks/tests/validateGeneric.js
  gulp-tasks/tests/validateHtml.js
  gulp-tasks/tests/validateJavaScript.js
  gulp-tasks/tests/validateJson.js
  gulp-tasks/tests/validateMarkdown.js
  gulp-tasks/tests/validateMedia.js
  gulp-tasks/tests/validateYaml.js
  src/tests/include-code.md
  src/tests/include-missing.md
  src/tests/md-include-good.md
  src/tests/md-include-missing.md
Labels: cla: yes

#5796 [lighthouse] add "meta description" reference
  src/content/en/tools/lighthouse/_toc.yaml
  src/content/en/tools/lighthouse/audits/description.md
Labels: P1, cla: yes, section-tools, type-Content

#5795 Updates to ILT, Code labs & BlinkComponents
  src/content/en/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/en/ilt/pwa/lab-integrating-analytics.md
  src/content/en/ilt/pwa/lab-integrating-web-push.md
  src/content/en/ilt/pwa/lab-migrating-to-workbox-from-sw-precache-and-sw-toolbox.md
  src/content/en/ilt/pwa/lab-workbox.md
  src/content/en/ilt/pwa/setting-up-the-labs.md
  src/data/blinkComponents.json
  src/data/codelabs/your-first-pwapp/codelab.json
  src/data/ilt-pwa/lab-integrating-analytics/codelab.json
  src/data/ilt-pwa/lab-integrating-web-push/codelab.json
  src/data/ilt-pwa/lab-migrating-to-workbox-from-sw-precache-and-sw-toolbox/codelab.json
  src/data/ilt-pwa/lab-workbox/codelab.json
  src/data/ilt-pwa/setting-up-the-labs/codelab.json
  tools/update-blink_components.sh
Labels: cla: yes

#5797 Fixed some typos in Image Optimization
  src/content/en/fundamentals/performance/optimizing-content-efficiency/image-optimization.md
Labels: P2, cla: yes, section-fundamentals, type-Content

#5804 Update Angular brand
  src/content/en/tools/_index.yaml
Labels: cla: yes

#5181 New Get Started section for Performance: Index
  src/content/en/fundamentals/instant-and-offline/get-started/index.md
Labels: cla: yes

#5182 New Getting Started section for Performance: Measuring Performance doc and all images
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_200.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_201.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_202.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_203.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_205.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_300.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_301.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_302.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_303.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_400.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_401.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_402.jpg
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_403.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_404.jpg
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_405.jpg
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_406.jpg
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_407.jpg
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_408.jpg
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_409.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_410.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_411.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_412.jpg
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_413.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_414.jpg
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_500.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_700.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_701.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_702.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_703.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_704.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_705.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_706.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_707.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_708.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_709.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_710.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_711.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_712.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_713.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_714.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_715.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_716.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_717.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_718.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_719.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_720.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_721.png
  src/content/en/fundamentals/instant-and-offline/get-started/images/image_722.png
  src/content/en/fundamentals/instant-and-offline/get-started/measuringperf-2.md
Labels: cla: yes

#5186 New Get Started section for Performance: Graphical Content doc
  src/content/en/fundamentals/instant-and-offline/get-started/graphicalcontent-4.md
Labels: cla: yes

#5187 New Get Started section for Performance: HTTP Requests doc
  src/content/en/fundamentals/instant-and-offline/get-started/httprequests-5.md
Labels: cla: yes

#5188 New Get Started section for Performance: HTTP Caching doc
  src/content/en/fundamentals/instant-and-offline/get-started/httpcaching-6.md
Labels: cla: yes

#5219 new Getting Started section docs: re-adding textcontent-3.md only
  src/content/en/fundamentals/instant-and-offline/get-started/textcontent-3.md
Labels: cla: yes

#5189 New Get Started Section for Performance: Wrap up and demo doc
  src/content/en/fundamentals/instant-and-offline/get-started/wrapup-7.md
Labels: cla: yes

#5805 update links to Google Pay API Payment Request tutorial
  src/content/en/fundamentals/payments/_toc.yaml
  src/content/en/fundamentals/payments/android-pay.md
  src/content/en/fundamentals/payments/deep-dive-into-payment-request.md
  src/content/en/fundamentals/payments/index.md
Labels: cla: yes

#5808 Different spell proposal
  src/content/en/fundamentals/instant-and-offline/get-started/httprequests-5.md
Labels: cla: yes

#5810 [lightouse] update template & add "font sizes" reference
  src/content/en/tools/lighthouse/_toc.yaml
  src/content/en/tools/lighthouse/audits/_template.md
  src/content/en/tools/lighthouse/audits/font-sizes.md
Labels: P1, cla: yes, section-tools, type-Content

#5806 Small change for ShortPixel mention
  src/content/en/fundamentals/performance/optimizing-content-efficiency/automating-image-optimization/index.md
Labels: cla: yes

#5807 Remove geofencing mention
  src/content/en/fundamentals/primers/service-workers/index.md
Labels: cla: yes

#5813 [ligthouse] add "descriptive link text" reference
  src/content/en/tools/lighthouse/_toc.yaml
  src/content/en/tools/lighthouse/audits/descriptive-link-text.md
Labels: P1, cla: yes, section-tools, type-Content

#5816 Asda casestudy
  src/content/en/showcase/2018/asda-george.md
  src/content/en/showcase/2018/images/asda-george/bottom_listing.png
  src/content/en/showcase/2018/images/asda-george/bottom_transition.png
  src/content/en/showcase/2018/images/asda-george/logo_.jpg
  src/content/en/showcase/_book.yaml
Labels: cla: yes

#5814 Moved performance get started to loading and added TOC
  src/content/en/fundamentals/performance/_toc.yaml
  src/content/en/fundamentals/performance/get-started/graphicalcontent-4.md
  src/content/en/fundamentals/performance/get-started/httpcaching-6.md
  src/content/en/fundamentals/performance/get-started/httprequests-5.md
  src/content/en/fundamentals/performance/get-started/images/image_200.png
  src/content/en/fundamentals/performance/get-started/images/image_201.png
  src/content/en/fundamentals/performance/get-started/images/image_202.png
  src/content/en/fundamentals/performance/get-started/images/image_203.png
  src/content/en/fundamentals/performance/get-started/images/image_205.png
  src/content/en/fundamentals/performance/get-started/images/image_300.png
  src/content/en/fundamentals/performance/get-started/images/image_301.png
  src/content/en/fundamentals/performance/get-started/images/image_302.png
  src/content/en/fundamentals/performance/get-started/images/image_303.png
  src/content/en/fundamentals/performance/get-started/images/image_400.png
  src/content/en/fundamentals/performance/get-started/images/image_401.png
  src/content/en/fundamentals/performance/get-started/images/image_402.jpg
  src/content/en/fundamentals/performance/get-started/images/image_403.png
  src/content/en/fundamentals/performance/get-started/images/image_404.jpg
  src/content/en/fundamentals/performance/get-started/images/image_405.jpg
  src/content/en/fundamentals/performance/get-started/images/image_406.jpg
  src/content/en/fundamentals/performance/get-started/images/image_407.jpg
  src/content/en/fundamentals/performance/get-started/images/image_408.jpg
  src/content/en/fundamentals/performance/get-started/images/image_409.png
  src/content/en/fundamentals/performance/get-started/images/image_410.png
  src/content/en/fundamentals/performance/get-started/images/image_411.png
  src/content/en/fundamentals/performance/get-started/images/image_412.jpg
  src/content/en/fundamentals/performance/get-started/images/image_413.png
  src/content/en/fundamentals/performance/get-started/images/image_414.jpg
  src/content/en/fundamentals/performance/get-started/images/image_500.png
  src/content/en/fundamentals/performance/get-started/images/image_700.png
  src/content/en/fundamentals/performance/get-started/images/image_701.png
  src/content/en/fundamentals/performance/get-started/images/image_702.png
  src/content/en/fundamentals/performance/get-started/images/image_703.png
  src/content/en/fundamentals/performance/get-started/images/image_704.png
  src/content/en/fundamentals/performance/get-started/images/image_705.png
  src/content/en/fundamentals/performance/get-started/images/image_706.png
  src/content/en/fundamentals/performance/get-started/images/image_707.png
  src/content/en/fundamentals/performance/get-started/images/image_708.png
  src/content/en/fundamentals/performance/get-started/images/image_709.png
  src/content/en/fundamentals/performance/get-started/images/image_710.png
  src/content/en/fundamentals/performance/get-started/images/image_711.png
  src/content/en/fundamentals/performance/get-started/images/image_712.png
  src/content/en/fundamentals/performance/get-started/images/image_713.png
  src/content/en/fundamentals/performance/get-started/images/image_714.png
  src/content/en/fundamentals/performance/get-started/images/image_715.png
  src/content/en/fundamentals/performance/get-started/images/image_716.png
  src/content/en/fundamentals/performance/get-started/images/image_717.png
  src/content/en/fundamentals/performance/get-started/images/image_718.png
  src/content/en/fundamentals/performance/get-started/images/image_719.png
  src/content/en/fundamentals/performance/get-started/images/image_720.png
  src/content/en/fundamentals/performance/get-started/images/image_721.png
  src/content/en/fundamentals/performance/get-started/images/image_722.png
  src/content/en/fundamentals/performance/get-started/index.md
  src/content/en/fundamentals/performance/get-started/measuringperf-2.md
  src/content/en/fundamentals/performance/get-started/textcontent-3.md
  src/content/en/fundamentals/performance/get-started/wrapup-7.md
Labels: cla: yes

#5817 Variable fonts article
  src/content/en/fundamentals/design-and-ux/_toc.yaml
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/images/Amstelvar-Alpha-example.png
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/images/Amstelvar-Ital-axis.png
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/images/amstel-grade-e.gif
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/images/axis-praxis.gif
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/images/gingham-weight-e.gif
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/images/grass-mandy.png
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/images/robot-specimen.png
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/images/roboto-family.png
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/index.md
Labels: cla: yes

#5818 [devtools] add get started section to homepage & polish the ToC
  src/content/en/tools/chrome-devtools/_toc.yaml
  src/content/en/tools/chrome-devtools/index.md
Labels: P1, cla: yes, section-tools, type-Content

#5820 [Webpack Performance Guide] Add notes about webpack 4
  src/content/en/fundamentals/performance/webpack/decrease-frontend-size.md
  src/content/en/fundamentals/performance/webpack/use-long-term-caching.md
Labels: cla: yes

#5819 headless article: add extra flag for repl mode.
  src/content/en/updates/2017/04/headless-chrome.md
Labels: cla: yes, type-Content

#5822 Fix typo
  src/content/en/fundamentals/architecture/app-shell.md
Labels: cla: no

#5825 [devtools] add WNDT66
  src/content/en/updates/2018/02/devtools.md
  src/content/en/updates/images/2018/02/blackbox-framework.png
  src/content/en/updates/images/2018/02/blackbox.png
  src/content/en/updates/images/2018/02/blackboxed-results.png
  src/content/en/updates/images/2018/02/click-breakpoint.png
  src/content/en/updates/images/2018/02/overrides.png
  src/content/en/updates/images/2018/02/preview-prettyprint.png
  src/content/en/updates/images/2018/02/preview.png
  src/content/en/updates/images/2018/02/resolved.png
  src/content/en/updates/images/2018/02/response-prettyprint.png
  src/content/en/updates/images/2018/02/wrapper.png
Labels: P1, cla: yes, section-updates, type-Content

#5799 [Translation it] Fundamentals > Design & User Experience > Accessibility > Accessible Styles
  src/content/it/fundamentals/accessibility/accessible-styles.md
Labels: cla: no

#5828 fixing link
  src/content/en/shows/designer-vs-developer/index.md
Labels: cla: yes

#5829 Fix typo
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/index.md
  src/content/en/showcase/2018/asda-george.md
Labels: cla: yes

#5823 typography/variable-fonts Minor corrections
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/index.md
Labels: cla: yes

#5832 Add SRI hashes to cdn hosted content
  src/content/en/fundamentals/accessibility/focus/using-tabindex.md
  src/content/en/fundamentals/primers/service-workers/lifecycle.md
Labels: cla: yes

#5833 wndt 66: fix published date.
  src/content/en/updates/2018/02/devtools.md
Labels: cla: yes

#5839 Weekly 0228
  src/content/en/fundamentals/codelabs/debugging-service-workers/img/132f9c0cd308546f.png
  src/content/en/fundamentals/codelabs/debugging-service-workers/img/265d8ff469201930.png
  src/content/en/fundamentals/codelabs/debugging-service-workers/img/306ae05a5ccff37f.png
  src/content/en/fundamentals/codelabs/debugging-service-workers/img/5f7ecd7d7f9c043a.png
  src/content/en/fundamentals/codelabs/debugging-service-workers/img/830dc8e341890d23.png
  src/content/en/fundamentals/codelabs/debugging-service-workers/img/8c59c74286a01362.png
  src/content/en/fundamentals/codelabs/debugging-service-workers/img/9377be2a4e29c16b.png
  src/content/en/fundamentals/codelabs/debugging-service-workers/img/ac3b3feec0554231.png
  src/content/en/fundamentals/codelabs/debugging-service-workers/img/ad313b2b4e3105be.png
  src/content/en/fundamentals/codelabs/debugging-service-workers/img/d2458f80800f4c2.png
  src/content/en/fundamentals/codelabs/debugging-service-workers/img/d6c0cc08665a2429.png
  src/content/en/fundamentals/codelabs/debugging-service-workers/index.md
  src/content/en/fundamentals/codelabs/offline/img/3ec8737c20a475df.png
  src/content/en/fundamentals/codelabs/offline/index.md
  src/content/en/fundamentals/codelabs/web-perf/img/17aaa204bd2ff067.png
  src/content/en/fundamentals/codelabs/web-perf/img/223fcf5a77de8ae3.png
  src/content/en/fundamentals/codelabs/web-perf/img/3d74ba7552fa6aaf.png
  src/content/en/fundamentals/codelabs/web-perf/img/43a288936220943e.png
  src/content/en/fundamentals/codelabs/web-perf/img/5c2a91c2a63b2c10.png
  src/content/en/fundamentals/codelabs/web-perf/index.md
  src/content/en/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/en/ilt/pwa/img/29d876d61333f92c.png
  src/content/en/ilt/pwa/img/574da956ee6c4880.png
  src/content/en/ilt/pwa/img/86995b70a765e9d0.png
  src/content/en/ilt/pwa/img/b02d7ec8d4d8ee51.png
  src/content/en/ilt/pwa/img/bf5139cbb5ea299.png
  src/content/en/ilt/pwa/img/f214108c1662394d.png
  src/content/en/ilt/pwa/img/f5cf17f8445690b1.png
  src/content/en/ilt/pwa/img/fe89035a861760b5.png
  src/content/en/ilt/pwa/lab-auditing-with-lighthouse.md
  src/content/en/ilt/pwa/lab-integrating-web-push.md
  src/content/en/ilt/pwa/lab-workbox.md
  src/content/en/ilt/pwa/lighthouse-pwa-analysis-tool.md
  src/content/en/ilt/pwa/offline-quickstart.md
  src/content/en/ilt/pwa/setting-up-the-labs.md
  src/content/en/ilt/pwa/tools-for-pwa-developers.md
  src/data/blinkComponents.json
  src/data/codelabs/your-first-pwapp/codelab.json
  src/data/ilt-pwa/lab-auditing-with-lighthouse/codelab.json
  src/data/ilt-pwa/lab-integrating-analytics/codelab.json
  src/data/ilt-pwa/lab-integrating-web-push/codelab.json
  src/data/ilt-pwa/lab-workbox/codelab.json
  src/data/ilt-pwa/offline-quickstart/codelab.json
Labels: cla: yes

#5837 Loading Third-party JavaScript
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_0.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_1.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_10.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_11.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_12.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_13.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_14.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_15.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_16.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_17.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_2.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_3.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_4.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_5.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_6.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_7.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_8.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/images/image_9.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/index.md
  src/content/en/images/contributors/addyosmani.jpg
  src/content/en/images/contributors/arthurevans.jpg
  src/data/_contributors.yaml
Labels: cla: yes, section-fundamentals, type-Content

#5835 Adds better redirects to payment articles
  src/content/en/fundamentals/_redirects.yaml
Labels: cla: yes

#5834 Update my author info so it's correctly linked on my contributors page.
  src/content/en/showcase/2016/service-worker-perf.md
Labels: cla: yes

#5826 Added "How to Think About Speed Tools" article.
  src/content/en/fundamentals/performance/_toc.yaml
  src/content/en/fundamentals/performance/speed-tools/images/icon-audit.svg
  src/content/en/fundamentals/performance/speed-tools/images/icon-business.svg
  src/content/en/fundamentals/performance/speed-tools/images/icon-debug.svg
  src/content/en/fundamentals/performance/speed-tools/images/icon-dev.svg
  src/content/en/fundamentals/performance/speed-tools/images/line-graph.svg
  src/content/en/fundamentals/performance/speed-tools/images/network-icons.svg
  src/content/en/fundamentals/performance/speed-tools/images/on-the-street.svg
  src/content/en/fundamentals/performance/speed-tools/images/tech.svg
  src/content/en/fundamentals/performance/speed-tools/images/tool-devtools.svg
  src/content/en/fundamentals/performance/speed-tools/images/tool-impact-calculator.svg
  src/content/en/fundamentals/performance/speed-tools/images/tool-lighthouse.svg
  src/content/en/fundamentals/performance/speed-tools/images/tool-psi.svg
  src/content/en/fundamentals/performance/speed-tools/images/tool-speed-scorecard.svg
  src/content/en/fundamentals/performance/speed-tools/images/tool-testmysite.svg
  src/content/en/fundamentals/performance/speed-tools/images/tool-webpagetest.svg
  src/content/en/fundamentals/performance/speed-tools/images/users.svg
  src/content/en/fundamentals/performance/speed-tools/index.md
  src/content/en/fundamentals/performance/speed-tools/pdf/Infographic_HowToThinkAboutSpeedTools.pdf
Labels: cla: yes
