Repository google/WebFundamentals, pull requests merged in 2019-10, with the labels that each got.

#8188 Fix relative URLs in YAML paths
  src/content/en/tools/workbox/modules/_index.yaml
Labels: cla: yes

#8191 Payment: add skip-the-sheet section
  src/content/en/fundamentals/payments/payment-apps-developer-guide/web-payment-apps.md
Labels: cla: yes, content-updated

#8202 docs: remove period in README.md
  README.md
Labels: cla: yes

#8199 Fixes to the NoState Prefetch article
  src/content/en/updates/2018/07/nostate-prefetch.md
Labels: cla: yes

#8198 Update performance content
  src/content/en/fundamentals/performance/navigation-and-resource-timing/index.md
Labels: cla: yes

#8197 Fixes to the CSS Scroll Snap article
  src/content/en/updates/2018/07/css-scroll-snap.md
Labels: cla: yes

#8189 Fixes to the getInstalledRelatedApps article
  src/content/en/updates/2018/12/get-installed-related-apps.md
Labels: cla: yes

#8186 Fixes to the Feature Policy article
  src/content/en/updates/2018/06/feature-policy.md
Labels: cla: yes

#8184 Fixes to the Unblocking Clipboard Access article
  src/content/en/updates/2018/03/clipboardapi.md
Labels: cla: yes

#8182 Fixes to the ReportingObserver article
  src/content/en/updates/2018/07/reportingobserver.md
Labels: cla: yes

#8180 fix(chrome-devtools/coverage): typo "instrumeting"
  src/content/en/tools/chrome-devtools/coverage/index.md
Labels: cla: yes

#8212 Indicate browser support for constructable stylesheets
  src/content/en/updates/2019/02/constructable-stylesheets.md
Labels: cla: yes

#8217 Migration review of getInstalledRelatedApps().
  src/content/en/updates/2018/12/get-installed-related-apps.md
Labels: P0, cla: yes, content-updated, migrate-content

#8216 This removal didn't actually go out in 78.
  src/content/en/updates/2019/09/chrome-78-deps-rems.md
Labels: cla: yes, content-updated

#8211 Improve "see all" blurb.
  src/content/en/updates/_shared/see-all-dep-rem.html
Labels: cla: yes, content-updated

#8208 Fix to Fundamentals index page
  src/content/en/fundamentals/_index.yaml
Labels: cla: yes

#8190 Fixes to the Cookie Store API article
  src/content/en/updates/2018/09/asynchronous-access-to-http-cookies.md
Labels: cla: yes

#8095 Fixes to devtools source maps guide
  src/content/en/tools/chrome-devtools/javascript/source-maps.md
Labels: cla: yes

#8221 Correct example used for "Relative sized images"
  src/content/en/fundamentals/design-and-ux/responsive/images.md
Labels: cla: yes

#8222 Update file type used in "Relative sized images"
  src/content/en/fundamentals/design-and-ux/responsive/images.md
Labels: cla: yes

#8127 CDS Watch Live Banner & Landing
  src/content/en/_index.yaml
  src/content/en/_project.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/site-kit/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes, type-Content

#8225 fix external url reference typo
  src/content/en/tools/workbox/guides/troubleshoot-and-debug.md
Labels: cla: yes

#8232 Add What's New In DevTools (Chrome 79)
  src/content/en/updates/2019/10/devtools.md
  src/content/en/updates/_shared/discover.md
  src/content/en/updates/images/2019/10/colorscheme.png
  src/content/en/updates/images/2019/10/cookiestab.png
  src/content/en/updates/images/2019/10/cookievalues.png
  src/content/en/updates/images/2019/10/coverage.png
  src/content/en/updates/images/2019/10/info.png
  src/content/en/updates/images/2019/10/initiator.png
  src/content/en/updates/images/2019/10/sources.png
Labels: DO NOT MERGE, P1, cla: yes, content-new, section-updates, type-Content

#8230 Fixes to the Abortable fetch article
  src/content/en/updates/2017/09/abortable-fetch.md
Labels: cla: yes

#8227 Fixes to the Device Memory API article
  src/content/en/updates/2017/12/device-memory.md
Labels: cla: yes

#8235 Improve *What's new in DevTools (Chrome 79)* article
  src/content/en/updates/2019/10/devtools.md
Labels: cla: yes

#8237 New HTTP203
  src/content/en/shows/http203/podcast/stability-todos-and-census.md
Labels: cla: yes, type-Content

#8238 Better HTTP203 img
  src/content/en/shows/http203/podcast/stability-todos-and-census.md
Labels: cla: yes

#8248 New in Chrome 78
  src/content/en/updates/2019/10/nic78.md
  src/content/en/updates/images/2019/10/cds-2019.png
  src/content/en/updates/images/2019/10/fs-open.jpg
  src/content/en/updates/images/2019/10/new-78.jpg
  src/content/en/updates/images/2019/10/ot-landing.png
  src/data/commonTags.json
Labels: cla: yes

#8231 Create the Chromium Chronicle Episode 7
  src/content/en/updates/2019/10/chromium-chronicle-7.md
Labels: cla: yes

#8253 Fixes to New in Chrome 78
  src/content/en/updates/2019/10/nic78.md
Labels: cla: yes

#8246 Update an expected removal version.
  src/content/en/updates/2019/02/chrome-73-deps-rems.md
Labels: cla: yes, content-updated

#8244 Fixes to the Expand & collapse animations article
  src/content/en/updates/2017/03/performant-expand-and-collapse.md
Labels: cla: yes

#8242 Fixes to the Custom Scrollbar article
  src/content/en/updates/2017/03/custom-scrollbar.md
Labels: cla: yes

#8241 Fixes to Performant Parallaxing
  src/content/en/updates/2016/12/performant-parallaxing.md
Labels: cla: yes

#8236 Fixes to Estimating Available Storage Space
  src/content/en/updates/2017/08/estimating-available-storage-space.md
Labels: cla: yes

#8240 Fixes to Aligned Input Events
  src/content/en/updates/2017/06/aligning-input-events.md
Labels: cla: yes

#8014 Fix background services URL hash to match what DevTools links to
  src/content/en/tools/chrome-devtools/javascript/background-services.md
Labels: cla: yes

#8259 Deprecations and removals 79.
  src/content/en/updates/2019/10/chrome-79-deps-rems.md
Labels: cla: yes
