Repository google/WebFundamentals, pull requests merged in 2019-07, with the labels that each got.

#7848 Fixes to Using Plugins Workbox guide
  src/content/en/tools/workbox/guides/using-plugins.md
Labels: cla: yes

#7846 Fixes to Third Party Requests Workbox guide
  src/content/en/tools/workbox/guides/handle-third-party-requests.md
Labels: cla: yes

#7845 Some fixes to Configure Workbox guide
  src/content/en/tools/workbox/guides/configure-workbox.md
Labels: cla: yes

#7834 Fixes to Route Requests Workbox guide
  src/content/en/tools/workbox/guides/route-requests.md
Labels: cla: yes

#7831 Some fixes to Precache Files with Webpack
  src/content/en/tools/workbox/guides/precache-files/webpack.md
Labels: cla: yes

#7810 Change how deprecations and removals are presented.
  src/content/en/updates/2018/06/chrome-68-deps-rems.md
  src/content/en/updates/2018/08/chrome-69-deps-rems.md
  src/content/en/updates/2018/09/chrome-70-deps-rems.md
  src/content/en/updates/2018/10/chrome-71-deps-rems.md
  src/content/en/updates/2018/12/chrome-72-deps-rems.md
  src/content/en/updates/2019/02/chrome-73-deps-rems.md
  src/content/en/updates/2019/03/chrome-74-deps-rems.md
  src/content/en/updates/2019/05/chrome-75-deps-rems.md
  src/content/en/updates/2019/06/chrome-76-deps-rems.md
  src/content/en/updates/_shared/deprecations.html
  src/content/en/updates/_shared/no-new-deprecations.html
  src/content/en/updates/_shared/see-all-dep-rem.html
  src/content/en/updates/images/generic/deps-rems.jpg
Labels: cla: yes, content-updated, section-updates

#7676 Status updates and fixes in Capabilities article
  src/content/en/updates/capabilities.md
Labels: cla: yes

#7851 Change Fundamentals landing page to _index.yaml file
  src/content/en/fundamentals/_index.yaml
  src/content/en/fundamentals/index.md
  src/content/pt-br/fundamentals/index.md
  src/templates/latest_articles.html
  src/templates/shows/latest.html
Labels: DevSiteV2, P0, cla: yes, section-fundamentals, type-Infrastructure

#7823 Async clipboard images article
  src/content/en/updates/2019/07/image-support-for-async-clipboard.md
  src/content/en/updates/capabilities.md
  src/data/commonTags.json
Labels: cla: yes, content-new, type-Content

#7852 Fixes to Understanding Storage Quota Workbox guide
  src/content/en/tools/workbox/guides/storage-quota.md
Labels: cla: yes

#7859 Fixes to Common Recipes Workbox guide
  src/content/en/tools/workbox/guides/common-recipes.md
Labels: cla: yes

#7862 Fixes to Generate Service Worker w/ workbox-build
  src/content/en/tools/workbox/guides/generate-service-worker/workbox-build.md
Labels: cla: yes

#7870 Fixes to the workbox-sw module page
  src/content/en/tools/workbox/modules/workbox-sw.md
Labels: cla: yes

#7869 Web components time to upgrade
  src/content/en/images/contributors/jbingham.jpg
  src/content/en/updates/2019/07/web-components-time-to-upgrade.md
  src/content/en/updates/images/2019/07/web-components-console-deprecations.png
  src/data/_contributors.yaml
Labels: cla: yes, content-new, section-updates, type-Content

#7873 [devtools] add coverage guide
  src/content/en/tools/chrome-devtools/_toc.yaml
  src/content/en/tools/chrome-devtools/coverage/images/coveragetab.png
  src/content/en/tools/chrome-devtools/coverage/images/example.png
  src/content/en/tools/chrome-devtools/coverage/index.md
  src/content/en/tools/chrome-devtools/images/shared/stop.png
  src/content/en/tools/chrome-devtools/index.md
Labels: P2, cla: yes, content-new, section-tools, type-Content

#7874 Fix formatting issue in blog post
  src/content/en/updates/2019/07/web-components-time-to-upgrade.md
Labels: cla: yes, content-updated, section-updates, type-Content

#7886 [DevTools] Add CSS overrides guide
  src/content/en/tools/chrome-devtools/css/imgs/computed.png
  src/content/en/tools/chrome-devtools/css/imgs/computedexpanded.png
  src/content/en/tools/chrome-devtools/css/imgs/computedfilter.png
  src/content/en/tools/chrome-devtools/css/imgs/computedshowall.png
  src/content/en/tools/chrome-devtools/css/imgs/computedsource.png
  src/content/en/tools/chrome-devtools/css/imgs/override.png
  src/content/en/tools/chrome-devtools/css/overrides.md
  src/content/en/tools/chrome-devtools/inspect-styles/edit-dom.md
  src/content/en/tools/chrome-devtools/inspect-styles/index.md
Labels: cla: yes

#7895 Fixes to workbox-cacheable-response module page
  src/content/en/tools/workbox/modules/workbox-cacheable-response.md
Labels: cla: yes

#7909 Fixes to the workbox-routing module page
  src/content/en/tools/workbox/modules/workbox-routing.md
Labels: cla: yes

#7911 Small fixes to the Workbox index page
  src/content/en/tools/workbox/_index.yaml
Labels: cla: yes

#7906 Small fixes to Workbox Google Analytics
  src/content/en/tools/workbox/modules/workbox-google-analytics.md
Labels: cla: yes

#7903 Small fixes to workbox-broadcast-cache-update page
  src/content/en/tools/workbox/modules/workbox-broadcast-cache-update.md
Labels: cla: yes

#7898 Small fixes to workbox-navigation-preload page
  src/content/en/tools/workbox/modules/workbox-navigation-preload.md
Labels: cla: yes

#7893 Small fixes to Using Bundlers with Workbox guide
  src/content/en/tools/workbox/guides/using-bundlers.md
Labels: cla: yes

#7889 Fixes to Workbox Background Sync page
  src/content/en/tools/workbox/modules/workbox-background-sync.md
Labels: cla: yes

#7887 Small fixes to the workbox-cache-expiration page
  src/content/en/tools/workbox/modules/workbox-cache-expiration.md
Labels: cla: yes

#7877 Fixes to the workbox-strategies module page
  src/content/en/tools/workbox/modules/workbox-strategies.md
Labels: cla: yes

#7864 Fixes to Generate a Service Worker with Webpack
  src/content/en/tools/workbox/guides/generate-service-worker/webpack.md
Labels: cla: yes

#7861 Fixes to Generate Service Worker with Workbox CLI
  src/content/en/tools/workbox/guides/generate-service-worker/cli.md
Labels: cla: yes

#7853 Fixes to Troubleshoot and Debug Workbox guide
  src/content/en/tools/workbox/guides/troubleshoot-and-debug.md
Labels: cla: yes

#7913 Add image survey banner
  src/content/en/_project.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/site-kit/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes, content-updated, type-Content

#7919 [devtools] add wndt77
  src/content/en/updates/2019/07/devtools.md
  src/content/en/updates/images/2019/07/audits.png
  src/content/en/updates/images/2019/07/backgroundservices.png
  src/content/en/updates/images/2019/07/breakpointeditor.png
  src/content/en/updates/images/2019/07/copystyles.png
  src/content/en/updates/images/2019/07/layoutshift.png
  src/content/en/updates/images/2019/07/prefetch.png
  src/content/en/updates/images/2019/07/privatefields.png
Labels: P1, cla: yes, content-new, section-updates, type-Content

#7921 updating bitly links as they changed.
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E01-creating-a-collaborative-environment.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E02-balancing-creativity-with-user-testing.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E03-Adopting-the-native-language-of-the-web.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E04-are-designers-born-or-made.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E05-who-is-responsible-for-design.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS1E06-are-design-tools-fit-for-purpose.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E01-becoming-a-creative-coder.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E02-designing-a-great-performance.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E03-improving-your-creative-confidence.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E04-learn-how-to-design.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E05-designing-for-the-next-billion-users.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS2E06-how-the-web-can-compete-with-native.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E01-designing-for-css-grid.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E02-designing-for-standards.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E03-getting-a-start-in-industry.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E04-creative-ways-of-prototyping.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E05-using-the-gestalt-principles.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E06-how-to-design-a-vr-game.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS3E07-Designing-for-offline.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS4E01-how-we-designed-chrome.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS4E02-ux-research-usability-testingy.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS4E03-material-design-components.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS4E04-prototyping-motion.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS4E05-using-autocomplete.md
  src/content/en/shows/designer-vs-developer/podcast/DVDS4E06-pwas-firebase.md
Labels: cla: yes

#7936 Small fixes to How the payment ecosystem works
  src/content/en/fundamentals/payments/basics/how-payment-ecosystem-works.md
Labels: cla: yes

#7933 Fixes to the Web Payments Overview article
  src/content/en/fundamentals/payments/index.md
Labels: cla: yes

#7930 Small fixes to the Click to Call article
  src/content/en/fundamentals/native-hardware/click-to-call/index.md
Labels: cla: yes

#7928 Fixes to the Save Credentials from Forms article
  src/content/en/fundamentals/security/credential-management/save-forms.md
Labels: cla: yes

#7920 Add "Audio/Video Updates in Chrome 75" article
  src/content/en/updates/2019/07/chrome-75-media-updates.md
  src/content/en/updates/images/2019/07/protected-content-prompt.jpg
Labels: cla: yes, type-Content

#7915 Fixes to the Sign in Users article
  src/content/en/fundamentals/security/credential-management/retrieve-credentials.md
Labels: cla: yes

#7914 Create chromium-chronicle-4.md
  src/content/en/updates/2019/07/chromium-chronicle-4.md
Labels: cla: yes, content-new, section-updates, type-Content

#7912 Fixes to the workbox-precaching module page
  src/content/en/tools/workbox/modules/workbox-precaching.md
Labels: cla: yes

#7908 Some slight corrections of the article
  src/content/en/fundamentals/web-components/customelements.md
Labels: cla: yes

#7890 Update simplify-paint-complexity, tiny typo
  src/content/en/fundamentals/performance/rendering/simplify-paint-complexity-and-reduce-paint-areas.md
Labels: cla: yes

#7884 Updates Library version for the TWA documentation
  src/content/en/updates/2019/02/using-twa.md
Labels: cla: yes

#7868 Specify a commit hash for the jsdoc-baseline package
  package.json
Labels: cla: yes

#7882 precacheController - .cleanup() -> .activate()
  src/content/en/tools/workbox/modules/workbox-precaching.md
Labels: cla: yes

#7899 Fix issue where backslash doesn't render
  src/content/en/updates/2015/01/ES6-Template-Strings.md
Labels: cla: yes

#7940 Adds a vscode-workspace file
  WebFu.code-workspace
Labels: cla: yes, type-Infrastructure

#7879 Fix anchor test. Fixes #7875.
  gulp-tasks/tests/validateMarkdown.js
  src/tests/anchor-bad.md
Labels: cla: yes, type-Infrastructure

#7938 New in Chrome 76 - updates post
  src/content/en/fundamentals/app-install-banners/_mini-info-bar.md
  src/content/en/fundamentals/app-install-banners/index.md
  src/content/en/fundamentals/app-install-banners/promoting-install-mobile.md
  src/content/en/fundamentals/integration/webapks.md
  src/content/en/updates/2019/05/mini-infobar-update.md
  src/content/en/updates/2019/06/webapk-update-frequency.md
  src/content/en/updates/2019/07/nic76.md
  src/content/en/updates/images/2019/07/nic076.jpg
Labels: DO NOT MERGE, cla: yes, content-new, section-updates, type-Content

#7916 [Translation ja] src/content/ja/fundamentals/design-and-ux/ux-basics/index.md
  src/content/ja/fundamentals/design-and-ux/ux-basics/index.md
Labels: cla: yes
