Repository google/WebFundamentals, pull requests merged in 2019-06, with the labels that each got.

#7691 Payment App: Restrict "default_applications"
  src/content/en/fundamentals/payments/payment-apps-developer-guide/android-payment-apps.md
Labels: cla: yes

#7687 fix: wrong translate
  src/content/zh-tw/tools/chrome-devtools/rendering-tools/js-execution.md
Labels: cla: yes

#7686 fix: wrong translate
  src/content/zh-cn/tools/chrome-devtools/rendering-tools/js-execution.md
Labels: cla: yes

#7680 Adds Instruction to generate an icon for the TWA
  src/content/en/updates/2019/02/using-twa.md
Labels: cla: yes

#7706 Update Site Kit GA property
  gulp-tasks/tests/projectYaml.js
  src/content/en/site-kit/_project.yaml
Labels: cla: yes, section-site-kit, type-Infrastructure

#7674 Update Audio Worklet articles
  src/content/en/updates/2017/12/audio-worklet.md
  src/content/en/updates/2018/06/audio-worklet-design-pattern.md
Labels: cla: yes

#7672 fix duplicate ids (#7670)
  src/content/en/fundamentals/index.md
Labels: cla: yes

#7671 Improve instructions.
  src/content/en/tools/chrome-devtools/beginners/html.md
Labels: cla: yes

#7700 Fixed broken links
  src/content/en/fundamentals/security/prevent-mixed-content/_code/xmlhttprequest-example.html
Labels: cla: yes

#7697 Improvements to Sending Messages with Web Push
  src/content/en/fundamentals/push-notifications/sending-messages-with-web-push-libraries.md
Labels: cla: yes

#7696 Some fixes to the Permission UX article
  src/content/en/fundamentals/push-notifications/permission-ux.md
Labels: cla: yes

#7692 Fixes and improvements to Subscribing a User
  src/content/en/fundamentals/push-notifications/subscribing-a-user.md
Labels: cla: yes

#7690 Fix typo
  src/content/en/updates/2018/09/inside-browser-part3.md
Labels: cla: yes

#7689 Fixed a typo in the "How Push Works" article
  src/content/en/fundamentals/push-notifications/how-push-works.md
Labels: cla: yes

#7688 Update unused-css.md
  src/content/en/tools/lighthouse/audits/unused-css.md
Labels: cla: yes

#7694 Patterns for Promoting PWA Installation (mobile)
  src/content/en/fundamentals/app-install-banners/images/install-promo/banner.png
  src/content/en/fundamentals/app-install-banners/images/install-promo/game-over.png
  src/content/en/fundamentals/app-install-banners/images/install-promo/game-start.png
  src/content/en/fundamentals/app-install-banners/images/install-promo/header.png
  src/content/en/fundamentals/app-install-banners/images/install-promo/in-feed.png
  src/content/en/fundamentals/app-install-banners/images/install-promo/journey.png
  src/content/en/fundamentals/app-install-banners/images/install-promo/landing.png
  src/content/en/fundamentals/app-install-banners/images/install-promo/nav.png
  src/content/en/fundamentals/app-install-banners/images/install-promo/plp.png
  src/content/en/fundamentals/app-install-banners/images/install-promo/sign-up.png
  src/content/en/fundamentals/app-install-banners/index.md
  src/content/en/fundamentals/app-install-banners/promoting-install-mobile.md
  src/content/en/fundamentals/integration/_toc.yaml
  src/content/en/progressive-web-apps/_book.yaml
  src/content/en/progressive-web-apps/desktop.md
  src/content/en/updates/2019/06/pwa-install-patterns.md
Labels: cla: yes, content-new, type-Content

#7705 New in Chrome 75
  src/content/en/updates/2019/06/nic75.md
  src/content/en/updates/images/2019/06/balazs-ketyi-1410250-unsplash-small.jpg
  src/content/en/updates/images/2019/06/nic075.jpg
  src/content/en/updates/images/2019/06/web-share-from-myntra-to-twitter.mp4
  src/content/en/updates/images/2019/06/web-share-from-myntra-to-twitter.webm
Labels: cla: yes, content-new, section-updates, type-Content

#7721 Make link to demo use HTTPS
  src/content/en/updates/2019/06/nic75.md
Labels: cla: yes

#7726 [devtools] add video
  src/content/en/updates/2019/04/devtools.md
Labels: P1, cla: yes, content-new, content-updated, section-updates, type-Content

#7693 Updated the description for monitoring background service events.
  src/content/en/updates/2019/05/devtools.md
Labels: cla: yes

#7729 [devtools] update background services section in wndt76
  src/content/en/tools/chrome-devtools/images/shared/record.png
  src/content/en/updates/2019/05/devtools.md
Labels: P1, cla: yes, content-new, section-updates, type-Content

#7735 Modified triggerPushMsg() in Web Push article
  src/content/en/fundamentals/push-notifications/sending-messages-with-web-push-libraries.md
Labels: cla: yes

#7732 remove errant word from NIC75
  src/content/en/updates/2019/06/nic75.md
Labels: cla: yes

#7725 Fixes to the Web Push Notifications FAQ
  src/content/en/fundamentals/push-notifications/faq.md
Labels: cla: yes

#7748 Some fixes to the Push Events article
  src/content/en/fundamentals/push-notifications/handling-messages.md
Labels: cla: yes

#7747 Updates TWA Documentation to include Splash Screen
  src/content/en/updates/2019/02/using-twa.md
Labels: cla: yes

#7743 Web Push - Notification/Vibrate
  src/content/en/fundamentals/push-notifications/common-notification-patterns.md
  src/content/en/fundamentals/push-notifications/display-a-notification.md
  src/content/en/fundamentals/push-notifications/faq.md
  src/content/en/fundamentals/push-notifications/notification-behaviour.md
  src/content/en/fundamentals/push-notifications/permission-ux.md
Labels: cla: yes, content-updated, section-fundamentals, type-Content

#7734 📖 Add more information about registration and scope
  src/content/en/ilt/pwa/introduction-to-service-worker.md
Labels: cla: yes

#7750 Surgical fixes to TWA article
  src/content/en/updates/2019/02/using-twa.md
Labels: cla: yes

#7751 Replace codelab index.md with index.yaml
  src/content/en/fundamentals/codelabs/_index.yaml
  src/content/en/fundamentals/codelabs/index.md
Labels: cla: yes

#7752 Rename system ui -> application ui
  src/content/en/fundamentals/app-install-banners/promoting-install-mobile.md
Labels: cla: yes, content-updated, section-fundamentals, type-Content

#7754 Some fixes to Displaying a Notification article
  src/content/en/fundamentals/push-notifications/display-a-notification.md
Labels: cla: yes

#7755 404 error correction for beforeinstallprompt link
  src/content/en/updates/2019/05/mini-infobar-update.md
Labels: cla: yes

#7756 Some fixes to the Notification Behavior article
  src/content/en/fundamentals/push-notifications/notification-behaviour.md
Labels: cla: yes

#7759 Update Permission UX article JA translation
  src/content/ja/fundamentals/push-notifications/permission-ux.md
Labels: cla: yes

#7764 Add modules article to TOC
  src/content/en/fundamentals/_toc-base.yaml
Labels: cla: yes

#7767 PWA on Desktop Install Button in Address Bar
  src/content/en/updates/2019/06/pwa-install-addressbar.md
  src/content/en/updates/images/2019/06/pwa-omnibox-install.jpg
  src/content/en/updates/videos/2019/06/pwa-install-addressbar.mp4
  src/content/en/updates/videos/2019/06/pwa-install-addressbar.webm
Labels: cla: yes, content-new, section-updates, type-Content

#7765 Some fixes to the "New in Chrome 75" article
  src/content/en/updates/2019/06/nic75.md
Labels: cla: yes

#7749 Remove migrated content
  src/content/en/fundamentals/primers/imgs/async-defer.svg
  src/content/en/fundamentals/primers/imgs/renderer-main-thread-time-breakdown.png
  src/content/en/fundamentals/primers/modules.md
  src/content/en/updates/2017/06/object-rest-spread.md
  src/content/en/updates/2017/10/intl-pluralrules.md
  src/content/en/updates/2017/10/promise-finally.md
  src/content/en/updates/2017/11/dynamic-import.md
  src/content/en/updates/2018/05/bigint.md
  src/content/en/updates/2018/10/intl-relativetimeformat.md
  src/content/en/updates/2018/12/class-fields.md
  src/content/en/updates/2018/12/intl-listformat.md
  src/content/en/updates/images/2018/05/bigint-perf.png
Labels: cla: yes

#7662 emscripten-npm: improve --host & --target flags to configure
  src/content/en/updates/2019/01/emscripten-npm.md
Labels: cla: yes

#7774 Show warning on Site Kit pages if an adblocker is used
  src/content/en/site-kit/apikey.html
  src/content/en/site-kit/index.html
Labels: cla: yes, section-site-kit, type-Content

#7773 Change word in PWA Address Bar Install on Desktop
  src/content/en/updates/2019/06/pwa-install-addressbar.md
Labels: cla: yes

#7720 Update webapk update interval
  src/content/en/fundamentals/integration/webapks.md
  src/content/en/updates/2019/06/webapk-update-frequency.md
  src/content/en/updates/images/2019/06/webapk.png
Labels: cla: yes, content-updated, section-fundamentals, type-Content

#7776 Add 'out of order' sign to Chacmool article.
  src/content/en/updates/2018/06/webar-chacmool.md
Labels: cla: yes

#7784 Translate rendering-on-the-web.md via GitLocalize
  src/content/ja/updates/2019/02/rendering-on-the-web.md
  src/data/_contributors.yaml
Labels: cla: no

#7797 Some fixes to Precache Files with Workbox CLI
  src/content/en/tools/workbox/guides/precache-files/cli.md
Labels: cla: yes

#7793 Typo
  src/content/en/tools/workbox/modules/workbox-sw.md
Labels: cla: yes

#7792 Typo
  src/content/en/tools/workbox/modules/workbox-window.md
Labels: cla: yes

#7791 Changed ` with <code> in Workbox install-cli.html
  src/content/en/tools/workbox/guides/_shared/install-cli.html
Labels: cla: yes

#7790 Some fixes to the Workbox Precache Files Overview
  src/content/en/tools/workbox/guides/precache-files/index.md
Labels: cla: yes

#7788 Improved comment in Workbox register-sw.html
  src/content/en/tools/workbox/guides/_shared/register-sw.html
Labels: cla: yes

#7787 Fixes to the Web Push Common Issues article
  src/content/en/fundamentals/push-notifications/common-issues-and-reporting-bugs.md
Labels: cla: yes

#7786 Fixes to the Common Notification Patterns article
  src/content/en/fundamentals/push-notifications/common-notification-patterns.md
Labels: cla: yes

#7783 Fixes #7799: Remove the 30 seconds heuristic
  src/content/en/fundamentals/app-install-banners/_a2hs-criteria.html
Labels: cla: yes

#7779 Fixes to the "WebAPKs on Android" article
  src/content/en/fundamentals/integration/webapks.md
Labels: cla: yes

#7798 Fix build break - remove developers.google.com from links
  src/content/ja/updates/2019/02/rendering-on-the-web.md
Labels: cla: yes

#7768 Add Deprecations and Removals for Chrome 76.
  src/content/en/updates/2019/06/chrome-76-deps-rems.md
Labels: cla: no

#7805 [devtools] update setup images for beginners html tutorial
  src/content/en/tools/chrome-devtools/beginners/html.md
  src/content/en/tools/chrome-devtools/beginners/imgs/setup1.png
  src/content/en/tools/chrome-devtools/beginners/imgs/setup2.png
Labels: P1, cla: yes, content-updated, section-tools, type-Content

#7803 Revert " Add Deprecations and Removals for Chrome 76."
  src/content/en/updates/2019/06/chrome-76-deps-rems.md
Labels: cla: yes

#7809 Deprecations and removals for Chrome 76.
  src/content/en/updates/2019/06/chrome-76-deps-rems.md
Labels: cla: yes

#7817 Fixed link and typo
  src/content/en/updates/2017/09/autoplay-policy-changes.md
Labels: cla: yes

#7816 Fixes #7813, #7814, #7777 - Misc doc tweaks
  src/content/en/fundamentals/app-install-banners/index.md
  src/content/en/fundamentals/web-app-manifest/index.md
Labels: cla: yes

#7812 fix naming of variable in payment handler api
  src/content/en/updates/2018/06/payment-handler-api.md
Labels: cla: yes

#7811 Fixed layout worklet example: Const -> const
  src/content/en/updates/2016/05/houdini.md
Labels: cla: yes

#7806 Changed backtick with <code> in Workbox shared files
  src/content/en/tools/workbox/guides/_shared/install-webpack.html
  src/content/en/tools/workbox/guides/_shared/install-workbox-build.html
Labels: cla: yes

#7801 Fixes to Precache Files with workbox-build article
  src/content/en/tools/workbox/guides/precache-files/workbox-build.md
Labels: cla: yes

#7794 chromium-chronicle-3
  src/content/en/updates/2019/06/chromium-chronicle-3.md
  src/content/en/updates/images/2019/06/cr-cron3-diff.jpg
  src/content/en/updates/images/2019/06/cr-cron3-left.png
  src/content/en/updates/images/2019/06/cr-cron3-right.png
Labels: cla: yes

#7808 update Japanese translation of the CSS Containment post
  src/content/ja/updates/2016/06/css-containment.md
Labels: cla: yes

#7822 Translation cleanup
  src/content/en/resources/translations.md
  src/content/ja/fundamentals/payments/index.md
Labels: cla: yes, type-Content-Translation

#7821 Replace apparently unsupported ~~ MD strike with <del>
  src/content/en/updates/2015/04/cut-and-copy-commands.md
Labels: cla: yes

#7820 Fixes to the Get Started Workbox guide
  src/content/en/tools/workbox/guides/get-started.md
Labels: cla: yes
