Repository google/WebFundamentals, pull requests merged in 2019-08, with the labels that each got.

#7944 Remove *-starter-kit content
  src/content/en/tools/_index.yaml
  src/content/en/tools/polymer-starter-kit/index.md
  src/content/en/tools/starter-kit/index.md
Labels: cla: yes, content-updated, type-Content

#7941 Fixes to the How Payment Request API Works article
  src/content/en/fundamentals/payments/basics/how-payment-request-api-works.md
Labels: cla: yes

#7937 [Translation ja] src/content/ja/fundamentals/performance/get-started/index.md
  src/content/ja/fundamentals/performance/get-started/index.md
Labels: cla: no

#7918 [Translation ja] src/content/ja/fundamentals/architecture/app-shell.md
  src/content/ja/fundamentals/architecture/app-shell.md
Labels: cla: yes

#7847 Rendering - French translation
  src/content/fr/_shared/udacity/ud860.html
  src/content/fr/fundamentals/performance/rendering/index.md
  src/data/_contributors.yaml
Labels: cla: yes

#7954 Remove image survey banner
  src/content/en/_project.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/site-kit/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes, content-updated, type-Content

#7945 Fixes to the Payment Method Basics article
  src/content/en/fundamentals/payments/basics/payment-method-basics.md
Labels: cla: yes

#7955 Fixes to the Recording Audio from the User article
  src/content/en/fundamentals/media/recording-audio/index.md
Labels: cla: yes

#7965 fix(capabilities): fix broken link to crbug.com
  src/content/en/updates/capabilities.md
Labels: cla: yes

#7964 Allow autoplay with sound if PWA installed on desktop
  src/content/en/updates/2017/09/autoplay-policy-changes.md
Labels: cla: yes

#7963 Small fixes to the Custom Easing article
  src/content/en/fundamentals/design-and-ux/animations/custom-easing.md
Labels: cla: yes

#7961 Small fixes to The Basics of Easing article
  src/content/en/fundamentals/design-and-ux/animations/the-basics-of-easing.md
Labels: cla: yes

#7960 Fixes to CSS Versus JavaScript Animations
  src/content/en/fundamentals/design-and-ux/animations/css-vs-javascript.md
Labels: cla: yes

#7970 Add article for Contact Picker API
  src/content/en/updates/2019/08/contact-picker.md
  src/content/en/updates/capabilities.md
  src/content/en/updates/images/2019/08/contact-picker-demo.jpg
  src/content/en/updates/images/2019/08/contact-picker-left.jpg
  src/content/en/updates/images/2019/08/contact-picker-long-press.jpg
  src/content/en/updates/images/2019/08/contact-picker-right.jpg
  src/content/en/updates/images/2019/08/contact-picker-user-choice.jpg
  src/content/en/updates/images/generic/contacts.png
  src/data/blinkComponents.json
  src/data/commonTags.json
Labels: cla: yes, content-new, proj-fugu, section-updates, type-Content

#7974 fix(web-share-target): fix link to the level 2 draft
  src/content/en/updates/2018/12/web-share-target.md
Labels: cla: yes

#7972 Fixes to CSS in the Animating Modal Views article
  src/content/en/fundamentals/design-and-ux/animations/animating-modal-views.md
Labels: cla: yes

#7976 Fix capitalisation in a section's title
  src/content/en/fundamentals/primers/service-workers/index.md
Labels: cla: yes

#7973 Contact Picker requires Android M or later
  src/content/en/updates/2019/08/contact-picker.md
Labels: cla: yes

#7871 Update agencies directory
  src/content/en/agencies/data/agencies.json
  src/content/en/agencies/images/balconia_limited.png
  src/content/en/agencies/images/escola_sa_inc.png
  src/content/en/agencies/images/isobar_uk.png
  src/content/en/agencies/images/long_live_king_ltd.png
  src/content/en/agencies/images/moovweb.png
  src/content/en/agencies/images/pwa_lab,_llp.png
  src/content/en/agencies/images/toaster.png
Labels: cla: yes

#7966 Add deps/rems 77 article.
  src/content/en/updates/2019/08/chrome-77-deps-rems.md
  src/content/en/updates/_shared/no-new-deprecations.html
  src/content/en/updates/_shared/no-new-removals.html
Labels: cla: yes, content-new

#7978 Add parens to method names.
  src/content/en/updates/2018/12/get-installed-related-apps.md
Labels: cla: yes

#7989 Correct link to web share demo after wicg→w3c move
  src/content/en/updates/2019/05/web-share-files.md
Labels: cla: yes, content-updated, proj-fugu

#7988 Fix async clipboard link from capabilities page
  src/content/en/updates/capabilities.md
Labels: cla: yes, content-updated, proj-fugu

#7985 Fixes to the Animating Between Views article
  src/content/en/fundamentals/design-and-ux/animations/animating-between-views.md
Labels: cla: yes

#7984 Fix typo
  src/content/en/tools/chrome-devtools/rendering-tools/forced-synchronous-layouts.md
  src/content/es/tools/chrome-devtools/rendering-tools/forced-synchronous-layouts.md
  src/content/id/tools/chrome-devtools/rendering-tools/forced-synchronous-layouts.md
  src/content/ja/tools/chrome-devtools/rendering-tools/forced-synchronous-layouts.md
  src/content/ko/tools/chrome-devtools/rendering-tools/forced-synchronous-layouts.md
  src/content/pt-br/tools/chrome-devtools/rendering-tools/forced-synchronous-layouts.md
  src/content/zh-cn/tools/chrome-devtools/rendering-tools/forced-synchronous-layouts.md
  src/content/zh-tw/tools/chrome-devtools/rendering-tools/forced-synchronous-layouts.md
Labels: cla: yes

#7982 Fixes to Manipulating Media Files > App Primers
  src/content/en/fundamentals/media/manipulating/applications.md
Labels: cla: yes

#7980 Fixes to the Animations and Performance article
  src/content/en/fundamentals/design-and-ux/animations/animations-and-performance.md
Labels: cla: yes

#7979 Update shadowdom.md
  src/content/en/fundamentals/web-components/shadowdom.md
Labels: cla: yes

#7986 Refresh alpha channel article with VP9 support
  src/content/en/updates/2013/07/Alpha-transparency-in-Chrome-video.md
Labels: cla: yes, content-updated

#7991 Fix overuse of "()".
  src/content/en/updates/2018/12/get-installed-related-apps.md
Labels: cla: yes

#7993 Experimenting with Periodic Background Sync
  src/content/en/updates/2019/08/periodic-background-sync.md
  src/content/en/updates/images/2019/08/periodic-background-sync/1-record.png
  src/content/en/updates/images/2019/08/periodic-background-sync/2-record-result.png
  src/content/en/updates/images/2019/08/periodic-background-sync/3-sw-panel.png
  src/content/en/updates/images/2019/08/periodic-background-sync/4-experiments.png
  src/content/en/updates/images/2019/08/periodic-background-sync/5-settings.png
  src/content/en/updates/images/2019/08/periodic-background-sync/6-checkbox.png
  src/content/en/updates/images/2019/08/periodic-background-sync/7-panel.png
  src/content/en/updates/images/generic/baseline-sync.png
  src/data/_contributors.yaml
Labels: cla: yes, content-new, proj-fugu, section-updates

#7994 [devtools] add background services guide
  src/content/en/tools/chrome-devtools/javascript/background-services.md
  src/content/en/tools/chrome-devtools/javascript/imgs/fetchdetails.png
  src/content/en/tools/chrome-devtools/javascript/imgs/fetchempty.png
  src/content/en/tools/chrome-devtools/javascript/imgs/fetchlog.png
  src/content/en/tools/chrome-devtools/javascript/imgs/gear.png
  src/content/en/tools/chrome-devtools/javascript/imgs/notificationsdetails.png
  src/content/en/tools/chrome-devtools/javascript/imgs/notificationsempty.png
  src/content/en/tools/chrome-devtools/javascript/imgs/notificationslog.png
  src/content/en/tools/chrome-devtools/javascript/imgs/pushdetails.png
  src/content/en/tools/chrome-devtools/javascript/imgs/pushempty.png
  src/content/en/tools/chrome-devtools/javascript/imgs/pushlog.png
  src/content/en/tools/chrome-devtools/javascript/imgs/syncdetails.png
  src/content/en/tools/chrome-devtools/javascript/imgs/syncempty.png
  src/content/en/tools/chrome-devtools/javascript/imgs/synclog.png
Labels: P1, cla: yes, content-new, section-tools, type-Content

#7995 Adds note on native lazy loading
  src/content/en/fundamentals/performance/lazy-loading-guidance/images-and-video/index.md
Labels: cla: yes, type-Content

#8005 Small fixes to the Web Share Target API article
  src/content/en/updates/2018/12/web-share-target.md
Labels: cla: yes

#7999 Clarify no install checks are needed before a badging attempt and no counter capping should be applied
  src/content/en/updates/2018/12/badging-api.md
  src/content/en/updates/capabilities.md
Labels: cla: yes, content-updated, proj-fugu

#7997 Fixes to the Security and Identity article
  src/content/en/fundamentals/security/index.md
Labels: cla: yes

#7996 Fixes to the Contact Picker API article
  src/content/en/updates/2019/08/contact-picker.md
Labels: cla: yes

#8006 AskChrome banner
  src/content/en/_project.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/site-kit/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes

#8007 Adds CDS hero
  src/content/en/_index.yaml
  src/content/en/styles/wf-landing.css
Labels: cla: yes

#8002 Native File System post
  src/content/en/updates/2018/11/writable-files.md
  src/content/en/updates/2019/08/native-file-system.md
  src/content/en/updates/_redirects.yaml
  src/content/en/updates/capabilities.md
  src/content/en/updates/images/2019/08/fs-open.jpg
  src/content/en/updates/images/2019/08/fs-save-icon.jpg
  src/content/en/updates/images/2019/08/fs-save-permission-crop.jpg
  src/content/en/updates/images/2019/08/fs-save-permission.jpg
  src/content/en/updates/images/2019/08/fs-save.jpg
  src/data/commonTags.json
Labels: cla: yes

#8008 with youtube video
  src/content/en/_index.yaml
  src/content/en/styles/wf-landing.css
Labels: cla: yes

#8011 Last minute edits.
  src/content/en/updates/2019/08/get-started-with-gpu-compute-on-the-web.md
Labels: cla: yes

#8010 Add "Get started with GPU Compute on the Web" article
  src/content/en/updates/2019/08/get-started-with-gpu-compute-on-the-web.md
  src/content/en/updates/images/2019/08/gpu-cpu-benchmark.jpg
  src/content/en/updates/images/2019/08/matrix-execution.jpg
  src/content/en/updates/images/2019/08/matrix-multiplication-diagram.jpg
  src/content/en/updates/images/2019/08/matrix-multiplication-result.jpg
  src/content/en/updates/images/2019/08/matrix-representation.jpg
Labels: cla: yes, content-new, section-updates, type-Content

#8050 Improvements to shape detection article.
  src/content/en/updates/2019/01/shape-detection.md
Labels: DO NOT MERGE, cla: yes, migrate-content
