Repository google/WebFundamentals, pull requests merged in 2019-09, with the labels that each got.

#8064 Update broken link
  src/content/en/fundamentals/performance/http2/index.md
Labels: cla: yes

#8074 New episode of http203
  src/content/en/shows/http203/podcast/block-drop-n-swap.md
  src/content/en/shows/http203/podcast/images/with-mariko.jpg
Labels: cla: yes, type-Content

#8072 Correct cache storage location
  src/content/en/tools/chrome-devtools/storage/cache.md
Labels: cla: yes

#8071 Update Surma's link for houdini intro
  src/content/en/updates/2016/02/smooth-scrolling-in-chrome-49.md
Labels: cla: yes

#8065 Fixes to the Content Security Policy article
  src/content/en/fundamentals/security/csp/index.md
Labels: cla: yes

#8063 Fixed a broken link to Blink
  src/content/en/updates/2018/03/cssom.md
Labels: cla: yes

#8060 Small fixes to the Icons & Browser Colors article
  src/content/en/fundamentals/design-and-ux/browser-customization/index.md
Labels: cla: yes

#8059 Fixes to the Native File System API article
  src/content/en/updates/2019/08/native-file-system.md
Labels: cla: yes

#8058 fixed two typos
  src/content/en/ilt/pwa/lab-integrating-analytics.md
Labels: cla: yes

#8055 Fixes to the Periodic Background Sync article
  src/content/en/updates/2019/08/periodic-background-sync.md
Labels: cla: yes

#7987 Add Trusted Web Activity Quick Start Guide.
  src/content/en/updates/2019/02/using-twa.md
  src/content/en/updates/2019/08/twas-quickstart.md
Labels: cla: yes

#8052 Fixes to the Animating a Blur article
  src/content/en/updates/2017/10/animated-blur.md
Labels: cla: yes

#8069 Move workbox-broadcast-cache-update module to workbox-broadcast-update
  src/content/en/tools/_redirects.yaml
  src/content/en/tools/workbox/_shared/config/single/runtimeCaching.html
  src/content/en/tools/workbox/modules/_index.yaml
  src/content/en/tools/workbox/modules/_toc.yaml
  src/content/en/tools/workbox/modules/workbox-broadcast-update.md
  src/content/en/tools/workbox/modules/workbox-window.md
Labels: cla: yes

#7447 2015 Updates - updating 2 more months
  src/content/en/updates/2015/04/DOM-attributes-now-on-the-prototype-chain.md
  src/content/en/updates/2015/04/a-new-home-for-devtools.md
  src/content/en/updates/2015/04/alt-click-to-expand-all-child-nodes.md
  src/content/en/updates/2015/04/autocapitalize.md
  src/content/en/updates/2015/04/better-incognito-devtools.md
  src/content/en/updates/2015/04/command-click-to-add-multiple-cursors-in-the-sources-panel.md
  src/content/en/updates/2015/04/copy-image-as-data-uri.md
  src/content/en/updates/2015/04/cut-and-copy-commands.md
  src/content/en/updates/2015/04/permissions-api-for-the-web.md
  src/content/en/updates/2015/04/quick-edit-element-tags.md
  src/content/en/updates/2015/04/quickly-monitor-events-from-the-console-panel.md
  src/content/en/updates/2015/04/reveal-in-elements-panel.md
  src/content/en/updates/2015/04/see-matching-selectors.md
  src/content/en/updates/2015/04/simplified-concepts-in-web-animations-naming.md
  src/content/en/updates/2015/04/the-currently-selected-dom-node.md
  src/content/en/updates/2015/04/the-easing-editor.md
  src/content/en/updates/2015/04/toggle-the-devtools-dock-state-with-a-keyboard-shortcut.md
  src/content/en/updates/2015/04/unfinished-network-requests.md
  src/content/en/updates/2015/06/Media-Source-Extensions-for-Audio.md
  src/content/en/updates/2015/06/checkout-faster-with-autofill.md
  src/content/en/updates/2015/06/quickly-edit-view-resources-from-the-elements-panel.md
Labels: cla: yes

#8079 CDS invite request banner
  src/content/en/_project.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/site-kit/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes

#8078 Add peconn to contributors
  src/content/en/images/contributors/peconn.jpg
  src/content/en/updates/2019/08/twas-quickstart.md
  src/data/_contributors.yaml
Labels: cla: yes, content-updated, section-updates

#8016 Update KV Storage syntax to use default export
  src/content/en/updates/2019/03/kv-storage.md
Labels: cla: yes

#8054 DevTools: Add What's New In DevTools (Chrome 78)
  src/content/en/updates/2019/09/devtools.md
  src/content/en/updates/_shared/discover.md
  src/content/en/updates/images/2019/09/lcp.png
  src/content/en/updates/images/2019/09/relatednode.png
  src/content/en/updates/images/2019/09/reportissue.png
  src/content/en/updates/images/2019/09/thirdpartycode.png
Labels: P1, cla: yes, content-new, content-updated, section-updates, type-Content

#8085 Update What's New In DevTools (Chrome 78)
  src/content/en/updates/2019/09/devtools.md
  src/content/en/updates/_shared/discover.md
  src/content/en/updates/images/2019/09/blocking.png
  src/content/en/updates/images/2019/09/payment1.png
  src/content/en/updates/images/2019/09/payment2.png
  src/content/en/updates/images/2019/09/renderblockingresources.png
  src/content/en/updates/images/2019/09/score1.png
  src/content/en/updates/images/2019/09/score2.png
Labels: P1, cla: yes, content-new, section-updates, type-Content

#8082 Updates TWA Support Library version
  src/content/en/updates/2019/02/using-twa.md
Labels: cla: yes

#8086 Update spec link in web share article.
  src/content/en/updates/2019/05/web-share-files.md
Labels: cla: yes

#8087 Fixes to the Preventing Mixed Content article
  src/content/en/fundamentals/security/prevent-mixed-content/fixing-mixed-content.md
Labels: cla: yes

#8090 Adds a note on light DOM to the web components best practices
  src/content/en/fundamentals/web-components/best-practices.md
Labels: cla: yes

#8083 Update to Wake Lock API article with latest API changes
  src/content/en/updates/2018/12/wakelock.md
  src/content/en/updates/_shared/capabilities.html
  src/content/en/updates/capabilities.md
Labels: cla: yes, content-updated, proj-fugu

#8084 Copy edit async clipboard article.
  src/content/en/updates/2019/07/image-support-for-async-clipboard.md
Labels: DO NOT MERGE, cla: yes

#8120 Fixes to Emscripting a C library to Wasm
  src/content/en/updates/2018/03/emscripting-a-c-library.md
Labels: cla: yes

#8116 Fixes to Making wheel scrolling fast by default
  src/content/en/updates/2019/02/scrolling-intervention.md
Labels: cla: yes

#8115 Updated to Trusted Web Activities Quickstart
  src/content/en/updates/2019/08/twas-quickstart.md
Labels: cla: yes

#8114 Fixes to the Priority Hints article
  src/content/en/updates/2019/02/priority-hints.md
Labels: cla: yes

#8112 PWA on Desktop works on all platforms
  src/content/en/progressive-web-apps/_index.yaml
Labels: cla: yes

#8110 Fixes to the Trusted Types article
  src/content/en/updates/2019/02/trusted-types.md
Labels: cla: yes

#8107 Fixes to the prefers-reduced-motion article
  src/content/en/updates/2019/03/prefers-reduced-motion.md
Labels: cla: yes

#8106 Solve 404 error
  src/content/en/fundamentals/performance/why-performance-matters/index.md
Labels: cla: yes

#8123 New in Chrome 77
  src/content/en/updates/2019/09/nic77.md
  src/content/en/updates/images/2019/09/cds2019.png
  src/content/en/updates/images/2019/09/lcp-google-filmstrip.png
  src/content/en/updates/images/2019/09/new-77.jpg
  src/content/en/updates/images/2019/09/perf-metrics-load-timeline.png
  src/data/commonTags.json
Labels: cla: yes

#8104 Fixes to the KV Storage article
  src/content/en/updates/2019/03/kv-storage.md
Labels: cla: yes

#8100 Fixes to the LayoutNG article
  src/content/en/updates/2019/06/layoutNG.md
Labels: cla: yes

#8096 Fixes to Enabling HTTPS on Your Servers
  src/content/en/fundamentals/security/encrypt-in-transit/enable-https.md
Labels: cla: yes

#8093 Fixes to the What Is Mixed Content article
  src/content/en/fundamentals/security/prevent-mixed-content/what-is-mixed-content.md
Labels: cla: yes

#8092 Fixes to the TWA Quick Start Guide
  src/content/en/updates/2019/08/twas-quickstart.md
Labels: cla: yes

#8124 Update /nic to nic77 article
  src/content/en/updates/_redirects.yaml
Labels: cla: yes

#8129 Fixes to New in Chrome 77
  src/content/en/updates/2019/09/nic77.md
Labels: cla: yes

#8130 Update chromium-chronicle-1.md
  src/content/en/updates/2019/04/chromium-chronicle-1.md
Labels: cla: yes

#8131 Update chromium-chronicle-5.md
  src/content/en/updates/2019/08/chromium-chronicle-5.md
Labels: cla: yes

#8132 [Async Clipboard article] Fix typo: blog==>blob
  src/content/en/updates/2019/07/image-support-for-async-clipboard.md
Labels: cla: yes

#8133 Stick to glslang version 0.0.7
  src/content/en/updates/2019/08/get-started-with-gpu-compute-on-the-web.md
Labels: cla: yes

#8140 [devtools] remove experiments
  src/content/en/updates/2018/04/_experiments.yaml
  src/content/en/updates/2018/04/devtools.md
  src/content/en/updates/2018/05/_experiments.yaml
  src/content/en/updates/2018/05/devtools.md
  src/content/en/updates/2018/08/_experiments.yaml
  src/content/en/updates/2018/08/devtools.md
Labels: cla: yes

#8135 SW importScripts update checks
  src/content/en/updates/2019/09/fresher-sw.md
  src/content/en/updates/_redirects.yaml
Labels: cla: yes, section-updates, type-Content

#8136 Update glslang version to 0.0.8
  src/content/en/updates/2019/08/get-started-with-gpu-compute-on-the-web.md
Labels: cla: yes

#8111 Depsrems78
  src/content/en/updates/2019/09/chrome-78-deps-rems.md
Labels: cla: yes, content-new

#8143 update tools and dataset recommendations
  src/content/en/updates/2018/07/search-ads-speed.md
Labels: cla: yes, type-Content

#8142 Fix devsite-v2 style issues in Site Kit pages
  src/content/en/site-kit/apikey.html
  src/content/en/site-kit/index.html
Labels: cla: yes, section-site-kit, type-Content

#8158 [devtools] fix #8105
  src/content/en/updates/2019/07/devtools.md
  src/content/en/updates/2019/09/devtools.md
Labels: P2, cla: yes, content-updated, section-updates, type-Content

#8160 tweaks demo code on payment-request.md
  src/content/en/updates/2016/07/payment-request.md
  src/content/ja/updates/2016/07/payment-request.md
Labels: cla: yes

#8159 Fixes to the Emscripten’s embind article
  src/content/en/updates/2018/08/embind.md
Labels: cla: yes

#8157 Fix simple typo in Introduction to variable fonts
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/index.md
Labels: cla: yes

#8155 Fixes to the Emscripten and npm article
  src/content/en/updates/2019/01/emscripten-npm.md
Labels: cla: yes

#8148 Fixes to the User Activation v2 article
  src/content/en/updates/2019/01/user-activation.md
Labels: cla: yes

#8144 Fixes to the Fresher service workers article
  src/content/en/updates/2019/09/fresher-sw.md
Labels: cla: yes

#8128 Creation chromium-chronicle-6.md
  src/content/en/updates/2019/09/chromium-chronicle-6.md
  src/content/en/updates/images/2019/09/chrom-chron-6-screenshot1.png
  src/content/en/updates/images/2019/09/chrom-chron-6-screenshot2.png
  src/content/en/updates/images/2019/09/chrom-chron-6-screenshot3.png
Labels: cla: yes, content-new, section-updates, type-Content

#8080 Copy edit of contact-picker.md.
  src/content/en/updates/2019/08/contact-picker.md
Labels: cla: yes

#8089 Copy edit Native File System API article.
  src/content/en/updates/2019/08/native-file-system.md
Labels: cla: yes

#8167 Add OT info to NativeFS article
  src/content/en/updates/2019/08/native-file-system.md
  src/content/en/updates/capabilities.md
Labels: cla: yes, content-updated, proj-fugu, section-updates, type-Content

#8168 Force DevSite v1 styles
  .gitignore
  gae/scripts/footer-closure.js
  gae/scripts/framebox.js
  gae/scripts/jquery-2.1.1.min.js
  gae/scripts/jquery-bundle.js
  gae/scripts/prettify-bundle.js
  gae/scripts/script_foot.js
  gae/scripts/script_foot_closure.js
  gae/styles/devsite-google-blue.css
  gae/styles/devsite-orange.css
  package.json
  start-appengine.sh
  tools/update-resources.sh
Labels: cla: yes

#8174 Copy edit Badging article.
  src/content/en/updates/2018/12/badging-api.md
Labels: cla: yes

#8176 Fixes to the CSS Paint API article
  src/content/en/updates/2018/01/paintapi.md
Labels: cla: yes

#8175 Fix unbalanced tags causing a rendering error
  src/content/en/fundamentals/codelabs/offline/index.md
Labels: cla: yes

#8178 Updating to the correct way to add audio to an element from a file
  src/content/en/fundamentals/media/recording-audio/index.md
Labels: cla: yes

#8177 Add notes on Google Play Signing to TWA Quickstart.
  src/content/en/updates/2019/08/twas-quickstart.md
Labels: cla: yes

#8170 Fixes to the WebAssembly Threads article
  src/content/en/updates/2018/10/wasm-threads.md
Labels: cla: yes
