Repository google/WebFundamentals, pull requests merged in 2019-01, with the labels that each got.

#7050 Guide to serving cached A/V content using Workbox
  src/content/en/tools/workbox/guides/advanced-recipes.md
Labels: cla: yes

#7055 Update 203 show listing
  src/content/en/shows/_book.yaml
  src/content/en/shows/http203/index.md
Labels: cla: yes

#7066 Fix incorrect tag name.
  src/content/en/updates/2018/12/chrome-72-deps-rems.md
Labels: cla: yes

#7065 Improved common-typos file
  src/data/common-typos.yaml
Labels: cla: yes

#7058 #7048 | Fix Samsung link
  src/content/en/fundamentals/app-install-banners/_a2hs-criteria.html
Labels: cla: yes

#7044 Fix Bundled HTTP Exchanges 404
  src/content/en/fundamentals/primers/modules.md
Labels: cla: yes

#7038 #7037 | Fix typo
  src/content/en/tools/chrome-devtools/evaluate-performance/index.md
Labels: cla: yes

#7028 #4100 | Fix Polymer links
  src/content/en/updates/2014/01/Yo-Polymer-A-Whirlwind-Tour-Of-Web-Component-Tooling.md
Labels: cla: yes

#7015 feature-policy: update moved spec.
  src/content/en/updates/2018/06/feature-policy.md
Labels: cla: yes

#7026 [Translate it] Fixed typo: ditto instead of dito (finger)
  src/content/it/fundamentals/performance/rendering/index.md
Labels: cla: yes

#7069 Tweaks TOC for HTTP203 podcasts/videos
  src/content/en/shows/_book.yaml
  src/content/en/shows/http203/_toc.yaml
Labels: P1, cla: yes, type-Infrastructure

#7089 Add profile for Thomas Steiner
  src/content/en/images/contributors/thomassteiner.jpg
  src/data/_contributors.yaml
Labels: cla: yes

#7074 #7060 | Grammar fix
  src/content/en/updates/2018/09/inside-browser-part4.md
Labels: cla: yes

#7053 Update web agencies JSON
  src/content/en/agencies/data/agencies.json
  src/content/en/agencies/images/asial.png
  src/content/en/agencies/images/elephants_can_dance.png
  src/content/en/agencies/images/gimc_chance.png
  src/content/en/agencies/images/iret.png
  src/content/en/agencies/images/lunar_works.png
Labels: P2, cla: yes, section-agencies

#7014 fix #6959
  gulp-tasks/tests/projectYaml.js
  src/content/en/_project.yaml
Labels: P2, cla: yes, content-new, type-Content

#7090 Case fixes from dlazin
  src/content/en/progressive-web-apps/_index.yaml
  src/content/en/tools/_index.yaml
Labels: cla: yes

#7107 Fixing DevSite build break
  src/content/en/updates/2015/10/devtools-digest-efficient-element-edits.md
  src/content/en/updates/2015/10/devtools-digest-reordering-tabs.md
  src/content/en/updates/2017/09/sticky-headers.md
  src/content/en/updates/2017/11/overscroll-behavior.md
  src/content/en/updates/2017/12/nic63.md
Labels: cla: yes

#7092 Update ResizeObserver to note shipping.
  src/content/en/updates/2016/10/resizeobserver.md
Labels: cla: yes

#7099 User Activation v2 article.
  src/content/en/updates/2019/01/user-activation.md
  src/data/_contributors.yaml
  src/data/commonTags.json
Labels: cla: yes

#7094 August 2011 link updates
  src/content/en/updates/2011/08/Debugging-the-Filesystem-API.md
  src/content/en/updates/2011/08/Downloading-resources-in-HTML5-a-download.md
  src/content/en/updates/2011/08/Saving-generated-files-on-the-client-side.md
  src/content/en/updates/2011/08/Seek-into-local-files-with-the-File-System-API.md
  src/content/en/updates/2011/08/What-s-different-in-the-new-WebSocket-protocol.md
  src/content/en/updates/2011/08/insertAdjacentHTML-Everywhere.md
Labels: cla: yes

#7100 update-resources.sh uses more idiomatic bash
  tools/update-resources.sh
Labels: cla: yes

#7102 September 2011 link updates
  src/content/en/updates/2011/09/7-minute-videos-Javascript-Console-Protips-newish-DOM-APIs.md
  src/content/en/updates/2011/09/New-Game-Conference-for-HTML5-Game-Developers-Coupon.md
  src/content/en/updates/2011/09/Workers-ArrayBuffer.md
Labels: cla: yes

#7097 Shape Detection API post
  src/content/en/updates/2019/01/shape-detection.md
  src/content/en/updates/_book.yaml
  src/data/commonTags.json
Labels: cla: yes, content-new, proj-fugu, section-updates, type-Content

#7114 Add article about Emscripten and npm
  src/content/en/updates/2019/01/emscripten-npm.md
  src/content/en/updates/images/2019/01/emscripten-npm/helloworld.png
  src/content/en/updates/images/2019/01/emscripten-npm/libvpx.png
  src/content/en/updates/images/generic/webassembly.png
Labels: cla: yes

#7130 [devtools] add wndt73
  src/content/en/tools/chrome-devtools/images/shared/export.png
  src/content/en/tools/chrome-devtools/images/shared/inspect.png
  src/content/en/tools/chrome-devtools/images/shared/reload.png
  src/content/en/updates/2019/01/devtools.md
  src/content/en/updates/images/2019/01/AAA.png
  src/content/en/updates/images/2019/01/add-logpoint.png
  src/content/en/updates/images/2019/01/breakpoint-editor.png
  src/content/en/updates/images/2019/01/command-menu.png
  src/content/en/updates/images/2019/01/coverage.png
  src/content/en/updates/images/2019/01/custom-geolocation.png
  src/content/en/updates/images/2019/01/focus1.png
  src/content/en/updates/images/2019/01/focus2.png
  src/content/en/updates/images/2019/01/focus3.png
  src/content/en/updates/images/2019/01/focus4.png
  src/content/en/updates/images/2019/01/fold.png
  src/content/en/updates/images/2019/01/folding.png
  src/content/en/updates/images/2019/01/geolocations.png
  src/content/en/updates/images/2019/01/inspect.png
  src/content/en/updates/images/2019/01/load-coverage.png
  src/content/en/updates/images/2019/01/logpoint-badge.png
  src/content/en/updates/images/2019/01/logpoint-expression.png
  src/content/en/updates/images/2019/01/logpoint-result.png
  src/content/en/updates/images/2019/01/messages.png
  src/content/en/updates/images/2019/01/sensors.png
  src/content/en/updates/images/2019/01/show-coverage.png
Labels: P1, cla: yes, content-new, section-updates, type-Content

#7135 fix description and featured snippet
  src/content/en/updates/2019/01/devtools.md
Labels: P2, cla: yes, content-updated, section-updates, type-Content

#7131 #7104 | Grammar update
  src/content/en/fundamentals/security/csp/index.md
Labels: cla: yes

#7140 Sync #inspect with latest UI
  src/content/en/updates/2019/01/devtools.md
Labels: P1, cla: yes, content-updated, section-updates, type-Content

#7146 fix typo
  src/content/en/fundamentals/native-hardware/build-for-webusb/index.md
Labels: cla: yes

#7136 December 2011 link updates
  src/content/en/updates/2011/12/CSS-Filter-Effects-Landing-in-WebKit.md
  src/content/en/updates/2011/12/Transferable-Objects-Lightning-Fast.md
  src/content/en/updates/2011/12/Use-mediump-precision-in-WebGL-when-possible.md
Labels: cla: yes

#7134 November 2011 link updates
  src/content/en/updates/2011/11/Chrome-Developer-Tools-for-Speed.md
  src/content/en/updates/2011/11/Quota-Management-API-Fast-Facts.md
  src/content/en/updates/2011/11/WebGL-demo-roundup.md
Labels: cla: yes

#7133 October 2011 link updates
  src/content/en/updates/2011/10/App-Cache-Tools-and-Auto-Generators.md
  src/content/en/updates/2011/10/Defining-Scope-In-IndexedDB-Transactions.md
  src/content/en/updates/2011/10/Having-a-ride-with-Three-js.md
  src/content/en/updates/2011/10/Keeping-up-with-HTML5-and-browser-support.md
  src/content/en/updates/2011/10/Let-Your-Content-Do-the-Talking-Fullscreen-API.md
  src/content/en/updates/2011/10/Spooktacular-HTML5-Pumpkin.md
  src/content/en/updates/2011/10/WebSockets-updated-to-latest-version-in-Chrome-Canary.md
Labels: cla: yes

#7126 Fix minor typo
  src/content/ko/fundamentals/security/encrypt-in-transit/why-https.md
Labels: cla: yes

#7125 Fixes link for "Inside look at modern web browser Part 3"
  src/content/en/updates/2018/09/inside-browser-part3.md
Labels: cla: yes

#7162 add video
  src/content/en/updates/2018/11/devtools.md
Labels: P1, cla: yes, content-updated, section-updates, type-Content

#7159 Add shape detection to capabilities page
  src/content/en/updates/capabilities.md
Labels: cla: yes, content-updated, proj-fugu, section-updates

#7147 ignore index.yaml
  .gitignore
Labels: P3, cla: yes, type-Infrastructure

#7167 fix typos
  src/content/en/updates/2011/11/Quota-Management-API-Fast-Facts.md
  src/content/en/updates/2011/12/Transferable-Objects-Lightning-Fast.md
Labels: cla: yes

#7168 New in Chrome 72 post
  src/content/en/updates/2019/01/nic72.md
  src/content/en/updates/_redirects.yaml
  src/content/en/updates/images/2019/01/user-activation.png
Labels: cla: yes, content-new, section-updates

#7160 Tweaks to capabilities landing page
  src/content/en/updates/capabilities.md
  src/content/en/updates/images/misc/capabilities-process.jpg
Labels: content-updated, proj-fugu, section-updates

#7158 Update Badging post with OT info for Cr73
  src/content/en/updates/2018/12/badging-api.md
  src/content/en/updates/capabilities.md
  src/content/en/updates/images/2018/12/badges-on-windows.jpg
Labels: cla: yes, content-updated, proj-fugu, section-updates, type-Content

#7163 Add lighthouse platform packs article
  src/content/en/images/contributors/housseindjirdeh.jpg
  src/content/en/updates/2019/01/lighthouse-platform-packs.md
  src/content/en/updates/images/2019/01/lighthouse-platform-packs/audit-with-wordpress-description.png
  src/content/en/updates/images/2019/01/lighthouse-platform-packs/lighthouse.png
  src/data/_contributors.yaml
Labels: cla: yes, section-updates, type-Content

#7179 [devtools] disable javascript guide (fix #7178)
  src/content/en/tools/chrome-devtools/_toc.yaml
  src/content/en/tools/chrome-devtools/javascript/disable.md
  src/content/en/tools/chrome-devtools/javascript/imgs/disable-javascript.png
  src/content/en/tools/chrome-devtools/javascript/imgs/disabled-javascript-warning.png
  src/content/en/tools/chrome-devtools/javascript/reference.md
Labels: P1, cla: yes, content-new, section-tools, type-Content
