Repository google/WebFundamentals, pull requests merged in 2019-11, with the labels that each got.

#8267 Updated workbox demos to glitch (v5, new content)
  src/content/en/tools/workbox/modules/_index.yaml
Labels: cla: yes

#8291 Replace getQueue() with defaultQueue in Web GPU article
  src/content/en/updates/2019/08/get-started-with-gpu-compute-on-the-web.md
Labels: cla: yes

#8293 update images and and content for tools/lighthouse page
  src/content/en/tools/lighthouse/images/audits.png
  src/content/en/tools/lighthouse/images/cdt-report.png
  src/content/en/tools/lighthouse/images/extension.png
  src/content/en/tools/lighthouse/images/lh_favicon_32px.png
  src/content/en/tools/lighthouse/images/lighthouse-icon-16.png
  src/content/en/tools/lighthouse/images/lighthouse-logo.svg
  src/content/en/tools/lighthouse/images/menu.png
  src/content/en/tools/lighthouse/images/report.png
  src/content/en/tools/lighthouse/images/share.png
  src/content/en/tools/lighthouse/images/viewer.png
  src/content/en/tools/lighthouse/index.md
Labels: cla: yes, type-Content

#8262 Update synchronous XHR notice.
  src/content/en/updates/2012/01/Getting-Rid-of-Synchronous-XHRs.md
Labels: cla: yes, content-updated

#8296 Popups on page unload didn't actuall go out.
  src/content/en/updates/2019/03/chrome-74-deps-rems.md
Labels: cla: yes

#8298 Fix XHR notice.
  src/content/en/updates/2012/01/Getting-Rid-of-Synchronous-XHRs.md
Labels: cla: yes

#8303 Change the CDS banner
  src/content/en/_project.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/site-kit/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes

#8302 Fugu redirects to web.dev
  src/content/en/updates/2016/09/navigator-share.md
  src/content/en/updates/2018/12/web-share-target.md
  src/content/en/updates/2019/05/web-share-files.md
  src/content/en/updates/2019/08/periodic-background-sync.md
  src/content/en/updates/_redirects.yaml
  src/content/en/updates/capabilities.md
Labels: cla: yes

#8292 deleted doubled paragraph
  src/content/de/fundamentals/media/video.md
Labels: cla: yes

#8290 Update CDS landing page with 2016–2019 links
  src/content/en/shows/cds/index.md
Labels: cla: yes

#8285 fix typo (reciver -> receiver)
  src/content/en/updates/2019/10/nic78.md
Labels: cla: yes

#8283 Update nic78.md
  src/content/en/updates/2019/10/nic78.md
Labels: cla: yes

#8278 Updated to include descriptions of new features
  src/content/en/tools/lighthouse/index.md
Labels: cla: yes

#8277 Fix spelling errors on Chromium Chronicle 7
  src/content/en/updates/2019/10/chromium-chronicle-7.md
Labels: cla: yes

#8269 Remove outdated links
  src/content/en/fundamentals/design-and-ux/responsive/patterns.md
Labels: cla: yes

#8257 Fixes to The Chromium Chronicle Episode 7
  src/content/en/updates/2019/10/chromium-chronicle-7.md
Labels: cla: yes

#8305 Redirect Web Serial codelab
  src/content/en/fundamentals/_redirects.yaml
  src/content/en/fundamentals/codelabs/_index.yaml
  src/content/en/fundamentals/codelabs/web-serial/img/15e2df0064b5de28.png
  src/content/en/fundamentals/codelabs/web-serial/img/67543f4caaaca5de.png
  src/content/en/fundamentals/codelabs/web-serial/img/cd1d0a764bcb2e8f.png
  src/content/en/fundamentals/codelabs/web-serial/img/dd52b5c37fc4b393.png
  src/content/en/fundamentals/codelabs/web-serial/img/e695daf2277cd3a2.png
  src/content/en/fundamentals/codelabs/web-serial/img/eead3553d29ee581.png
  src/content/en/fundamentals/codelabs/web-serial/index.md
  src/data/codelabs/web-serial/codelab.json
Labels: cla: yes

#8270 Update Jekyll naming
  src/content/en/updates/2019/02/rendering-on-the-web.md
Labels: cla: yes

#8306 Hide CDS hero video
  src/content/en/_index.yaml
Labels: cla: yes

#8301 Cr Chron 8
  src/content/en/updates/2019/11/chromium-chronicle-8.md
  src/content/en/updates/images/2019/11/cr-chron/img1.png
  src/content/en/updates/images/2019/11/cr-chron/img2.png
Labels: cla: yes
