Repository google/WebFundamentals, pull requests merged in 2019-02, with the labels that each got.

#7177 Updates scope docs in web app manifest
  src/content/en/fundamentals/web-app-manifest/index.md
Labels: cla: yes, content-updated, section-fundamentals, type-Content

#7175 Add RTCQuicTransport origin trial article
  src/content/en/updates/2019/01/rtcquictransport-api.md
  src/content/en/updates/images/2019/01/rtcquictransport/rtcquictransport-overview.png
  src/content/en/updates/images/2019/01/rtcquictransport/rtcquictransport-setup.png
  src/data/_contributors.yaml
  src/data/commonTags.json
Labels: cla: yes

#7180 Update _contributors.yaml
  src/data/_contributors.yaml
Labels: cla: yes

#7187 Changes naming from platform packs to stack packs in updates/ article
  src/content/en/updates/2019/01/lighthouse-platform-packs.md
  src/content/en/updates/images/2019/01/lighthouse-platform-packs/audit.png
Labels: cla: yes, section-updates, type-Content

#7192 Fix typo
  src/content/en/tools/chrome-devtools/javascript/disable.md
Labels: cla: yes

#7189 Add Chrome version number in #SmooshGate write-up
  src/content/en/updates/2018/03/smooshgate.md
Labels: cla: yes

#7190 March 2012 link updates
  src/content/en/updates/2012/03/A-New-Experimental-Feature-style-scoped.md
  src/content/en/updates/2012/03/CSS-layout-gets-smarter-with-calc.md
  src/content/en/updates/2012/03/Optimizing-JavaScript.md
Labels: cla: yes

#7188 February 2012 link updates
  src/content/en/updates/2012/02/Chrome-for-Android-Accelerating-the-Mobile-Web.md
  src/content/en/updates/2012/02/Detect-DOM-changes-with-Mutation-Observers.md
  src/content/en/updates/2012/02/Getting-Gmail-to-handle-all-mailto-links-with-registerProtocolHandler.md
  src/content/en/updates/2012/02/HTML5-audio-and-the-Web-Audio-API-are-BFFs.md
  src/content/en/updates/2012/02/Pointer-Lock-API-Brings-FPS-Games-to-the-Browser.md
  src/content/en/updates/2012/02/SwiftShader-brings-software-3D-rendering-to-Chrome.md
  src/content/en/updates/2012/02/WebGL-and-Web-Audio-API-demo-roundup.md
Labels: cla: yes

#7200 LitElement & lit-html release update
  src/content/en/images/contributors/justinfagnani.jpg
  src/content/en/updates/2019/02/lit-element-and-lit-html.md
  src/content/en/updates/images/2019/02/lit-element.jpg
  src/data/_contributors.yaml
  src/data/commonTags.json
Labels: P1, cla: yes, content-new, section-updates, type-Content

#7201 Updates article about Using TWAs
  src/content/en/updates/2017/10/using-twa.md
Labels: cla: yes

#7176 Remove 'certified' and widen scope
  src/content/en/agencies/_index.yaml
Labels: cla: yes, content-updated, section-agencies, type-Content

#7206 Tweak image for badging
  src/content/en/updates/images/2018/12/badges-on-windows.jpg
Labels: cla: yes, content-updated, proj-fugu, type-Content

#7185 January 2012 link updates
  src/content/en/updates/2012/01/Getting-Rid-of-Synchronous-XHRs.md
  src/content/en/updates/2012/01/Introducing-Video-Player-Sample.md
  src/content/en/updates/2012/01/Web-Audio-FAQ.md
Labels: cla: yes

#7116 Fix typos
  src/content/en/tools/puppeteer/articles/ssr.md
  src/content/en/updates/2011/07/Announcing-New-Game-the-conference-for-HTML5-game-developers.md
  src/content/en/updates/2011/07/Don-t-Miss-a-Frame-Using-the-Page-Visibility-API-HTML5-Video.md
  src/content/en/updates/2011/07/HTML5-Libraries-polyfills-Mid-July.md
  src/content/en/updates/2011/07/Multiplayer-Audio-Fun.md
  src/content/en/updates/2011/07/Using-Cross-domain-images-in-WebGL.md
  src/content/en/updates/2011/08/Debugging-the-Filesystem-API.md
  src/content/en/updates/2011/08/Downloading-resources-in-HTML5-a-download.md
  src/content/en/updates/2011/08/Saving-generated-files-on-the-client-side.md
  src/content/en/updates/2011/08/Seek-into-local-files-with-the-File-System-API.md
  src/content/en/updates/2011/08/What-s-different-in-the-new-WebSocket-protocol.md
  src/content/en/updates/2011/08/insertAdjacentHTML-Everywhere.md
  src/content/en/updates/2011/09/7-minute-videos-Javascript-Console-Protips-newish-DOM-APIs.md
  src/content/en/updates/2011/09/New-Game-Conference-for-HTML5-Game-Developers-Coupon.md
  src/content/en/updates/2011/09/Workers-ArrayBuffer.md
  src/content/en/updates/2011/11/Quota-Management-API-Fast-Facts.md
  src/content/en/updates/2011/12/Transferable-Objects-Lightning-Fast.md
  src/content/en/updates/2012/01/Getting-Rid-of-Synchronous-XHRs.md
  src/content/en/updates/2012/01/Web-Audio-FAQ.md
  src/content/en/updates/2012/04/Big-boost-to-DOM-performance-WebKit-s-innerHTML-is-240-faster.md
  src/content/en/updates/2012/05/Websocket-Frame-Inspection-now-in-Chrome-DevTools.md
  src/content/en/updates/2012/12/Canvas-driven-background-images.md
  src/content/en/updates/2012/12/WebRTC-hits-Firefox-Android-and-iOS.md
  src/content/en/updates/2013/12/300ms-tap-delay-gone-away.md
  src/content/en/updates/2013/12/The-Yeoman-Monthly-Digest-2.md
  src/content/en/updates/2014/02/The-Yeoman-Monthly-Digest-3.md
  src/content/en/updates/2014/12/web-animation-playback.md
  src/content/en/updates/2015/04/DOM-attributes-now-on-the-prototype-chain.md
  src/content/en/updates/2015/07/measuring-performance-in-a-service-worker.md
  src/content/en/updates/2015/07/rotationAngle-and-touchRadius.md
  src/content/en/updates/2015/08/using-poster-images-on-plugin-content.md
  src/content/en/updates/2015/11/app-shell.md
  src/content/en/updates/2016/04/devtools-digest-command-menu.md
  src/content/en/updates/2016/04/keyboardevent-keys-codes.md
  src/content/en/updates/2016/05/houdini.md
  src/content/en/updates/2016/06/devtools-digest.md
  src/content/en/updates/2016/09/broadcastchannel.md
  src/content/en/updates/2016/10/resizeobserver.md
  src/content/en/updates/2016/12/devtools-javascript-cpu-profile-migration.md
  src/content/en/updates/2017/03/custom-scrollbar.md
  src/content/en/updates/2019/01/emscripten-npm.md
Labels: cla: yes

#7142 Add examples to User Activation v2 article.
  src/content/en/updates/2019/01/user-activation.md
Labels: cla: yes, content-updated

#7207 Minor updates to TWA docs
  src/content/en/updates/2017/10/using-twa.md
Labels: cla: yes

#7210 Rendering on the web
  src/content/en/updates/2019/02/rendering-on-the-web.md
  src/content/en/updates/images/2019/02/rendering-on-the-web/client-rendering-tti.png
  src/content/en/updates/images/2019/02/rendering-on-the-web/html.png
  src/content/en/updates/images/2019/02/rendering-on-the-web/icon.png
  src/content/en/updates/images/2019/02/rendering-on-the-web/infographic.png
  src/content/en/updates/images/2019/02/rendering-on-the-web/rehydration-tti.png
  src/content/en/updates/images/2019/02/rendering-on-the-web/server-rendering-tti.png
  src/content/en/updates/images/2019/02/rendering-on-the-web/static-rendering-tti.png
  src/content/en/updates/images/2019/02/rendering-on-the-web/trisomorphic.png
Labels: cla: yes, content-new, section-updates, type-Content

#7170 Fix small things in sources.md
  src/content/en/tools/chrome-devtools/sources.md
Labels: cla: yes

#7205 Add "Audio/Video Updates in Chrome 73" article
  src/content/en/updates/2018/08/chrome-69-media-updates.md
  src/content/en/updates/2019/02/chrome-73-media-updates.md
  src/content/en/updates/images/2019/02/media-keys.jpg
  src/content/en/updates/images/2019/02/skip-ad.png
Labels: cla: yes, content-new, section-updates, type-Content

#7216 Move TWA article to 2019
  src/content/en/updates/2019/02/using-twa.md
  src/content/en/updates/_redirects.yaml
Labels: cla: yes, content-updated, section-updates

#7215 rendering-on-the-web: longer description
  src/content/en/updates/2019/02/rendering-on-the-web.md
Labels: cla: yes, content-updated, section-updates, type-Content

#7184 Add model-viewer article.
  src/content/en/updates/2019/02/model-viewer.md
  src/content/en/updates/images/2019/02/responsive-space-suit.png
  src/content/en/updates/images/2019/02/space-suit.png
Labels: cla: yes

#7196 Deprecations and Removals, Chrome 73
  src/content/en/updates/2019/02/chrome-73-deps-rems.md
Labels: cla: yes

#7171 Add matchAll() article.
  src/content/en/updates/2019/02/string-matchall.md
Labels: cla: yes

#7204 Add a translation into Russian for updates/2018/12/class-fields
  src/content/ru/updates/2018/12/class-fields.md
Labels: cla: yes

#7221 Remove seek actions from Chrome 73 media updates article
  src/content/en/updates/2019/02/chrome-73-media-updates.md
Labels: cla: yes

#7226 Rendering web seo tweaks
  src/content/en/updates/2019/02/rendering-on-the-web.md
  src/content/en/updates/images/2019/02/rendering-on-the-web/mobile-friendly-test.png
Labels: cla: yes

#7227 [devtools] new network tutorial
  src/content/en/tools/chrome-devtools/images/shared/add.png
  src/content/en/tools/chrome-devtools/images/shared/filter.png
  src/content/en/tools/chrome-devtools/images/shared/format.png
  src/content/en/tools/chrome-devtools/images/shared/screenshots.png
  src/content/en/tools/chrome-devtools/images/shared/search.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/addblock.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/allscreenshots.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/block.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/blockedstyles.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/cache.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/commandmenu.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/console.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/css.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/cssjs.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/demo.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/docked.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/domain.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/filters.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/firstscreenshot.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/hardreload.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/headers.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/log.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/negative.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/network.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/png.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/preview.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/property.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/regex.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/response.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/results.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/runtime.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/search.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/slow3g.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/throttling.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/timing.png
  src/content/en/tools/chrome-devtools/network-performance/imgs/tutorial/windows.png
  src/content/en/tools/chrome-devtools/network-performance/index.md
Labels: P1, cla: yes, content-updated, section-tools, type-Content

#7223 fix typo
  src/content/en/updates/2019/02/chrome-73-media-updates.md
Labels: cla: yes

#7222 Update rendering on the web: add note on SEO
  src/content/en/updates/2019/02/rendering-on-the-web.md
  src/content/en/updates/images/2019/02/rendering-on-the-web/mobile-friendly-test.png
Labels: cla: yes

#7242 Corrections from Twitter
  src/content/en/updates/2019/02/rendering-on-the-web.md
Labels: cla: yes, content-updated, section-updates, type-Content

#7244 Typo fixes in Lighthouse scoring docs
  src/content/en/tools/lighthouse/scoring.md
  src/content/en/tools/lighthouse/v3/scoring.md
Labels: cla: yes

#7232 Construct Stylesheets
  src/content/en/updates/2019/02/constructable-stylesheets.md
  src/content/en/updates/images/2019/02/constructable-stylesheets/demo.mp4
  src/content/en/updates/images/2019/02/constructable-stylesheets/overview.png
Labels: cla: yes, content-new, section-updates, type-Content

#7240 June 2012 updates
  src/content/en/updates/2012/06/Don-t-Build-Blobs-Construct-Them.md
  src/content/en/updates/2012/06/How-to-convert-ArrayBuffer-to-and-from-String.md
  src/content/en/updates/2012/06/The-amazing-powers-of-CSS.md
Labels: cla: yes

#7239 May 2012 updates
  src/content/en/updates/2012/05/Websocket-Frame-Inspection-now-in-Chrome-DevTools.md
  src/content/en/updates/2012/05/requestAnimationFrame-API-now-with-sub-millisecond-precision.md
Labels: cla: yes

#7238 April 2012 updates
  src/content/en/updates/2012/04/Processing-XHR2-file-uploads-in-PHP.md
  src/content/en/updates/2012/04/Round-up-of-Web-Browser-Internals-Resources.md
  src/content/en/updates/2012/04/Taking-an-Entire-Page-Offline-using-the-HTML5-FileSystem-API.md
  src/content/en/updates/2012/04/WebRTC-Protothon.md
  src/content/en/updates/2012/04/datalist-landed-in-Chrome-Canary.md
Labels: cla: yes

#7236 #7233 | Fix broken link
  src/content/en/tools/chrome-devtools/network/index.md
Labels: cla: yes

#7235 #7234 | Fix typos
  src/content/en/updates/2018/09/inside-browser-part3.md
Labels: cla: yes

#7230 Updated A2HS docs
  src/content/en/fundamentals/app-install-banners/_a2hs-criteria.html
  src/content/en/fundamentals/app-install-banners/_mini-info-bar.md
  src/content/en/fundamentals/app-install-banners/index.md
  src/content/en/fundamentals/app-install-banners/native.md
Labels: cla: yes, content-updated, section-fundamentals, type-Content

#7224 Remove g+ links from contributors
  gulp-tasks/tests/contributorsYaml.js
  src/data/_contributors.yaml
  src/templates/contributors/article-list.md
  src/templates/contributors/index.md
Labels: cla: yes, type-Infrastructure

#7246 Constructable Stylesheets: remove extra newline in code sample
  src/content/en/updates/2019/02/constructable-stylesheets.md
Labels: cla: yes

#7248 update the feedback widget to get more information
  src/content/en/_shared/helpful.html
Labels: P1, cla: yes, content-updated, type-Content, type-Infrastructure

#7251 Trivial typo fix: add missing "of"
  src/content/en/tools/workbox/modules/workbox-google-analytics.md
Labels: cla: yes

#7252 Fix typos and other errors in mv article.
  src/content/en/updates/2019/02/model-viewer.md
Labels: cla: yes

#7259 fix #7257
  src/content/en/tools/chrome-devtools/images/shared/close.png
  src/content/en/tools/chrome-devtools/network/imgs/tutorial/close-buttons.png
  src/content/en/tools/chrome-devtools/network/imgs/tutorial/close-timing.png
  src/content/en/tools/chrome-devtools/network/index.md
Labels: P2, cla: yes, content-updated, section-tools, type-Content

#7241 Add hot path with WebAssembly article
  src/content/en/updates/2019/02/hotpath-with-wasm.md
  src/content/en/updates/images/2019/02/hotpath-with-wasm/poster.png
  src/content/en/updates/images/2019/02/hotpath-with-wasm/scatter.svg
  src/content/en/updates/images/2019/02/hotpath-with-wasm/social.png
  src/content/en/updates/images/2019/02/hotpath-with-wasm/speed-per-browser.svg
  src/content/en/updates/images/2019/02/hotpath-with-wasm/speed-per-lang.svg
  src/content/en/updates/images/2019/02/hotpath-with-wasm/twiggy.png
Labels: cla: yes

#7254 "Updating the WebAPK" updates
  src/content/en/fundamentals/integration/webapks.md
Labels: cla: yes

#7253 Fixes link for Add to Home Screen criteria
  src/content/en/updates/2019/02/using-twa.md
Labels: cla: yes

#7247 Constructable Stylesheets: fix img alt
  src/content/en/updates/2019/02/constructable-stylesheets.md
Labels: cla: yes, content-updated, section-updates, type-Content

#7263 Floating point fix
  src/content/en/fundamentals/design-and-ux/responsive/_code/mostly-fluid.html
Labels: cla: yes

#7264 Turn off experiments temporarily
  src/content/en/updates/2018/04/devtools.md
  src/content/en/updates/2018/05/devtools.md
  src/content/en/updates/2018/08/devtools.md
Labels: cla: yes

#7250 PiP shipped in Chrome OS 72
  src/content/en/updates/2018/10/watch-video-using-picture-in-picture.md
Labels: cla: yes

#7267 Hotpath wasm article fixes
  src/content/en/updates/2019/02/hotpath-with-wasm.md
Labels: cla: yes

#7261 Priority Hints article
  package.json
  src/content/en/images/contributors/yoavweiss.jpg
  src/content/en/updates/2019/02/priority-hints.md
  src/content/en/updates/images/2019/02/priority-hints/image1.png
  src/content/en/updates/images/2019/02/priority-hints/image2.png
  src/content/en/updates/images/2019/02/priority-hints/image3.png
  src/content/en/updates/images/2019/02/priority-hints/image4.png
  src/data/_contributors.yaml
Labels: cla: yes

#7245 Add IntersectionObserver v2 article
  src/content/en/updates/2019/02/intersectionobserver-v2.md
  src/content/en/updates/images/2019/02/intersectionobserver-v2.png
  src/content/en/updates/images/2019/02/trick-ad-click.png
Labels: cla: yes, content-new

#7268 Eliminate new line from description
  src/content/en/updates/2019/02/priority-hints.md
Labels: cla: yes

#7270 Trusted types introductory article
  src/content/en/images/contributors/koto.jpg
  src/content/en/updates/2019/02/trusted-types.md
  src/data/_contributors.yaml
  src/data/commonTags.json
Labels: cla: yes

#7272 Typo fix.
  src/data/_contributors.yaml
Labels: cla: yes

#7266 Translation for Nikkei article
  src/content/ja/showcase/2018/nikkei.md
Labels: cla: no

#7283 Typo
  src/content/en/updates/2019/02/rendering-on-the-web.md
Labels: cla: yes

#7265 Add back/forward cache brief updates post
  src/content/en/updates/2019/02/back-forward-cache.md
Labels: cla: yes

#7290 fix typo
  src/content/en/updates/2019/02/priority-hints.md
Labels: cla: yes

#7258 Use srcObject instead of createObjectURL for audio recording example
  src/content/en/fundamentals/media/recording-audio/index.md
Labels: cla: yes

#7292 New podcast
  src/content/en/shows/http203/podcast/rotating-an-image-to-the-extreme.md
Labels: cla: yes, type-Content

#7273 Fix character entity.
  src/content/en/updates/2019/02/model-viewer.md
Labels: cla: yes

#7286 Update Shape Detection API article
  src/content/en/updates/2019/01/shape-detection.md
  src/content/en/updates/capabilities.md
Labels: cla: yes, content-updated

#7293 Update manifest docs - with support for minimal-ui
  src/content/en/fundamentals/web-app-manifest/index.md
Labels: cla: yes

#7294 Remove watch CDS banner
  src/content/en/_project.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes

#7295 July 2012 link updates
  src/content/en/updates/2012/07/Arrived-xhr-send-ArrayBufferView.md
  src/content/en/updates/2012/07/Drag-and-drop-a-folder-onto-Chrome-now-available.md
  src/content/en/updates/2012/07/How-to-measure-browser-graphics-performance.md
  src/content/en/updates/2012/07/Taking-advantage-of-GPU-acceleration-in-the-2D-canvas.md
  src/content/en/updates/2012/07/Writing-a-flippable-book-using-CSS-Regions-and-3D-transforms.md
Labels: cla: yes

#7296 Typo fix
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/index.md
Labels: cla: yes

#7297 August 2012 link updates
  src/content/en/updates/2012/08/Integrating-input-type-file-with-the-Filesystem-API.md
  src/content/en/updates/2012/08/Quick-FAQs-on-input-type-date-in-Google-Chrome.md
  src/content/en/updates/2012/08/Stick-your-landings-position-sticky-lands-in-WebKit.md
  src/content/en/updates/2012/08/When-milliseconds-are-not-enough-performance-now.md
  src/content/en/updates/2012/08/datalist-for-range-color-inputs-offer-some-default-choices.md
Labels: cla: yes

#7300 lol wrong year
  src/content/en/shows/http203/podcast/rotating-an-image-to-the-extreme.md
Labels: cla: yes

#7301 Update Shape Detection OT info
  src/content/en/updates/2019/01/shape-detection.md
Labels: cla: yes, content-updated

#7275 Fixes #7191: Fixed Typo
  src/content/en/tools/chrome-devtools/javascript/breakpoints.md
Labels: cla: yes

#7305 Fix capitalization
  src/content/en/fundamentals/performance/prpl-pattern/index.md
Labels: cla: yes

#6877 #4099 | Fix Yeoman links
  src/content/en/updates/2014/02/The-Yeoman-Monthly-Digest-3.md
Labels: cla: yes

#7310 Fix a typo in the bug link for Media Keys.
  src/content/en/updates/2019/02/chrome-73-media-updates.md
Labels: cla: yes

#7307 7302 | Fixes busted internal links
  src/content/en/fundamentals/payments/basics/how-payment-ecosystem-works.md
  src/content/en/fundamentals/payments/basics/payment-method-basics.md
Labels: cla: yes

#7298 New social image
  src/content/en/images/social-webfu-16x9.png
Labels: cla: yes

#7249 Fixed links on audit home page
  src/content/en/fundamentals/performance/audit/index.md
Labels: cla: yes

#7312 Removes Google+ links from WebFu
  src/content/en/fundamentals/discovery/social-discovery/index.md
  src/content/en/fundamentals/security/encrypt-in-transit/enable-https.md
  src/content/en/shows/polycasts/season-2/AskPolymer_PC27.md
  src/content/en/shows/polycasts/season-2/AskPolymer_PC29.md
  src/content/en/shows/polycasts/season-2/Behaviors.md
  src/content/en/shows/polycasts/season-2/Data_Binding_101.md
  src/content/en/shows/polycasts/season-2/Iron-Iconsets.md
  src/content/en/shows/polycasts/season-2/WebAnimations.md
  src/content/en/shows/polycasts/season-2/binding-to-objects.md
  src/content/en/shows/polycasts/season-2/create-reusable-elements.md
  src/content/en/shows/polycasts/season-2/give-your-element-an-API.md
  src/content/en/shows/polycasts/season-2/go-offline.md
  src/content/en/shows/polycasts/season-2/iron-ajax.md
  src/content/en/shows/polycasts/season-2/neon-animated-pages.md
  src/content/en/shows/polycasts/season-2/polymer-starter-kit.md
  src/content/en/shows/polycasts/season-2/theming-elements.md
  src/content/en/shows/ttt/series-2/windows-commandline.md
  src/content/en/updates/2011/10/Spooktacular-HTML5-Pumpkin.md
  src/content/en/updates/2012/04/WebRTC-Protothon.md
  src/content/en/updates/2012/08/Quick-FAQs-on-input-type-date-in-Google-Chrome.md
  src/content/en/updates/2013/11/The-Yeoman-Monthly-Digest-1.md
  src/content/en/updates/2013/12/The-Yeoman-Monthly-Digest-2.md
  src/content/en/updates/2014/02/The-Yeoman-Monthly-Digest-3.md
  src/content/en/updates/2015/01/What-the-Viewport.md
  src/content/en/updates/2015/03/creating-semantic-sites-with-web-components-and-jsonld.md
  src/content/en/updates/2015/07/interact-with-ble-devices-on-the-web.md
  src/content/en/updates/2017/01/nic56.md
  src/content/es/fundamentals/discovery/social-discovery/index.md
  src/content/es/fundamentals/security/encrypt-in-transit/enable-https.md
  src/content/id/fundamentals/discovery/social-discovery/index.md
  src/content/id/fundamentals/security/encrypt-in-transit/enable-https.md
  src/content/ja/fundamentals/discovery/social-discovery/index.md
  src/content/ja/fundamentals/security/encrypt-in-transit/enable-https.md
  src/content/ko/fundamentals/discovery/social-discovery/index.md
  src/content/ko/fundamentals/security/encrypt-in-transit/enable-https.md
  src/content/nl/fundamentals/discovery/social-discovery/index.md
  src/content/pt-br/fundamentals/discovery/social-discovery/index.md
  src/content/pt-br/fundamentals/security/encrypt-in-transit/enable-https.md
  src/content/zh-cn/fundamentals/discovery/social-discovery/index.md
  src/content/zh-cn/fundamentals/security/encrypt-in-transit/enable-https.md
  src/data/_contributors.yaml
Labels: cla: yes

#7306 Sept-Dec 2012 link updates
  src/content/en/updates/2012/09/Interactive-Globe-with-CSS-shaders-Google-Maps.md
  src/content/en/updates/2012/09/Live-Web-Audio-Input-Enabled.md
  src/content/en/updates/2012/09/Stacking-Changes-Coming-to-position-fixed-elements.md
  src/content/en/updates/2012/11/Content-Security-Policy-1-0-is-officially-awesome.md
  src/content/en/updates/2012/11/Respond-to-change-with-Object-observe.md
  src/content/en/updates/2012/12/Canvas-driven-background-images.md
  src/content/en/updates/2012/12/Screensharing-with-WebRTC.md
  src/content/en/updates/2012/12/WebRTC-hits-Firefox-Android-and-iOS.md
Labels: cla: yes

#7117 Parallelize update-resources.sh
  tools/update-resources.sh
Labels: cla: yes, type-Infrastructure

#7316 Delete ignoreUrlParametersMatching.html
  src/content/en/tools/workbox/_shared/config/single/ignoreUrlParametersMatching.html
Labels: cla: yes

#7317 Delete dontCacheBustUrlsMatching.html
  src/content/en/tools/workbox/_shared/config/single/dontCacheBustUrlsMatching.html
Labels: cla: yes

#7318 Delete templatedUrls.html
  src/content/en/tools/workbox/_shared/config/single/templatedUrls.html
Labels: cla: yes

#7319 Delete modifyUrlPrefix.html
  src/content/en/tools/workbox/_shared/config/single/modifyUrlPrefix.html
Labels: cla: yes

#7324 Workbox docs redirects
  src/content/en/tools/workbox/reference-docs/_redirects.yaml
Labels: cla: yes

#7325 Fix auto-generated workbox v4 doc issues
  src/content/en/tools/workbox/_reference-docs.yaml
  src/content/en/tools/workbox/reference-docs/latest/_toc.yaml
  src/content/en/tools/workbox/reference-docs/latest/index-all.html
  src/content/en/tools/workbox/reference-docs/latest/index.html
  src/content/en/tools/workbox/reference-docs/latest/workbox-routing_index.mjs.html
  src/content/en/tools/workbox/reference-docs/latest/workbox-sw_index.mjs.html
  src/content/en/tools/workbox/reference-docs/latest/workbox.html
  src/content/en/tools/workbox/reference-docs/latest/workbox.routing.html
Labels: cla: yes, type-Content

#7326 fix link
  src/content/en/tools/chrome-devtools/console/utilities.md
Labels: P1, cla: yes, content-updated, section-tools, type-Content
