Repository google/WebFundamentals, pull requests merged in 2019-05, with the labels that each got.

#7558 /ilt/pwa update
  src/content/en/ilt/pwa/_shared/update.html
  src/content/en/ilt/pwa/caching-files-with-service-worker-slides.md
  src/content/en/ilt/pwa/caching-files-with-service-worker.md
  src/content/en/ilt/pwa/challenge-convert-a-news-app-to-a-pwa.md
  src/content/en/ilt/pwa/challenge-convert-an-e-commerce-site-to-a-pwa.md
  src/content/en/ilt/pwa/core-technologies.md
  src/content/en/ilt/pwa/design-for-all-your-users.md
  src/content/en/ilt/pwa/e-commerce-lab-1-create-a-service-worker.md
  src/content/en/ilt/pwa/e-commerce-lab-2-add-to-homescreen.md
  src/content/en/ilt/pwa/e-commerce-lab-3-payment-request-api.md
  src/content/en/ilt/pwa/index.md
  src/content/en/ilt/pwa/integrating-analytics-slides.md
  src/content/en/ilt/pwa/integrating-analytics.md
  src/content/en/ilt/pwa/introduction-to-gulp-slides.md
  src/content/en/ilt/pwa/introduction-to-gulp.md
  src/content/en/ilt/pwa/introduction-to-progressive-web-app-architectures-slides.md
  src/content/en/ilt/pwa/introduction-to-progressive-web-app-architectures.md
  src/content/en/ilt/pwa/introduction-to-push-notifications-slides.md
  src/content/en/ilt/pwa/introduction-to-push-notifications.md
  src/content/en/ilt/pwa/introduction-to-service-worker-slides.md
  src/content/en/ilt/pwa/introduction-to-service-worker.md
  src/content/en/ilt/pwa/introduction-to-the-payment-request-api-slides.md
  src/content/en/ilt/pwa/introduction-to-the-payment-request-api.md
  src/content/en/ilt/pwa/lab-auditing-with-lighthouse.md
  src/content/en/ilt/pwa/lab-build-a-progressive-web-amp.md
  src/content/en/ilt/pwa/lab-caching-files-with-service-worker.md
  src/content/en/ilt/pwa/lab-cloud-firestore.md
  src/content/en/ilt/pwa/lab-fetch-api.md
  src/content/en/ilt/pwa/lab-gulp-setup.md
  src/content/en/ilt/pwa/lab-indexeddb.md
  src/content/en/ilt/pwa/lab-integrating-analytics.md
  src/content/en/ilt/pwa/lab-integrating-web-push.md
  src/content/en/ilt/pwa/lab-migrating-to-workbox-from-sw-precache-and-sw-toolbox.md
  src/content/en/ilt/pwa/lab-offline-quickstart.md
  src/content/en/ilt/pwa/lab-promises.md
  src/content/en/ilt/pwa/lab-responsive-design.md
  src/content/en/ilt/pwa/lab-responsive-images.md
  src/content/en/ilt/pwa/lab-scripting-the-service-worker.md
  src/content/en/ilt/pwa/lab-workbox.md
  src/content/en/ilt/pwa/lighthouse-pwa-analysis-tool-slides.md
  src/content/en/ilt/pwa/lighthouse-pwa-analysis-tool.md
  src/content/en/ilt/pwa/live-data-in-the-service-worker-slides.md
  src/content/en/ilt/pwa/live-data-in-the-service-worker.md
  src/content/en/ilt/pwa/offline-quickstart-slides.md
  src/content/en/ilt/pwa/offline-quickstart.md
  src/content/en/ilt/pwa/responsive-design-slides.md
  src/content/en/ilt/pwa/responsive-images-slides.md
  src/content/en/ilt/pwa/setting-up-the-labs.md
  src/content/en/ilt/pwa/tools-for-pwa-developers.md
  src/content/en/ilt/pwa/why-build-pwa.md
  src/content/en/ilt/pwa/working-with-indexeddb-slides.md
  src/content/en/ilt/pwa/working-with-indexeddb.md
  src/content/en/ilt/pwa/working-with-promises-slides.md
  src/content/en/ilt/pwa/working-with-promises.md
  src/content/en/ilt/pwa/working-with-the-fetch-api-slides.md
  src/content/en/ilt/pwa/working-with-the-fetch-api.md
  src/content/en/ilt/pwa/your-audience-your-content.md
Labels: cla: yes

#7562 RU translation of PWA codelab
  src/content/ru/fundamentals/codelabs/your-first-pwapp/index.md
Labels: cla: yes, section-fundamentals, type-Content-Translation

#7568 HTTP 203 podcast
  src/content/en/shows/http203/podcast/performance-trailers-dentistry.md
Labels: cla: yes, type-Content

#7567 [Workbox] Update the debugging guide
  src/content/en/tools/workbox/guides/troubleshoot-and-debug.md
Labels: cla: yes

#7560 Web share article
  src/content/en/updates/2016/09/navigator-share.md
  src/content/en/updates/2018/12/web-share-target.md
  src/content/en/updates/2019/05/web-share-files.md
Labels: cla: yes, content-new, content-updated

#7529 Deprecations and removals for Chrome 75.
  src/content/en/updates/2019/05/chrome-75-deps-rems.md
Labels: cla: yes

#7566 Add desynchronized hint article.
  src/content/en/updates/2019/05/desynchronized.md
  src/content/en/updates/images/2019/05/latency.png
  src/content/en/updates/images/2019/05/sintel.png
Labels: cla: yes, content-new

#7571 Remove future API from Site Kit services to enable
  src/content/en/site-kit/index.html
Labels: P0, cla: yes, section-site-kit, type-Content

#7581 Escape characters in strings.
  src/content/en/updates/2019/05/web-share-files.md
Labels: cla: yes

#7577 Adds Paint Holding article.
  src/content/en/updates/2019/05/paint-holding.md
  src/content/en/updates/images/2019/05/paint-holding-poster.jpg
  src/content/en/updates/images/2019/05/paint-holding.mp4
  src/content/en/updates/images/2019/05/paint-holding.webm
Labels: cla: yes, type-Content

#7561 [lighthouse] add performance budget docs
  src/content/en/tools/lighthouse/_toc.yaml
  src/content/en/tools/lighthouse/audits/budgets.md
  src/content/en/tools/lighthouse/audits/images/budgetscustom.png
  src/content/en/tools/lighthouse/audits/images/budgetsdefault.png
  src/content/en/tools/lighthouse/audits/images/requestcounts.png
Labels: DO NOT MERGE, cla: yes

#7585 Model viewer article
  src/content/en/updates/2019/02/model-viewer.md
  src/content/en/updates/2019/05/model-viewer-ar.md
  src/content/en/updates/images/2019/05/masthead.jpg
  src/content/en/updates/images/2019/05/rover.png
  src/data/commonTags.json
Labels: cla: yes

#7588 Fix image size.
  src/content/en/updates/images/2019/05/rover.png
Labels: cla: yes

#7589 Fix character escaping.
  src/content/en/updates/2019/05/model-viewer-ar.md
Labels: cla: yes

#7582 update apple-touch-icon guidance
  src/content/en/fundamentals/design-and-ux/browser-customization/index.md
Labels: P0, cla: yes, content-updated, section-fundamentals, type-Content

#7592 Fix typos model-viewer article
  src/content/en/updates/2019/05/model-viewer-ar.md
Labels: cla: yes

#7597 Fix paint timing links
  src/content/en/fundamentals/performance/user-centric-performance-metrics.md
Labels: cla: yes

#7590 Add Media Session API section for PiP window controls
  src/content/en/updates/2018/10/watch-video-using-picture-in-picture.md
  src/content/en/updates/images/2018/10/media-playback-controls.png
Labels: cla: yes

#7591 Add note about fullscreen
  src/content/en/updates/2018/10/watch-video-using-picture-in-picture.md
Labels: cla: yes

#7604 Fix image URL
  src/content/en/updates/2018/10/watch-video-using-picture-in-picture.md
Labels: cla: yes

#7603 Fix nit
  src/content/en/updates/2018/10/watch-video-using-picture-in-picture.md
Labels: cla: yes

#7607 Fix a typo in the documentation
  src/content/en/tools/workbox/modules/workbox-window.md
Labels: cla: yes

#7611 Update screenshot for devtools changes
  src/content/en/updates/images/2019/03/kv-storage-devtools-source.png
Labels: cla: yes

#7612 Add new Site Kit page for obtaining API Key
  src/content/en/site-kit/_footer.yaml
  src/content/en/site-kit/_project.yaml
  src/content/en/site-kit/apikey.html
  src/content/en/site-kit/index.html
Labels: cla: yes, section-site-kit, type-Content

#7621 [devtools] update feature discovery list
  src/content/en/updates/_shared/discover.md
Labels: P1, cla: yes, content-updated, section-updates, type-Content

#7622 [devtools] add bonus tips and remove periods
  src/content/en/updates/_shared/discover.md
Labels: P2, cla: yes, content-updated, section-updates, type-Content

#7576 #7572 | Spec reference fix
  src/content/en/updates/2016/06/css-containment.md
Labels: cla: yes

#7467 Fix Korean typo
  src/content/ko/fundamentals/codelabs/your-first-pwapp/index.md
Labels: cla: yes

#7620 Updated outdated links and added mixed content issue; Fixes #7619
  src/content/en/fundamentals/security/prevent-mixed-content/_code/simple-example.html
Labels: cla: yes

#7570 Fix app-shell appspot 404s
  src/content/en/fundamentals/architecture/app-shell.md
  src/content/en/ilt/pwa/introduction-to-progressive-web-app-architectures.md
  src/content/es/fundamentals/architecture/app-shell.md
  src/content/id/fundamentals/architecture/app-shell.md
  src/content/it/fundamentals/architecture/app-shell.md
  src/content/ja/fundamentals/architecture/app-shell.md
  src/content/ko/fundamentals/architecture/app-shell.md
  src/content/pt-br/fundamentals/architecture/app-shell.md
  src/content/zh-cn/fundamentals/architecture/app-shell.md
  src/content/zh-tw/fundamentals/architecture/app-shell.md
Labels: cla: yes

#7616 Added missing verb
  src/content/en/tools/workbox/modules/workbox-google-analytics.md
Labels: cla: yes

#7626 [devtools] refactor the customization docs
  src/content/en/tools/_redirects.yaml
  src/content/en/tools/chrome-devtools/_toc.yaml
  src/content/en/tools/chrome-devtools/customize/dark-theme.md
  src/content/en/tools/chrome-devtools/customize/images/bottomicon.png
  src/content/en/tools/chrome-devtools/customize/images/custom-panel-tab-ordering.png
  src/content/en/tools/chrome-devtools/customize/images/darktheme.png
  src/content/en/tools/chrome-devtools/customize/images/darkthemecommand.png
  src/content/en/tools/chrome-devtools/customize/images/dockbottom.png
  src/content/en/tools/chrome-devtools/customize/images/dockleft.png
  src/content/en/tools/chrome-devtools/customize/images/drawer-example.png
  src/content/en/tools/chrome-devtools/customize/images/lefticon.png
  src/content/en/tools/chrome-devtools/customize/images/more-drawer-tabs.svg
  src/content/en/tools/chrome-devtools/customize/images/more.png
  src/content/en/tools/chrome-devtools/customize/images/opensettings.png
  src/content/en/tools/chrome-devtools/customize/images/preferences.png
  src/content/en/tools/chrome-devtools/customize/images/settings.png
  src/content/en/tools/chrome-devtools/customize/images/undock.png
  src/content/en/tools/chrome-devtools/customize/images/undockcommand.png
  src/content/en/tools/chrome-devtools/customize/images/undockicon.png
  src/content/en/tools/chrome-devtools/customize/images/undocksettings.png
  src/content/en/tools/chrome-devtools/customize/index.md
  src/content/en/tools/chrome-devtools/customize/placement.md
  src/content/en/tools/chrome-devtools/ui.md
Labels: P2, cla: yes, content-new, content-updated, section-tools, type-Content

#7627 Add video & codelab to capabilities page
  src/content/en/updates/capabilities.md
Labels: cla: yes, content-updated, proj-fugu, section-updates, type-Content

#7593 docs: translate to chinese
  src/content/zh-cn/fundamentals/codelabs/your-first-pwapp/index.md
Labels: cla: yes

#7580 es:your-first-pwapp
  src/content/es/fundamentals/codelabs/your-first-pwapp/index.md
Labels: cla: yes

#7563 Fixing Bahasa Indonesa translation
  src/content/id/fundamentals/codelabs/your-first-pwapp/index.md
Labels: cla: yes

#7630 Minor codelab cleanup
  src/content/de/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/es/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/hi/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/id/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/ko/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/pt-br/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/ru/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/zh-cn/fundamentals/codelabs/your-first-pwapp/index.md
Labels: cla: yes

#7629 Remove feed widget
  src/templates/latest_articles.html
Labels: cla: yes, type-Infrastructure

#7628 Adds IO videos to pages
  src/content/en/progressive-web-apps/_index.yaml
  src/content/en/updates/2019/02/using-twa.md
Labels: cla: yes, content-updated, type-Content

#7633 Save The Save for CDS
  src/content/en/_index.yaml
Labels: cla: yes, type-Content

#7635 Update for Cr76
  src/content/en/images/contributors/pjmclachlan.jpg
  src/content/en/site-kit/_project.yaml
  src/content/en/updates/2019/05/mini-infobar-update.md
  src/content/en/updates/images/2019/05/pinterest-a2hs.png
  src/data/_contributors.yaml
Labels: cla: yes, content-new, section-updates, type-Content

#7643 Fix typo in the word "can"
  src/content/en/updates/2016/10/resizeobserver.md
Labels: cla: yes

#7639 Adds additional detail about uninstall
  src/content/en/fundamentals/codelabs/your-first-pwapp/index.md
Labels: cla: yes, content-updated, section-fundamentals, type-Content

#7625 CrChron Epispde 2
  src/content/en/updates/2019/05/chromium-chronicle-2.md
Labels: cla: yes, section-updates, type-Content

#7640 Update web agencies directory data
  src/content/en/agencies/data/agencies.json
  src/content/en/agencies/images/e-point_sa.png
  src/content/en/agencies/images/microtekblue_inc.png
  src/content/en/agencies/images/simicart_joint_stock_company_.png
  src/content/en/agencies/images/unbound_commerce.png
Labels: cla: yes

#7645 New HTTP203
  src/content/en/shows/http203/podcast/edge-n-css-with-greg.md
  src/content/en/shows/http203/podcast/images/with-greg.jpg
Labels: cla: yes, type-Content

#7657 emscripten-npm: minor fixes
  src/content/en/updates/2019/01/emscripten-npm.md
Labels: cla: yes

#7667 [devtools] add wndt76
  src/content/en/tools/chrome-devtools/images/shared/export.png
  src/content/en/tools/chrome-devtools/images/shared/import.png
  src/content/en/tools/chrome-devtools/images/shared/settings.png
  src/content/en/updates/2019/05/devtools.md
  src/content/en/updates/images/2019/05/fetch.png
  src/content/en/updates/images/2019/05/har-buttons.png
  src/content/en/updates/images/2019/05/mapping.png
  src/content/en/updates/images/2019/05/memory.png
  src/content/en/updates/images/2019/05/portals.png
  src/content/en/updates/images/2019/05/settings.png
  src/content/en/updates/images/2019/05/sw-ports.png
  src/content/en/updates/images/2019/05/sync.png
  src/content/en/updates/images/2019/05/values.png
Labels: P0, cla: yes, content-new, section-updates, type-Content

#7668 Update PWACompat post with latest version
  src/content/en/updates/2018/07/pwacompat.md
Labels: cla: yes

#7652 Fix powerful APIs link
  src/content/en/updates/capabilities.md
Labels: cla: yes

#7655 Made some improvements to Paint Holding article
  src/content/en/updates/2019/05/paint-holding.md
Labels: cla: yes

#7660 Fixes and improvements to Share files article
  src/content/en/updates/2019/05/web-share-files.md
Labels: cla: yes

#7669 Fix typo
  src/content/en/updates/2019/05/desynchronized.md
  src/content/en/updates/2019/05/web-share-files.md
Labels: cla: yes

#7663 Small fixes to String.prototype.matchAll() article
  src/content/en/updates/2019/02/string-matchall.md
Labels: cla: yes

#7658 #7617 | Fix W3C link
  src/content/en/tools/lighthouse/audits/required-aria-attributes.md
Labels: cla: yes

#7653 Made a few improvements in AR with model-viewer
  src/content/en/updates/2019/05/model-viewer-ar.md
Labels: cla: yes

#7648 Fix typo in Text Compression page
  src/content/en/tools/lighthouse/audits/text-compression.md
Labels: cla: yes

#7601 Update axe links
  src/content/en/tools/lighthouse/audits/alt-attribute.md
  src/content/en/tools/lighthouse/audits/aria-allowed-attributes.md
  src/content/en/tools/lighthouse/audits/button-name.md
  src/content/en/tools/lighthouse/audits/form-labels.md
  src/content/en/tools/lighthouse/audits/tabindex.md
  src/content/en/tools/lighthouse/audits/valid-aria-attributes.md
  src/content/en/tools/lighthouse/audits/valid-aria-values.md
  src/content/ko/tools/lighthouse/audits/aria-allowed-attributes.md
  src/content/ko/tools/lighthouse/audits/valid-aria-attributes.md
Labels: cla: yes

#7595 Update cache-policy.md to account for leap years
  src/content/en/tools/lighthouse/audits/cache-policy.md
Labels: cla: yes

#7546 Add Uploadcare to the list of GIFs to video convertors
  src/content/en/fundamentals/performance/optimizing-content-efficiency/replace-animated-gifs-with-video/index.md
Labels: cla: yes

#7545 Add Uploadcare to the list of CDNs
  src/content/en/updates/2018/08/web-performance-made-easy.md
Labels: cla: yes

#7537 Corrected keyboard shortcut for opening DevTools on Mac
  src/content/en/tools/chrome-devtools/console/log.md
Labels: cla: yes

#7314 [Lighthouse] Add variability doc
  src/content/en/tools/lighthouse/images/lighthouse-psi.png
  src/content/en/tools/lighthouse/index.md
  src/content/en/tools/lighthouse/variability.md
Labels: cla: yes

#7214 added link to asyncCSS (advanced CSS loader)
  src/content/en/tools/lighthouse/audits/unused-css.md
Labels: cla: yes

#6802 Update shortcuts.md
  src/content/en/tools/chrome-devtools/shortcuts.md
Labels: cla: yes

#7304 Closes Issue #7303: Updates instructions to open Animations Inspector
  src/content/en/tools/chrome-devtools/inspect-styles/animations.md
  src/content/en/tools/chrome-devtools/inspect-styles/imgs/animations-button.png
  src/content/en/tools/chrome-devtools/inspect-styles/imgs/animations-via-main-menu.png
Labels: cla: yes

#7256 Add python 3 webserver example to workspaces setup example
  src/content/en/tools/chrome-devtools/workspaces/index.md
Labels: cla: yes

#7677 [devtools] update wndt76
  src/content/en/updates/2019/05/devtools.md
Labels: P0, cla: yes, content-updated, section-updates, type-Content

#7675 Site kit updates
  src/content/en/site-kit/apikey.html
  src/content/en/site-kit/index.html
Labels: cla: yes, section-site-kit, type-Content

#7682 Changes license per DevSite request
  gulp-tasks/tests/projectYaml.js
  src/content/en/_project.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/site-kit/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
Labels: cla: yes, type-Infrastructure
