Repository google/WebFundamentals, pull requests merged in 2019-04, with the labels that each got.

#7468 [Workbox] Fixes for the broadcastUpdate.Plugin guide
  src/content/en/tools/workbox/modules/workbox-broadcast-cache-update.md
Labels: cla: yes

#7471 [Workbox] Manual updates for v4.2.0
  src/content/en/tools/workbox/_shared/config/groups/common-generate-schema.html
  src/content/en/tools/workbox/_shared/config/single/navigationPreload.html
  src/content/en/tools/workbox/guides/using-plugins.md
Labels: cla: yes

#7475 [Workbox] Precaching guide updates
  src/content/en/tools/workbox/images/modules/workbox-precaching/precaching-step-1.png
  src/content/en/tools/workbox/images/modules/workbox-precaching/precaching-step-2.png
  src/content/en/tools/workbox/images/modules/workbox-precaching/precaching-step-3.png
  src/content/en/tools/workbox/modules/workbox-precaching.md
Labels: cla: yes

#7474 performance.getEntries() doesn't have an optional param
  src/content/en/fundamentals/performance/navigation-and-resource-timing/index.md
Labels: cla: yes

#7479 Fix typo
  src/content/en/updates/2014/12/web-animation-playback.md
Labels: cla: yes

#7481 DevSite style updates
  src/content/en/fundamentals/primers/service-workers/lifecycle.md
  src/content/en/tools/workbox/reference-docs/latest/jsdoc.css
Labels: cla: yes

#7482 Remove private members from v4.2.0 Workbox docs
  src/content/en/tools/workbox/_shared/contributors.html
  src/content/en/tools/workbox/reference-docs/latest/index-all.html
  src/content/en/tools/workbox/reference-docs/latest/index.html
  src/content/en/tools/workbox/reference-docs/latest/jsdoc.css
  src/content/en/tools/workbox/reference-docs/latest/workbox-background-sync_Queue.mjs.html
  src/content/en/tools/workbox/reference-docs/latest/workbox-background-sync_lib_QueueStore.mjs.html
  src/content/en/tools/workbox/reference-docs/latest/workbox-broadcast-update_BroadcastCacheUpdate.mjs.html
  src/content/en/tools/workbox/reference-docs/latest/workbox-core__private_DBWrapper.mjs.html
  src/content/en/tools/workbox/reference-docs/latest/workbox-expiration_models_CacheTimestampsModel.mjs.html
  src/content/en/tools/workbox/reference-docs/latest/workbox-window_utils_EventTargetShim.mjs.html
  src/content/en/tools/workbox/reference-docs/latest/workbox.backgroundSync.Queue.html
  src/content/en/tools/workbox/reference-docs/latest/workbox.broadcastUpdate.BroadcastCacheUpdate.html
  src/content/en/tools/workbox/reference-docs/v4.2.0/index-all.html
  src/content/en/tools/workbox/reference-docs/v4.2.0/index.html
  src/content/en/tools/workbox/reference-docs/v4.2.0/workbox-background-sync_Queue.mjs.html
  src/content/en/tools/workbox/reference-docs/v4.2.0/workbox-background-sync_lib_QueueStore.mjs.html
  src/content/en/tools/workbox/reference-docs/v4.2.0/workbox-broadcast-update_BroadcastCacheUpdate.mjs.html
  src/content/en/tools/workbox/reference-docs/v4.2.0/workbox-core__private_DBWrapper.mjs.html
  src/content/en/tools/workbox/reference-docs/v4.2.0/workbox-expiration_models_CacheTimestampsModel.mjs.html
  src/content/en/tools/workbox/reference-docs/v4.2.0/workbox-window_utils_EventTargetShim.mjs.html
  src/content/en/tools/workbox/reference-docs/v4.2.0/workbox.backgroundSync.Queue.html
  src/content/en/tools/workbox/reference-docs/v4.2.0/workbox.broadcastUpdate.BroadcastCacheUpdate.html
Labels: cla: yes

#7490 Ask Chrome banner & hero
  src/content/en/_index.yaml
  src/content/en/_project.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: P0, cla: yes, type-Content

#7486 Add user gesture expection to PiP article
  src/content/en/updates/2018/10/watch-video-using-picture-in-picture.md
Labels: cla: yes

#7487 Update how-payment-ecosystem-works.md
  src/content/en/fundamentals/payments/basics/how-payment-ecosystem-works.md
Labels: cla: yes

#7463 Update push-notifications-on-the-open-web.md
  src/content/en/updates/2015/03/push-notifications-on-the-open-web.md
Labels: cla: yes

#7455 Typo: duplicated word
  src/content/en/updates/2019/03/nic73.md
Labels: cla: yes

#7495 Update Android payment app documentation.
  src/content/en/fundamentals/payments/payment-apps-developer-guide/android-payment-apps.md
Labels: cla: yes, content-updated, section-fundamentals, type-Content

#7501 Remove reference to expired push subscriptions
  src/content/en/fundamentals/push-notifications/common-issues-and-reporting-bugs.md
Labels: cla: yes

#7493 Adding `webp` to the image file extensions
  src/content/en/tools/workbox/guides/common-recipes.md
Labels: cla: yes

#7499 Remove warning about user gesture propagation through Promises
  src/content/en/updates/2016/03/access-usb-devices-on-the-web.md
Labels: cla: yes

#7511 Update SGX abbrev to SXG.
  src/content/en/updates/2019/03/nic73.md
Labels: cla: yes

#7512 Remove AskChrome hero & banner
  src/content/en/_index.yaml
  src/content/en/_project.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes, content-updated

#7508 Fix typo: Networ -> Network.
  src/content/zh-cn/tools/chrome-devtools/network-performance/reference.md
Labels: cla: yes

#7504 Add missing close bracket
  src/content/en/fundamentals/performance/http2/index.md
Labels: cla: yes

#7498 Web share target updates for new manifest values
  src/content/en/updates/2018/12/web-share-target.md
Labels: cla: yes

#7473 Chromium Chronicle - episode 1
  src/content/en/updates/2019/04/chromium-chronicle-1.md
  src/content/en/updates/images/generic/cr-chron.jpg
  src/data/commonTags.json
Labels: cla: yes, section-updates, type-Content

#7380 Typo: missing word
  src/content/en/updates/2019/03/kv-storage.md
Labels: cla: yes

#7509 Update reportingobserver.md
  src/content/en/updates/2018/07/reportingobserver.md
Labels: cla: no

#6963 [Translate ENG-KO] updates/2016/05/Houdini.md
  src/content/ko/updates/2016/05/houdini.md
  src/data/_contributors.yaml
Labels: cla: yes

#7515 [devtools] add wndt75
  src/content/en/updates/2019/04/devtools.md
  src/content/en/updates/images/2019/04/blur1.png
  src/content/en/updates/images/2019/04/blur2.png
  src/content/en/updates/images/2019/04/breakpoints1.png
  src/content/en/updates/images/2019/04/breakpoints2.png
  src/content/en/updates/images/2019/04/clearsitedata.png
  src/content/en/updates/images/2019/04/clearstoragepane.png
  src/content/en/updates/images/2019/04/hover.png
  src/content/en/updates/images/2019/04/idb1.png
  src/content/en/updates/images/2019/04/idb2.png
  src/content/en/updates/images/2019/04/inspect1.png
  src/content/en/updates/images/2019/04/inspect2.png
  src/content/en/updates/images/2019/04/totalentries.png
Labels: P0, cla: yes, content-new, section-updates, type-Content

#7517 docs(workbox): v4x renames addRequest to pushRequest
  src/content/en/tools/workbox/modules/workbox-background-sync.md
Labels: cla: yes

#7524 [devtools] link to wndt74 video
  src/content/en/updates/2019/03/devtools.md
Labels: P1, cla: yes, content-new, section-updates, type-Content

#7528 Correct a heading.
  src/content/en/updates/2019/03/chrome-74-deps-rems.md
Labels: cla: yes

#7531 New in Chrome 74
  src/content/en/updates/2019/04/nic74.md
  src/content/en/updates/_redirects.yaml
  src/data/commonTags.json
Labels: cla: yes, content-new, section-updates, type-Content

#7533 Expand image optimization CDNs list with Uploadcare.com
  src/content/en/tools/lighthouse/audits/optimize-images.md
Labels: P2, cla: yes, content-new, section-tools, type-Content

#7535 [lighthouse] remove link to unpopular tool
  src/content/en/tools/lighthouse/audits/oversized-images.md
Labels: P2, cla: yes, content-updated, section-tools, type-Content

#7539 Trans pwa codelab
  src/content/de/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/en/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/es/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/hi/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/id/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/ja/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/ko/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/pt-br/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/zh-cn/fundamentals/codelabs/your-first-pwapp/index.md
  src/content/zh-tw/fundamentals/codelabs/your-first-pwapp/index.md
  tools/translate.sh
Labels: cla: yes

#7548 Explicitly mention private methods and accessors support
  src/content/en/updates/2018/12/class-fields.md
Labels: cla: yes

#7541 Add "cast" tag to cast related articles
  src/content/en/updates/2015/11/presentation-api.md
  src/content/en/updates/2018/04/present-web-pages-to-secondary-attached-displays.md
  src/data/commonTags.json
Labels: cla: yes

#7514 Introduce Site Kit section
  gulp-tasks/build.js
  gulp-tasks/tests/projectYaml.js
  gulp-tasks/tests/validateContent.js
  gulp-tasks/wfRegEx.js
  src/content/en/_footer.yaml
  src/content/en/site-kit/_book.yaml
  src/content/en/site-kit/_footer.yaml
  src/content/en/site-kit/_project.yaml
  src/content/en/site-kit/index.html
Labels: cla: yes, section-site-kit, type-Content

#7551 Wording: `are are` => `are` for workbox NetworkFirst strategy
  src/content/en/tools/workbox/reference-docs/v4.2.0/workbox-strategies_NetworkFirst.mjs.html
  src/content/en/tools/workbox/reference-docs/v4.2.0/workbox.strategies.NetworkFirst.html
Labels: cla: yes

#7554 Add pseudo elements to styles forcing no motion
  src/content/en/updates/2019/03/prefers-reduced-motion.md
Labels: cla: yes

#7555 JA: review your-first-pwapp/index.md
  src/content/ja/fundamentals/codelabs/your-first-pwapp/index.md
Labels: cla: yes

#7552 Fix some zh-tw translation problems
  src/content/zh-tw/fundamentals/codelabs/your-first-pwapp/index.md
Labels: cla: yes
