Repository google/WebFundamentals, pull requests merged in 2020-03, with the labels that each got.

#6161 [Translate ru] Accessibility -> focus
  src/content/ru/fundamentals/accessibility/focus/index.md
  src/data/_contributors.yaml
Labels: cla: no, type-Content-Translation

#7826 [KO] Translation of layoutNG.md
  src/content/ko/updates/2019/06/layoutNG.md
Labels: cla: no, type-Content-Translation

#7922 [KO] Translation of rendering-on-the-web.md
  src/content/ko/updates/2019/02/rendering-on-the-web.md
Labels: cla: no, type-Content-Translation

#8523 Remove a Workbox nav link that 404s
  src/content/en/tools/workbox/modules/_toc.yaml
Labels: cla: yes

#8526 Improves guidance on multi origin twas
  src/content/en/updates/2020/01/twa-multi-origin.md
Labels: cla: yes

#8527 Remove MDN survey banner
  src/content/en/_project.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/site-kit/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes

#8549 Update install criteria URL
  src/content/en/updates/2018/06/a2hs-updates.md
Labels: cla: yes

#8544 Fix Missing ')' after the 'timeupdate' addEventListener call
  src/content/en/fundamentals/media/mobile-web-video-playback.md
Labels: cla: yes

#8542 Fix broken CSP link
  src/content/en/fundamentals/security/prevent-mixed-content/fixing-mixed-content.md
Labels: cla: yes

#8541 Fix codeblock syntax
  src/content/en/fundamentals/media/recording-video/index.md
Labels: cla: yes

#8531 Adds article "Passing Information to a Trusted Web Activity using Query Parameters"
  src/content/en/updates/2020/03/trusted-web-activity-passing-information.md
  src/content/en/updates/images/2020/03/llama-pack-init-custom-start-url.png
Labels: cla: yes, type-Content

#8530 link to issue templates for lighthouse
  src/content/en/tools/lighthouse/index.md
  src/content/en/tools/lighthouse/scoring.md
  src/content/en/tools/lighthouse/v3/scoring.md
  src/content/ko/tools/lighthouse/index.md
Labels: cla: yes

#8547 Update index.md
  src/content/en/fundamentals/performance/why-performance-matters/index.md
Labels: cla: yes

#8550 Add 202002 release to CrUX changelog
  src/content/en/tools/chrome-user-experience-report/changelog.md
Labels: cla: yes

#8551 Creates /web/android
  src/content/en/_footer.yaml
  src/content/en/android/_book.yaml
  src/content/en/android/_index_android.yaml
  src/content/en/android/_project.yaml
  src/content/en/android/_redirects.yaml
  src/content/en/android/custom-tabs/_toc.yaml
  src/content/en/android/custom-tabs/best-practices/index.md
  src/content/en/android/custom-tabs/implementation-guide/index.md
  src/content/en/android/custom-tabs/index.md
  src/content/en/android/custom-tabs/low-level-api/index.md
  src/content/en/android/trusted-web-activity/_toc.yaml
  src/content/en/android/trusted-web-activity/android-browser-helper-migration/index.md
  src/content/en/android/trusted-web-activity/index.md
  src/content/en/android/trusted-web-activity/integration-guide/index.md
  src/content/en/android/trusted-web-activity/lay-of-the-land/index.md
  src/content/en/android/trusted-web-activity/multi-origin/index.md
  src/content/en/android/trusted-web-activity/query-parameters/index.md
  src/content/en/android/trusted-web-activity/quick-start/index.md
  src/content/en/updates/_redirects.yaml
Labels: cla: yes

#8548 What's New In DevTools (Chrome 82)
  src/content/en/updates/2020/03/devtools.md
  src/content/en/updates/_shared/discover.md
  src/content/en/updates/images/2020/03/dock-to-left.png
  src/content/en/updates/images/2020/03/guidance.png
  src/content/en/updates/images/2020/03/lighthouse.png
  src/content/en/updates/images/2020/03/long-task.png
  src/content/en/updates/images/2020/03/maskable-icons.png
  src/content/en/updates/images/2020/03/overrides.png
  src/content/en/updates/images/2020/03/status.png
  src/content/en/updates/images/2020/03/vision.png
Labels: P1, cla: yes, content-new, section-tools, type-Content

#8554 Add item I just learned about to Chrome 74.
  src/content/en/updates/2019/03/chrome-74-deps-rems.md
Labels: cla: yes

#8555 CrUX feedback module
  src/content/en/tools/chrome-user-experience-report/_footer.yaml
  src/content/en/tools/chrome-user-experience-report/_project.yaml
Labels: cla: yes

#8553 Web on Android back ports from DevSite
  src/content/en/_redirects.yaml
  src/content/en/android/_book.yaml
  src/content/en/android/_redirects.yaml
Labels: cla: yes

#8552 llama-pack => Bubblewrap
  src/content/en/android/trusted-web-activity/lay-of-the-land/index.md
  src/content/en/android/trusted-web-activity/query-parameters/index.md
Labels: cla: yes

#8561 New in Chrome 81
  src/content/en/updates/2020/03/nic81.md
  src/content/en/updates/images/2020/03/badging.jpg
  src/content/en/updates/images/2020/03/form-controls.jpg
  src/content/en/updates/images/2020/03/hit-test.jpg
  src/content/en/updates/images/2020/03/new-81.jpg
Labels: cla: yes

#8562 NIC81 - forms-punted
  src/content/en/updates/2020/03/nic81.md
Labels: cla: yes

#8563 remove NIC
  src/content/en/updates/2020/03/nic81.md
Labels: cla: yes

#8566 New 203 episode
  src/content/en/shows/http203/podcast/social-distance-ssr-patterns-and-bedtime-routines.md
Labels: cla: yes, type-Content

#8568 Add Chromium Chronicle 13
  src/content/en/updates/2020/03/chromium-chronicle.md
Labels: cla: yes

#8582 Update the skipWaiting recipe with updated guidance
  src/content/en/tools/workbox/guides/advanced-recipes.md
Labels: cla: yes, section-tools, type-Content

#8584 New HTTP203 podcast
  src/content/en/shows/http203/podcast/vr-api-design-lockdown.md
Labels: cla: yes, type-Content

#8586 RSS builder doesn't properly escape &
  src/content/en/shows/http203/podcast/vr-api-design-lockdown.md
Labels: cla: yes, type-Content

#8579 [8351] - Fix and update speed links
  src/content/en/fundamentals/performance/get-started/httprequests-5.md
Labels: cla: yes

#8590 Add note about TLS removals
  src/content/en/updates/2020/02/chrome-81-deps-rems.md
Labels: cla: yes

#8569 Simplify list of vision deficiencies
  src/content/en/updates/2020/03/devtools.md
Labels: cla: yes, type-Content

#8593 Mention DevTools support for vision deficiency simulation
  src/content/en/fundamentals/accessibility/accessible-styles.md
Labels: cla: yes

#8591 Convert WNDT82 into WNDT83
  src/content/en/updates/2020/03/devtools.md
Labels: P1, cla: yes, content-updated, section-updates, type-Content

#8587 Remove inline Bug Searcher
  src/content/en/feedback/_book.yaml
  src/content/en/feedback/_index.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/feedback/_redirects.yaml
  src/content/en/feedback/browser-bug-searcher.md
  src/content/en/feedback/file-a-bug.md
  src/content/ru/feedback/browser-bug-searcher.md
Labels: cla: yes

#8578 [8505] - Fix and update links
  src/content/en/tools/chrome-devtools/device-mode/testing-other-browsers.md
Labels: cla: yes

#8577 [8576] - Fix spelling error
  src/content/en/fundamentals/accessibility/semantics-aria/hiding-and-updating-content.md
Labels: cla: yes

#8564 Fix broken link in _reference-docs.yaml
  src/content/en/tools/workbox/_reference-docs.yaml
Labels: cla: yes

#8594 Revert "Convert WNDT82 into WNDT83"
  src/content/en/updates/2020/03/devtools.md
Labels: cla: yes

#8595 Convert WNDT82 to WNDT83
  src/content/en/updates/2020/03/devtools.md
  src/content/en/updates/_shared/discover.md
  src/content/en/updates/images/2020/03/breakpoint.png
  src/content/en/updates/images/2020/03/conditional.png
  src/content/en/updates/images/2020/03/logpoint.png
  src/content/en/updates/images/2020/03/settings.png
Labels: DO NOT MERGE, P1, cla: yes, content-updated, section-tools, type-Content
