Repository google/WebFundamentals, pull requests merged in 2020-12, with the labels that each got.

#9148 [devtools] Add video link
  src/content/en/updates/2020/05/devtools.md
Labels: cla: yes, content-updated, section-tools, type-Content

#9149 Correct "search and replace" string added for injectManifest mode
  src/content/en/tools/workbox/modules/workbox-cli.md
Labels: cla: yes

#9150 Workbox docs tweaks
  src/content/en/tools/workbox/_index.yaml
  src/content/en/tools/workbox/_reference-docs.yaml
  src/content/en/tools/workbox/modules/_index.yaml
  src/content/en/tools/workbox/modules/_toc.yaml
  src/content/en/tools/workbox/modules/workbox-recipes.md
Labels: cla: yes

#9154 Workbox 6.0.2 docs
  package.json
  src/content/en/tools/workbox/_shared/workbox-latest-version.html
  src/content/en/tools/workbox/_shared/workbox-sw-cdn-url.html
  src/content/en/tools/workbox/reference-docs/latest/_toc.yaml
  src/content/en/tools/workbox/reference-docs/latest/index-all.html
  src/content/en/tools/workbox/reference-docs/latest/index.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-background-sync.BackgroundSyncPlugin.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-background-sync.Queue.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-background-sync.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-broadcast-update.BroadcastCacheUpdate.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-broadcast-update.BroadcastUpdatePlugin.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-broadcast-update.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-build.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-cacheable-response.CacheableResponse.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-cacheable-response.CacheableResponsePlugin.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-cacheable-response.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-core.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-expiration.CacheExpiration.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-expiration.ExpirationPlugin.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-expiration.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-google-analytics.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-navigation-preload.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-precaching.PrecacheController.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-precaching.PrecacheFallbackPlugin.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-precaching.PrecacheRoute.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-precaching.PrecacheStrategy.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-precaching.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-range-requests.RangeRequestsPlugin.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-range-requests.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-recipes.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-routing.NavigationRoute.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-routing.RegExpRoute.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-routing.Route.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-routing.Router.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-routing.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-strategies.CacheFirst.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-strategies.CacheOnly.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-strategies.NetworkFirst.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-strategies.NetworkOnly.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-strategies.StaleWhileRevalidate.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-strategies.Strategy.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-strategies.StrategyHandler.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-strategies.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-streams.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.GenerateSW.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.InjectManifest.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-window.Workbox.html
  src/content/en/tools/workbox/reference-docs/latest/module-workbox-window.html
  src/content/en/tools/workbox/reference-docs/latest/workbox.html
Labels: cla: yes

#9124 Redirect build for webusb article to web.dev
  src/content/en/_redirects.yaml
  src/content/en/fundamentals/native-hardware/_toc.yaml
  src/content/en/fundamentals/native-hardware/build-for-webusb/index.md
Labels: cla: yes

#9153 Deprecations and removals for Chrome 88.
  src/content/en/updates/2020/10/chrome-87-deps-rems.md
  src/content/en/updates/2020/12/chrome-88-deps-rems.md
Labels: cla: yes

#9157 Update Device Orientation sample code.
  src/content/en/fundamentals/native-hardware/device-orientation/_code/dev-orientation.html
Labels: cla: yes

#9152 Update devtools remote debugging articles
  src/content/en/tools/chrome-devtools/remote-debugging/index.md
  src/content/ja/tools/chrome-devtools/remote-debugging/index.md
Labels: cla: yes

#9140 Adds the Using Play Billing with TWA documentation
  src/content/en/android/trusted-web-activity/_toc.yaml
  src/content/en/android/trusted-web-activity/play-billing/index.md
Labels: cla: yes, content-new

#9139 Web in play whats new
  src/content/en/android/trusted-web-activity/_toc.yaml
  src/content/en/android/trusted-web-activity/whats-new/in-app-products.jpg
  src/content/en/android/trusted-web-activity/whats-new/index.md
  src/content/en/android/trusted-web-activity/whats-new/play-menu.jpg
  src/content/en/android/trusted-web-activity/whats-new/product-details.jpg
  src/content/en/images/contributors/adrianajara.jpg
  src/data/_contributors.yaml
Labels: cla: yes, content-new

#9162 Fix Device Orientation sample code axis inversions.
  src/content/en/fundamentals/native-hardware/device-orientation/_code/dev-orientation.html
Labels: cla: yes

#9163 [devtools-blog] New post and add contributor: Migrating to web components
  src/content/en/images/contributors/jackfranklin.jpg
  src/content/en/updates/2020/09/migrating-to-js-modules.md
  src/content/en/updates/2020/12/migrating-to-web-components.md
  src/content/en/updates/_shared/discover-devtools-blog.md
  src/content/en/updates/images/2020/12/migrating-to-web-components.jpg
  src/data/_contributors.yaml
Labels: DO NOT MERGE, P1, cla: yes, content-new, section-tools, type-Content

#9164 Updates TWA docs with latest libraries
  src/content/en/android/custom-tabs/implementation-guide/index.md
  src/content/en/android/trusted-web-activity/android-browser-helper-migration/index.md
  src/content/en/android/trusted-web-activity/integration-guide/index.md
  src/content/en/android/trusted-web-activity/play-billing/index.md
  src/content/en/android/trusted-web-activity/quick-start/index.md
  src/content/en/android/trusted-web-activity/web-share-target/index.md
Labels: cla: yes, content-updated

#9167 CDS Now Banner & Landing
  src/content/en/_index.yaml
  src/content/en/_project.yaml
  src/content/en/android/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/site-kit/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/chrome-devtools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes

#9165 Include a full SSRI precaching example
  src/content/en/tools/workbox/modules/workbox-precaching.md
Labels: cla: yes

#9166 Debugging WebAssembly with modern tools
  package.json
  src/content/en/updates/2020/12/webassembly.md
  src/content/en/updates/_shared/discover-devtools-blog.md
  src/content/en/updates/images/2020/12/webassembly/image1.png
  src/content/en/updates/images/2020/12/webassembly/image10.png
  src/content/en/updates/images/2020/12/webassembly/image11.png
  src/content/en/updates/images/2020/12/webassembly/image12.png
  src/content/en/updates/images/2020/12/webassembly/image13.png
  src/content/en/updates/images/2020/12/webassembly/image14.png
  src/content/en/updates/images/2020/12/webassembly/image15.png
  src/content/en/updates/images/2020/12/webassembly/image2.png
  src/content/en/updates/images/2020/12/webassembly/image3.png
  src/content/en/updates/images/2020/12/webassembly/image4.png
  src/content/en/updates/images/2020/12/webassembly/image5.png
  src/content/en/updates/images/2020/12/webassembly/image6.png
  src/content/en/updates/images/2020/12/webassembly/image7.png
  src/content/en/updates/images/2020/12/webassembly/image8.png
  src/content/en/updates/images/2020/12/webassembly/image9.png
  src/data/_contributors.yaml
  src/data/blinkComponents.json
Labels: cla: yes

#9169 Fix dead link in Wasm post
  src/content/en/updates/2020/12/webassembly.md
Labels: cla: yes

#9172 CDS Over Banner
  src/content/en/_index.yaml
  src/content/en/_project.yaml
  src/content/en/android/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/site-kit/_project.yaml
  src/content/en/styles/wf-landing.css
  src/content/en/tools/_project.yaml
  src/content/en/tools/chrome-devtools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes

#9171 Add YouTube video to WebAssembly post
  src/content/en/updates/2020/12/webassembly.md
Labels: cla: yes

#9177 Correct release version of Background Fetch
  src/content/en/updates/2018/12/background-fetch.md
Labels: cla: yes
