Repository google/WebFundamentals, pull requests merged in 2020-11, with the labels that each got.

#9093 Update Workbox getting started docs
  src/content/en/tools/workbox/guides/get-started.md
Labels: cla: yes

#9099 Remove and redirect outdated Workbox docs
  src/content/en/tools/_redirects.yaml
  src/content/en/tools/workbox/guides/_toc.yaml
  src/content/en/tools/workbox/guides/codelabs/_shared/config.md
  src/content/en/tools/workbox/guides/codelabs/_shared/create.md
  src/content/en/tools/workbox/guides/codelabs/_shared/end.md
  src/content/en/tools/workbox/guides/codelabs/_shared/register.md
  src/content/en/tools/workbox/guides/codelabs/_shared/try-complete.md
  src/content/en/tools/workbox/guides/codelabs/_shared/try-initial.md
  src/content/en/tools/workbox/guides/codelabs/gulp.md
  src/content/en/tools/workbox/guides/codelabs/imgs/gulp/add-package.png
  src/content/en/tools/workbox/guides/codelabs/imgs/gulp/demo.png
  src/content/en/tools/workbox/guides/codelabs/imgs/npm-script/add-package.png
  src/content/en/tools/workbox/guides/codelabs/imgs/npm-script/demo.png
  src/content/en/tools/workbox/guides/codelabs/imgs/shared/lib-src.png
  src/content/en/tools/workbox/guides/codelabs/imgs/shared/live.png
  src/content/en/tools/workbox/guides/codelabs/imgs/shared/no-internet.png
  src/content/en/tools/workbox/guides/codelabs/imgs/shared/offline-capable.png
  src/content/en/tools/workbox/guides/codelabs/imgs/shared/offline-complete.png
  src/content/en/tools/workbox/guides/codelabs/imgs/shared/offline.png
  src/content/en/tools/workbox/guides/codelabs/imgs/shared/push.png
  src/content/en/tools/workbox/guides/codelabs/imgs/shared/sources.png
  src/content/en/tools/workbox/guides/codelabs/imgs/shared/sw-pane.png
  src/content/en/tools/workbox/guides/codelabs/imgs/webpack/add-package.png
  src/content/en/tools/workbox/guides/codelabs/imgs/webpack/demo.png
  src/content/en/tools/workbox/guides/codelabs/npm-script.md
  src/content/en/tools/workbox/guides/codelabs/webpack.md
  src/content/en/tools/workbox/guides/precache-files/cli.md
  src/content/en/tools/workbox/guides/precache-files/index.md
  src/content/en/tools/workbox/guides/precache-files/webpack.md
  src/content/en/tools/workbox/guides/precache-files/workbox-build.md
Labels: cla: yes

#9102 Add jobay as contributor
  src/content/en/images/contributors/jobay.jpg
  src/data/_contributors.yaml
Labels: cla: yes

#9103 [devtools-blog] Puppetaria - Johan
  src/content/en/updates/2020/11/puppetaria.md
  src/content/en/updates/_shared/discover-devtools-blog.md
  src/content/en/updates/images/2020/11/puppetaria/puppetaria-01.jpg
  src/content/en/updates/images/2020/11/puppetaria/puppetaria-02.svg
  src/content/en/updates/images/2020/11/puppetaria/puppetaria-03.svg
  src/content/en/updates/images/2020/11/puppetaria/puppetaria-04.svg
  src/content/en/updates/images/2020/11/puppetaria/puppetaria.png
Labels: P1, cla: yes, content-new, section-tools, type-Content

#9107 [devtools] Add video for WNDT 87
  src/content/en/updates/2020/10/devtools.md
Labels: cla: yes

#9110 [devtools] Add CSS <angle> guide
  src/content/en/tools/chrome-devtools/css/imgs/angle-clock.png
  src/content/en/tools/chrome-devtools/css/imgs/angle-preview.png
  src/content/en/tools/chrome-devtools/css/imgs/pseudo-class.png
  src/content/en/tools/chrome-devtools/css/reference.md
  src/content/en/tools/chrome-devtools/shortcuts.md
Labels: cla: yes, content-updated, section-tools, type-Content

#9094 fix a typo
  src/content/en/tools/workbox/guides/route-requests.md
Labels: cla: yes

#9104 Adds a Trusted Web Activity / Web share target how-to
  src/content/en/android/trusted-web-activity/_toc.yaml
  src/content/en/android/trusted-web-activity/integration-guide/index.md
  src/content/en/android/trusted-web-activity/web-share-target/index.md
Labels: cla: yes, type-Content

#9106 jankfree[.]com is no longer a valid domain, and it's up for sale.
  src/content/en/updates/2013/02/Profiling-Long-Paint-Times-with-DevTools-Continuous-Painting-Mode.md
Labels: cla: yes

#9111 [devtools] What's New In DevTools (Chrome 88)
  src/content/en/updates/2020/11/devtools.md
  src/content/en/updates/_shared/discover.md
  src/content/en/updates/images/2020/11/devtools/01-css-angle.png
  src/content/en/updates/images/2020/11/devtools/02-emulate-image-type.png
  src/content/en/updates/images/2020/11/devtools/03-storage-quota.png
  src/content/en/updates/images/2020/11/devtools/04-web-vitals-lane.png
  src/content/en/updates/images/2020/11/devtools/05-cors-err.png
  src/content/en/updates/images/2020/11/devtools/06-frame-cross-origin-isolated-api.png
  src/content/en/updates/images/2020/11/devtools/07-frame-worker.png
  src/content/en/updates/images/2020/11/devtools/08-frame-opener.png
  src/content/en/updates/images/2020/11/devtools/09-sw-network-request.png
  src/content/en/updates/images/2020/11/devtools/10-copy-prop-value.png
  src/content/en/updates/images/2020/11/devtools/11-copy-stacktrace.png
  src/content/en/updates/images/2020/11/devtools/12-wasm-mouseover.png
  src/content/en/updates/images/2020/11/devtools/13-flex-debugging.png
  src/content/en/updates/images/2020/11/devtools/14-keyboard-shortcuts.png
Labels: P1, cla: yes, content-new, section-tools, type-Content

#9114 [devtools] Update CSS <angle> screenshot
  src/content/en/updates/2020/11/devtools.md
  src/content/en/updates/images/2020/11/devtools/01-angle.png
  src/content/en/updates/images/2020/11/devtools/01-css-angle.png
Labels: P1, cla: yes, content-updated, section-tools, type-Content

#9122 Update my description
  src/data/_contributors.yaml
Labels: cla: yes

#9123 New in Chrome 87
  src/content/en/updates/2020/11/nic87.md
  src/content/en/updates/_redirects.yaml
  src/content/en/updates/images/2020/11/camera-ptz-user-prompt.jpg
  src/content/en/updates/images/2020/11/nic87.png
  src/content/en/updates/images/2020/11/photopea.png
Labels: cla: yes

#9011 [WIP] Adds Workbox Migrate from v5 to v6 guide
  src/content/en/tools/workbox/guides/_toc.yaml
  src/content/en/tools/workbox/guides/migrations/migrate-from-v5.md
Labels: cla: yes, type-Content

#9116 Support webp and avif image formats in WebFu
  app.yaml
  gulp-tasks/test.js
Labels: cla: yes

#9115 [devtools-blog] Simulate CVD in the Blink Renderer
  src/content/en/tools/workbox/guides/migrations/migrate-from-v5.md
  src/content/en/updates/2020/11/cvd.md
  src/content/en/updates/images/2020/11/cvd/0-regular.avif
  src/content/en/updates/images/2020/11/cvd/0-regular.png
  src/content/en/updates/images/2020/11/cvd/0-regular.webp
  src/content/en/updates/images/2020/11/cvd/0-regular@2x.avif
  src/content/en/updates/images/2020/11/cvd/0-regular@2x.png
  src/content/en/updates/images/2020/11/cvd/0-regular@2x.webp
  src/content/en/updates/images/2020/11/cvd/1-achromatopsia.avif
  src/content/en/updates/images/2020/11/cvd/1-achromatopsia.png
  src/content/en/updates/images/2020/11/cvd/1-achromatopsia.webp
  src/content/en/updates/images/2020/11/cvd/1-achromatopsia@2x.avif
  src/content/en/updates/images/2020/11/cvd/1-achromatopsia@2x.png
  src/content/en/updates/images/2020/11/cvd/1-achromatopsia@2x.webp
  src/content/en/updates/images/2020/11/cvd/2-deuteranopia.avif
  src/content/en/updates/images/2020/11/cvd/2-deuteranopia.png
  src/content/en/updates/images/2020/11/cvd/2-deuteranopia.webp
  src/content/en/updates/images/2020/11/cvd/2-deuteranopia@2x.avif
  src/content/en/updates/images/2020/11/cvd/2-deuteranopia@2x.png
  src/content/en/updates/images/2020/11/cvd/2-deuteranopia@2x.webp
  src/content/en/updates/images/2020/11/cvd/3-protanopia.avif
  src/content/en/updates/images/2020/11/cvd/3-protanopia.png
  src/content/en/updates/images/2020/11/cvd/3-protanopia.webp
  src/content/en/updates/images/2020/11/cvd/3-protanopia@2x.avif
  src/content/en/updates/images/2020/11/cvd/3-protanopia@2x.png
  src/content/en/updates/images/2020/11/cvd/3-protanopia@2x.webp
  src/content/en/updates/images/2020/11/cvd/4-tritanopia.avif
  src/content/en/updates/images/2020/11/cvd/4-tritanopia.png
  src/content/en/updates/images/2020/11/cvd/4-tritanopia.webp
  src/content/en/updates/images/2020/11/cvd/4-tritanopia@2x.avif
  src/content/en/updates/images/2020/11/cvd/4-tritanopia@2x.png
  src/content/en/updates/images/2020/11/cvd/4-tritanopia@2x.webp
  src/content/en/updates/images/2020/11/cvd/common-a11y-issues.svg
  src/content/en/updates/images/2020/11/cvd/cvd.png
Labels: DO NOT MERGE, cla: yes, content-new, section-tools, type-Content

#9127 [devtools-blog] Remove unused ID
  src/content/en/updates/2020/11/cvd.md
Labels: cla: yes

#9129 Attempt to fix minification issue on live site
  src/content/en/updates/2020/11/cvd.md
Labels: cla: yes

#9130 [devtools-blog] Attempt to fix deployment
  src/content/en/updates/2020/11/cvd.md
  src/content/en/updates/images/2020/11/cvd/0-regular-2x.avif
  src/content/en/updates/images/2020/11/cvd/0-regular-2x.png
  src/content/en/updates/images/2020/11/cvd/0-regular-2x.webp
  src/content/en/updates/images/2020/11/cvd/1-achromatopsia-2x.avif
  src/content/en/updates/images/2020/11/cvd/1-achromatopsia-2x.png
  src/content/en/updates/images/2020/11/cvd/1-achromatopsia-2x.webp
  src/content/en/updates/images/2020/11/cvd/2-deuteranopia-2x.avif
  src/content/en/updates/images/2020/11/cvd/2-deuteranopia-2x.png
  src/content/en/updates/images/2020/11/cvd/2-deuteranopia-2x.webp
  src/content/en/updates/images/2020/11/cvd/3-protanopia-2x.avif
  src/content/en/updates/images/2020/11/cvd/3-protanopia-2x.png
  src/content/en/updates/images/2020/11/cvd/3-protanopia-2x.webp
  src/content/en/updates/images/2020/11/cvd/4-tritanopia-2x.avif
  src/content/en/updates/images/2020/11/cvd/4-tritanopia-2x.png
  src/content/en/updates/images/2020/11/cvd/4-tritanopia-2x.webp
Labels: cla: yes

#9126 [devtools] Update WNDT88 to include Wasm and Pseudo element updates
  src/content/en/updates/2020/11/cvd.md
  src/content/en/updates/2020/11/devtools.md
  src/content/en/updates/2020/11/puppetaria.md
  src/content/en/updates/_shared/discover-devtools-blog.md
  src/content/en/updates/_shared/discover.md
  src/content/en/updates/images/2020/11/devtools/12-wasm-console.png
  src/content/en/updates/images/2020/11/devtools/15-pseudo.png
Labels: P1, cla: yes, content-updated, section-tools, type-Content

#9134 workbox/guides/advanced-recipes: fix snippet typo
  src/content/en/tools/workbox/guides/advanced-recipes.md
Labels: cla: yes

#9141 Small fixes to the TWA docs
  src/content/en/android/trusted-web-activity/android-browser-helper-migration/index.md
  src/content/en/android/trusted-web-activity/web-share-target/index.md
Labels: cla: yes, content-updated

#9137 Add link about cost transparency
  src/content/en/fundamentals/design-and-ux/responsive/content.md
Labels: cla: yes

#9135 Chromium Chronicle Ep 15
  src/content/en/updates/2020/11/chromium-chronicle.md
  src/content/en/updates/2020/11/nic87.md
Labels: cla: yes

#9125 Fix typo in nic87.md
  src/content/en/updates/2020/11/nic87.md
Labels: cla: yes

#9118 Feature/workbox recipes
  src/content/en/tools/workbox/_index.yaml
  src/content/en/tools/workbox/modules/_index.yaml
  src/content/en/tools/workbox/modules/_toc.yaml
  src/content/en/tools/workbox/modules/workbox-recipes.md
Labels: cla: yes

#9019 Updates Workbox strategies guide to include section on custom strategies
  src/content/en/tools/workbox/modules/workbox-strategies.md
Labels: cla: yes, type-Content

#9017 Update Workbox "Using Plugins" documentation
  src/content/en/tools/workbox/guides/using-plugins.md
Labels: DO NOT MERGE, cla: yes, type-Content
