Repository google/WebFundamentals, pull requests merged in 2020-01, with the labels that each got.

#6177 [Translate ru] Agencies -> index
  src/content/ru/agencies/_index.yaml
Labels: cla: yes, type-Content-Translation

#6194 [Translate ru] feedback -> file a bug
  src/content/ru/feedback/file-a-bug.md
Labels: cla: yes, type-Content-Translation

#6245 [Translate ru] Accessibility -> a11y-for-teams
  src/content/ru/fundamentals/accessibility/a11y-for-teams.md
Labels: cla: yes, type-Content-Translation

#6313 [Translate ru] Accessibility -> a11y-styles
  src/content/ru/fundamentals/accessibility/accessible-styles.md
Labels: cla: yes, type-Content-Translation

#6454 [Translate ru] Accessibility ->how-to-review
  src/content/ru/fundamentals/accessibility/how-to-review.md
Labels: cla: yes, type-Content-Translation

#6573 [Translate ru] Accessibility ->index
  src/content/ru/fundamentals/accessibility/index.md
Labels: cla: yes, type-Content-Translation

#8375 Updates using-twa to use android-browser-helper
  src/content/en/updates/2019/02/using-twa.md
Labels: cla: yes

#8377 Fix version number in title.
  src/content/en/updates/2019/12/chrome-80-deps-rems.md
Labels: cla: yes

#8383 Introducing android-browser-helper update
  src/content/en/images/contributors/andreban.jpg
  src/content/en/updates/2020/twa-android-browser-helper.md
  src/data/_contributors.yaml
Labels: cla: yes

#8368 Fixed Typo in Full Screen Video method #8330
  src/content/en/fundamentals/media/video.md
Labels: cla: yes

#8384 Fix build to deploy
  src/content/ru/agencies/_index.yaml
  src/content/ru/resources/writing-an-update.md
Labels: cla: yes

#6842 [Translate ru] web-components/customelements
  src/content/ru/fundamentals/web-components/customelements.md
Labels: cla: yes, type-Content-Translation

#8382 Update Capabilities landing page
  src/content/en/updates/capabilities.md
Labels: cla: yes, content-updated

#8394 Add redirect for prefers-reduced-motion article
  src/content/en/updates/_redirects.yaml
Labels: cla: yes

#8392 Fix typo in Microsoft OS descriptor
  src/content/en/fundamentals/native-hardware/build-for-webusb/index.md
Labels: cla: yes

#8412 Wrong date on 203
  src/content/en/shows/http203/podcast/observables-board-games-and-artechulate.md
Labels: cla: yes

#8399 Adds the Multi Origin TWA Blogpost
  src/content/en/updates/2020/01/twa-multi-origin.md
  src/content/en/updates/images/2020/01/twa-multi-origin/off-origin-navigation.gif
Labels: cla: yes

#8387 Fixes blogpost location
  src/content/en/_redirects.yaml
  src/content/en/updates/2020/01/twa-android-browser-helper.md
Labels: cla: yes

#8367 Fixed error in url #8362
  src/content/en/ilt/pwa/lab-indexeddb.md
Labels: cla: yes

#8366 Fixed a typo #8359
  src/content/en/ilt/pwa/lab-scripting-the-service-worker.md
Labels: cla: yes

#8419 URL updates in feature policy samples
  src/content/en/updates/2018/06/feature-policy.md
Labels: cla: yes

#8422 Add the Workbox v5 upgrade guide to the sidebar
  src/content/en/tools/workbox/guides/_toc.yaml
Labels: cla: yes, section-tools, type-Content

#8425 Fix typo in rollup plugin name
  src/content/en/tools/workbox/guides/using-bundlers.md
Labels: cla: yes

#8423 Add What's New In DevTools (Chrome 81)
  src/content/en/updates/2019/10/devtools.md
  src/content/en/updates/2019/12/devtools.md
  src/content/en/updates/2020/01/devtools.md
  src/content/en/updates/_shared/canary.md
  src/content/en/updates/_shared/devtools-feedback.md
  src/content/en/updates/_shared/discover.md
  src/content/en/updates/images/2020/01/blockedcookies.png
  src/content/en/updates/images/2020/01/editcookie.png
  src/content/en/updates/images/2020/01/escapedstring.png
  src/content/en/updates/images/2020/01/fetchcookies.png
  src/content/en/updates/images/2020/01/manifesticons.png
  src/content/en/updates/images/2020/01/motog4.png
  src/content/en/updates/images/2020/01/motog4frame.png
  src/content/en/updates/images/2020/01/sourcemap.png
  src/content/en/updates/images/2020/01/unescapedstring.png
Labels: cla: yes, content-new, section-tools, type-Content

#8426 Update workbox latest version and jsdoc template
  package.json
  src/content/en/tools/workbox/_shared/workbox-latest-version.html
  src/content/en/tools/workbox/_shared/workbox-sw-cdn-url.html
Labels: cla: yes, section-tools, type-Content

#8428 workbox-expiration URL change
  src/content/en/tools/_redirects.yaml
  src/content/en/tools/workbox/guides/migrations/migrate-from-v4.md
  src/content/en/tools/workbox/modules/_index.yaml
  src/content/en/tools/workbox/modules/workbox-expiration.md
Labels: cla: yes
