Repository google/WebFundamentals, pull requests merged in 2020-02, with the labels that each got.

#8431 Fix an incorrect link in workbox-webpack-plugin guide
  src/content/en/tools/workbox/modules/workbox-webpack-plugin.md
Labels: cla: yes

#8435 New in Chrome 80
  src/content/en/updates/2020/02/nic80.md
  src/content/en/updates/_redirects.yaml
  src/content/en/updates/images/2020/02/new-80.jpg
Labels: cla: yes

#8436 Chromium Chronicle
  src/content/en/updates/2020/02/chromium-chronicle.md
  src/content/en/updates/images/2020/02/cc12-omnibox.png
Labels: cla: yes

#8461 Update source map errors section in WNDT81
  src/content/en/updates/2020/01/devtools.md
  src/content/en/updates/images/2020/01/sourcemap.png
Labels: cla: yes, type-Content

#8464 Fix formatting issues on the Workbox homepage
  src/content/en/tools/workbox/_index.yaml
Labels: cla: yes, section-tools, type-Content

#8465 CrUX Notifications Post
  src/content/en/updates/2020/02/notification-permission-data-in-crux.md
  src/content/en/updates/images/2020/02/crux-gnews.png
  src/data/_contributors.yaml
Labels: cla: yes

#8466 Fix a typo
  src/content/zh-cn/fundamentals/performance/why-performance-matters/index.md
Labels: cla: yes

#8393 CrUX changelog
  src/content/en/tools/chrome-user-experience-report/_toc.yaml
  src/content/en/tools/chrome-user-experience-report/changelog.md
  src/content/en/tools/chrome-user-experience-report/images/logo.png
  src/content/en/tools/chrome-user-experience-report/index.md
Labels: cla: yes

#8471 Small fix in Workbox module docs
  src/content/en/tools/workbox/modules/workbox-broadcast-update.md
Labels: cla: yes

#8467 Crux not
  src/content/en/images/contributors/pjmclachlan.jpg
  src/content/en/updates/2020/02/notification-permission-data-in-crux.md
Labels: cla: yes

#8474 More Workbox docs typo fixes
  src/content/en/tools/workbox/modules/workbox-strategies.md
Labels: cla: yes

#8473 Mention timezone emulation
  src/content/en/updates/2019/10/devtools.md
Labels: cla: yes

#8477 Deprecate KV storage
  src/content/en/updates/2019/03/kv-storage.md
Labels: cla: yes

#8495 Add GitLocalize configuration file
  .gitlocalize.yml
Labels: cla: yes

#8491 Redirect older metrics articles to web.dev
  src/content/en/_redirects.yaml
  src/content/en/fundamentals/performance/images/perf-metrics-hero-elements.png
  src/content/en/fundamentals/performance/images/perf-metrics-histogram.png
  src/content/en/fundamentals/performance/images/perf-metrics-load-timeline.png
  src/content/en/fundamentals/performance/images/perf-metrics-long-tasks.png
  src/content/en/fundamentals/performance/images/perf-metrics-test-cycle.png
  src/content/en/fundamentals/performance/images/perf-metrics-tti-mobile-v-desktop.png
  src/content/en/fundamentals/performance/user-centric-performance-metrics.md
  src/content/en/updates/2018/05/first-input-delay.md
  src/content/en/updates/images/2018/05/first-input-delay-base.svg
  src/content/en/updates/images/2018/05/first-input-delay-fcp-tti.svg
  src/content/en/updates/images/2018/05/first-input-delay-full.svg
Labels: cla: yes, section-fundamentals, section-updates, type-Content

#8433 Trusted Web Activities, the Lay of the Land
  src/content/en/updates/2020/02/twa-lay-of-the-land.md
Labels: cla: yes

#8417 Fixed "input" element typo #8402
  src/content/en/fundamentals/accessibility/semantics-builtin/the-accessibility-tree.md
Labels: cla: yes

#8509 Add MDN compat survey banner
  src/content/en/_project.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/site-kit/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes

#8511 Add link to web.dev article on image support to Async Clipboard article
  src/content/en/updates/2018/03/clipboardapi.md
Labels: cla: yes

#8510 fugu page update
  src/content/en/updates/capabilities.md
Labels: cla: yes

#8513 MDN Compat Survey Banner
  src/content/en/_project.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/site-kit/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes

#8508 Removes & redirect PWA content to web.dev
  src/content/en/_footer.yaml
  src/content/en/_index.yaml
  src/content/en/_redirects.yaml
  src/content/en/fundamentals/_redirects.yaml
  src/content/en/fundamentals/app-install-banners/index.md
  src/content/en/fundamentals/app-install-banners/native.md
  src/content/en/fundamentals/app-install-banners/promoting-install-mobile.md
  src/content/en/fundamentals/design-and-ux/_toc.yaml
  src/content/en/fundamentals/integration/_toc.yaml
  src/content/en/fundamentals/integration/webapks.md
  src/content/en/fundamentals/security/prevent-mixed-content/_code/active-mixed-content.html
  src/content/en/fundamentals/security/prevent-mixed-content/_code/image-gallery-example.html
  src/content/en/fundamentals/security/prevent-mixed-content/_code/passive-mixed-content.html
  src/content/en/fundamentals/web-app-manifest/images/background-color.gif
  src/content/en/fundamentals/web-app-manifest/images/devtools-manifest.png
  src/content/en/fundamentals/web-app-manifest/images/homescreen-icon.png
  src/content/en/fundamentals/web-app-manifest/images/manifest-display-options.png
  src/content/en/fundamentals/web-app-manifest/images/manifest-orientation-options.png
  src/content/en/fundamentals/web-app-manifest/images/theme-color.png
  src/content/en/fundamentals/web-app-manifest/index.md
  src/content/en/images/web-dev-logo.png
  src/content/en/progressive-web-apps/_book.yaml
  src/content/en/progressive-web-apps/_index.yaml
  src/content/en/progressive-web-apps/checklist.md
  src/content/en/progressive-web-apps/desktop.md
  src/content/en/progressive-web-apps/styles/wf-pwa.css
  src/content/es/fundamentals/web-app-manifest/index.md
  src/content/id/fundamentals/web-app-manifest/index.md
  src/content/it/progressive-web-apps/desktop.md
Labels: cla: yes

#8519 Deprecations and removals for Chrome 81.
  src/content/en/updates/2018/12/chrome-72-deps-rems.md
  src/content/en/updates/2020/02/chrome-81-deps-rems.md
Labels: cla: yes

#8520 Fix a few typos found in the clipboard article
  src/content/en/updates/2018/03/clipboardapi.md
Labels: cla: yes
