Repository google/WebFundamentals, pull requests merged in 2020-04, with the labels that each got.

#8606 Typo fix in Workbox docs
  src/content/en/tools/workbox/modules/workbox-strategies.md
Labels: cla: yes

#8605 Correct section on locale emulation
  src/content/en/updates/2020/03/devtools.md
Labels: cla: yes

#8608 Add COVID banner to pages
  src/content/en/_project.yaml
  src/content/en/android/_project.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/site-kit/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/chrome-user-experience-report/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes

#8612 Fix nits in Web NFC section
  src/content/en/updates/2020/04/nic81.md
Labels: cla: yes

#8613 Redirect the Promises guide to web.dev
  src/content/en/fundamentals/_toc-base.yaml
  src/content/en/fundamentals/primers/_redirects.yaml
  src/content/en/fundamentals/primers/promises.md
Labels: DO NOT MERGE, cla: yes, type-Content

#8614 Redirect the HTTPS overview
  src/content/en/fundamentals/security/_redirects.yaml
  src/content/en/fundamentals/security/_toc.yaml
  src/content/en/fundamentals/security/encrypt-in-transit/why-https.md
Labels: DO NOT MERGE, cla: yes, type-Content

#8621 Rename bindings to entries in GPU Compute article
  src/content/en/updates/2019/08/get-started-with-gpu-compute-on-the-web.md
Labels: cla: yes

#8628 Fix link to M81 deps&rems article
  src/content/en/updates/2020/04/nic81.md
Labels: cla: yes

#8627 Update /nic to M81
  src/content/en/updates/_redirects.yaml
Labels: cla: yes

#8633 Added an option to enable in GitLocalize special front matter treatment
  .gitlocalize.yml
Labels: cla: yes

#8632 fix broken links that accidentally start with http://localhost:8080/
  src/content/en/fundamentals/performance/audit/next.md
  src/content/en/updates/2020/01/devtools.md
Labels: cla: yes

#8630 Update performance budget docs
  src/content/en/tools/lighthouse/audits/budgets.md
Labels: cla: yes

#8634 Added redirect to the Trusted Types article.
  src/content/en/_redirects.yaml
  src/content/en/updates/2019/02/trusted-types.md
Labels: cla: yes

#8635 Add CrUX 202003 release notes to change log
  src/content/en/tools/chrome-user-experience-report/changelog.md
Labels: cla: yes

#8623 Add deprecations and removals for Chrome 83.
  src/content/en/updates/2020/04/chrome-83-deps-rems.md
Labels: cla: yes

#8604 Small update to the Payment Handler article
  src/content/en/fundamentals/payments/payment-apps-developer-guide/web-payment-apps.md
Labels: P2, cla: yes, content-updated, section-fundamentals, type-Content

#8615 Update mixed content article to reflect plans to upgrade/block passive mixed content
  src/content/en/fundamentals/security/prevent-mixed-content/what-is-mixed-content.md
Labels: cla: yes

#8643 [8629] - Replace broken link
  src/content/en/updates/2016/08/removing-document-write.md
Labels: cla: yes

#8637 update pwacompat to point to unpkg
  src/content/en/updates/2018/07/pwacompat.md
Labels: cla: yes

#8650 Fix missed Workbox v5 documenation change
  src/content/en/tools/workbox/guides/using-bundlers.md
Labels: cla: yes

#8651 [GitLocalize] Advise contributors that translations are no longer rev…
  .gitlocalize.yml
Labels: cla: yes

#8661 Updates Trusted Web Activity docs
  src/content/en/android/trusted-web-activity/android-browser-helper-migration/index.md
  src/content/en/android/trusted-web-activity/index.md
  src/content/en/android/trusted-web-activity/integration-guide/index.md
Labels: cla: yes, content-updated

#8660 Remove & redirect migrated docs
  src/content/en/fundamentals/_redirects.yaml
  src/content/en/fundamentals/_toc-base.yaml
  src/content/en/fundamentals/discovery/_redirects.yaml
  src/content/en/fundamentals/discovery/search-optimization/imgs/different_url-2x.png
  src/content/en/fundamentals/discovery/search-optimization/imgs/different_url.png
  src/content/en/fundamentals/discovery/search-optimization/imgs/remove-urls-2x.png
  src/content/en/fundamentals/discovery/search-optimization/imgs/remove-urls.png
  src/content/en/fundamentals/discovery/search-optimization/imgs/responsive-2x.png
  src/content/en/fundamentals/discovery/search-optimization/imgs/responsive.png
  src/content/en/fundamentals/discovery/search-optimization/imgs/robots-txt-validator-2x.png
  src/content/en/fundamentals/discovery/search-optimization/imgs/robots-txt-validator.png
  src/content/en/fundamentals/discovery/search-optimization/imgs/same_url-2x.png
  src/content/en/fundamentals/discovery/search-optimization/imgs/same_url.png
  src/content/en/fundamentals/discovery/search-optimization/index.md
  src/content/en/fundamentals/instant-and-offline/web-storage/cache-api.md
  src/content/en/fundamentals/integration/_toc.yaml
  src/content/en/fundamentals/performance/_toc.yaml
Labels: cla: yes

#8671 Update to the matchCb and handlerCb description
  src/content/en/tools/workbox/modules/workbox-routing.md
Labels: cla: yes

#8673 Remove & redirect outdated storage articles
  src/content/en/fundamentals/_redirects.yaml
  src/content/en/fundamentals/instant-and-offline/web-storage/index.md
  src/content/en/fundamentals/instant-and-offline/web-storage/offline-for-pwa.md
  src/content/en/fundamentals/performance/_toc.yaml
  src/content/en/updates/2011/11/Quota-Management-API-Fast-Facts.md
  src/content/en/updates/_redirects.yaml
Labels: cla: yes
