Repository google/WebFundamentals, pull requests merged in 2020-05, with the labels that each got.

#8676 Android Payment Apps developer's guide update
  src/content/en/fundamentals/payments/payment-apps-developer-guide/android-payment-apps.md
Labels: cla: yes, content-updated, section-fundamentals, type-Content

#8680 Use matchCallbacks instead of RegExps in Workbox docs
  src/content/en/tools/workbox/_index.yaml
  src/content/en/tools/workbox/guides/advanced-recipes.md
  src/content/en/tools/workbox/guides/codelabs/_shared/create.md
  src/content/en/tools/workbox/guides/codelabs/webpack.md
  src/content/en/tools/workbox/guides/common-recipes.md
  src/content/en/tools/workbox/guides/configure-workbox.md
  src/content/en/tools/workbox/guides/get-started.md
  src/content/en/tools/workbox/guides/route-requests.md
  src/content/en/tools/workbox/guides/storage-quota.md
  src/content/en/tools/workbox/guides/using-bundlers.md
  src/content/en/tools/workbox/guides/using-plugins.md
  src/content/en/tools/workbox/modules/workbox-broadcast-update.md
  src/content/en/tools/workbox/modules/workbox-cacheable-response.md
  src/content/en/tools/workbox/modules/workbox-expiration.md
  src/content/en/tools/workbox/modules/workbox-range-requests.md
  src/content/en/tools/workbox/modules/workbox-strategies.md
  src/content/en/tools/workbox/modules/workbox-sw.md
Labels: cla: yes

#8686 Redirect Lighthouse pages to new resources
  src/content/en/tools/_redirects.yaml
  src/content/en/tools/lighthouse/_toc.yaml
Labels: cla: yes, type-Content

#8687 Remove COOP support
  src/content/en/updates/2020/03/devtools.md
Labels: cla: yes

#8685 Updates TWA QuickStart to point to Bubblewrap
  src/content/en/android/trusted-web-activity/quick-start/index.md
Labels: cla: yes, content-updated

#8688 Update footer
  src/content/en/_footer.yaml
Labels: cla: yes

#8690 Remove the TTFB and unload examples
  src/content/en/fundamentals/performance/navigation-and-resource-timing/index.md
Labels: cla: yes

#8696 Another update to skipWating recipe
  src/content/en/tools/workbox/guides/advanced-recipes.md
Labels: cla: yes

#8697 Remove CrUX docs from WebFu
  gulp-tasks/test.js
  src/content/en/fundamentals/security/hacked/_README.md
  src/content/en/tools/chrome-user-experience-report/_README.md
  src/content/en/tools/chrome-user-experience-report/_footer.yaml
  src/content/en/tools/chrome-user-experience-report/_project.yaml
  src/content/en/tools/chrome-user-experience-report/_toc.yaml
  src/content/en/tools/chrome-user-experience-report/changelog.md
  src/content/en/tools/chrome-user-experience-report/getting-started.md
  src/content/en/tools/chrome-user-experience-report/images/bq-compose.png
  src/content/en/tools/chrome-user-experience-report/images/bq-welcome.png
  src/content/en/tools/chrome-user-experience-report/images/dataset.png
  src/content/en/tools/chrome-user-experience-report/images/fcp-histogram.png
  src/content/en/tools/chrome-user-experience-report/images/gcp-project.png
  src/content/en/tools/chrome-user-experience-report/images/logo.png
  src/content/en/tools/chrome-user-experience-report/index.md
Labels: cla: yes

#8689 Refactor redirects & add redirect for persistent storage
  src/content/en/_redirects.yaml
  src/content/en/fundamentals/_redirects.yaml
  src/content/en/updates/2016/06/persistent-storage.md
  src/content/en/updates/_redirects.yaml
Labels: cla: yes

#8694 add note to native install banners
  src/content/en/fundamentals/app-install-banners/native.md
Labels: cla: yes

#8700 Add What's New In DevTools (Chrome 84)
  src/content/en/updates/2020/05/devtools.md
  src/content/en/updates/images/2020/05/a11y.jpg
  src/content/en/updates/images/2020/05/cls.jpg
  src/content/en/updates/images/2020/05/color.jpg
  src/content/en/updates/images/2020/05/fulfilled.jpg
  src/content/en/updates/images/2020/05/image-preview.jpg
  src/content/en/updates/images/2020/05/issues.jpg
  src/content/en/updates/images/2020/05/properties.jpg
  src/content/en/updates/images/2020/05/resolved.jpg
  src/content/en/updates/images/2020/05/revert.jpg
  src/content/en/updates/images/2020/05/tbt.jpg
Labels: DO NOT MERGE, cla: yes, type-Content

#8704 DevTools Issues tab article
  src/content/en/tools/chrome-devtools/_toc.yaml
  src/content/en/tools/chrome-devtools/issues/images/issues-tab-affected-resources.png
  src/content/en/tools/chrome-devtools/issues/images/issues-tab-after-reload.png
  src/content/en/tools/chrome-devtools/issues/images/issues-tab-before-reload.png
  src/content/en/tools/chrome-devtools/issues/images/issues-tab-issue-open.png
  src/content/en/tools/chrome-devtools/issues/images/issues-tab-view-issue.png
  src/content/en/tools/chrome-devtools/issues/images/issues-tab-view-request.png
  src/content/en/tools/chrome-devtools/issues/images/more-tools-menu.png
  src/content/en/tools/chrome-devtools/issues/images/open-issues-tab.png
  src/content/en/tools/chrome-devtools/issues/index.md
Labels: cla: yes

#8706 Heavy ad interventions
  src/content/en/images/contributors/rowanmerewood.jpg
  src/content/en/updates/2020/05/heavy-ad-interventions.md
  src/content/en/updates/images/2020/05/heavy-ad-01.png
  src/content/en/updates/images/2020/05/heavy-ad-02.png
  src/content/en/updates/images/2020/05/heavy-ad-03.png
  src/content/en/updates/images/2020/05/heavy-ad-04.png
  src/content/en/updates/images/2020/05/heavy-ad-05.png
  src/content/en/updates/images/2020/05/heavy-ad-06.png
  src/content/en/updates/images/2020/05/heavy-ad-07.png
  src/data/_contributors.yaml
Labels: cla: yes, content-new, section-updates

#8703 Delete & redirect variable fonts guide
  src/content/en/fundamentals/_redirects.yaml
  src/content/en/fundamentals/design-and-ux/_toc.yaml
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/images/Amstelvar-Alpha-example.png
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/images/Amstelvar-Ital-axis.png
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/images/amstel-grade-e.gif
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/images/axis-praxis.gif
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/images/gingham-weight-e.gif
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/images/grass-mandy.png
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/images/robot-specimen.png
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/images/roboto-family.png
  src/content/en/fundamentals/design-and-ux/typography/variable-fonts/index.md
Labels: DO NOT MERGE, cla: yes, type-Content, type-Infrastructure

#8705 Fixed image URLs on Issues tab article
  src/content/en/tools/chrome-devtools/issues/images/issues-tab-affected-resources.png
  src/content/en/tools/chrome-devtools/issues/index.md
Labels: cla: yes

#8708 Update index.md with last changes
  src/content/en/tools/chrome-devtools/issues/index.md
Labels: cla: yes

#8693 Update DevTools breakpoint images and text
  src/content/en/updates/2020/03/devtools.md
  src/content/en/updates/images/2020/03/breakpoint.png
  src/content/en/updates/images/2020/03/conditional.png
  src/content/en/updates/images/2020/03/logpoint.png
Labels: cla: yes

#8714 Parameter in precacheAndRoute code sample changed to reflect v5
  src/content/en/tools/workbox/guides/precache-files/workbox-build.md
Labels: cla: yes

#8717 New in Chrome 83 post
  src/content/en/updates/2020/05/nic83.md
  src/content/en/updates/images/2020/05/forms-after.png
  src/content/en/updates/images/2020/05/forms-before.png
  src/content/en/updates/images/2020/05/forms-focus-ring.gif
  src/content/en/updates/images/2020/05/new-83.jpg
  src/content/en/updates/images/2020/05/vitals-core.jpg
Labels: cla: yes

#8707 Update to the Issues tab snippet
  src/content/en/updates/2020/05/devtools.md
  src/content/en/updates/_shared/discover.md
  src/content/en/updates/images/2020/05/issues.jpg
  src/content/en/updates/images/2020/05/issues.png
Labels: cla: yes

#8715 Adds PWABuilder as a GUI alternative for Bubblewrap
  src/content/en/android/trusted-web-activity/integration-guide/index.md
  src/content/en/android/trusted-web-activity/quick-start/index.md
Labels: cla: yes

#8718 moving Responsive Web Design Basics
  src/content/en/_redirects.yaml
  src/content/en/fundamentals/design-and-ux/_toc.yaml
  src/content/en/fundamentals/design-and-ux/responsive/imgs/devtools-media-queries-example.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/mq-2x.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/mq.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/no-vp-2x.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/no-vp.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/reading-de-2x.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/reading-de.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/reading-ph-2x.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/reading-ph.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/vp-2x.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/vp-fixed-iph-2x.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/vp-fixed-iph.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/vp-fixed-n5-2x.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/vp-fixed-n5.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/vp.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/weather-1-2x.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/weather-1.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/weather-2-2x.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/weather-2.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/weather-3-2x.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/weather-3.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/weather-4-l-2x.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/weather-4-l.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/weather-4-r-2x.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/weather-4-r.png
  src/content/en/fundamentals/design-and-ux/responsive/imgs/webpagetest-first-and-repeat.png
  src/content/en/fundamentals/design-and-ux/responsive/index.md
Labels: cla: yes

#8716 Add app shortcuts to what's new in DevTools (Chrome 84)
  src/content/en/updates/2020/05/devtools.md
  src/content/en/updates/images/2020/05/app-shortcuts.png
Labels: cla: yes, content-updated, type-Content

#8721 Remove CrUX from _book.yaml
  src/content/en/tools/_book.yaml
Labels: cla: yes

#8731 fix broken demo link
  src/content/en/updates/2018/06/payment-handler-api.md
Labels: cla: yes

#8730 Redirect ResizeObserver article.
  src/content/en/_redirects.yaml
  src/content/en/updates/2016/10/resizeobserver.md
Labels: cla: yes

#8724 Remove extra word in get-started.md
  src/content/en/tools/chrome-devtools/speed/get-started.md
Labels: cla: yes

#8723 Figure X replaced respectively by Figure 8 and Figure 9
  src/content/en/tools/chrome-devtools/console/reference.md
Labels: cla: yes

#8722 web.dev/live promo banner & home screen promo
  src/content/en/_index.yaml
  src/content/en/_project.yaml
  src/content/en/android/_project.yaml
  src/content/en/feedback/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/images/wd-live-wide.png
  src/content/en/images/wd-live.png
  src/content/en/site-kit/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes

#8720 Fix one zh-cn translatation error
  src/content/zh-cn/fundamentals/performance/http2/index.md
Labels: cla: yes

#8732 llama-pack => Bubblewrap
  src/content/en/android/trusted-web-activity/lay-of-the-land/index.md
  src/content/en/android/trusted-web-activity/multi-origin/index.md
  src/content/en/android/trusted-web-activity/query-parameters/index.md
  src/content/en/updates/images/2020/03/bubblewrap-init-custom-start-url.png
  src/content/en/updates/images/2020/03/llama-pack-init-custom-start-url.png
Labels: cla: yes, content-updated

#8729 Deprecations and Removals 84.
  src/content/en/updates/2020/05/chrome-84-deps-rems.md
  src/content/en/updates/images/2020/05/dep-rem_480.jpg
Labels: P0, cla: yes, content-updated, section-updates, type-Content

#8735 Adds tools menu
  gulp-tasks/test.js
  gulp-tasks/tests/bookYaml.js
  src/content/en/_upper_tabs-Tools.yaml
  src/content/en/tools/_book.yaml
  src/content/en/tools/_menu_toc.yaml
  src/content/en/tools/workbox/_book.yaml
Labels: cla: yes

#8736 Change Page Navigation Cache to Back-Forward Cache
  src/content/en/updates/2018/07/page-lifecycle-api.md
Labels: cla: yes

#8739 Update instructions for DevTools feature request
  src/content/en/tools/chrome-devtools/index.md
Labels: cla: yes

#8734 Depsrems
  src/content/en/updates/2018/12/chrome-72-deps-rems.md
  src/content/en/updates/2020/02/chrome-81-deps-rems.md
  src/content/en/updates/2020/05/chrome-84-deps-rems.md
Labels: cla: yes
