Repository google/WebFundamentals, pull requests merged in 2020-10, with the labels that each got.

#9022 [devtools] WebAuthn tab documentation
  src/content/en/tools/chrome-devtools/_toc.yaml
  src/content/en/tools/chrome-devtools/webauthn/images/01-webauthn-tab.png
  src/content/en/tools/chrome-devtools/webauthn/images/02-enable-virtual-auth.png
  src/content/en/tools/chrome-devtools/webauthn/images/03-authenticor.png
  src/content/en/tools/chrome-devtools/webauthn/images/03-export-remove.png
  src/content/en/tools/chrome-devtools/webauthn/images/03-no-cred.png
  src/content/en/tools/chrome-devtools/webauthn/images/03-view-cred.png
  src/content/en/tools/chrome-devtools/webauthn/images/04-rename.png
  src/content/en/tools/chrome-devtools/webauthn/images/05-set-active.png
  src/content/en/tools/chrome-devtools/webauthn/images/06-remove-authenticor.png
  src/content/en/tools/chrome-devtools/webauthn/index.md
  src/content/en/updates/2019/12/devtools.md
Labels: P1, cla: yes, content-new, section-tools

#9040 [devtools] Refresh Settings menu description as it's deprecated in More settings
  src/content/en/tools/chrome-devtools/customize/dark-theme.md
  src/content/en/tools/chrome-devtools/customize/images/settings-menu.png
  src/content/en/tools/chrome-devtools/customize/index.md
  src/content/en/tools/chrome-devtools/javascript/guides/blackbox-chrome-extension-scripts.md
Labels: P1, cla: yes, content-updated, section-tools, type-Content

#9037 [devtools] CSS Grid documentation
  src/content/en/tools/chrome-devtools/_toc.yaml
  src/content/en/tools/chrome-devtools/css/grid.md
  src/content/en/tools/chrome-devtools/css/imgs/grid/01-discover-grid.png
  src/content/en/tools/chrome-devtools/css/imgs/grid/02-highlight-grid.png
  src/content/en/tools/chrome-devtools/css/imgs/grid/03-layout-pane.png
  src/content/en/tools/chrome-devtools/css/imgs/grid/04-show-line-numbers.png
  src/content/en/tools/chrome-devtools/css/imgs/grid/05-hide-line-labels.png
  src/content/en/tools/chrome-devtools/css/imgs/grid/06-show-line-names.png
  src/content/en/tools/chrome-devtools/css/imgs/grid/07-show-track-sizes.png
  src/content/en/tools/chrome-devtools/css/imgs/grid/08-show-area-names-just.png
  src/content/en/tools/chrome-devtools/css/imgs/grid/08-show-area-names.png
  src/content/en/tools/chrome-devtools/css/imgs/grid/09-extend-grid-lines-just.png
  src/content/en/tools/chrome-devtools/css/imgs/grid/09-extend-grid-lines.png
  src/content/en/tools/chrome-devtools/css/imgs/grid/10-grid-overlays.png
  src/content/en/tools/chrome-devtools/css/imgs/grid/11-grid-overlays-color.png
  src/content/en/tools/chrome-devtools/css/imgs/grid/12-grid-overlays-highlight.png
Labels: P1, cla: yes, content-new, section-tools, type-Content

#9036 [devtools] What's New In DevTools (Chrome 87)
  src/content/en/updates/2020/10/devtools.md
  src/content/en/updates/_shared/discover.md
  src/content/en/updates/images/2020/10/devtools/01-css-grid.png
  src/content/en/updates/images/2020/10/devtools/02-webauthn.png
  src/content/en/updates/images/2020/10/devtools/03-move-to-bottom.png
  src/content/en/updates/images/2020/10/devtools/04-move-to-top.png
  src/content/en/updates/images/2020/10/devtools/05-computed-sidebar-pane.png
  src/content/en/updates/images/2020/10/devtools/06-grouping-css-prop.png
  src/content/en/updates/images/2020/10/devtools/07-lighthouse.png
  src/content/en/updates/images/2020/10/devtools/08-perf-mark.png
  src/content/en/updates/images/2020/10/devtools/09-filter.png
  src/content/en/updates/images/2020/10/devtools/10-reporting-endpoint.png
  src/content/en/updates/images/2020/10/devtools/11-report-only.png
  src/content/en/updates/images/2020/10/devtools/12-settings.png
  src/content/en/updates/images/2020/10/devtools/13-css-overview.png
  src/content/en/updates/images/2020/10/devtools/14-keyboard-shortcut.png
Labels: P1, cla: yes, content-new, section-tools, type-Content

#9043 [devtools] add desc for reporting api
  src/content/en/updates/2020/10/devtools.md
Labels: cla: yes

#9023 [devtools] Update video link for M86
  src/content/en/updates/2020/08/devtools.md
Labels: P1, cla: yes, content-updated, section-tools, type-Content

#9050 Fix wrong links for "Open the Command Menu" in shortcuts section
  src/content/en/tools/chrome-devtools/shortcuts.md
Labels: cla: yes, content-updated, section-tools

#9049 Update README.md
  README.md
Labels: cla: yes

#9033 redirect the mixed content posts
  src/content/en/_redirects.yaml
  src/content/en/fundamentals/security/_toc.yaml
  src/content/en/fundamentals/security/prevent-mixed-content/fixing-mixed-content.md
  src/content/en/fundamentals/security/prevent-mixed-content/imgs/active-mixed-content-errors.png
  src/content/en/fundamentals/security/prevent-mixed-content/imgs/https-cert-warning.png
  src/content/en/fundamentals/security/prevent-mixed-content/imgs/https-not-available.png
  src/content/en/fundamentals/security/prevent-mixed-content/imgs/image-gallery-warning.png
  src/content/en/fundamentals/security/prevent-mixed-content/imgs/passive-mixed-content-warnings.png
  src/content/en/fundamentals/security/prevent-mixed-content/imgs/puppy-http.png
  src/content/en/fundamentals/security/prevent-mixed-content/imgs/puppy-https.png
  src/content/en/fundamentals/security/prevent-mixed-content/imgs/simple-mixed-content-error.png
  src/content/en/fundamentals/security/prevent-mixed-content/imgs/xmlhttprequest-mixed-content-error.png
  src/content/en/fundamentals/security/prevent-mixed-content/what-is-mixed-content.md
  src/content/es/fundamentals/security/prevent-mixed-content/fixing-mixed-content.md
  src/content/es/fundamentals/security/prevent-mixed-content/what-is-mixed-content.md
  src/content/id/fundamentals/security/prevent-mixed-content/fixing-mixed-content.md
  src/content/id/fundamentals/security/prevent-mixed-content/what-is-mixed-content.md
  src/content/ja/fundamentals/security/prevent-mixed-content/fixing-mixed-content.md
  src/content/ja/fundamentals/security/prevent-mixed-content/what-is-mixed-content.md
  src/content/ko/fundamentals/security/prevent-mixed-content/fixing-mixed-content.md
  src/content/ko/fundamentals/security/prevent-mixed-content/what-is-mixed-content.md
  src/content/pt-br/fundamentals/security/prevent-mixed-content/fixing-mixed-content.md
  src/content/pt-br/fundamentals/security/prevent-mixed-content/what-is-mixed-content.md
  src/content/zh-cn/fundamentals/security/prevent-mixed-content/fixing-mixed-content.md
  src/content/zh-cn/fundamentals/security/prevent-mixed-content/what-is-mixed-content.md
Labels: cla: yes

#9032 Updating with link to integration guidelines
  src/content/en/tools/lighthouse/index.md
Labels: cla: yes

#9051 New in Chrome 86
  src/content/en/updates/2020/10/nic86.md
  src/content/en/updates/_redirects.yaml
  src/content/en/updates/images/2020/10/fs-save-permission-crop.jpg
  src/content/en/updates/images/2020/10/game-controller.jpg
  src/content/en/updates/images/2020/10/new-86.jpg
  src/content/en/updates/images/2020/10/webhid-prompt.jpg
Labels: cla: yes

#8999 Change variable name in recording-audio page
  src/content/es/fundamentals/media/recording-audio/index.md
  src/content/id/fundamentals/media/recording-audio/index.md
  src/content/ja/fundamentals/media/recording-audio/index.md
  src/content/ko/fundamentals/media/recording-audio/index.md
  src/content/pt-br/fundamentals/media/recording-audio/index.md
  src/content/zh-cn/fundamentals/media/recording-audio/index.md
  src/content/zh-tw/fundamentals/media/recording-audio/index.md
Labels: cla: yes

#9038 Http cache partitioning
  src/content/en/updates/2020/10/http-cache-partitioning.md
  src/content/en/updates/images/2020/10/http-cache-partitioning-1.png
  src/content/en/updates/images/2020/10/http-cache-partitioning-2.png
  src/content/en/updates/images/2020/10/http-cache-partitioning-3.png
  src/content/en/updates/images/2020/10/http-cache-partitioning-4.png
  src/content/en/updates/images/2020/10/http-cache-partitioning-5.png
  src/content/en/updates/images/2020/10/http-cache-partitioning-6.png
  src/content/en/updates/images/2020/10/http-cache-partitioning-7.png
  src/data/commonTags.json
Labels: cla: yes, section-updates

#9055 [devtools] add video for Chrome 83
  src/content/en/updates/2020/03/devtools.md
Labels: cla: yes

#9057 DevFest banner
  src/content/en/_project.yaml
  src/content/en/android/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/site-kit/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/chrome-devtools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes

#9061 Add deprecations and removals for Chrome 87.
  src/content/en/updates/2020/10/chrome-87-deps-rems.md
  src/content/en/updates/images/2020/10/dep-rem_87.jpg
Labels: cla: yes

#9030 Add redirect for offline cookbook article
  src/content/en/fundamentals/instant-and-offline/_redirects.yaml
  src/content/en/fundamentals/instant-and-offline/offline-cookbook/images/cm-on-activate.png
  src/content/en/fundamentals/instant-and-offline/offline-cookbook/images/cm-on-bg-sync.png
  src/content/en/fundamentals/instant-and-offline/offline-cookbook/images/cm-on-install-dep.png
  src/content/en/fundamentals/instant-and-offline/offline-cookbook/images/cm-on-install-not.png
  src/content/en/fundamentals/instant-and-offline/offline-cookbook/images/cm-on-network-response.png
  src/content/en/fundamentals/instant-and-offline/offline-cookbook/images/cm-on-push.png
  src/content/en/fundamentals/instant-and-offline/offline-cookbook/images/cm-on-user-interaction.png
  src/content/en/fundamentals/instant-and-offline/offline-cookbook/images/cm-stale-while-revalidate.png
  src/content/en/fundamentals/instant-and-offline/offline-cookbook/images/ss-cache-and-network-race.png
  src/content/en/fundamentals/instant-and-offline/offline-cookbook/images/ss-cache-only.png
  src/content/en/fundamentals/instant-and-offline/offline-cookbook/images/ss-cache-then-network.png
  src/content/en/fundamentals/instant-and-offline/offline-cookbook/images/ss-falling-back-to-network.png
  src/content/en/fundamentals/instant-and-offline/offline-cookbook/images/ss-generic-fallback.png
  src/content/en/fundamentals/instant-and-offline/offline-cookbook/images/ss-network-falling-back-to-cache.png
  src/content/en/fundamentals/instant-and-offline/offline-cookbook/images/ss-network-only.png
  src/content/en/fundamentals/instant-and-offline/offline-cookbook/images/ss-sw-side-templating.png
  src/content/en/fundamentals/instant-and-offline/offline-cookbook/index.md
  src/content/es/fundamentals/instant-and-offline/offline-cookbook/index.md
  src/content/id/fundamentals/instant-and-offline/offline-cookbook/index.md
  src/content/ja/fundamentals/instant-and-offline/offline-cookbook/index.md
  src/content/ko/fundamentals/instant-and-offline/offline-cookbook/index.md
  src/content/pt-br/fundamentals/instant-and-offline/offline-cookbook/index.md
  src/content/zh-cn/fundamentals/instant-and-offline/offline-cookbook/index.md
  src/content/zh-tw/fundamentals/instant-and-offline/offline-cookbook/index.md
Labels: cla: yes

#9067 Updated landing page for CDS20
  src/content/en/_index.yaml
  src/content/en/_project.yaml
  src/content/en/android/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/images/cds20-art.png
  src/content/en/site-kit/_project.yaml
  src/content/en/styles/wf-landing.css
  src/content/en/tools/_project.yaml
  src/content/en/tools/chrome-devtools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes

#9074 Update Space Jam URL
  src/content/en/updates/2018/03/smooshgate.md
Labels: cla: yes

#9076 Add redirect for WebUSB and Web Bluetooth articles
  src/content/en/_redirects.yaml
  src/content/en/updates/2015/07/interact-with-ble-devices-on-the-web.md
  src/content/en/updates/2016/03/access-usb-devices-on-the-web.md
  src/content/en/updates/images/2015-07-22-interact-with-ble-devices-on-the-web/bluetooth-device-chooser.mp4
  src/content/en/updates/images/2015-07-22-interact-with-ble-devices-on-the-web/bluetooth-device-chooser.png
  src/content/en/updates/images/2015-07-22-interact-with-ble-devices-on-the-web/bluetooth-device-chooser.webm
  src/content/en/updates/images/2015-07-22-interact-with-ble-devices-on-the-web/bluetooth-internals.png
  src/content/en/updates/images/2015-07-22-interact-with-ble-devices-on-the-web/featured.png
  src/content/en/updates/images/2015-07-22-interact-with-ble-devices-on-the-web/web-bluetooth-flag.png
  src/content/en/updates/images/2016-03-02-access-usb-devices-on-the-web/usb-device-chooser.png
  src/content/en/updates/images/2016-03-02-access-usb-devices-on-the-web/web-usb-device-log-page.png
  src/content/en/updates/images/2016-03-02-access-usb-devices-on-the-web/web-usb-hero-sm.jpg
  src/content/en/updates/images/2016-03-02-access-usb-devices-on-the-web/web-usb-internals-page.png
  src/content/en/updates/images/2016-03-02-access-usb-devices-on-the-web/web-usb-notification.png
Labels: cla: yes

#9075 Update HTTP Cache Partitioning article
  src/content/en/updates/2020/10/http-cache-partitioning.md
Labels: cla: yes, content-updated, section-updates

#9078 Add nsatragno as contributor
  src/content/en/images/contributors/nsatragno.jpg
  src/data/_contributors.yaml
Labels: cla: yes

#9079 [devtools-blog] Update discover list
  src/content/en/updates/_shared/discover-devtools-blog.md
Labels: cla: yes

#9086 fix duplicated entry for "HAR Analyzer"
  src/content/en/tools/chrome-devtools/network/reference.md
Labels: cla: yes

#9081 Fix babel-plugin-lodash link
  src/content/en/fundamentals/design-and-ux/responsive/images.md
  src/content/en/fundamentals/performance/optimizing-javascript/tree-shaking/index.md
Labels: cla: yes

#9087 new Chromium Chronicle
  src/content/en/updates/2020/10/chromium-chronicle.md
Labels: cla: yes

#9003 Migrate Offline UX Considerations to web.dev
  src/content/en/_redirects.yaml
  src/content/en/fundamentals/instant-and-offline/offline-ux.md
  src/content/es/fundamentals/instant-and-offline/offline-ux.md
  src/content/id/fundamentals/instant-and-offline/offline-ux.md
  src/content/ja/fundamentals/instant-and-offline/offline-ux.md
  src/content/ko/fundamentals/instant-and-offline/offline-ux.md
  src/content/pt-br/fundamentals/instant-and-offline/offline-ux.md
  src/content/zh-cn/fundamentals/instant-and-offline/offline-ux.md
  src/content/zh-tw/fundamentals/instant-and-offline/offline-ux.md
Labels: cla: yes, migrate-content
