Repository google/WebFundamentals, pull requests merged in 2020-08, with the labels that each got.

#8922 Updates links, versions on Trusted Web Activity docs
  src/content/en/android/trusted-web-activity/android-browser-helper-migration/index.md
  src/content/en/android/trusted-web-activity/index.md
  src/content/en/android/trusted-web-activity/integration-guide/index.md
  src/content/en/android/trusted-web-activity/lay-of-the-land/index.md
  src/content/en/android/trusted-web-activity/multi-origin/index.md
  src/content/en/android/trusted-web-activity/quick-start/index.md
Labels: cla: yes, content-updated

#8931 add survey banner
  src/content/en/_project.yaml
  src/content/en/android/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/site-kit/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/chrome-devtools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes

#8926 Workbox landing page revamp
  gulp-tasks/workbox/workbox-generate-contributors.js
  gulp-tasks/workbox/workbox.js
  src/content/en/tools/workbox/_index.yaml
  src/content/en/tools/workbox/_shared/contributors.html
  src/content/en/tools/workbox/images/third_party/logos/bbva.png
  src/content/en/tools/workbox/images/third_party/logos/forbes.png
  src/content/en/tools/workbox/images/third_party/logos/iheartradio.png
  src/content/en/tools/workbox/images/third_party/logos/pinterest.png
  src/content/en/tools/workbox/images/third_party/logos/starbucks.png
  src/content/en/tools/workbox/images/third_party/logos/tinder.png
  src/content/en/tools/workbox/images/third_party/logos/wired.png
Labels: cla: yes

#8924 Updates to the Workbox debugging guide
  src/content/en/tools/workbox/guides/troubleshoot-and-debug.md
  src/content/en/tools/workbox/images/guides/troubleshoot-and-debug/devtools-bypass-for-network.png
  src/content/en/tools/workbox/images/guides/troubleshoot-and-debug/devtools-clear-site-data.png
  src/content/en/tools/workbox/images/guides/troubleshoot-and-debug/devtools-pending.png
  src/content/en/tools/workbox/images/guides/troubleshoot-and-debug/devtools-through-sw-network.png
  src/content/en/tools/workbox/images/guides/troubleshoot-and-debug/devtools-update-on-reload.png
  src/content/en/tools/workbox/images/guides/troubleshoot-and-debug/scope-no-clients.png
  src/content/en/tools/workbox/images/guides/troubleshoot-and-debug/scope-with-clients.png
Labels: cla: yes

#8932 migrating resource prioritization
  src/content/en/_redirects.yaml
  src/content/en/fundamentals/performance/_toc.yaml
  src/content/en/fundamentals/performance/images/res-prio-prefetch.png
  src/content/en/fundamentals/performance/images/res-prio-priorities.png
  src/content/en/fundamentals/performance/images/res-prio-timeout.png
  src/content/en/fundamentals/performance/resource-prioritization.md
  src/content/es/fundamentals/performance/resource-prioritization.md
  src/content/id/fundamentals/performance/resource-prioritization.md
  src/content/it/fundamentals/performance/resource-prioritization.md
  src/content/ja/fundamentals/performance/resource-prioritization.md
  src/content/ko/fundamentals/performance/resource-prioritization.md
  src/content/pt-br/fundamentals/performance/resource-prioritization.md
  src/content/zh-cn/fundamentals/performance/resource-prioritization.md
Labels: cla: yes

#8938 Fix code samples of CE whenDefined
  src/content/en/fundamentals/web-components/customelements.md
  src/content/es/fundamentals/web-components/customelements.md
  src/content/id/fundamentals/web-components/customelements.md
  src/content/ja/fundamentals/web-components/customelements.md
  src/content/ko/fundamentals/web-components/customelements.md
  src/content/pt-br/fundamentals/web-components/customelements.md
  src/content/ru/fundamentals/web-components/customelements.md
  src/content/zh-cn/fundamentals/web-components/customelements.md
  src/content/zh-tw/fundamentals/web-components/customelements.md
Labels: cla: yes

#8943 Updated mapping operations
  src/content/en/updates/2019/08/get-started-with-gpu-compute-on-the-web.md
Labels: cla: yes

#8941 Add janscheffler to contributors
  src/content/en/images/contributors/janscheffler.jpg
  src/data/_contributors.yaml
Labels: cla: yes

#8944 Change end of xhr deprecation.
  src/content/en/updates/2019/12/chrome-80-deps-rems.md
Labels: cla: yes

#8949 Update _contributors.yaml
  src/content/en/images/contributors/fawazm.jpg
  src/data/_contributors.yaml
Labels: cla: yes

#8953 [devtools] What's New In DevTools (Chrome 86)
  src/content/en/updates/2020/08/devtools.md
  src/content/en/updates/_shared/discover.md
  src/content/en/updates/images/2020/08/capture-node-screenshot.png
  src/content/en/updates/images/2020/08/clear-button.png
  src/content/en/updates/images/2020/08/contrast-color-suggestion.mp4
  src/content/en/updates/images/2020/08/coverage-compare.png
  src/content/en/updates/images/2020/08/disable-font.png
  src/content/en/updates/images/2020/08/emulate-idle.png
  src/content/en/updates/images/2020/08/emulate-prefers-reduced-data.png
  src/content/en/updates/images/2020/08/font-auto-complete.png
  src/content/en/updates/images/2020/08/frame-details.png
  src/content/en/updates/images/2020/08/issue-console-msg.png
  src/content/en/updates/images/2020/08/lighthouse-unsize-img.png
  src/content/en/updates/images/2020/08/media-panel.png
  src/content/en/updates/images/2020/08/network-redirect.png
  src/content/en/updates/images/2020/08/sw-other-origins.png
  src/content/en/updates/images/2020/08/third-party-cookies.png
  src/content/en/updates/images/2020/08/window-opener.png
  src/content/en/updates/images/2020/08/x-client-data.png
Labels: P1, cla: yes, content-new, section-tools, type-Content

#8964 Add sigurds as contributor (author)
  src/content/en/images/contributors/sigurds.jpg
  src/data/_contributors.yaml
Labels: cla: yes

#8963 [partner request] Correct branding
  src/content/en/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/index.md
Labels: cla: yes

#8959 [devtools] New Media panel documentation
  src/content/en/tools/chrome-devtools/_toc.yaml
  src/content/en/tools/chrome-devtools/media/images/01-empty.png
  src/content/en/tools/chrome-devtools/media/images/02-view.png
  src/content/en/tools/chrome-devtools/media/images/03-events.png
  src/content/en/tools/chrome-devtools/media/images/04-messages.png
  src/content/en/tools/chrome-devtools/media/images/05-timeline.mp4
  src/content/en/tools/chrome-devtools/media/images/06-remote-debug.png
  src/content/en/tools/chrome-devtools/media/images/07-hide-show.png
  src/content/en/tools/chrome-devtools/media/images/08-save.png
  src/content/en/tools/chrome-devtools/media/index.md
Labels: P1, cla: yes, content-new, section-tools, type-Content

#8958 #8907 | Fix frame typo
  src/content/en/updates/2018/09/inside-browser-part3.md
Labels: cla: yes

#8957 fixes close #8956 for hyperlink correction which was going to 404 page.
  src/content/en/fundamentals/_index.yaml
Labels: cla: yes

#8955 Revise Constructable Stylesheets article to reflect removed support for @import
  src/content/en/updates/2019/02/constructable-stylesheets.md
Labels: cla: yes, type-Content

#8946 Add custom tabs headers article
  src/content/en/android/custom-tabs/_toc.yaml
  src/content/en/android/custom-tabs/headers/index.md
Labels: DO NOT MERGE, cla: yes, content-new

#8966 [ES6 template strings article] Improve loaded language
  src/content/en/updates/2015/01/ES6-Template-Strings.md
Labels: cla: yes

#8965 fix typo
  src/content/en/tools/chrome-devtools/remote-debugging/index.md
Labels: cla: yes

#8973 Workbox docs improvements
  src/content/en/tools/_redirects.yaml
  src/content/en/tools/workbox/guides/advanced-recipes.md
  src/content/en/tools/workbox/guides/service-worker-checklist.md
  src/content/en/tools/workbox/guides/using-bundlers.md
  src/content/en/tools/workbox/modules/workbox-precaching.md
Labels: cla: yes

#8971 [devtools] Add new announcements in WNDT86, rename media url
  src/content/en/tools/chrome-devtools/_toc.yaml
  src/content/en/tools/chrome-devtools/media-panel/images/01-empty.png
  src/content/en/tools/chrome-devtools/media-panel/images/02-view.png
  src/content/en/tools/chrome-devtools/media-panel/images/03-events.png
  src/content/en/tools/chrome-devtools/media-panel/images/04-messages.png
  src/content/en/tools/chrome-devtools/media-panel/images/05-timeline.mp4
  src/content/en/tools/chrome-devtools/media-panel/images/06-remote-debug.png
  src/content/en/tools/chrome-devtools/media-panel/images/07-hide-show.png
  src/content/en/tools/chrome-devtools/media-panel/images/08-save.png
  src/content/en/tools/chrome-devtools/media-panel/index.md
  src/content/en/tools/chrome-devtools/media/images/01-empty.png
  src/content/en/tools/chrome-devtools/media/images/02-view.png
  src/content/en/tools/chrome-devtools/media/images/03-events.png
  src/content/en/tools/chrome-devtools/media/images/04-messages.png
  src/content/en/tools/chrome-devtools/media/images/06-remote-debug.png
  src/content/en/tools/chrome-devtools/media/images/07-hide-show.png
  src/content/en/tools/chrome-devtools/media/images/08-save.png
  src/content/en/updates/2020/08/devtools.md
  src/content/en/updates/_shared/discover.md
  src/content/en/updates/images/2020/08/coep-coop.png
  src/content/en/updates/images/2020/08/properties-pane.png
Labels: cla: yes

#8977 [devtools] adding video
  src/content/en/updates/2020/06/devtools.md
Labels: P1, cla: yes, content-updated

#8979 [devtools] Update content
  src/content/en/updates/2020/08/devtools.md
Labels: DO NOT MERGE, P1, cla: yes, content-updated, section-tools

#8980 New in Chrome 85
  src/content/en/updates/2020/07/nic84.md
  src/content/en/updates/2020/08/nic85.md
  src/content/en/updates/_redirects.yaml
  src/content/en/updates/images/2020/08/app-shortcuts-menu-windows.png
  src/content/en/updates/images/2020/08/browser-0.png
  src/content/en/updates/images/2020/08/cva.jpg
  src/content/en/updates/images/2020/08/new-85.jpg
Labels: cla: yes
