Repository google/WebFundamentals, pull requests merged in 2020-06, with the labels that each got.

#8753 Redirects to newer WebPerf content on web.dev
  src/content/en/_redirects.yaml
Labels: cla: yes

#7683 Changed variable name in Fix Memory Problems
  src/content/en/tools/chrome-devtools/memory-problems/index.md
Labels: cla: yes

#7896 Adding initial connection time phase fix #7883
  src/content/en/tools/chrome-devtools/network/reference.md
Labels: cla: yes

#8478 fix console.debug log level
  src/content/en/tools/chrome-devtools/console/api.md
Labels: cla: yes

#8501 $ no longer an alias for document.querySelector
  src/content/en/tools/chrome-devtools/console/utilities.md
Labels: cla: yes

#8599 Add description of queryObjects method
  src/content/en/tools/chrome-devtools/console/utilities.md
Labels: cla: yes

#8699 Added documentation for Cookie Priority (#8698)
  src/content/en/tools/chrome-devtools/storage/cookies.md
Labels: cla: yes

#8755 Clarify when various aspects of locale emulation takes place
  src/content/en/updates/2020/03/devtools.md
Labels: cla: yes

#8752 Update typo in how-to-review.md
  src/content/en/fundamentals/accessibility/how-to-review.md
Labels: cla: yes

#8746 Fixed two typos in query-parameters
  src/content/en/android/trusted-web-activity/query-parameters/index.md
Labels: cla: yes

#8742 Add redirects to the new web.dev payment articles
  src/content/en/_redirects.yaml
  src/content/en/fundamentals/_redirects.yaml
  src/content/en/fundamentals/payments/_toc.yaml
  src/content/en/fundamentals/payments/payment-apps-developer-guide/android-payment-apps.md
Labels: cla: no, type-Content

#8800 migrating the lazy-loading article
  src/content/en/_redirects.yaml
  src/content/en/fundamentals/performance/_toc.yaml
  src/content/en/fundamentals/performance/lazy-loading-guidance/images-and-video/images/lazy-loading-example-1x.jpg
  src/content/en/fundamentals/performance/lazy-loading-guidance/images-and-video/images/lazy-loading-example-2x.jpg
  src/content/en/fundamentals/performance/lazy-loading-guidance/images-and-video/images/offscreen-audit-1x.png
  src/content/en/fundamentals/performance/lazy-loading-guidance/images-and-video/images/offscreen-audit-2x.png
  src/content/en/fundamentals/performance/lazy-loading-guidance/images-and-video/index.md
Labels: cla: yes

#8789 Fixes broken link on Updates 2019/02 Model Viewer page
  src/content/en/updates/2019/02/model-viewer.md
Labels: cla: yes

#8794 Remove RAIL guide and redirect to web.dev
  src/content/en/_redirects.yaml
  src/content/en/fundamentals/performance/_toc.yaml
  src/content/en/fundamentals/performance/images/rail-response-details.png
  src/content/en/fundamentals/performance/images/rail.png
  src/content/en/fundamentals/performance/rail.md
Labels: cla: yes

#8796 Updates and enables Custom Tabs documentation
  src/content/en/android/_book.yaml
  src/content/en/android/_index.yaml
  src/content/en/android/_redirects.yaml
  src/content/en/android/custom-tabs/_toc.yaml
  src/content/en/android/custom-tabs/best-practices/index.md
  src/content/en/android/custom-tabs/implementation-guide/index.md
  src/content/en/android/custom-tabs/implementation-guide/tumblr_action.png
  src/content/en/android/custom-tabs/implementation-guide/twitter_menu.png
  src/content/en/android/custom-tabs/index.md
  src/content/en/android/custom-tabs/low-level-api/index.md
  src/content/en/android/custom-tabs/performance.gif
Labels: cla: yes, content-updated

#8804 Remove translated files that have been migrated to web.dev
  src/content/es/fundamentals/performance/lazy-loading-guidance/images-and-video/index.md
  src/content/es/fundamentals/performance/rail.md
  src/content/id/fundamentals/performance/lazy-loading-guidance/images-and-video/index.md
  src/content/id/fundamentals/performance/rail.md
  src/content/it/fundamentals/performance/rail.md
  src/content/ja/fundamentals/performance/lazy-loading-guidance/images-and-video/index.md
  src/content/ja/fundamentals/performance/rail.md
  src/content/ko/fundamentals/performance/lazy-loading-guidance/images-and-video/index.md
  src/content/ko/fundamentals/performance/rail.md
  src/content/pt-br/fundamentals/performance/lazy-loading-guidance/images-and-video/index.md
  src/content/pt-br/fundamentals/performance/rail.md
  src/content/zh-cn/fundamentals/performance/lazy-loading-guidance/images-and-video/index.md
  src/content/zh-cn/fundamentals/performance/rail.md
Labels: cla: yes

#8791 Invalid aria in Introduction to ARIA page
  src/content/en/fundamentals/accessibility/semantics-aria/index.md
Labels: cla: yes

#8808 Update whitelist to allowlist
  src/content/en/fundamentals/security/csp/index.md
Labels: cla: yes

#8816 Add jecelynyeen contributor
  src/content/en/images/contributors/jecelynyeen.jpg
  src/data/_contributors.yaml
Labels: cla: yes

#8810 Revert "[ZH-CN] Translate file-a-bug.md into Chinese"
  src/content/zh-cn/feedback/file-a-bug.md
Labels: cla: yes

#8818 Revert "[PT-BR] translate sources.md into Portuguese (Brazil)"
  src/content/pt-BR/tools/chrome-devtools/sources.md
Labels: cla: yes

#8812 Update "WebAssembly debugging in Chrome DevTools"
  src/content/en/updates/2019/12/webassembly.md
Labels: cla: yes

#8814 Fix link to Trusted Web Activity
  src/content/en/android/custom-tabs/index.md
Labels: cla: yes

#8807 Update README - Getting set up
  README.md
Labels: cla: yes

#8790 Note Side Bar Disables Default Levels Dropdown in Console
  src/content/en/tools/chrome-devtools/console/log.md
Labels: cla: yes

#8786 Fix broken link IndexedDB Chrome Devtools
  src/content/en/tools/chrome-devtools/storage/indexeddb.md
Labels: cla: yes

#8770 Fix broken link in command menu
  src/content/en/tools/chrome-devtools/css/reference.md
Labels: cla: yes

#7684 Updated image format table in Image Optimization
  src/content/en/fundamentals/performance/optimizing-content-efficiency/image-optimization.md
Labels: cla: yes

#8824 fix case sensitivity
  src/content/pt-br/fundamentals/accessibility/how-to-review.md
  src/content/pt-br/tools/chrome-devtools/accessibility/reference.md
Labels: cla: yes

#8825 What's New In DevTools (Chrome 85)
  src/content/en/updates/2020/06/devtools.md
  src/content/en/updates/_shared/discover.md
  src/content/en/updates/images/2020/06/app-shortcut-warnings.png
  src/content/en/updates/images/2020/06/break.png
  src/content/en/updates/images/2020/06/breakpoints-buttons.png
  src/content/en/updates/images/2020/06/bytecode-offset.png
  src/content/en/updates/images/2020/06/computed-pane.mp4
  src/content/en/updates/images/2020/06/css-in-js.mp4
  src/content/en/updates/images/2020/06/js-compilation-cache.png
  src/content/en/updates/images/2020/06/lighthouse.png
  src/content/en/updates/images/2020/06/line-wise-cut.mp4
  src/content/en/updates/images/2020/06/nav-timing.png
  src/content/en/updates/images/2020/06/selected-context.png
  src/content/en/updates/images/2020/06/timing-tab.png
  src/content/en/updates/images/2020/06/ungroup-similar.mp4
Labels: P1, cla: yes, content-new, section-tools, type-Content

#8829 Update incorrect rendered Lighthouse URL
  src/content/en/updates/2020/06/devtools.md
Labels: P1, cla: yes, content-updated, section-tools

#8830 Add a new content in What's new in DevTools 85
  src/content/en/updates/2020/06/devtools.md
  src/content/en/updates/_shared/discover.md
  src/content/en/updates/images/2020/06/breakpoints.png
Labels: P1, cla: yes, content-updated, section-tools

#8828 Improve image layout on custom-tabs guide
  src/content/en/android/custom-tabs/implementation-guide/index.md
Labels: cla: yes, content-updated

#8827 Fixes a strategy name typo in WB docs
  src/content/en/tools/workbox/modules/workbox-cacheable-response.md
Labels: cla: yes

#8826 Add missing return and indent header comment correctly
  src/content/en/android/custom-tabs/implementation-guide/index.md
Labels: cla: yes

#8841 Fix typo
  src/content/en/updates/2020/06/devtools.md
Labels: P2, cla: yes, content-updated, section-tools

#8844 update links per Luke
  src/content/en/fundamentals/security/prevent-mixed-content/_code/image-gallery-example.html
  src/content/en/resources/widgets.md
Labels: cla: yes

#8843 Add WDL live now banner/homepage promo
  src/content/en/_index.yaml
  src/content/en/_project.yaml
  src/content/en/android/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/site-kit/_project.yaml
  src/content/en/styles/wf-landing.css
  src/content/en/tools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes

#8819 Remove /billions/ content
  src/content/en/_footer.yaml
  src/content/en/_redirects.yaml
  src/content/en/billions/_index.yaml
  src/content/en/billions/images/2g.jpg
  src/content/en/billions/images/capability.png
  src/content/en/billions/images/checkout.jpg
  src/content/en/billions/images/connectivity.png
  src/content/en/billions/images/consumption.png
  src/content/en/billions/images/content.png
  src/content/en/billions/images/cost.jpg
  src/content/en/billions/images/cost.png
  src/content/en/billions/images/devices.jpg
  src/content/en/billions/images/localization.jpg
  src/content/en/billions/images/localization.png
  src/content/en/billions/images/monetization.png
  src/content/en/billions/images/multi.jpg
  src/content/en/billions/images/power.jpg
  src/content/en/updates/2016/07/autoplay.md
  src/content/es/billions/_index.yaml
  src/content/id/billions/_index.yaml
  src/content/ja/billions/_index.yaml
  src/content/ko/billions/_index.yaml
  src/content/pt-br/billions/_index.yaml
  src/content/ru/billions/_index.yaml
  src/content/zh-cn/billions/_index.yaml
  src/content/zh-tw/billions/_index.yaml
Labels: cla: yes

#8845 redirect Image Optimization
  src/content/ar/fundamentals/performance/optimizing-content-efficiency/image-optimization.md
  src/content/de/fundamentals/performance/optimizing-content-efficiency/image-optimization.md
  src/content/en/_redirects.yaml
  src/content/en/fundamentals/performance/_toc.yaml
  src/content/en/fundamentals/performance/optimizing-content-efficiency/image-optimization.md
  src/content/en/fundamentals/performance/optimizing-content-efficiency/images/css-vs-device-pixels.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/images/raster-zoom.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/images/resized-image.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/images/vector-zoom.png
  src/content/es/fundamentals/performance/optimizing-content-efficiency/image-optimization.md
  src/content/fr/fundamentals/performance/optimizing-content-efficiency/image-optimization.md
  src/content/id/fundamentals/performance/optimizing-content-efficiency/image-optimization.md
  src/content/it/fundamentals/performance/optimizing-content-efficiency/image-optimization.md
  src/content/ja/fundamentals/performance/optimizing-content-efficiency/image-optimization.md
  src/content/ko/fundamentals/performance/optimizing-content-efficiency/image-optimization.md
  src/content/nl/fundamentals/performance/optimizing-content-efficiency/image-optimization.md
  src/content/pl/fundamentals/performance/optimizing-content-efficiency/image-optimization.md
  src/content/pt-br/fundamentals/performance/optimizing-content-efficiency/image-optimization.md
  src/content/ru/fundamentals/performance/optimizing-content-efficiency/image-optimization.md
  src/content/tr/fundamentals/performance/optimizing-content-efficiency/image-optimization.md
  src/content/zh-cn/fundamentals/performance/optimizing-content-efficiency/image-optimization.md
  src/content/zh-tw/fundamentals/performance/optimizing-content-efficiency/image-optimization.md
Labels: cla: yes
