Repository google/WebFundamentals, pull requests merged in 2020-07, with the labels that each got.

#8852 Add post-WDL banner
  src/content/en/_index.yaml
  src/content/en/_project.yaml
  src/content/en/android/_project.yaml
  src/content/en/fundamentals/_project.yaml
  src/content/en/site-kit/_project.yaml
  src/content/en/tools/_project.yaml
  src/content/en/tools/workbox/_project.yaml
  src/data/announcement.yaml
Labels: cla: yes

#8848 Updates Custom Tabs docs for Android 11
  src/content/en/android/custom-tabs/best-practices/index.md
  src/content/en/android/custom-tabs/implementation-guide/index.md
Labels: cla: yes, content-updated

#8847 Update anchor id
  src/content/en/updates/2020/06/devtools.md
Labels: P2, cla: yes, content-updated, section-tools

#8850 [PT-BR] Fix Link to original URL
  src/content/pt-BR/tools/chrome-devtools/javascript/reference.md
Labels: cla: yes

#8835 Fixes grammar error in Introduction to Aria page
  src/content/en/fundamentals/accessibility/semantics-aria/index.md
Labels: cla: yes

#8856 Customtabs android 11
  src/content/en/android/custom-tabs/implementation-guide/index.md
  src/content/en/updates/2020/07/custom-tabs-android-11.md
  src/data/commonTags.json
Labels: cla: yes, content-new

#8863 New in Chrome 84
  src/content/en/updates/2020/07/nic84.md
  src/content/en/updates/images/2020/07/content-indexing.mp4
  src/content/en/updates/images/2020/07/content-indexing.webm
  src/content/en/updates/images/2020/07/hand.mp4
  src/content/en/updates/images/2020/07/new-84.jpg
  src/content/en/updates/images/2020/07/twitter-app-icon-shortcut.jpg
  src/content/en/updates/images/2020/07/wake-lock-enabled.jpg
Labels: cla: yes

#8862 Update JavaScript Snippet command
  src/content/en/_project.yaml
  src/content/en/tools/chrome-devtools/javascript/imgs/run-snippet-command.png
  src/content/en/tools/chrome-devtools/javascript/imgs/runsnippetcommand.png
  src/content/en/tools/chrome-devtools/javascript/snippets.md
Labels: P2, cla: yes, content-updated, section-tools

#8861 redirecting optimizing webfonts article
  src/content/ar/fundamentals/performance/optimizing-content-efficiency/webfont-optimization.md
  src/content/de/fundamentals/performance/optimizing-content-efficiency/webfont-optimization.md
  src/content/en/_redirects.yaml
  src/content/en/fundamentals/performance/_toc.yaml
  src/content/en/fundamentals/performance/optimizing-content-efficiency/images/font-crp.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/images/font-synthesis.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/images/font-weights.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/images/glyphs.png
  src/content/en/fundamentals/performance/optimizing-content-efficiency/webfont-optimization.md
  src/content/es/fundamentals/performance/optimizing-content-efficiency/webfont-optimization.md
  src/content/fr/fundamentals/performance/optimizing-content-efficiency/webfont-optimization.md
  src/content/id/fundamentals/performance/optimizing-content-efficiency/webfont-optimization.md
  src/content/it/fundamentals/performance/optimizing-content-efficiency/webfont-optimization.md
  src/content/ja/fundamentals/performance/optimizing-content-efficiency/webfont-optimization.md
  src/content/ko/fundamentals/performance/optimizing-content-efficiency/webfont-optimization.md
  src/content/nl/fundamentals/performance/optimizing-content-efficiency/webfont-optimization.md
  src/content/pl/fundamentals/performance/optimizing-content-efficiency/webfont-optimization.md
  src/content/pt-br/fundamentals/performance/optimizing-content-efficiency/webfont-optimization.md
  src/content/ru/fundamentals/performance/optimizing-content-efficiency/webfont-optimization.md
  src/content/tr/fundamentals/performance/optimizing-content-efficiency/webfont-optimization.md
  src/content/zh-cn/fundamentals/performance/optimizing-content-efficiency/webfont-optimization.md
  src/content/zh-tw/fundamentals/performance/optimizing-content-efficiency/webfont-optimization.md
Labels: cla: yes

#8870 Add section on "blocking mixed downloads"
  src/content/en/fundamentals/security/prevent-mixed-content/what-is-mixed-content.md
Labels: cla: yes

#8876 Update devtools remote debugging articles
  src/content/en/tools/chrome-devtools/remote-debugging/imgs/add-rule.png
  src/content/en/tools/chrome-devtools/remote-debugging/imgs/connected-remote-device.png
  src/content/en/tools/chrome-devtools/remote-debugging/imgs/discover-usb-devices.png
  src/content/en/tools/chrome-devtools/remote-debugging/imgs/offline-device.png
  src/content/en/tools/chrome-devtools/remote-debugging/imgs/port-forwarding-button.png
  src/content/en/tools/chrome-devtools/remote-debugging/imgs/port-forwarding-status.png
  src/content/en/tools/chrome-devtools/remote-debugging/imgs/reload.png
  src/content/en/tools/chrome-devtools/remote-debugging/index.md
  src/content/en/tools/chrome-devtools/remote-debugging/local-server.md
Labels: cla: yes, content-updated, section-tools

#8872 Workbox: Updates to using bundlers guide
  src/content/en/tools/workbox/guides/_toc.yaml
  src/content/en/tools/workbox/guides/using-bundlers.md
Labels: cla: yes

#8892 Depsrems85
  src/content/en/updates/2020/07/chrome-85-deps-rems.md
  src/content/en/updates/images/2020/07/dep-rem_85.jpg
Labels: cla: yes

#8894 Added contributor
  src/content/en/images/contributors/maudnalpas.jpg
  src/data/_contributors.yaml
Labels: cla: yes

#8867 docs: Fix typo, link to package visibility page
  src/content/en/android/custom-tabs/best-practices/index.md
Labels: cla: yes

#8878 Fix 'Run Lighthouse in DevTools' button
  src/content/en/tools/lighthouse/index.md
Labels: cla: yes

#8882 devtools.md: Correct 'rbg()' typo
  src/content/en/updates/2020/05/devtools.md
Labels: cla: yes

#8888 Update /nic to nic84
  src/content/en/updates/_redirects.yaml
Labels: cla: yes

#8890 8860 | Fix Modern.ie links
  src/content/en/tools/chrome-devtools/device-mode/testing-other-browsers.md
  src/content/es/tools/chrome-devtools/device-mode/testing-other-browsers.md
  src/content/id/tools/chrome-devtools/device-mode/testing-other-browsers.md
  src/content/ja/tools/chrome-devtools/device-mode/testing-other-browsers.md
  src/content/ko/tools/chrome-devtools/device-mode/testing-other-browsers.md
  src/content/pt-br/tools/chrome-devtools/device-mode/testing-other-browsers.md
  src/content/zh-cn/tools/chrome-devtools/device-mode/testing-other-browsers.md
  src/content/zh-tw/tools/chrome-devtools/device-mode/testing-other-browsers.md
Labels: cla: yes

#8891 Update switches and flags in the Autoplay Policy changes article
  src/content/en/updates/2017/09/autoplay-policy-changes.md
Labels: cla: yes

#8873 Remove the GA guide and redirect to module page
  src/content/en/tools/_redirects.yaml
  src/content/en/tools/workbox/guides/_toc.yaml
  src/content/en/tools/workbox/guides/enable-offline-analytics.md
Labels: cla: yes

#8884 Update web agencies directory
  src/content/en/agencies/_index.yaml
  src/content/en/agencies/css/directory.css
  src/content/en/agencies/data/agencies.json
  src/content/en/agencies/images/22feet_tribal_worldwide_pvt_ltd.png
  src/content/en/agencies/images/asial.png
  src/content/en/agencies/images/balconia_limited.png
  src/content/en/agencies/images/digifutura.png
  src/content/en/agencies/images/digitaldot_servicios_informaticos_sl.png
  src/content/en/agencies/images/e-point_sa.png
  src/content/en/agencies/images/elephants_can_dance.png
  src/content/en/agencies/images/enforce.png
  src/content/en/agencies/images/enovate.png
  src/content/en/agencies/images/escola_sa_inc.png
  src/content/en/agencies/images/featurist_ltd.png
  src/content/en/agencies/images/gimc_chance.png
  src/content/en/agencies/images/gits_indonesia.png
  src/content/en/agencies/images/hero-web-agencies.png
  src/content/en/agencies/images/hex_digital_ltd.png
  src/content/en/agencies/images/imj_corporation.png
  src/content/en/agencies/images/iret.png
  src/content/en/agencies/images/isobar_uk.png
  src/content/en/agencies/images/jh.png
  src/content/en/agencies/images/long_live_king_ltd.png
  src/content/en/agencies/images/lunar_works.png
  src/content/en/agencies/images/lunar_works_lab_ltd.png
  src/content/en/agencies/images/makassar_website.png
  src/content/en/agencies/images/mediology_software_readwhere_cms.png
  src/content/en/agencies/images/microtekblue_inc.png
  src/content/en/agencies/images/mobx.png
  src/content/en/agencies/images/moovweb.png
  src/content/en/agencies/images/netarum.png
  src/content/en/agencies/images/positive_technology.png
  src/content/en/agencies/images/proditech_solutions.png
  src/content/en/agencies/images/pt_logique_digital_indonesia.png
  src/content/en/agencies/images/pwa_lab,_llp.png
  src/content/en/agencies/images/remarkable.net.png
  src/content/en/agencies/images/scriptpainter.png
  src/content/en/agencies/images/selesti_ltd.png
  src/content/en/agencies/images/sidekick_digital_limited.png
  src/content/en/agencies/images/simicart_joint_stock_company_.png
  src/content/en/agencies/images/toaster.png
  src/content/en/agencies/images/uasoft.png
  src/content/en/agencies/images/uatech.png
  src/content/en/agencies/images/unbound_commerce.png
  src/content/en/agencies/images/wunderman.png
  src/content/en/agencies/images/your_favourite_story.png
Labels: P1, cla: no, section-agencies

#8900 redirecting: Why performance matters
  src/content/en/_redirects.yaml
  src/content/en/fundamentals/performance/_toc.yaml
  src/content/en/fundamentals/performance/why-performance-matters/images/impact-calculator-1x.png
  src/content/en/fundamentals/performance/why-performance-matters/images/impact-calculator-2x.png
  src/content/en/fundamentals/performance/why-performance-matters/images/lighthouse-1x.png
  src/content/en/fundamentals/performance/why-performance-matters/images/lighthouse-2x.png
  src/content/en/fundamentals/performance/why-performance-matters/images/speed-comparison.png
  src/content/en/fundamentals/performance/why-performance-matters/images/speed-scorecard-1x.png
  src/content/en/fundamentals/performance/why-performance-matters/images/speed-scorecard-2x.png
  src/content/en/fundamentals/performance/why-performance-matters/index.md
  src/content/id/fundamentals/performance/why-performance-matters/index.md
  src/content/ja/fundamentals/performance/why-performance-matters/index.md
  src/content/ko/fundamentals/performance/why-performance-matters/index.md
  src/content/pt-br/fundamentals/performance/why-performance-matters/index.md
  src/content/zh-cn/fundamentals/performance/why-performance-matters/index.md
Labels: cla: yes

#8903 8895 | Fix grammatical error
  src/content/en/android/custom-tabs/implementation-guide/index.md
Labels: cla: yes

#8901 Restrict app shortcuts support to Android
  src/content/en/updates/2020/07/nic84.md
Labels: cla: yes

#8899 Add redirects to payment articles
  src/content/en/_redirects.yaml
  src/content/en/fundamentals/payments/_toc.yaml
  src/content/en/fundamentals/payments/payment-apps-developer-guide/web-payment-apps.md
Labels: cla: yes, migrate-content, section-fundamentals

#7659 #7602 | Fix incorrect attribute
  src/content/en/fundamentals/performance/resource-prioritization.md
  src/content/es/fundamentals/performance/resource-prioritization.md
  src/content/id/fundamentals/performance/resource-prioritization.md
  src/content/it/fundamentals/performance/resource-prioritization.md
  src/content/ja/fundamentals/performance/resource-prioritization.md
  src/content/ko/fundamentals/performance/resource-prioritization.md
  src/content/pt-br/fundamentals/performance/resource-prioritization.md
  src/content/zh-cn/fundamentals/performance/resource-prioritization.md
Labels: cla: yes

#8834 Adds information about HTML imports deprecation in shadow dom
  src/content/en/fundamentals/web-components/shadowdom.md
Labels: cla: yes

#8910 remove translation article info
  src/content/en/resources/translations.md
  src/content/ja/resources/translations.md
  src/content/ko/resources/translations.md
  src/content/ru/resources/translations.md
  src/content/zh-cn/resources/translations.md
  src/content/zh-tw/resources/translations.md
Labels: cla: yes

#8919 Fix translation typo
  src/content/zh-cn/fundamentals/primers/service-workers/registration.md
  src/content/zh-tw/fundamentals/primers/service-workers/registration.md
Labels: cla: yes

#8914 Fix a small typo in Workbox bundler docs
  src/content/en/tools/workbox/guides/using-bundlers.md
Labels: cla: yes

#8837 Fixes Fibonacci example
  src/content/en/updates/2018/03/emscripting-a-c-library.md
Labels: cla: yes

#8413 Add License Badge to README.md
  README.md
Labels: cla: yes

#8920 New article: Referrer-Policy new Chrome default
  src/content/en/updates/2020/07/referrer-policy-new-chrome-default.md
  src/content/en/updates/images/2020/07/referrer-policy-default-01.png
  src/content/en/updates/images/2020/07/referrer-policy-default-02.png
  src/content/en/updates/images/2020/07/referrer-policy-default-03.png
Labels: DO NOT MERGE, cla: yes, type-Content

#8923 Small fix: Referrer-Policy new Chrome default
  src/content/en/updates/2020/07/referrer-policy-new-chrome-default.md
Labels: cla: yes, content-updated, type-Content

#8927 Fix the Workbox guides table of contents
  src/content/en/tools/workbox/guides/_toc.yaml
Labels: cla: yes

#8925 Remove Workbox community page
  src/content/en/tools/_redirects.yaml
  src/content/en/tools/workbox/_footer.yaml
  src/content/en/tools/workbox/community.md
Labels: cla: yes
