Repository google/WebFundamentals, pull requests merged in 2021-01, with the labels that each got.

#9195 Remove remaining createBufferMapped in example
  src/content/en/updates/2019/08/get-started-with-gpu-compute-on-the-web.md
Labels: cla: yes

#9191 fix #9128
  src/content/en/updates/_shared/discover.md
Labels: cla: yes

#9190 Fix #9186
  src/content/en/tools/workbox/guides/get-started.md
Labels: cla: yes

#9175 Send CA to CSR -> Send CSR to CA
  src/content/en/fundamentals/security/encrypt-in-transit/enable-https.md
Labels: cla: yes

#9170 Fixing typo
  src/content/en/tools/workbox/guides/migrations/migrate-from-v5.md
Labels: cla: yes

#9176 Fixes navigationPreload import
  src/content/en/tools/workbox/guides/advanced-recipes.md
Labels: cla: yes

#9202 Update guidance to use the pagehide event over unload
  src/content/en/updates/2020/05/heavy-ad-interventions.md
Labels: cla: yes, content-updated, type-Content

#9200 [WebGPU article] Use new syntax for createBindGroupLayout
  src/content/en/updates/2019/08/get-started-with-gpu-compute-on-the-web.md
Labels: cla: yes

#9198 [WebGPU article] Check adapter before using it
  src/content/en/updates/2019/08/get-started-with-gpu-compute-on-the-web.md
Labels: cla: yes

#9205 Redirect Chromium Chronicle articles to dcc
  src/content/en/_redirects.yaml
  src/content/en/updates/2019/04/chromium-chronicle-1.md
  src/content/en/updates/2019/05/chromium-chronicle-2.md
  src/content/en/updates/2019/06/chromium-chronicle-3.md
  src/content/en/updates/2019/07/chromium-chronicle-4.md
  src/content/en/updates/2019/08/chromium-chronicle-5.md
  src/content/en/updates/2019/09/chromium-chronicle-6.md
  src/content/en/updates/2019/10/chromium-chronicle-7.md
  src/content/en/updates/2019/11/chromium-chronicle-8.md
  src/content/en/updates/2019/12/chromium-chronicle-9.md
  src/content/en/updates/2020/02/chromium-chronicle.md
  src/content/en/updates/2020/03/chromium-chronicle.md
  src/content/en/updates/2020/10/chromium-chronicle.md
  src/content/en/updates/2020/11/chromium-chronicle.md
Labels: cla: yes

#9213 [devtools] include user research link
  src/content/en/tools/chrome-devtools/blog/index.md
  src/content/en/tools/chrome-devtools/updates/index.md
  src/content/en/updates/2020/08/devtools.md
  src/content/en/updates/2020/10/devtools.md
  src/content/en/updates/2020/11/devtools.md
  src/content/en/updates/_shared/devtools-research.md
Labels: cla: yes

#9214 [devtools] What's New in DevTools (Chrome 89)
  src/content/en/updates/2021/01/devtools.md
  src/content/en/updates/_shared/discover.md
  src/content/en/updates/images/2021/01/devtools/apca.png
  src/content/en/updates/images/2021/01/devtools/clear-cookies.png
  src/content/en/updates/images/2021/01/devtools/color-picker.png
  src/content/en/updates/images/2021/01/devtools/cookies-decoded.png
  src/content/en/updates/images/2021/01/devtools/copy-css-class.png
  src/content/en/updates/images/2021/01/devtools/copy-css-prop.png
  src/content/en/updates/images/2021/01/devtools/copy-css.png
  src/content/en/updates/images/2021/01/devtools/copy-object-console.png
  src/content/en/updates/images/2021/01/devtools/copy-object-sources.png
  src/content/en/updates/images/2021/01/devtools/csp.png
  src/content/en/updates/images/2021/01/devtools/dropped-frames.png
  src/content/en/updates/images/2021/01/devtools/dual-screen.png
  src/content/en/updates/images/2021/01/devtools/duplicate-element.png
  src/content/en/updates/images/2021/01/devtools/flexbox.png
  src/content/en/updates/images/2021/01/devtools/font.png
  src/content/en/updates/images/2021/01/devtools/force-target.png
  src/content/en/updates/images/2021/01/devtools/issues-feedback-02.png
  src/content/en/updates/images/2021/01/devtools/issues-feedback.png
  src/content/en/updates/images/2021/01/devtools/lighthouse.png
  src/content/en/updates/images/2021/01/devtools/lmi.png
  src/content/en/updates/images/2021/01/devtools/measure-memory.png
  src/content/en/updates/images/2021/01/devtools/network-log.png
  src/content/en/updates/images/2021/01/devtools/no-throttling.png
  src/content/en/updates/images/2021/01/devtools/node-screenshot.png
  src/content/en/updates/images/2021/01/devtools/sw.png
  src/content/en/updates/images/2021/01/devtools/third-party-cookies.png
  src/content/en/updates/images/2021/01/devtools/trust-token.png
  src/content/en/updates/images/2021/01/devtools/trusted-type-link.png
  src/content/en/updates/images/2021/01/devtools/trusted-type-violations.png
  src/content/en/updates/images/2021/01/devtools/ua-ch.png
  src/content/en/updates/images/2021/01/devtools/webtransport.png
Labels: DO NOT MERGE, cla: yes, content-new, section-tools, type-Content

#9216 [devtools] Remove leftover comment
  src/content/en/updates/2021/01/devtools.md
Labels: cla: yes

#9217 New in Chrome 88
  src/content/en/updates/2021/01/nic88.md
  src/content/en/updates/images/2021/01/nic88.jpg
  src/content/en/updates/images/2021/01/pillars.png
Labels: cla: yes

#9212 fix #9204
  src/content/en/tools/chrome-devtools/storage/applicationcache.md
Labels: cla: yes

#9207 Fix typo in fundamentals/security/csp docs in korean
  src/content/ko/fundamentals/security/csp/index.md
Labels: cla: yes

#9206 [Workbox] Small example tweak
  src/content/en/tools/workbox/modules/workbox-routing.md
Labels: cla: yes

#9219 Correct graphic in deps/rems article.
  src/content/en/updates/2020/12/chrome-88-deps-rems.md
  src/content/en/updates/images/2020/12/dep-rem_480.jpg
Labels: cla: yes

#9220 [devtools] update WNDT 89
  src/content/en/updates/2021/01/devtools.md
  src/content/en/updates/_shared/discover.md
  src/content/en/updates/images/2021/01/devtools/copy-file-name.png
Labels: cla: yes, content-updated, section-tools, type-Content

#9221 [devtools] Add missing image
  src/content/en/updates/images/2021/01/devtools/recorder.png
Labels: cla: yes

#9215 [devtools-blog] Migrating Puppeteer to TypeScript
  src/content/en/updates/2021/01/puppeteer-typescript.md
  src/content/en/updates/_shared/discover-devtools-blog.md
  src/content/en/updates/images/2021/01/devtools-blog.png
Labels: P2, cla: yes, content-new, type-Content

#9218 Delete & redirect New in Chrome posts to dcc
  src/content/de/updates/2018/01/nic64.md
  src/content/en/_redirects.yaml
  src/content/en/updates/2016/10/nic54.md
  src/content/en/updates/2016/11/nic55.md
  src/content/en/updates/2017/01/nic56.md
  src/content/en/updates/2017/03/nic57.md
  src/content/en/updates/2017/04/nic58.md
  src/content/en/updates/2017/05/nic59.md
  src/content/en/updates/2017/07/nic60.md
  src/content/en/updates/2017/09/nic61.md
  src/content/en/updates/2017/10/nic62.md
  src/content/en/updates/2017/12/nic63.md
  src/content/en/updates/2018/01/nic64.md
  src/content/en/updates/2018/03/nic65.md
  src/content/en/updates/2018/04/nic66.md
  src/content/en/updates/2018/05/nic67.md
  src/content/en/updates/2018/07/nic68.md
  src/content/en/updates/2018/09/nic69.md
  src/content/en/updates/2018/10/nic70.md
  src/content/en/updates/2018/12/nic71.md
  src/content/en/updates/2019/01/nic72.md
  src/content/en/updates/2019/03/nic73.md
  src/content/en/updates/2019/04/nic74.md
  src/content/en/updates/2019/06/nic75.md
  src/content/en/updates/2019/07/nic76.md
  src/content/en/updates/2019/09/nic77.md
  src/content/en/updates/2019/10/nic78.md
  src/content/en/updates/2019/12/nic79.md
  src/content/en/updates/2020/02/nic80.md
  src/content/en/updates/2020/04/nic81.md
  src/content/en/updates/2020/05/nic83.md
  src/content/en/updates/2020/07/nic84.md
  src/content/en/updates/2020/08/nic85.md
  src/content/en/updates/2020/10/nic86.md
  src/content/en/updates/2020/11/nic87.md
  src/content/en/updates/2021/01/nic88.md
  src/content/es/updates/2018/01/nic64.md
  src/content/fr/updates/2018/01/nic64.md
  src/content/hi/updates/2018/01/nic64.md
  src/content/id/updates/2018/01/nic64.md
  src/content/ja/updates/2018/01/nic64.md
  src/content/ru/updates/2018/01/nic64.md
  src/content/vi/updates/2018/01/nic64.md
Labels: cla: yes

#9224 Adds DCC & web.dev to updates & fundamentals
  gulp-tasks/build.js
  src/content/en/_footer.yaml
  src/content/en/fundamentals/_index.yaml
  src/content/en/updates/_book.yaml
  src/templates/updates/index.yaml
Labels: cla: yes

#9230 Restore media articles
  src/content/en/_redirects.yaml
  src/content/en/fundamentals/media/_redirects.yaml
  src/content/en/fundamentals/media/_toc.yaml
  src/content/en/fundamentals/media/capturing-images/images/android-chooser.png
  src/content/en/fundamentals/media/capturing-images/images/ios-chooser.png
  src/content/en/fundamentals/media/capturing-images/index.md
  src/content/en/fundamentals/media/eme.md
  src/content/en/fundamentals/media/images/html-layout.jpg
  src/content/en/fundamentals/media/images/mobile-web-video-playback-hero.png
  src/content/en/fundamentals/media/images/mp3_gap.png
  src/content/en/fundamentals/media/images/mp3_gap_end.png
  src/content/en/fundamentals/media/images/mp3_mid.png
  src/content/en/fundamentals/media/images/video-metadata-only.png
  src/content/en/fundamentals/media/manipulating/live-effects.md
  src/content/en/fundamentals/media/mobile-web-video-playback.md
  src/content/en/fundamentals/media/mse/_redirects.yaml
  src/content/en/fundamentals/media/mse/basics.md
  src/content/en/fundamentals/media/mse/images/basic-mse-flow.png
  src/content/en/fundamentals/media/mse/images/media-url.png
  src/content/en/fundamentals/media/mse/seamless-playback.md
  src/content/en/fundamentals/media/recording-audio/index.md
  src/content/en/fundamentals/media/recording-video/index.md
Labels: cla: yes, type-Content

#9227 Fix typo in headless-karma-mocha-chai.md
  src/content/en/updates/2017/06/headless-karma-mocha-chai.md
Labels: cla: yes

#9231 Receive Payments via Google Play Billing with the Digital Goods API
  src/content/en/android/trusted-web-activity/_toc.yaml
  src/content/en/android/trusted-web-activity/receive-payments-play-billing/index.md
Labels: cla: yes, content-new

#9236 Replace defaultQueue with queue
  src/content/en/updates/2019/08/get-started-with-gpu-compute-on-the-web.md
Labels: cla: yes

#9232 Fix a typo that could be seen as insensitive.
  src/content/en/updates/2015/09/automating-resource-selection-with-client-hints.md
Labels: cla: yes

#9210 Update for Recipes 6.1.0
  src/content/en/tools/workbox/modules/workbox-recipes.md
Labels: cla: yes
