Repository google/WebFundamentals, pull requests merged in 2021-02, with the labels that each got.

#9244 [devtools-blog] New blog post & contributor
  src/content/en/images/contributors/sadym.jpg
  src/content/en/updates/2021/02/faster-devtools-startup.md
  src/content/en/updates/_shared/discover-devtools-blog.md
  src/content/en/updates/images/2021/02/faster/devtools-blog.png
  src/content/en/updates/images/2021/02/faster/faster-1.svg
  src/content/en/updates/images/2021/02/faster/faster-2.svg
  src/content/en/updates/images/2021/02/faster/faster-3.svg
  src/content/en/updates/images/2021/02/faster/faster-4.svg
  src/data/_contributors.yaml
Labels: cla: yes, content-new, section-tools

#9253 workbox-window v6 updates
  src/content/en/tools/workbox/modules/workbox-window.md
Labels: cla: yes

#9252 Bring Site Kit page up to date with styles and correct redirect URI.
  src/content/en/site-kit/index.html
Labels: cla: yes

#9243 fix a typo ru locale
  src/content/ru/fundamentals/performance/rendering/index.md
Labels: cla: yes

#9240 Adds a link to the blog post about Chrome Custom Tabs sharing update
  src/content/en/android/custom-tabs/index.md
Labels: cla: yes, content-updated

#9237 Remove 2nd parameter when creating a PaymentRequest with DGAPI
  src/content/en/android/trusted-web-activity/receive-payments-play-billing/index.md
Labels: cla: yes, content-updated

#9260 [devtools] Update research link
  src/content/en/updates/_shared/devtools-research.md
Labels: cla: yes, section-tools

#9262 Site Kit page: fix search console API was renamed webmasters->searchconsole.
  src/content/en/site-kit/apikey.html
  src/content/en/site-kit/index.html
Labels: cla: yes

#9257 fix: correct link to 2021/01/devtools
  src/content/en/updates/_shared/discover-devtools-blog.md
Labels: cla: yes

#9254 Fix warmStrategyCache call
  src/content/en/tools/workbox/modules/workbox-recipes.md
Labels: cla: yes

#9242 Fixes #9241 - Remove references to Accept-CH-Lifetime
  src/content/en/fundamentals/performance/optimizing-content-efficiency/client-hints/index.md
  src/content/en/updates/2017/12/device-memory.md
Labels: cla: yes

#9263 Cleanup some language
  src/content/en/android/custom-tabs/headers/index.md
  src/content/en/updates/2012/02/SwiftShader-brings-software-3D-rendering-to-Chrome.md
Labels: cla: yes

#9270 [devtools] Chrome 89 add video link
  src/content/en/updates/2021/01/devtools.md
Labels: cla: yes, content-updated, section-tools

#9249 Redirect Generic Sensor update article
  src/content/en/_redirects.yaml
  src/content/en/updates/2017/09/sensors-for-the-web.md
  src/content/zh-cn/updates/2017/09/sensors-for-the-web.md
Labels: cla: yes, migrate-content

#9274 [devtools-blog] CSS-in-JS in DevTools
  src/content/en/images/contributors/orkon.jpg
  src/content/en/updates/2021/02/css-in-js.md
  src/content/en/updates/_shared/discover-devtools-blog.md
  src/content/en/updates/images/2021/02/css-in-js/constructable.png
  src/content/en/updates/images/2021/02/css-in-js/css-edit.mp4
  src/content/en/updates/images/2021/02/css-in-js/devtools-blog.jpg
  src/content/en/updates/images/2021/02/css-in-js/mechanism.svg
  src/data/_contributors.yaml
Labels: cla: yes, content-new, section-tools, type-Content

#9273 Update workbox-window.md
  src/content/en/tools/workbox/modules/workbox-window.md
Labels: cla: yes

#9272 Update advanced-recipes.md
  src/content/en/tools/workbox/guides/advanced-recipes.md
Labels: cla: yes

#9276 Move site-kit source of truth to g3
  src/content/en/site-kit/_book.yaml
  src/content/en/site-kit/_footer.yaml
  src/content/en/site-kit/_project.yaml
  src/content/en/site-kit/apikey.html
  src/content/en/site-kit/index.html
Labels: cla: yes
