Repository google/WebFundamentals, pull requests merged in 2021-03, with the labels that each got.

#9280 [devtools] What's New in DevTools 90
  src/content/en/updates/2021/02/devtools.md
  src/content/en/updates/_shared/discover.md
  src/content/en/updates/images/2021/02/devtools/accesibility-tree.png
  src/content/en/updates/images/2021/02/devtools/css-gamut.png
  src/content/en/updates/images/2021/02/devtools/cwv.png
  src/content/en/updates/images/2021/02/devtools/deprecated.png
  src/content/en/updates/images/2021/02/devtools/display-name-name.png
  src/content/en/updates/images/2021/02/devtools/display-name-old.png
  src/content/en/updates/images/2021/02/devtools/display-name.png
  src/content/en/updates/images/2021/02/devtools/double-quotes.png
  src/content/en/updates/images/2021/02/devtools/flexbox-layout.png
  src/content/en/updates/images/2021/02/devtools/flexbox-nav.png
  src/content/en/updates/images/2021/02/devtools/flexbox.png
  src/content/en/updates/images/2021/02/devtools/issue-count.png
  src/content/en/updates/images/2021/02/devtools/low-contrast.png
  src/content/en/updates/images/2021/02/devtools/permission-policy.png
  src/content/en/updates/images/2021/02/devtools/pwa-desc.png
  src/content/en/updates/images/2021/02/devtools/pwa-installable.png
  src/content/en/updates/images/2021/02/devtools/pwa-screenshot.png
  src/content/en/updates/images/2021/02/devtools/remote-address-space.png
  src/content/en/updates/images/2021/02/devtools/sameparty.png
  src/content/en/updates/images/2021/02/devtools/trust-token-pane.png
  src/content/en/updates/images/2021/02/devtools/twa.png
Labels: P1, cla: yes, content-new, section-tools, type-Content

#9275 Redirect IntersectionObserver v2 article
  src/content/en/_redirects.yaml
  src/content/en/updates/2019/02/intersectionobserver-v2.md
Labels: cla: yes

#9282 [devtools] update link
  src/content/en/updates/2021/01/devtools.md
Labels: cla: yes, content-updated, section-tools, type-Content

#9284 Set up redirects to DCC for Android content
  src/content/en/_footer.yaml
  src/content/en/_redirects.yaml
  src/content/en/android/_book.yaml
  src/content/en/android/_index.yaml
  src/content/en/android/_project.yaml
  src/content/en/android/custom-tabs/_toc.yaml
  src/content/en/android/custom-tabs/best-practices/index.md
  src/content/en/android/custom-tabs/headers/index.md
  src/content/en/android/custom-tabs/implementation-guide/index.md
  src/content/en/android/custom-tabs/implementation-guide/tumblr_action.png
  src/content/en/android/custom-tabs/implementation-guide/twitter_menu.png
  src/content/en/android/custom-tabs/index.md
  src/content/en/android/custom-tabs/low-level-api/index.md
  src/content/en/android/custom-tabs/performance.gif
  src/content/en/android/trusted-web-activity/_toc.yaml
  src/content/en/android/trusted-web-activity/android-browser-helper-migration/index.md
  src/content/en/android/trusted-web-activity/index.md
  src/content/en/android/trusted-web-activity/integration-guide/index.md
  src/content/en/android/trusted-web-activity/lay-of-the-land/index.md
  src/content/en/android/trusted-web-activity/multi-origin/index.md
  src/content/en/android/trusted-web-activity/play-billing/index.md
  src/content/en/android/trusted-web-activity/query-parameters/index.md
  src/content/en/android/trusted-web-activity/quick-start/index.md
  src/content/en/android/trusted-web-activity/receive-payments-play-billing/index.md
  src/content/en/android/trusted-web-activity/web-share-target/index.md
  src/content/en/android/trusted-web-activity/whats-new/in-app-products.jpg
  src/content/en/android/trusted-web-activity/whats-new/index.md
  src/content/en/android/trusted-web-activity/whats-new/play-menu.jpg
  src/content/en/android/trusted-web-activity/whats-new/product-details.jpg
Labels: cla: yes

#9298 Add a post for CrUX Rank Magnitude.
  src/content/en/updates/2021/03/crux-rank-magnitude.md
  src/content/en/updates/2021/03/images/crux-rank-magnitude/crux-rank-magnitude.png
  src/data/_contributors.yaml
Labels: cla: yes

#9283 Fix broken links in WB recipes docs
  src/content/en/tools/workbox/modules/workbox-recipes.md
Labels: cla: yes

#9304 Make HTML examples valid
  src/content/en/updates/2020/11/cvd.md
Labels: cla: yes
